### ISSUE TITLE
datachannel.send() ought to support bare strings (as well as ArrayBuffers)

### ISSUE THREAD

**Issue by cjb** [node-webrtc/node-webrtc#100]
`channel.send("hi")` results in:

```
(gdb) bt
#0  __memcpy_ssse3_back ()
    at ../sysdeps/x86_64/multiarch/memcpy-ssse3-back.S:1578
#1  0x00007ffff53a6911 in DataChannel::Send(v8::Arguments const&) ()
   from /home/cjb/git/node-webrtc/build/Release/webrtc.node
#2  0x00007ffff743f0c3 in ?? () from /usr/lib/libv8.so.3.14.5
```

**Comment by modeswitch** [comment]
The binding assumes typed array here without checking. The fix here is to check what the argument is and handle typed arrays and strings and complain if it received something else. Note that blobs will not be supported, even though they are in the spec.

On a side note, it makes sense to accept Buffer objects so I think I'll do that.

**Comment by piranna** [comment]
> On a side note, it makes sense to accept Buffer objects so I think I'll
> do that.
> 
> Shouldn't we just fit to the spec?

**Comment by modeswitch** [comment]
Node.js does not have blobs, so I'm not planning on supporting that part of the spec.

**Comment by piranna** [comment]
> Node.js does not have blobs, so I'm not planning on supporting that part
> of the spec.
> 
> Not natively, but there are modules:

https://github.com/coolaj86/node-file-api/

But I agree it would make sense to have support for Buffer objects, I'm
only concern about Node.js and browsers compatibility and interoperability.

**Comment by modeswitch** [comment]
@piranna Does that module actually provide a Blob API?

>  File is not (yet) a subclass of Blob

**Comment by modeswitch** [comment]
I'll do Buffer support in a separate issue.
