### ISSUE TITLE
Allow sending node.js Buffer objects

### ISSUE THREAD

**Issue by modeswitch** [node-webrtc/node-webrtc#103]
Send() should accept Buffer objects. Easy to convert them to ArrayBuffers. This might need a flag to indicate whether `onmessage` should provide an ArrayBuffer or a Buffer.

**Comment by piranna** [comment]
The .binaryType attribute should be enough to identify if using arrayBuffer objects or not. Buffer objects seems to be equivalent on Node.js to browser Blobs.

**Comment by modeswitch** [comment]
Yep, I think that's correct.

**Comment by feross** [comment]
Just wanted to point out that `Buffer` is a subclass of `Uint8Array` since iojs v3 and node v4, but this still doesn't work. Seems to fail with a `FATAL ERROR: v8::ArrayBuffer::Externalize ArrayBuffer already externalized` error.

**Comment by markandrus** [comment]
I have a PR that adds support for sending Buffers. We don't have `binaryType` support yet, though. The spec says `binaryType` can be one of "blob" or "arraybuffer". Right now, the behavior matches "arraybuffer". For "blob" support, we may want to depend on something like https://github.com/chrisdickinson/w3c-blob; however, I'm not sure how we should communicate the
 `type` across the wire. Only Firefox implements this ATM.

Also, I wonder if we'd want to support a non-standard `binaryType` extension like "buffer" which would allow receiving Buffers in the "message" event.
