### ISSUE TITLE
No package 'xscrnsaver' found

### ISSUE THREAD

**Issue by jeena** [node-webrtc/node-webrtc#106]
So I cloned the repo to my ubuntu computer and try to compile it but I get this error:

```
➜ jeena@Dipsy node-webrtc (develop) node bin/build.js --verbose
[...]
________ running '/usr/bin/python trunk/webrtc/build/gyp_webrtc -Dextra_gyp_flag=0' in '/home/jeena/Downloads/node-webrtc/third_party/libwebrtc'
Error: Command /usr/bin/python trunk/webrtc/build/gyp_webrtc -Dextra_gyp_flag=0 returned non-zero exit status 1 in /home/jeena/Downloads/node-webrtc/third_party/libwebrtc
Generating gyp files from GN...
Updating projects from gyp files...
Package xscrnsaver was not found in the pkg-config search path.
Perhaps you should add the directory containing `xscrnsaver.pc'
to the PKG_CONFIG_PATH environment variable
No package 'xscrnsaver' found
gyp: Call to 'pkg-config --cflags xscrnsaver' returned exit status 1.

gclient runhooks finished
For gclient runhooks something went wrong: error code 2, signal null.
    Try to run build script with --verbose option to find the possible problem.
```

Any idea why this might be? A couple of months ago I tried it once and everything compiled and I was able to run the tests successfully, I have this version still here and it still works. But obviously I'd like to run the newest version.

**Comment by modeswitch** [comment]
Install xscreensaver? For some reason I guess libjingle wants this library.

**Comment by jeena** [comment]
I installed xscreensaver but it didn't help. I still get the same exactly same error. And it says xscrnsaver not xscreensaver btw.

**Comment by wouldgo** [comment]
Have you tried to install libxss-dev?

If I remember well this is the package for that dependency.
Il 29/mar/2014 17:10 "Jeena Paradies" notifications@github.com ha scritto:

**Comment by jeena** [comment]
Oh yes, that helped, then I had to install libgnome-keyring-dev too. Quite a lot of dependencies for webrtc on node. Thanks!

**Comment by RoundSparrow** [comment]
Seems like a recent change to libjingle... as I found this page and i"m not using node-webrtc ;)
