### ISSUE TITLE
WebRTC / Jingle build instructions not valid for mac

### ISSUE THREAD

**Issue by fuson** [node-webrtc/node-webrtc#11]
Run (on mac):
ninja -C trunk/out/Release peerconnection_client
Will receive:
ninja: error: unknown target 'peerconnection_client'

Some information in:
https://code.google.com/p/webrtc/source/browse/trunk/talk/app/webrtc/objc/README

For now i'm try to run "ninja -C trunk/out/Release" without target. Maybe it will be good.

**Comment by fuson** [comment]
well, librtc and module builded successfully, but there is no result, i have the same error as in #10 

I found this patch: in https://github.com/helloIAmPau/node-rtc/blob/master/confs/buildall.patch
Is it possible that it fix the problem?

**Comment by fuson** [comment]
found https://discussions.apple.com/thread/3020481?start=0&tstart=0
But how...? :)

**Comment by fuson** [comment]
after adding '-framework Cocoa', linking issue solved, but:

after running tests:

pc: { createOffer: [Function: createOffer],
  createAnswer: [Function: createAnswer],
  setLocalDescription: [Function: setLocalDescription],
  setRemoteDescription: [Function: setRemoteDescription],
  addIceCandidate: [Function: addIceCandidate] }
Segmentation fault: 11

**Comment by fuson** [comment]
I'm tried to change linking strategy to:
['OS=="mac"', {
            'libraries': [
              '$(SDKROOT)/System/Library/Frameworks/QTKit.framework',
              '../<(libwebrtc_out)/../libwebrtc.a'
            ]
          }]

Fail, the same segmentation fault :(

**Comment by modeswitch** [comment]
These are the instructions I used for linux: https://code.google.com/p/libjingle/source/browse/trunk/README?r=375

There's some notes about osx in there. I'll have a mac this afternoon and I'll try to get this sorted.

**Comment by modeswitch** [comment]
Btw, are you syncing to the same revision as me? `gclient sync --revision r4953`? I had problems running with the head revision.

**Comment by fuson** [comment]
Sure, it was your revision. :(

**Comment by jbuck** [comment]
`export GYP_GENERATORS=ninja` seemed to get things further?

**Comment by modeswitch** [comment]
Yeah, that was missing from the instructions. I updated the README. The mac ninja build seems to be missing the peerconnection_client target; not sure why.

**Comment by fuson** [comment]
But build is not a valid :( Segfault in test every time. Something wrong with code portability or maybe with linking.

**Comment by modeswitch** [comment]
I think there's something wrong with the link step. @jbuck and I are going to investigate further tonight. Getting this working on mac and windows is a priority!

**Comment by fuson** [comment]
Thank you guys! I really rely on you.

**Comment by modeswitch** [comment]
The build instructions in the README really only work for Linux it seems. Mac instructions will follow when I get things building there.
