### ISSUE TITLE
Segmentation fault on `npm test` with pre-built binary

### ISSUE THREAD

**Issue by chris--** [node-webrtc/node-webrtc#111]
Hi! I'm getting a segfault with the pre-built binary on my system:

```
$ uname -rvm && node -v && npm -v
3.2.0-4-amd64 #1 SMP Debian 3.2.57-3 x86_64
v0.10.26
1.4.3

$ npm install
...
node-pre-gyp http GET https://wrtc-binaries.s3.amazonaws.com/wrtc/v0.0.18/Release/wrtc-v0.0.18-node-v11-linux-x64.tar.gz
node-pre-gyp http 200 https://wrtc-binaries.s3.amazonaws.com/wrtc/v0.0.18/Release/wrtc-v0.0.18-node-v11-linux-x64.tar.gz
[wrtc] Success: "/home/christian/dev/node-webrtc/lib/binding/wrtc.node" is installed
...

$ npm test
> wrtc@0.0.18 test /home/christian/dev/node-webrtc
> node test/all.js
TAP version 13
# create a peer connection
Segmentation fault
npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0
```

**Comment by modeswitch** [comment]
I'm aware of at least two different segfaults, so chances are you're hitting #110. Does it happen every time you run the tests, or only occasionally?

**Comment by chris--** [comment]
It's happening every time I run the tests (~10 times in a row). It segfaults on RTCPeerConn instantiation:

```
var webrtc = require('wrtc');
var pc = new webrtc.RTCPeerConnection(); // segfault
```

I'm running a stock stable debian with just `glibc` updated to `2.18-4`.

**Comment by modeswitch** [comment]
If you're able to retry this with a debug build (you'll need to clone and build from github), having a backtrace would be a big help.

**Comment by chris--** [comment]
Apparently, `npm install --build-from-source` fails with

```
make: Entering directory `/home/christian/dev/node-webrtc/build'
  ACTION Run build script /dev/null
TARGET_ARCH=x64 r5982 Release
Cloning depot tools ... error (see build.log for details): make: *** [/dev/null] Fehler 255
make: Leaving directory `/home/christian/dev/node-webrtc/build'
```

`build.log` is empty

**Comment by bicubic** [comment]
Looks like you have the problem I described in #114 
I was eventually able to compile by following the steps documented there and additionally installing libgnome-keyring-dev

**Comment by chris--** [comment]
It built successfully with steps described by @tricubic. `npm test` now passes all tests. As such, the segfaults seem to only occur with the pre-built binary.

**Comment by modeswitch** [comment]
To clarify: you upgraded libc and the segfaults stopped?

**Comment by bicubic** [comment]
Upgrading libc will resolve segfaults in the prebuilt binary if all the other dependencies are satisfied but won't help building from source. I later learned that it also caused a number of issues with other packages and broke aptitude, so I had to downgrade in the end. I wouldn't recommend it.

I think the build script needs some work with the issues around installing `depot_tools` which is where the build process crashes in a lot of reports.

**Comment by chris--** [comment]
Unfortunately, I cannot reproduce the error anymore. Both, the pre-built+source-built (`v0.0.22`) now pass all tests without any segfaults.
