### ISSUE TITLE
Tests pass after install, but unable to get bridge/peer example to work

### ISSUE THREAD

**Issue by hughlomas** [node-webrtc/node-webrtc#115]
node-webrtc was installed on a remote Ubuntu server by a coworker

Running npm test gave me

```
# tests 54
# pass  54

# ok
```

I then ran `examples/bridge.js` on the remote server and accessed it from my local development machine via `file:///C:/workspace/node-webrtc/examples/peer.html?<remote_ip>` on chrome `Version 36.0.1966.0 canary`, with the `--enable-data-channels` flag. 

The chrome console only outputs the first line of the example output on the readme, `signaling state change:  have-local-offer`. Nothing else comes up. The running bridge.js example produces no output at all and sits silently.

Is there something that I am missing? I am unfamiliar with WebRTC.

Thank you.

**Comment by bicubic** [comment]
Did you allow tcp/udp on the remote server port you're running bridge.js on?

**Comment by hughlomas** [comment]
Well it seems that I merely assumed that it would use the default ports without specifying anything. I didn't check bridge.js to see what the default port is. By explicitly specifying a port when running `node bridge.js <port>` everything worked as expected. I think that if I had used :9001 in the URL it would have worked as well. Thank you.
