### ISSUE TITLE
onaddstream doesn't get invoked in node.js

### ISSUE THREAD

**Issue by zoltanbettenbuk** [node-webrtc/node-webrtc#117]
I've implemented a node.js app to receive remote stream from a browser. Everything seems to work fine (offer/answer created/received), state changes happen fine, but onaddstream doesn't get invoked on node.js side.

// ############ node.js side #################

<pre>
var httpModule = require("http");
var fsModule = require("fs");
var websocketModule = require("websocket").server;
var logger = require("./logger.js");
var wrtc = require("wrtc");

//types
var RTCPeerConnection = wrtc.RTCPeerConnection;
var RTCSessionDescription = wrtc.RTCSessionDescription;

// globals
var port = 80;
var stunConfig = {iceServers: [{url: 'stun:stun.l.google.com:19302'}, {"url": "turn:66.228.45.110", "username": "zoltan@bettenbuk.com", "credential": "cer900"}]};
var peerConfig = {'optional': [{DtlsSrtpKeyAgreement: false}]};
var wsConnection;

// single peerConnection (yet)
var peerConnection = new RTCPeerConnection(stunConfig);

peerConnection.onaddstream = function(event) {
    logger.log("Remote stream arrived");
};
peerConnection.onicecandidate = function(event) {
    onIceCandidateReceived(event, wsConnection);
};
peerConnection.onnegotiationneeded = function() {
    logger.log("Negotiation is needed!!");
};

peerConnection.onsignalingstatechange = function(event) {
    logger.log("State changed: " + peerConnection.signalingState);
};

//streamChecker();

// simple web server
var httpServer = httpModule.createServer(function(request, response) {
    logger.log("HTTP connection for: " + request.url);
    fsModule.readFile("index.html", function(error, data) {
        if (error) {
            logger.log(error);
            response.end("");
        } else {
            response.end(data);
        }
    });
});

// starting web server
httpServer.listen(port, function() {
    logger.log("Server is listening on " + port);
});

var signalServer = new websocketModule({httpServer: httpServer});

signalServer.on("request", function(request) {
    var connection = request.accept(null, null);
    logger.log("Websocket connection from: " + connection.remoteAddress);
    connection.on("message", function(message) {
        wsConnection = connection;
        signalHandler(message, connection);
    });
});

function signalHandler(rawMessage, wsConnection) {
    logger.log("Message received: " + rawMessage.utf8Data);
    try {
        var message = JSON.parse(rawMessage.utf8Data);
        if (message.messageType === "connect") {
            // caller mode
            peerConnection.createOffer(function(description) {
                createLocalDescriptionCallback(description, wsConnection, "offer");
            }, logger.logError, {OfferToReceiveAudio: true, OfferToReceiveVideo: true});

        } else if (message.messageType === "offer.peerDescription") {
            // callee mode
            logger.log("Offer received");
            peerConnection.setRemoteDescription(new RTCSessionDescription(message.peerDescription), function() {
                setRemoteDescriptionCallback(wsConnection);
            }, logger.logError);

        } else if (message.messageType === "answer.peerDescription") {
            // caller mode
            logger.log("Answer received");
            peerConnection.setRemoteDescription(new RTCSessionDescription(message.peerDescription), function() {
                logger.log("Remote description set");
            }, logger.logError);

        } else if (message.messageType === "iceCandidate") {
            logger.log("Remote ICE candidate received");
            peerConnection.addIceCandidate(new wrtc.RTCIceCandidate(message.candidate));

        } else {
            logger.log("Message not handled: " + message.messageType);
        }
    } catch (e) {
        logger.log("Error handling message: " + rawMessage.utf8Data);
        logger.logError(JSON.stringify(e));
        return;
    }
}

function streamChecker() {
    if (peerConnection) {
        logger.log("Remote stream count: " + peerConnection.remoteStreams);
    }
    setTimeout(function() {
        streamChecker();
    }, 1000);
}

function onIceCandidateReceived(event, wsConnection) {
    if (event.candidate) {
        logger.log("Valid Ice candidate received: " + JSON.stringify(event.candidate));
        wsConnection.sendUTF(JSON.stringify({
            "messageType": "iceCandidate",
            "candidate": event.candidate
        }));
    } else {
        logger.log("Empty Ice candidate received");
    }
}

function setRemoteDescriptionCallback(wsConnection) {
    logger.log("Remote description is set");
    peerConnection.createAnswer(function(description) {
        createLocalDescriptionCallback(description, wsConnection, "answer");
    }, logger.logError);
}

// both mode
function createLocalDescriptionCallback(localDescription, wsConnection, type) {
    logger.log(type + " created: " + JSON.stringify(localDescription));
    localDescription.sdp = processSDP(localDescription.sdp);
    peerConnection.setLocalDescription(
            localDescription, function() {
                setLocalDescriptionCallback(localDescription, wsConnection, type);
            }, logger.logError
            );
}

function setLocalDescriptionCallback(localDescription, wsConnection, type) {
    wsConnection.sendUTF(JSON.stringify({
        "messageType": type + ".peerDescription",
        "peerDescription": localDescription
    }));
}

function processSDP(sdp) {
    // TODO: altering SDP here
    return sdp;
}
</pre>

//################# index.html ################

<pre>
&lt;!DOCTYPE html&gt;
&lt;html&gt;
    &lt;head&gt;
        &lt;title&gt;WebRTC client&lt;/title&gt;
        &lt;meta charset="UTF-8"&gt;
        &lt;meta name="viewport" content="width=device-width, initial-scale=1.0"&gt;
        &lt;script&gt;
            // common methods
            function log(comment) {
                console.log((new Date()) + " ::: " + comment);
            }

            function logError(error) {
                log("Error - " + JSON.stringify(error));
            }
        &lt;/script&gt;
        &lt;script&gt;
            // cross browser functionality
            var webRTCCapable = true;
            var PeerConnection = null;
            var SessionDescription = null;
            var IceCandidate = null;
            var getUserMedia = null;
            var addStreamToElement = null;
            var stunServer = "stun.l.google.com:19302";
            var localMediaElementId = "localMediaElement";
            var remoteMediaElementContainerId = "remoteStreamsDiv";

            if (navigator.getUserMedia) {
                log("WebRTC 1.0 standard");
                PeerConnection = RTCPeerConnection;
                SessionDescription = RTCSessionDescription;
                IceCandidate = RTCIceCandidate;
                getUserMedia = navigator.getUserMedia.bind(navigator);
                addStreamToElement = function(media_stream, media_element) {
                    // https://www.w3.org/Bugs/Public/show_bug.cgi?id=21606
                    media_element.srcObject = media_stream;
                    media_element.play();
                };
            } else if (navigator.mozGetUserMedia) {
                log("Early FireFox WebRTC");
                PeerConnection = mozRTCPeerConnection;
                SessionDescription = mozRTCSessionDescription;
                IceCandidate = mozRTCIceCandidate;
                getUserMedia = navigator.mozGetUserMedia.bind(navigator);
                addStreamToElement = function(media_stream, media_element) {
                    media_element.mozSrcObject = media_stream;
                    media_element.play();
                };
                stunServer = "23.21.150.121"; // Mozilla's STUN server
            } else if (navigator.webkitGetUserMedia) {
                log("Early WebKit");
                PeerConnection = webkitRTCPeerConnection;
                SessionDescription = RTCSessionDescription;
                IceCandidate = RTCIceCandidate;
                getUserMedia = navigator.webkitGetUserMedia.bind(navigator);
                addStreamToElement = function(media_stream, media_element) {
                    media_element.src = webkitURL.createObjectURL(media_stream);
                    media_element.play();
                };
            } else {
                alert("No WebRTC support");
                webRTCCapable = false;
            }
        &lt;/script&gt;
        &lt;script&gt;
            var signalingServer;
            var remoteStreams = 0;
            var clientId;
            var remoteDescription;
            var localDescription;

            var callerMode = true;

            var peerConnection = new PeerConnection({
                "iceServers": [{"url": "stun:" + stunServer}, {"url": "turn:66.228.45.110", "username": "zoltan@bettenbuk.com", "credential": "cer900"}]
            });

            peerConnection.onicecandidate = function(iceCandidateEvent) {
                log("New ice candidate: " + JSON.stringify(iceCandidateEvent));
                if (iceCandidateEvent.candidate) {
                    log("New ice candidate found: " + iceCandidateEvent.candidate);
                    signalingServer.send(JSON.stringify({
                        "clientId": clientId,
                        "messageType": "iceCandidate",
                        "candidate": iceCandidateEvent.candidate
                    }));
                }
            };

            peerConnection.onaddstream = function(event) {
                log("Remote stream connected");
                //var remoteVideoElement = document.getElementById("remoteVideoElement");
                //addStreamToElement(event.stream, remoteVideoElement);
            };

            peerConnection.onnegotiationneeded = function() {
                log("Negotiation is needed!!");
            };

            peerConnection.onsignalingstatechange = function(event) {
                log("State changed: " + JSON.stringify(event));
            };

            function init() {
                if (!webRTCCapable)
                    return false;

                log("Opening signaling server connection");
                signalingServer = new WebSocket("ws://localhost");

                signalingServer.onopen = function() {
                    signalingServer.onmessage = signalingServerMessageHandler;
                    if (callerMode) {
                        startStream();
                    } else {
                        signalingServer.send(JSON.stringify({
                            "messageType": "connect"
                        }));
                    }
                };
            }

            function signalingServerMessageHandler(messageEvent) {
                log("Message: " + messageEvent.data);
                var message = JSON.parse(messageEvent.data);
                if (message && message.messageType) {
                    if (message.messageType === "offer.peerDescription") {
                        remoteDescription = message.peerDescription;
                        startStream();
                    } else if (message.messageType === "answer.peerDescription") {
                        remoteDescription = message.peerDescription;
                        peerConnection.setRemoteDescription(new SessionDescription(remoteDescription), setRemoteDescriptionCallback, logError);
                    } else if (message.messageType === "iceCandidate") {
                        peerConnection.addIceCandidate(new IceCandidate(message.candidate));
                        log("Candidate added");
                    } else {
                        log("Message not handled: " + message.messageType);
                    }
                }
            }

            function startStream() {
                // initialising local media
                getUserMedia({"audio": true, "video": true}, getUserMediaCallback, logError);
            }

            function getUserMediaCallback(localMediaStream) {
                var localVideoElement = document.getElementById(localMediaElementId);
                addStreamToElement(localMediaStream, localVideoElement);
                localVideoElement.muted = true;
                peerConnection.addStream(localMediaStream);
                if (callerMode) {
                    peerConnection.createOffer(createOfferCallback, logError);
                } else {
                    peerConnection.setRemoteDescription(new SessionDescription(remoteDescription), setRemoteDescriptionCallback, logError);
                }
            }

            function setRemoteDescriptionCallback() {
                log("Remote description added");
                if (!callerMode) {
                    peerConnection.createAnswer(createAnswerCallback, logError);
                }
                log(JSON.stringify(peerConnection));
            }

            function createAnswerCallback(description) {
                localDescription = description;
                //localDescription.sdp = localDescription.sdp.replace(/a=sendrecv/g, "a=sendonly");
                //localDescription.sdp = localDescription.sdp.replace(/a=sendrecv/g, "a=recvonly");
                log("Local description created");
                peerConnection.setLocalDescription(localDescription, setLocalDescriptionCallback, logError);
            }

            function createOfferCallback(description) {
                localDescription = description;
                //localDescription.sdp = localDescription.sdp.replace(/a=sendrecv/g, "a=sendonly");
                //localDescription.sdp = localDescription.sdp.replace(/a=sendrecv/g, "a=recvonly");
                log("Local description created");
                peerConnection.setLocalDescription(localDescription, setLocalDescriptionCallback, logError);
            }

            function setLocalDescriptionCallback() {
                signalingServer.send(JSON.stringify({
                    "clientId": clientId,
                    "messageType": (callerMode ? "offer" : "answer") + ".peerDescription",
                    "peerDescription": localDescription
                }));
            }

            function addNewRemoteMediaElement() {
                var elementId = "remoteMediaElement_" + remoteStreams++;
                document.getElementById(remoteMediaElementContainerId).innerHTML += "&lt;video id=\"" + elementId + "\"&gt;&lt;/video&gt;";
                return document.getElementById(elementId);
            }

        &lt;/script&gt;
    &lt;/head&gt;
    &lt;body onload="init()"&gt;
        &lt;video id="localMediaElement"&gt;&lt;/video&gt;
        &lt;video id="remoteMediaElement"&gt;&lt;/video&gt;
        &lt;button onclick="peerConnection.close()"&gt;Close stream&lt;/button&gt;
    &lt;/body&gt;
&lt;/html&gt;

</pre>

**Comment by zoltanbettenbuk** [comment]
Sorry, forgot to mention that I implemeted it only for Firefox. It won't properly work on Chrome

**Comment by modeswitch** [comment]
The mediastream callbacks are disabled until mediastream support is finished.

**Comment by devand123** [comment]
@modeswitch firstly, I love the work that's been done so far, thank you (and all other contributors) very much!

Do you happen to have an ETA on when we may see mediastream support implemented, and thus the mediastream callbacks available for use? Is it actively being worked on? Or is there anything we can help with in order to move things along?

**Comment by modeswitch** [comment]
I haven't had much time to do the mediastream implementation, so it's up for grabs. It's a combination of C++ and JavaScript work. If you're comfortable with that, feel free to hack on it. I can provide guidance by email or in #filer on irc.mozilla.org.
