### ISSUE TITLE
Fedora 20 packages

### ISSUE THREAD

**Issue by vmolsa** [node-webrtc/node-webrtc#119]
Packages that is required on Fedora 20 

yum install @Development-tools nodejs nodejs-devel npm node-gyp nss-devel alsa-lib-devel pulseaudio-libs-devel java-1.7.0-openjdk-devel libjpeg-turbo-devel libXv-devel gtk2-devel expat-devel libXScrnSaver-devel libXtst-devel dbus-devel GConf2-devel libgnome-keyring-devel libgcrypt-devel pciutils-devel systemd-devel 

export JAVA_HOME=/usr/lib/jvm/java-1.7.0-openjdk/

**Comment by modeswitch** [comment]
I've refactored the native backend, so most of these deps are out of date. It's also not necessary to set `JAVA_HOME` anymore.
