### ISSUE TITLE
DataChannel on Linux don't work correctly

### ISSUE THREAD

**Issue by fuson** [node-webrtc/node-webrtc#12]
On Chrome 29 (started with proper parameters for datachannel turn on, what you write in README):

[27:27:1018/011325:ERROR:rtc_data_channel_handler.cc(63)] WebRTCDataChannelHandlerClient not set.

And guys, building in linux was not clear :) You're commented linking with openssl and i have to remove # on it to start testing.

**Comment by modeswitch** [comment]
Which linux distro? You may need to use Chrome 30+ (I'm using 32).

SSL lib isn't linked because it's causing an assert to fail.

**Comment by modeswitch** [comment]
What error do you get if libopenssl.a is commented out?

**Comment by fuson** [comment]
If i have no linking with openssl:

ws connected
{ type: 'offer',
  sdp: 'v=0\r\no=- 1164403742104461061 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE audio data\r\na=msid-semantic: WMS\r\nm=audio 1 RTP/SAVPF 111 103 104 0 8 107 106 105 13 126\r\nc=IN IP4 0.0.0.0\r\na=rtcp:1 IN IP4 0.0.0.0\r\na=ice-ufrag:DEiI/joNVzAPVmoR\r\na=ice-pwd:3majYMNA50DX6yHhBYoE3w+6\r\na=ice-options:google-ice\r\na=fingerprint:sha-256 11:DE:5E:B0:94:83:ED:9B:0A:66:EC:E6:D3:F9:10:CC:53:86:59:AC:54:F7:08:B3:1B:4A:60:C5:36:BA:60:B2\r\na=mid:audio\r\na=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\na=recvonly\r\na=rtcp-mux\r\na=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:UNZZ+Hm60QY508s2voKa5IQyJAxTVqGTYOT+dLjq\r\na=rtpmap:111 opus/48000/2\r\na=fmtp:111 minptime=10\r\na=rtpmap:103 ISAC/16000\r\na=rtpmap:104 ISAC/32000\r\na=rtpmap:0 PCMU/8000\r\na=rtpmap:8 PCMA/8000\r\na=rtpmap:107 CN/48000\r\na=rtpmap:106 CN/32000\r\na=rtpmap:105 CN/16000\r\na=rtpmap:13 CN/8000\r\na=rtpmap:126 telephone-event/8000\r\na=maxptime:60\r\nm=application 1 RTP/SAVPF 101\r\nc=IN IP4 0.0.0.0\r\na=rtcp:1 IN IP4 0.0.0.0\r\na=ice-ufrag:DEiI/joNVzAPVmoR\r\na=ice-pwd:3majYMNA50DX6yHhBYoE3w+6\r\na=ice-options:google-ice\r\na=fingerprint:sha-256 11:DE:5E:B0:94:83:ED:9B:0A:66:EC:E6:D3:F9:10:CC:53:86:59:AC:54:F7:08:B3:1B:4A:60:C5:36:BA:60:B2\r\na=mid:data\r\na=sendrecv\r\nb=AS:30\r\na=rtcp-mux\r\na=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:UNZZ+Hm60QY508s2voKa5IQyJAxTVqGTYOT+dLjq\r\na=rtpmap:101 google-data/90000\r\na=ssrc:2994073915 cname:6LrwDsgAJSgCrLvP\r\na=ssrc:2994073915 msid:reliable reliable\r\na=ssrc:2994073915 mslabel:reliable\r\na=ssrc:2994073915 label:reliable\r\n' }
node: symbol lookup error: /home/masim/src/node-webrtc/build/Release/webrtc.node: undefined symbol: X509_set_pubkey

**Comment by fuson** [comment]
Guys, i can't understand, when i'm running test datachannel on public test page (f.e. https://www.webrtc-experiment.com/DataChannel/auto-session-establishment.html#3LWCPXOU-ZAUG14I) in 2 tabs in my chrome (i made all tests with 29 and with last stable 30.xxxx) it works fine, but with node-webrtc it don't work ON CHROME SIDE! How it possible?

For sure i'll test on last public beta and write the result.

**Comment by piranna** [comment]
Chrome v30.1650.x enabled SCTP DataChannels by default, previous ones use
RTP DataChannels and SCTP ones needed to be enabled by a flag. Hope that
helps...

**Comment by fuson** [comment]
piranna, may be you know how can i manage DataChannel transport? May be in SDP settings, may be in DataChannel options, may be in options in Chrome... oh...

**Comment by piranna** [comment]
Sorry, I have been trying to keep out of this low level things, sorry...
Maybe you could mofify the SDP or look on the Chrome flags...

2013/10/18 Aleksey Mihailiuk notifications@github.com

> piranna, may be you know how can i manage DataChannel transport? May be in
> SDP settings, my be in DataChannel options, may be in options in Chrome...
> oh...
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/modeswitch/node-webrtc/issues/12#issuecomment-26576370
> .

## 

"Si quieres viajar alrededor del mundo y ser invitado a hablar en un monton
de sitios diferentes, simplemente escribe un sistema operativo Unix."
– Linus Tordvals, creador del sistema operativo Linux

**Comment by fuson** [comment]
The same status with last public beta :(

All tests on:

uname -a
Linux x220 3.2.0-54-generic #82-Ubuntu SMP Tue Sep 10 20:08:42 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

Ubuntu 12.04

**Comment by piranna** [comment]
F*ck :-/ Maybe the problem would be in our side? Have you tried asking for
advice on https://groups.google.com/forum/#!forum/discuss-webrtc ?

2013/10/18 Aleksey Mihailiuk notifications@github.com

> The same status with last public beta :(
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/modeswitch/node-webrtc/issues/12#issuecomment-26577788
> .

## 

"Si quieres viajar alrededor del mundo y ser invitado a hablar en un monton
de sitios diferentes, simplemente escribe un sistema operativo Unix."
– Linus Tordvals, creador del sistema operativo Linux

**Comment by fuson** [comment]
Oh :( It dont work with serverside on linux + clientside chrome canary on mac / windows too.

**Comment by modeswitch** [comment]
@fuson Please try with chrome dev (version 32). The example is using RTP data channels because SCTP isn't enabled yet in libjingle.

Also, I'm definitely not getting undefined symbols. Which linux distro are you using?

**Comment by modeswitch** [comment]
@fusion I disabled dtls/srtp key exchange and uncommented libssl. Try rebuilding and testing in chrome dev (v.32).

**Comment by fuson** [comment]
uname -a
Linux x220 3.2.0-54-generic #82-Ubuntu SMP Tue Sep 10 20:08:42 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

Ubuntu 12.04

I'm try in mac canary (on client machine) + linux (serverside), for now i'll try canary 32 dev on linux on the same machine.

**Comment by modeswitch** [comment]
Yeah, don't bother with mac yet. Let's get linux working in more places first :)

**Comment by fuson** [comment]
God! It works! YES YES YES!!!!!!

**Comment by fuson** [comment]
Guys, fix it for mac pls and i'll be happiest man!

**Comment by piranna** [comment]
> God! It works! YES YES YES!!!!!!
> 
> With SCTP? If yes, upload it to npm and I'll test it against my library.

**Comment by fuson** [comment]
piranna, rtp only as i see in SDP, but for my purpose its great already. :)

**Comment by modeswitch** [comment]
@piranna It's RTP only until an upstream bug is fixed in libjingle.

**Comment by piranna** [comment]
Let's wait then.
