### ISSUE TITLE
npm install wrtc fails on osx

### ISSUE THREAD

**Issue by ZECTBynmo** [node-webrtc/node-webrtc#120]
OSX Mavericks, XCode 5

npm http GET http://registry.npm.hubteam.com/wrtc
npm http 304 http://registry.npm.hubteam.com/wrtc
npm http GET http://registry.npm.hubteam.com/nan
npm http GET http://registry.npm.hubteam.com/nopt
npm http GET http://registry.npm.hubteam.com/node-gyp
npm http 304 http://registry.npm.hubteam.com/nan
npm http 304 http://registry.npm.hubteam.com/nopt
npm ERR! Error: No compatible version found: nopt@'^2.2.0'
npm ERR! Valid install targets:
npm ERR! ["1.0.0","1.0.1","1.0.2","1.0.3","1.0.4","1.0.5","1.0.6","1.0.7","1.0.8","1.0.9","1.0.10","2.0.0","2.1.0","2.1.1","2.1.2","2.2.0","2.2.1"]
npm ERR!     at installTargetsError (/opt/boxen/nodenv/versions/v0.10.1/lib/node_modules/npm/lib/cache.js:684:10)
npm ERR!     at /opt/boxen/nodenv/versions/v0.10.1/lib/node_modules/npm/lib/cache.js:606:10
npm ERR!     at saved (/opt/boxen/nodenv/versions/v0.10.1/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Darwin 13.1.0
npm ERR! command "/opt/boxen/nodenv/versions/v0.10.1/bin/node" "/opt/boxen/nodenv/versions/v0.10.1/bin/npm" "install" "wrtc"
npm ERR! cwd /Users/mvegeto/Projects/audionet_server
npm ERR! node -v v0.10.1
npm ERR! npm -v 1.2.15
npm http 304 http://registry.npm.hubteam.com/node-gyp
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/mvegeto/Projects/audionet_server/npm-debug.log
npm ERR! not ok code 0

**Comment by modeswitch** [comment]
Not sure what's going on there, but the error above is regarding `nopt`. What happens if you retry?

**Comment by modeswitch** [comment]
This looks like an issue with `npm`. It's failing to install packages from `package.json`.

**Comment by enedrio** [comment]
I'm having the same problem building on raspberry pi (raspbian).
Anything I can do to make it work?

**Comment by modeswitch** [comment]
@enedrio There isn't a binary image for ARM yet, so you'll have to build it on the device after installing all the build deps.

**Comment by enedrio** [comment]
@modeswitch hmm, ok, this could take a while on the pi... :\ thanks for the reply

**Comment by modeswitch** [comment]
Latest version has an easier build process. OSX isn't fully supported yet, but if you want to give it a try and open issues I can address them.
