### ISSUE TITLE
WebP2P compatibility

### ISSUE THREAD

**Issue by piranna** [node-webrtc/node-webrtc#121]
I have been developing the last months [WebP2P](http://webp2p.io), a WebRTC P2P signaling channel that makes a huge use of DataChannels for inter-peers routing, and now it's on a release candidate status (feature complete and all the tests passing, only some ocasional failure due to third-party servers used for handshake). Since I build it on top of node-webrtc, this can be a good testbed for a real world use case, so it can be used to see what features are missing on node-webrtc and where to work.

**Comment by modeswitch** [comment]
Very cool! Please open issues for missing features or issues that you find.

**Comment by piranna** [comment]
Thanks! :-D Ok, now I'm busy with exams and re-implementing the XMPP handshake connector, when I have time (maybe July) I'll put this as a priority :-) From my head, one obvious is issue #44, onicecandidate handling, I'll look for another missing features :-)
