### ISSUE TITLE
Failed to insall via GIT or NPM

### ISSUE THREAD

**Issue by esdrasportillo** [node-webrtc/node-webrtc#125]
I am Trying to install it on Ubuntu 14.04, I ve tried to install both using NPM or GIT clone, but I am still receiving the same error:

> wrtc@0.0.21 install /usr/local/lib/node_modules/wrtc
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Source compile required: 404 status code downloading tarball 
gyp ERR! configure error 
gyp ERR! stack Error: "pre" versions of node cannot be installed, use the --nodedir flag instead
gyp ERR! stack     at install (/usr/local/lib/node_modules/wrtc/node_modules/node-gyp/lib/install.js:65:16)
gyp ERR! stack     at Object.self.commands.(anonymous function) [as install](/usr/local/lib/node_modules/wrtc/node_modules/node-gyp/lib/node-gyp.js:66:37)
gyp ERR! stack     at getNodeDir (/usr/local/lib/node_modules/wrtc/node_modules/node-gyp/lib/configure.js:228:20)
gyp ERR! stack     at /usr/local/lib/node_modules/wrtc/node_modules/node-gyp/lib/configure.js:110:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:720:7)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at maybeClose (child_process.js:994:16)
gyp ERR! stack     at Socket.<anonymous> (child_process.js:1160:11)
gyp ERR! stack     at Socket.emit (events.js:107:17)
gyp ERR! stack     at Pipe.close (net.js:461:12)
gyp ERR! System Linux 3.13.0-29-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/wrtc/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--name=wrtc" "--configuration=Release" "--module_name=wrtc" "--version=0.0.21" "--patch=21" "--runtime=node" "--node_abi=node-v14" "--platform=linux" "--arch=x64" "--target_arch=x64" "--module_main=lib/index.js" "--host=https://wrtc-binaries.s3.amazonaws.com/" "--module_path=/usr/local/lib/node_modules/wrtc/lib/binding" "--remote_path=./wrtc/v0.0.21/Release/" "--package_name=wrtc-v0.0.21-node-v14-linux-x64.tar.gz" "--staged_tarball=build/stage/wrtc/v0.0.21/Release/wrtc-v0.0.21-node-v14-linux-x64.tar.gz" "--hosted_path=https://wrtc-binaries.s3.amazonaws.com/wrtc/v0.0.21/Release/" "--hosted_tarball=https://wrtc-binaries.s3.amazonaws.com/wrtc/v0.0.21/Release/wrtc-v0.0.21-node-v14-linux-x64.tar.gz"
gyp ERR! cwd /usr/local/lib/node_modules/wrtc
gyp ERR! node -v v0.11.14-pre
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node rebuild --name=wrtc --configuration=Release --module_name=wrtc --version=0.0.21 --patch=21 --runtime=node --node_abi=node-v14 --platform=linux --arch=x64 --target_arch=x64 --module_main=lib/index.js --host=https://wrtc-binaries.s3.amazonaws.com/ --module_path=/usr/local/lib/node_modules/wrtc/lib/binding --remote_path=./wrtc/v0.0.21/Release/ --package_name=wrtc-v0.0.21-node-v14-linux-x64.tar.gz --staged_tarball=build/stage/wrtc/v0.0.21/Release/wrtc-v0.0.21-node-v14-linux-x64.tar.gz --hosted_path=https://wrtc-binaries.s3.amazonaws.com/wrtc/v0.0.21/Release/ --hosted_tarball=https://wrtc-binaries.s3.amazonaws.com/wrtc/v0.0.21/Release/wrtc-v0.0.21-node-v14-linux-x64.tar.gz' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/wrtc/node_modules/node-pre-gyp/lib/util/compile.js:76:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:994:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1066:5)
node-pre-gyp ERR! System Linux 3.13.0-29-generic
node-pre-gyp ERR! command "node" "/usr/local/lib/node_modules/wrtc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/wrtc
node-pre-gyp ERR! node -v v0.11.14-pre
node-pre-gyp ERR! node-pre-gyp -v v0.5.9
node-pre-gyp ERR! not ok 
npm ERR! wrtc@0.0.21 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wrtc@0.0.21 install script.
npm ERR! This is most likely a problem with the wrtc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls wrtc
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.13.0-29-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "wrtc" "-g"
npm ERR! cwd /
npm ERR! node -v v0.11.14-pre
npm ERR! npm -v 1.4.14
npm ERR! code ELIFECYCLE

I ve checked all the dependencies and issues to try to solve it but nothing until now, 

Thanks

**Comment by cjb** [comment]
@esdrasportillo Could you try again?  There's a binary available now, it should get that instead of compiling.

**Comment by esdrasportillo** [comment]
It is working now, brilliant, Thank you!
