### ISSUE TITLE
OSX binary to bundle

### ISSUE THREAD

**Issue by fallenhitokiri** [node-webrtc/node-webrtc#127]
I compiled a binary for OSX and confirmed that it is working (serverless-webrtc chat) and passes all "npm tests" on 10.9.3 and 10.7.5. You can find the binary here[1]. I can provide the output of the test runner if necessary or run additional tests.

[1] http://screamingatmyscreen.com/~tizi/wrtc/osx/10.9.3/

**Comment by modeswitch** [comment]
That's awesome, thanks! I'll put this up on aws as soon as possible. Which version of wrtc is this?

**Comment by fallenhitokiri** [comment]
It is 0.0.22 (as dependency of serverless-webrtc). If it helps I can also try building other versions / branches.

**Comment by springmeyer** [comment]
It is fairly easy to use travis.ci to build automatically for both linux and osx: https://github.com/mapbox/node-pre-gyp#travis-automation

**Comment by modeswitch** [comment]
@springmeyer Will it also build for Windows? I'd like to find a solution that will let me build for all three platforms.

**Comment by springmeyer** [comment]
Yes, you can build for windows with a free appveyor account. The node-pre-gyp README has docs on this too: https://github.com/mapbox/node-pre-gyp#appveyor-automation.

**Comment by feross** [comment]
Can we merge this?

**Comment by cjb** [comment]
Hi @modeswitch, how's this going?

**Comment by modeswitch** [comment]
@cjb I haven't done this yet, hoping to get to it in a couple of hours. Btw, the link @fallenhitokiri gave above is no longer valid.

**Comment by fallenhitokiri** [comment]
sorry - moved the host and didn't copy the public directory https://s3-us-west-2.amazonaws.com/blazeit-share/wrtc.node

**Comment by feross** [comment]
Any update on this? I still get:

```
> wrtc@0.0.22 install /Users/feross/code/webtorrent-client/node_modules/wrtc
> node-pre-gyp install --fallback-to-build

node-pre-gyp http GET https://wrtc-binaries.s3.amazonaws.com/wrtc/v0.0.22/Release/wrtc-v0.0.22-node-v14-darwin-x64.tar.gz
node-pre-gyp http 404 https://wrtc-binaries.s3.amazonaws.com/wrtc/v0.0.22/Release/wrtc-v0.0.22-node-v14-darwin-x64.tar.gz
node-pre-gyp ERR! Source compile required: 404 status code downloading tarball 
```

when I install. Is there some way I can help solve this issue? Would love to see this land!

**Comment by szimek** [comment]
I'm getting the same error as @feross...

**Comment by cjb** [comment]
@modeswitch ping?

**Comment by modeswitch** [comment]
@cjb pong; getting around to this today.

@fallenhitokiri Can you run `node-pre-gyp package` and send me the output? It should be a `.tar.gz` that will have some machine info in the filename that's important.

**Comment by fallenhitokiri** [comment]
@modeswitch https://s3-us-west-2.amazonaws.com/blazeit-share/wrtc-v0.0.22-node-v11-darwin-x64.tar.gz

**Comment by cjb** [comment]
@modeswitch Need anything else here? Would be awesome to get this done soon, thanks!

**Comment by modeswitch** [comment]
I checked in a `.travis.yml` but it's not working and I'm having trouble getting it to barf up the log file. If you feel like taking a peak? Ideally this would build for linux and osx so we can all get on with our lives :)

**Comment by cjb** [comment]
@modeswitch My guess (purely a guess since the error's hidden) would be that $JAVA_HOME is unset, that's why I usually get errors like that one.

**Comment by cjb** [comment]
@modeswitch Maybe this:

```
env:
  - "JAVA_HOME=/usr/lib/jvm/java-7-oracle"
```

should instead be:

```
env:
  - JAVA_HOME="/usr/lib/jvm/java-7-oracle"
```

(Doesn't help with the issue of not being able to get access to the log, though, I know.)

**Comment by cjb** [comment]
(I think we're also supposed to have a first line of "language: node_js".)

**Comment by cjb** [comment]
Quick update for the bug watchers:  we're running out of memory during compilation on travis, even though the hosts there get 3GB RAM.  Passing `MAKEOPTS="-j1"` doesn't seem to help.

**Comment by modeswitch** [comment]
I have this mostly working now. There may not be space immediately on travis-ci for osx builds, but linux builds are now automated.

**Comment by modeswitch** [comment]
@fallenhitokiri I've uploaded your binary. Could you make one with node v11 as well?

**Comment by modeswitch** [comment]
OK, automated builds are set up for linux and will publish for new tags. Still waiting for a reply about multi-OS builds from travis-ci.

**Comment by feross** [comment]
Awesome progress! Thanks!!

On Monday, August 25, 2014, Alan K notifications@github.com wrote:

> OK, automated builds are set up for linux and will publish for new tags.
> Still waiting for a reply about multi-OS builds from travis-ci.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/js-platform/node-webrtc/issues/127#issuecomment-53355520
> .

## 

_Feross_ | blog http://feross.org/ | webtorrent http://webtorrent.io/ |
studynotes http://www.apstudynotes.org/

**Comment by fallenhitokiri** [comment]
@modeswitch the build with node 0.11.13 is failing. Here is the terminal output[1]

I cannot upload `npm-debug.log` because my working directory is deleted when the installation fails. Is this intended?

[1] https://gist.github.com/fallenhitokiri/6fbcc5e910949f4646ca

**Comment by modeswitch** [comment]
@fallenhitokiri Maybe try a fresh copy? Looks like old nan problems.

**Comment by modeswitch** [comment]
@kkoopa Can you take a look at the log @fallenhitokiri posted?

**Comment by kkoopa** [comment]
It's likely pulling in NAN 0.8 from somewhere. Probably using some old version, check package.json.

**Comment by modeswitch** [comment]
@kkoopa `"nan": "~1.3.0"` in `package.json`.

**Comment by kkoopa** [comment]
In master, yes, but not what he ran.

**Comment by fallenhitokiri** [comment]
I tried `npm install nan` which installs 1.3.0, when doing `npm install wrtc` followed by `cat node_modules/wrtc/node_modules/nan/package.json` it shows version 0.4.4 - time window for this isn't big since the working directory where I try to install wrtc is still deleting itself after failing

**Comment by kkoopa** [comment]
Then you are actually installing 0.0.20, not 0.0.22.

Check out master from git and build that.

**Comment by fallenhitokiri** [comment]
building the development branch works[1]

@kkoopa here is the package.json[2] I get when I do `npm install wrtc`  it shows version 0.0.22 with nan 0.4.4 as dependency or am I reading it wrong?

[1] https://s3-us-west-2.amazonaws.com/blazeit-share/wrtc-v0.0.22-node-v14-darwin-x64.tar.gz
[2] https://gist.github.com/fallenhitokiri/42e4cdfe53a216acc1af

**Comment by kkoopa** [comment]
You are reading it right. How something like that ever came to exist is beyond my comprehension.

**Comment by modeswitch** [comment]
I just bumped the version and republished. Travis should rebuild for linux. @fallenhitokiri can you rebuild for osx?

**Comment by fallenhitokiri** [comment]
https://s3-us-west-2.amazonaws.com/blazeit-share/wrtc-v0.0.23-node-v11-darwin-x64.tar.gz
https://s3-us-west-2.amazonaws.com/blazeit-share/wrtc-v0.0.23-node-v14-darwin-x64.tar.gz

**Comment by modeswitch** [comment]
`gclient runhooks` is not working on travis-ci (it times out after 50 minutes). Investigating.

**Comment by modeswitch** [comment]
@fallenhitokiri uploaded your new binaries. Can make sure they download via `npm install wrtc`?

**Comment by modeswitch** [comment]
Looks like an upstream repo problem that's now fixed.
