### ISSUE TITLE
Build Issue with Ubuntu 14.04 32bit

### ISSUE THREAD

**Issue by blions18** [node-webrtc/node-webrtc#129]
npm install wrtc fails with the following:
node-pre-gyp http GET https://wrtc-binaries.s3.amazonaws.com/wrtc/v0.0.22/Release/wrtc-v0.0.22-node-v11-linux-ia32.tar.gz
node-pre-gyp http 404 https://wrtc-binaries.s3.amazonaws.com/wrtc/v0.0.22/Release/wrtc-v0.0.22-node-v11-linux-ia32.tar.gz
node-pre-gyp ERR! Source compile required: 404 status code downloading tarball 
make: Entering directory `/home/joe/node_modules/wrtc/build'
  ACTION Run build script /dev/null
TARGET_ARCH=ia32 r5982 Release
Preparing directories ... done
Cloning depot tools ... done
Configuring gclient ... done
Syncing upstream libjingle ... emake: *** [/dev/null] Error 255
make: Leaving directory`/home/joe/node_modules/wrtc/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/joe/node_modules/wrtc/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.13.0-24-generic
gyp ERR! command "/usr/bin/node" "/home/joe/node_modules/wrtc/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--name=wrtc" "--configuration=Release" "--module_name=wrtc" "--version=0.0.22" "--patch=22" "--runtime=node" "--node_abi=node-v11" "--platform=linux" "--arch=ia32" "--target_arch=ia32" "--module_main=lib/index.js" "--host=https://wrtc-binaries.s3.amazonaws.com/" "--module_path=/home/joe/node_modules/wrtc/lib/binding" "--remote_path=./wrtc/v0.0.22/Release/" "--package_name=wrtc-v0.0.22-node-v11-linux-ia32.tar.gz" "--staged_tarball=build/stage/wrtc/v0.0.22/Release/wrtc-v0.0.22-node-v11-linux-ia32.tar.gz" "--hosted_path=https://wrtc-binaries.s3.amazonaws.com/wrtc/v0.0.22/Release/" "--hosted_tarball=https://wrtc-binaries.s3.amazonaws.com/wrtc/v0.0.22/Release/wrtc-v0.0.22-node-v11-linux-ia32.tar.gz"
gyp ERR! cwd /home/joe/node_modules/wrtc
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node rebuild --name=wrtc --configuration=Release --module_name=wrtc --version=0.0.22 --patch=22 --runtime=node --node_abi=node-v11 --platform=linux --arch=ia32 --target_arch=ia32 --module_main=lib/index.js --host=https://wrtc-binaries.s3.amazonaws.com/ --module_path=/home/joe/node_modules/wrtc/lib/binding --remote_path=./wrtc/v0.0.22/Release/ --package_name=wrtc-v0.0.22-node-v11-linux-ia32.tar.gz --staged_tarball=build/stage/wrtc/v0.0.22/Release/wrtc-v0.0.22-node-v11-linux-ia32.tar.gz --hosted_path=https://wrtc-binaries.s3.amazonaws.com/wrtc/v0.0.22/Release/ --hosted_tarball=https://wrtc-binaries.s3.amazonaws.com/wrtc/v0.0.22/Release/wrtc-v0.0.22-node-v11-linux-ia32.tar.gz' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/joe/node_modules/wrtc/node_modules/node-pre-gyp/lib/util/compile.js:76:29)
node-pre-gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:743:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:5)
node-pre-gyp ERR! System Linux 3.13.0-24-generic
node-pre-gyp ERR! command "node" "/home/joe/node_modules/wrtc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/joe/node_modules/wrtc
node-pre-gyp ERR! node -v v0.10.25
node-pre-gyp ERR! node-pre-gyp -v v0.5.9
node-pre-gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! weird error 1
npm ERR! not ok code 0

**Comment by modeswitch** [comment]
I've only build for 64-bit architectures. If you want to use on 32-bit linux, you'll have to build it from source. That involves installing all the build prerequisites.
