### ISSUE TITLE
DTLS/SRTP key exchange doesn't work with Chrome 32

### ISSUE THREAD

**Issue by modeswitch** [node-webrtc/node-webrtc#13]
Not sure what's broken. Release build stalls, debug build has an assert.

**Comment by modeswitch** [comment]
Upstream issue [here](https://code.google.com/p/webrtc/issues/detail?id=2538).

**Comment by modeswitch** [comment]
Fixed by using system libssl on linux as well.

**Comment by feross** [comment]
Does this mean that this works with latest Chrome now (which defaults to SCTP) now?

**Comment by modeswitch** [comment]
No, SCTP data channels still don't work (there's an open issue for libjingle), so you'll have to stick to RTP data channels and sending strings.

SCTP data channels is high on my list though. Basically right after I get the npm module experience working right.

**Comment by feross** [comment]
Awesome -- I'll hopefully be able to help out at some point, perhaps getting this to build on mac.
