### ISSUE TITLE
ALSA lib control.c:953:(snd_ctl_open_noupdate) Invalid CTL

### ISSUE THREAD

**Issue by galaxor** [node-webrtc/node-webrtc#130]
Hi.  I compiled this package from the git master, using ubuntu 14.04.  When I try to createAnswer, I get these errors:
ALSA lib control.c:953:(snd_ctl_open_noupdate) Invalid CTL 
ALSA lib control.c:953:(snd_ctl_open_noupdate) Invalid CTL 
ALSA lib control.c:953:(snd_ctl_open_noupdate) Invalid CTL 
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM 
ALSA lib control.c:953:(snd_ctl_open_noupdate) Invalid CTL 
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM 
ALSA lib control.c:953:(snd_ctl_open_noupdate) Invalid CTL 
ALSA lib control.c:953:(snd_ctl_open_noupdate) Invalid CTL 
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM 
ALSA lib control.c:953:(snd_ctl_open_noupdate) Invalid CTL 
ALSA lib control.c:953:(snd_ctl_open_noupdate) Invalid CTL 
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM 
undefined

> /home/ubuntu/WebRTC/WebRTCPeer.js:1596: Uncaught TypeError: undefined is not a function

(note:  /home/ubuntu/WebRTC/WebRTCPeer.js is only 115 lines, so I don't know why it's complaining about line 1596).

This is ubuntu 14.04 and node 0.10.29, installed via the ppa.

It's on an lxc virtual machine which does not have a sound card.  That's probably the problem.  But I don't need sound or video -- I just want this peer to use the DataChannel.  This should be possible and should not error out.

**Comment by modeswitch** [comment]
This file `/home/ubuntu/WebRTC/WebRTCPeer.js:1596` isn't part of node-webrtc. Is that your own code?

**Comment by galaxor** [comment]
Yeah, sorry I wasn't clear about that.  WebRTCPeer.js is my own code.  Just a little wrapper that instantiates stuff, to test out the api of node-webrtc.  So I figure whatever file has a problem on line 1596, it's not mine, but there's no way to actually know where it is.

**Comment by modeswitch** [comment]
If you link me to your project I can have a look.

**Comment by venturio1256** [comment]
Hi, 
I have the same issue when I run the streamtest example.
node examples/streamtest/webbridge.js 
ALSA lib control.c:951:(snd_ctl_open_noupdate) Invalid CTL 
ALSA lib control.c:951:(snd_ctl_open_noupdate) Invalid CTL 
ALSA lib control.c:951:(snd_ctl_open_noupdate) Invalid CTL 
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM 
ALSA lib control.c:951:(snd_ctl_open_noupdate) Invalid CTL 
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM 
ALSA lib control.c:951:(snd_ctl_open_noupdate) Invalid CTL 
ALSA lib control.c:951:(snd_ctl_open_noupdate) Invalid CTL 
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM 
ALSA lib control.c:951:(snd_ctl_open_noupdate) Invalid CTL 
ALSA lib control.c:951:(snd_ctl_open_noupdate) Invalid CTL 
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM 

then the normal log messages from webbridge.js and finally
WARMING: no real random source present!
ALSA lib control.c:951:(snd_ctl_open_noupdate) Invalid CTL 
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM 

on ubuntu 12.04TLS (@digitalocean). I upgraded the libasound2-plugins as recommended after a google search.. but same result. Don't understand this message. Should I have video source on the node.js server side?!!!!

**Comment by modeswitch** [comment]
I disabled the existing media stream implementation due to debugging issues. See https://github.com/js-platform/node-webrtc/commit/cd69bf647686822bc572b1fe059e5299e39a9e6c

There's some additional work to be done to get the media streams API going.

**Comment by venturio1256** [comment]
Thank you for your prompt response. I am checking the commit but not a very good C guy. Is that means the remote stream from the browser not available on the node.js side?

**Comment by modeswitch** [comment]
Yeah, no streams yet. I'm just getting back to working on this project after some time away.

**Comment by modeswitch** [comment]
Media streams won't be supported in the native backend. Only data channels.
