### ISSUE TITLE
Extract Chromium WebRTC v8 bindings?

### ISSUE THREAD

**Issue by blakelapierre** [node-webrtc/node-webrtc#140]
Have you thought about trying to extract Chromium's WebRTC bindings instead of reimplementing them?

I'm not too familiar with Chromium's source yet, but I've been looking into it the last two days. It looks like Chromium auto-generates the bindings: https://code.google.com/p/chromium/codesearch#chromium/src/out/Debug/gen/blink/bindings/modules/v8/&sq=package:chromium

One problem I see is that there are a decent number of includes for DOM related file, which we probably don't want.

I'll be looking more into how they are generating these files.

**Comment by modeswitch** [comment]
Yeah, there's a bunch of DOM-related stuff in there (same with Firefox), and we need to handle things like buffers. The bindings aren't that complicated anyway.

**Comment by blakelapierre** [comment]
I've been looking into it because I am getting segmentation faults that seem to be coming from nowhere, when returning the array from MediaStream::getAudioTracks and MediaStream::getVideoTracks.

The current code works on my dev machine and segfaults on the production machine [of course]. I've been pouring through v8 documentation and example code [Very little out there directly returns arrays of wrapped objects], and I just don't see anything wrong with the code.

Realized Chrome must already have this code somewhere and decided to look for it. It has its own routines for setting up the bindings that are not as straightforward as the current code or other v8 bindings out there, which makes it difficult to pull any of its code directly into this project.

**Comment by modeswitch** [comment]
Are you running with identical shared libraries in both environments?

**Comment by blakelapierre** [comment]
No, one is a Fedora 20 machine, the other is a Ubuntu14.04+Docker VM on Digital Ocean.

Both machines pull all their own dependencies and run the build themselves. One issue with the Digital Ocean machine is that it doesn't have a soundcard, so I've loaded up the `snd-dummy` module.

The seg fault occurs in HandleScope::RawClose. I'll make an issue on it soon.

**Comment by modeswitch** [comment]
Given the backend differences, I'm going to close this and continue using the hand-generated bindings.

**Comment by markandrus** [comment]
This issue has been closed for a while, but I was reinvestigating the possibility of using the existing [`idl_compiler.py`](https://www.chromium.org/developers/design-documents/idl-compiler) with a different code generator. This would be nice, as we could get the already implemented argument validation for the various WebRTC constructors and methods for "free" and get behavior closer to that which is in Chrome; however, the work involved appears very large and would require a rewrite of the templates used by `code_generator_v8.py`. Not to mention there are additional components in the Chromium layer that interface between WebRTC and the Blink/V8 bindings. I think hand-generated bindings are still the way to go, perhaps cross-referenced with the WebIDL and generated bindings.
