### ISSUE TITLE
DataChannel.send() sometimes does nothing

### ISSUE THREAD

**Issue by makkes** [node-webrtc/node-webrtc#144]
When testing our DataChannel-heavy application in node-webrtc we sometimes have the effect that calling send() on a DataChannel doesn't result in the data being sent to the remote end. We're currently trying to reproduce the issue but as of now would like to ask, if that is a known problem.

**Comment by cjb** [comment]
@Makkes I haven't seen this happen, but it's quite possible that you're the heaviest user of datachannels in wrtc.

**Comment by modeswitch** [comment]
I haven't encountered this. Does it occur shortly after the channel transitions to open?

**Comment by makkes** [comment]
Hej,

I've created a very simple test scenario script: https://gist.github.com/Makkes/44675a0ef9c61aa88283

It creates 10 PeerConnections and 5 DataChannels. On each channel it sends a 'ping' from A to B and B answers with a 'pong'. When the ping/pong pair has been transferred on each DataChannel, the script exits.

When you call that script with 'node test.js', it sometimes hangs after 3 or 4 transfers. We tested it under Linux and OSX.

**Comment by makkes** [comment]
I've updated the Gist so that you can play around with the number of PCs created more easily (MAX_PCS). It seems that, independently of the total number of PCs the script creates, there is always only one DataChannel that hangs.

**Comment by makkes** [comment]
Is there any update on this issue? Were you able to reproduce it? If I can be of any further help, do not hesitate to drop me a line.

**Comment by modeswitch** [comment]
I haven't had a chance to look into this yet. I'll have some time when I'm back in Canada.

**Comment by jcrubino** [comment]
Bump.
Have you run an strace on it? 
I can get up to a MAX_PCS of 40 to complete the script.

**Comment by modeswitch** [comment]
Yeah, I'll have a look. I need to check through libjingle to see what has changed, it may need an update as well.

**Comment by modeswitch** [comment]
@Makkes Are you still experiencing this with the latest build?
