### ISSUE TITLE
Investigate openwebrtc

### ISSUE THREAD

**Issue by modeswitch** [node-webrtc/node-webrtc#145]
https://github.com/EricssonResearch/openwebrtc/

**Comment by cjb** [comment]
Already investigated.  :)  There's no datachannel support at all right now.

**Comment by gigafied** [comment]
Data channels are now supported in openwebrtc, might be work re-evaluating?

I've personally run into several issues with `libjingle` and getting attention/traction on Chrome src issues, is very hard.

**Comment by modeswitch** [comment]
@gigafied Indeed. I had a look at the build process for `openwebrtc` and it's much simpler than `libjingle`. As long as the DataChannel support is on par, I'm open to switching over.

**Comment by modeswitch** [comment]
Potential downside here is no support on Windows. That might be a deal breaker.

**Comment by maritz** [comment]
Supposedly it should be simple to implement according to the openwebrtc guys. So if there are people invested enough in this, they would be welcome to add support for it. So I think that shouldn't be a large downside.

What exactly are the upsides of using openwebrtc over libjingle?
