### ISSUE TITLE
dont get onclose event

### ISSUE THREAD

**Issue by bjoernKulas** [node-webrtc/node-webrtc#146]
Hi,
first of all, thank you for this nice nodeJS module.

I have a problem, when i close the webrtc datachannel. 
I use a test website in Firefox on side A and your webrtc module on side B, on a linux machine with nodejs. Before i used your webrtc module i tested with Chrome on side B,
If i disconnect the connection on side A (call dataChannel.close(); ), side B dont get the close event. So i cant create a new dataChannel later, if i connect the b side client again.
onerror, onopen and onmessage works fine, i get all events.

Must i do anything else  as with chrome, to get the close event?

**Comment by modeswitch** [comment]
Can you share a test case for this?

**Comment by modeswitch** [comment]
Can you retest this on the latest build?

**Comment by bjoernKulas** [comment]
Hi,
it works very well now, I get the event and the correct readyState, perfect! Thank you for your great work and please excuse my late reply
