### ISSUE TITLE
Max number of peer's

### ISSUE THREAD

**Issue by murugan-pandian** [node-webrtc/node-webrtc#147]
Max number of peer's for client request

**Comment by modeswitch** [comment]
Can you provide more details? I'm not clear what the problem is.

**Comment by murugan-pandian** [comment]
ya sure,I plan to use node-webrtc for MCU,So i need to know maximum number of peers can able to connect node-webrtc

**Comment by modeswitch** [comment]
There isn't a special limit in node-webrtc.
