### ISSUE TITLE
Consider Implementing Testing using Tape

### ISSUE THREAD

**Issue by DamonOehlman** [node-webrtc/node-webrtc#15]
Hey Alan,

Love what you are doing here. I hope that you, with assistance from @helloIAmPau and others can turn this into an awesome WebRTC binding for node.  We definitely need one.

I'd be happy to pitch in with development as well (doing a lot of stuff with WebRTC over at https://github.com/rtc-io - keeping a low profile at the moment but I think we've got some good stuff in the mix).

Anyway, one of the things I'd recommend very early on is considering using [tape](https://github.com/substack/tape) for testing.  In combination with [testling](https://github.com/substack/testling) it's a great way to do testing between node and browser environments.

If you'd be open to going this way, then I'd be happy to take on implementation of a pretty solid suite of tests using tape straight up.

Cheers,
Damon.

**Comment by Raynos** [comment]
:+1: for tape & testling.

**Comment by modeswitch** [comment]
Thanks! I'd love to have a good suite of tests for this, if you're volunteering :)

**Comment by DamonOehlman** [comment]
Sure am - will fork and send through a PR for you to review in the next couple of days.

**Comment by DamonOehlman** [comment]
Sorry about the delay on this guys, got caught up with some other stuff in the WebRTC work that I'm doing.  Well get it through as soon as I can...

**Comment by modeswitch** [comment]
I think I closed this by accident yesterday. Reopening.

**Comment by modeswitch** [comment]
@DamonOehlman Also, no worries! I've been AFK at a conference so I'm just getting back to work this week.

**Comment by modeswitch** [comment]
@DamonOehlman Heya, are you still interested in tackling this?

**Comment by DamonOehlman** [comment]
@modeswitch Yeah, sorry Alan.  Got caught up doing other WebRTC things and also a trip to the US.

Let me see if I can make some progress on this over the next couple of days...

**Comment by DamonOehlman** [comment]
Having a look at this now...

Would be great to see #33 implemented when possible as this will definitely assist with validating connectivity between two server side peers is working.

For the moment, I'll just write the tests to check for iceConnectionState of connected.

**Comment by DamonOehlman** [comment]
Some progress here: https://github.com/DamonOehlman/node-webrtc/tree/tape-tests/test

Another nice to have would be the `close` method on the peerconnection so I can clean up after my self and have the tape tests close cleanly.  I can't see an open issue for this yet, so did you want me to create one?

**Comment by modeswitch** [comment]
I'm doing createDataChannel tonight/tomorrow and I'll do close as well. Shouldn't be too bad.

Yay for tests :)

**Comment by DamonOehlman** [comment]
Another progress update - unable to setup a connection at this stage between two peer connections.  Everything seems to progress nicely until you are setting the remote description of the peer that originally created the offer with the peer that generated the answer:

```
➜  node-webrtc git:(tape-tests) ✗ node test/connect.js
TAP version 13
# create the peer connections
ok 1 peer:0 created ok
ok 2 peer:1 created ok
# peers are created and in the expected connection state
ok 3 should be equal
ok 4 should be equal
# create a datachannel on peer:0
ok 5 (unnamed assert)
ok 6 created with correct label
# createOffer for peer:0
ok 7 createOffer succeeded
ok 8 type === offer
ok 9 got sdp
# setLocalDescription for peer:0
ok 10 ok
# setRemoteDescription for peer:1
ok 11 ok
# createAnswer for peer:1
ok 12 createOffer succeeded
ok 13 type === answer
ok 14 got sdp
# setLocalDescription for peer:1
ok 15 ok
# setRemoteDescription for peer:0
node: symbol lookup error: /home/doehlman/code/github/node-webrtc/build/Release/webrtc.node: undefined symbol: _ZN6webrtc13SincResampler12Convolve_SSEEPKfS2_S2_d
```

The test logic can be found here:

https://github.com/DamonOehlman/node-webrtc/blob/tape-tests/test/connect.js

**Comment by modeswitch** [comment]
Looks like something got missed at link time. What platform are you on?

**Comment by DamonOehlman** [comment]
Linux 64bit.  Here's the output of `uname -a`:

```
➜  switchboard git:(master) uname -a
Linux nicta-djo 3.8.0-33-generic #48-Ubuntu SMP Wed Oct 23 09:16:58 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by modeswitch** [comment]
SDP offer from tests/peer.html:

```
v=0
o=- 5657877242864809896 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE audio data
a=msid-semantic: WMS
m=audio 1 RTP/SAVPF 111 103 104 0 8 106 105 13 126
c=IN IP4 0.0.0.0
a=rtcp:1 IN IP4 0.0.0.0
a=ice-ufrag:1MqClSRLo+pvWZhT
a=ice-pwd:8DIMJ/OOBSwJDNNRN1raTR8X
a=ice-options:google-ice
a=mid:audio
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=recvonly
a=rtcp-mux
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:VSV4TknrfTGGxXw9tEs4OeZ29acqBQy54hLH4jR8
a=rtpmap:111 opus/48000/2
a=fmtp:111 minptime=10
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:126 telephone-event/8000
a=maxptime:60
m=application 1 RTP/SAVPF 101
c=IN IP4 0.0.0.0
a=rtcp:1 IN IP4 0.0.0.0
a=ice-ufrag:1MqClSRLo+pvWZhT
a=ice-pwd:8DIMJ/OOBSwJDNNRN1raTR8X
a=ice-options:google-ice
a=mid:data
a=sendrecv
b=AS:30
a=rtcp-mux
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:VSV4TknrfTGGxXw9tEs4OeZ29acqBQy54hLH4jR8
a=rtpmap:101 google-data/90000
a=ssrc:3802960094 cname:rxsLGVBQyH8aK5KG
a=ssrc:3802960094 msid:reliable reliable
a=ssrc:3802960094 mslabel:reliable
a=ssrc:3802960094 label:reliable
```

**Comment by modeswitch** [comment]
SDP offer from test/connect.js:

```
v=0
o=- 2853063460030502758 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE audio data
a=msid-semantic: WMS
m=audio 1 RTP/SAVPF 111 103 104 9 102 0 8 106 105 13 127 126
c=IN IP4 0.0.0.0
a=rtcp:1 IN IP4 0.0.0.0
a=ice-ufrag:EGQkQTq0eBi6Inh9
a=ice-pwd:LgXG16XKfRN0DrbS0nt0L/Su
a=ice-options:google-ice
a=fingerprint:sha-1 66:34:86:68:38:A7:4E:D0:92:FF:A6:93:F2:25:79:7E:18:54:E1:F9
a=setup:actpass
a=mid:audio
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=recvonly
a=rtcp-mux
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:X0rFdvn4Yq87hm2A1k9b9OJmO6hmxiOZSwQcQw7a
a=rtpmap:111 opus/48000/2
a=fmtp:111 minptime=10
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/16000
a=rtpmap:102 ILBC/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:127 red/8000
a=rtpmap:126 telephone-event/8000
a=maxptime:60
m=application 1 RTP/SAVPF 101
c=IN IP4 0.0.0.0
a=rtcp:1 IN IP4 0.0.0.0
a=ice-ufrag:EGQkQTq0eBi6Inh9
a=ice-pwd:LgXG16XKfRN0DrbS0nt0L/Su
a=ice-options:google-ice
a=fingerprint:sha-1 66:34:86:68:38:A7:4E:D0:92:FF:A6:93:F2:25:79:7E:18:54:E1:F9
a=setup:actpass
a=mid:data
a=sendrecv
b=AS:30
a=rtcp-mux
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:X0rFdvn4Yq87hm2A1k9b9OJmO6hmxiOZSwQcQw7a
a=rtpmap:101 google-data/90000
a=ssrc:1246936916 cname:37CcCiQJ37sNSi6L
a=ssrc:1246936916 msid:test test
a=ssrc:1246936916 mslabel:test
a=ssrc:1246936916 label:test
```

**Comment by modeswitch** [comment]
Btw, I get the same error on my machine so I can help debug.

**Comment by modeswitch** [comment]
Response SDP from tests/peer.html:

```
=0
o=- 24662356135063817 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE audio data
a=msid-semantic: WMS
m=audio 1 RTP/SAVPF 111 103 104 0 8 106 105 13 126
c=IN IP4 0.0.0.0
a=rtcp:1 IN IP4 0.0.0.0
a=ice-ufrag:ewjH+R9KA+iJbrHu
a=ice-pwd:9kjR8LeK5VBGVbcttI6eCaLR
a=mid:audio
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=sendonly
a=rtcp-mux
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:m4dN2zrj9b8H9lbtGrsnAFhHLhLCN8DoyS/+rcsd
a=rtpmap:111 opus/48000/2
a=fmtp:111 minptime=10
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:126 telephone-event/8000
a=maxptime:60
m=application 1 RTP/SAVPF 101
c=IN IP4 0.0.0.0
a=rtcp:1 IN IP4 0.0.0.0
a=ice-ufrag:ewjH+R9KA+iJbrHu
a=ice-pwd:9kjR8LeK5VBGVbcttI6eCaLR
a=mid:data
a=sendrecv
b=AS:30
a=rtcp-mux
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:m4dN2zrj9b8H9lbtGrsnAFhHLhLCN8DoyS/+rcsd
a=rtpmap:101 google-data/90000
a=ssrc:2257534059 cname:4FNU/oH2Nps4+wnM
a=ssrc:2257534059 msid:reliable reliable
a=ssrc:2257534059 mslabel:reliable
a=ssrc:2257534059 label:reliable
```

**Comment by modeswitch** [comment]
Response SDP from test/connect.js:

```
v=0
o=- 2641811076965454830 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE audio data
a=msid-semantic: WMS
m=audio 1 RTP/SAVPF 111 103 104 9 102 0 8 106 105 13 127 126
c=IN IP4 0.0.0.0
a=rtcp:1 IN IP4 0.0.0.0
a=ice-ufrag:yyBAP/JhMNU+Q1bl
a=ice-pwd:vfWx7LxOPj5SQy4uG4wVdl/d
a=fingerprint:sha-1 48:DC:3D:CE:0D:35:4A:5D:05:33:91:D7:AA:BB:21:CC:6E:8F:AF:FB
a=setup:active
a=mid:audio
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=sendonly
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=fmtp:111 minptime=10
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/16000
a=rtpmap:102 ILBC/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:127 red/8000
a=rtpmap:126 telephone-event/8000
a=maxptime:60
m=application 1 RTP/SAVPF 101
c=IN IP4 0.0.0.0
a=rtcp:1 IN IP4 0.0.0.0
a=ice-ufrag:yyBAP/JhMNU+Q1bl
a=ice-pwd:vfWx7LxOPj5SQy4uG4wVdl/d
a=fingerprint:sha-1 48:DC:3D:CE:0D:35:4A:5D:05:33:91:D7:AA:BB:21:CC:6E:8F:AF:FB
a=setup:active
a=mid:data
a=sendrecv
b=AS:30
a=rtcp-mux
a=rtpmap:101 google-data/90000
a=ssrc:2333484524 cname:bajVYh4UVDcddIUk
a=ssrc:2333484524 msid:test test
a=ssrc:2333484524 mslabel:test
a=ssrc:2333484524 label:test
```

**Comment by modeswitch** [comment]
I think it might be trying to offer audio, which isn't supported. Investigating.

**Comment by modeswitch** [comment]
@DamonOehlman I pushed up a small change that should fix this issue. Can you test and let me know?

**Comment by modeswitch** [comment]
@DamonOehlman Also, make sure to pull from `develop` since I've made that the default branch now.

**Comment by DamonOehlman** [comment]
Cool - thanks Alan.  I'll give it a test soon.

**Comment by DamonOehlman** [comment]
Nice - all fixed.  Will keep pushing ahead with the tests :)

**Comment by modeswitch** [comment]
@DamonOehlman I've implemented enough cleanup so that the tests can exit when you close the peer connections. Hopefully that will let the tests run properly.

**Comment by DamonOehlman** [comment]
Awesome - I'll be back into stuff tomorrow so I'll take a look then :)

**Comment by DamonOehlman** [comment]
Yep looking good so far.  I'm going to hack around #44 for the moment so should be able to progress to a point where two local peer connections are sending messages to each other really soon :)

**Comment by DamonOehlman** [comment]
Right, I reckon we are in a position where these are worth merging back into the `develop` branch.  There are two pull requests I have created (#60 and #61) which need to be applied for the tests to pass, but once they are I'll raise another pull request to bring the tape tests in.

From there, I'll do feature-branches to add new tests (such as data channel comms, etc).  

Things are looking really good - thanks @modeswitch and others for your continued hard work on this project!

**Comment by modeswitch** [comment]
First round of Tape tests are merged and passing.
