### ISSUE TITLE
Failed to construct 'RTCIceCandidate': The 'candidate' property is not a string, or is empty.

### ISSUE THREAD

**Issue by kevzettler** [node-webrtc/node-webrtc#150]
Getting this from `examples/bridge.js`

is that a concern?
![screenshot 2014-12-24 13 04 09](https://cloud.githubusercontent.com/assets/126209/5551041/82c0ace0-8b6d-11e4-98bb-f89238e94578.png)

**Comment by modeswitch** [comment]
Yeah, it might be that `bridge.js` hasn't been updated in a while. I merged a patch a while ago that sends a null candidate after that last ice candidate, so the browser side of the bridge may not be checking for that.

**Comment by modeswitch** [comment]
This should be fixed now.
