### ISSUE TITLE
wrtc not build on window

### ISSUE THREAD

**Issue by vahpetr** [node-webrtc/node-webrtc#155]
Hello

>  : Updating clang ...
>   events.js:72
>           throw er; // Unhandled 'error' event
>                 ^
> CUSTOMBUILD : error : spawn ENOENT [C:\Users\admin\AppData\Roaming\npm\node_mod
> ules\wrtc\build\action_before_build.vcxproj]
>       at errnoException (child_process.js:1001:11)
>       at Process.ChildProcess._handle.onexit (child_process.js:792:34)
>   binding.cc
>   create-offer-observer.cc
>   create-answer-observer.cc
>   set-local-description-observer.cc
>   set-remote-description-observer.cc
>   peerconnection.cc
>   datachannel.cc
> c:\users\admin\appdata\roaming\npm\node_modules\wrtc\src\create-answer-observer
> .h(1): fatal error C1083: Cannot open include file: 'talk/app/webrtc/peerconnec
> tioninterface.h': No such file or directory (..\src\create-answer-observer.cc)
> [C:\Users\admin\AppData\Roaming\npm\node_modules\wrtc\build\wrtc.vcxproj]
> c:\users\admin\appdata\roaming\npm\node_modules\wrtc\src\set-remote-description
> -observer.h(1): fatal error C1083: Cannot open include file: 'talk/app/webrtc/p
> eerconnectioninterface.h': No such file or directory (..\src\set-remote-descrip
> tion-observer.cc) [C:\Users\admin\AppData\Roaming\npm\node_modules\wrtc\build\w
> rtc.vcxproj]
> c:\users\admin\appdata\roaming\npm\node_modules\wrtc\src\create-offer-observer.
> h(1): fatal error C1083: Cannot open include file: 'talk/app/webrtc/peerconnect
> ioninterface.h': No such file or directory (..\src\create-offer-observer.cc) [C
> :\Users\admin\AppData\Roaming\npm\node_modules\wrtc\build\wrtc.vcxproj]
> c:\users\admin\appdata\roaming\npm\node_modules\wrtc\src\set-local-description-
> observer.h(1): fatal error C1083: Cannot open include file: 'talk/app/webrtc/pe
> erconnectioninterface.h': No such file or directory (..\src\set-local-descripti
> on-observer.cc) [C:\Users\admin\AppData\Roaming\npm\node_modules\wrtc\build\wrt
> c.vcxproj]
> ..\src\binding.cc(4): fatal error C1083: Cannot open include file: 'webrtc/base
> /ssladapter.h': No such file or directory [C:\Users\admin\AppData\Roaming\npm\n
> ode_modules\wrtc\build\wrtc.vcxproj]
> C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xlocale(337): wa
> rning C4530: C++ exception handler used, but unwind semantics are not enabled.
> Specify /EHsc (..\src\datachannel.cc) [C:\Users\admin\AppData\Roaming\npm\node_
> modules\wrtc\build\wrtc.vcxproj]
> C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xlocale(337): wa
> rning C4530: C++ exception handler used, but unwind semantics are not enabled.
> Specify /EHsc (..\src\peerconnection.cc) [C:\Users\admin\AppData\Roaming\npm\no
> de_modules\wrtc\build\wrtc.vcxproj]
> ..\src\peerconnection.cc(11): fatal error C1083: Cannot open include file: 'tal
> k/app/webrtc/jsep.h': No such file or directory [C:\Users\admin\AppData\Roaming
> \npm\node_modules\wrtc\build\wrtc.vcxproj]
> ..\src\datachannel.cc(7): fatal error C1083: Cannot open include file: 'talk/ap
> p/webrtc/jsep.h': No such file or directory [C:\Users\admin\AppData\Roaming\npm
> \node_modules\wrtc\build\wrtc.vcxproj]
> gyp ERR! build error
> gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` fail
> ed with exit code: 1
> gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
> npm\node_modules\node-gyp\lib\build.js:267:23)
> gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:
> 12)
> gyp ERR! System Windows_NT 6.2.9200
> gyp ERR! command "node" "C:\Program Files\nodejs\node_modules\npm\node_modu
> les\node-gyp\bin\node-gyp.js" "rebuild"
> gyp ERR! cwd C:\Users\admin\AppData\Roaming\npm\node_modules\wrtc
> gyp ERR! node -v v0.10.33
> gyp ERR! node-gyp -v v1.0.1
> gyp ERR! not ok
> npm ERR! wrtc@0.0.44 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the wrtc@0.0.44 install script.
> npm ERR! This is most likely a problem with the wrtc package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-gyp rebuild
> npm ERR! You can get their info via:
> npm ERR!     npm owner ls wrtc
> npm ERR! There is likely additional logging output above.
> npm ERR! System Windows_NT 6.2.9200
> npm ERR! command "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nod
> ejs\node_modules\npm\bin\npm-cli.js" "update" "wrtc" "-g"
> npm ERR! cwd C:\Windows\system32
> npm ERR! node -v v0.10.33
> npm ERR! npm -v 1.4.28
> npm ERR! code ELIFECYCLE
> npm ERR! not ok code 0

**Comment by modeswitch** [comment]
Windows isn't a supported platform yet.

**Comment by wubin1989** [comment]
I encountered the same error. When will it be supported for windows platform?
