### ISSUE TITLE
Is it possible to stream audio/video over data channels?

### ISSUE THREAD

**Issue by modeswitch** [node-webrtc/node-webrtc#156]
https://github.com/muaz-khan/WebRTC-Experiment/tree/master/RecordRTC
https://github.com/streamproc/MediaStreamRecorder

Seems like it might be possible.

**Comment by markandrus** [comment]
@modeswitch Yes, see the [MediaSource API](https://developer.mozilla.org/en-US/docs/Web/API/MediaSource) and [this example](http://html5-demos.appspot.com/static/media-source.html). Splitting a pre-recording file into chunks and sending them down over the data channel should be doable. Reconstructing them in a &lt;video&gt; element in the browser would look roughly like

``` javascript
var mediaSource = new MediaSource();
var sourceBuffer = mediaSource.addSourceBuffer('video/webm; codecs="vorbis,vp8"');

// Then, for each chunk of your file...
sourceBuffer.appendBuffer(new Uint8Array(data));
```

**Comment by modeswitch** [comment]
Very cool. This looks like an acceptable workaround for media streams using the current native codebase.

**Comment by amki** [comment]
Do you also have a workaround for receiving and sending MediaStreams generated with getUserMedia?

**Comment by zhirzh** [comment]
webrtc also features media streams, which are meant for live stream (i.e., with getUserMedia).
Read more [here](https://developer.mozilla.org/en-US/docs/Web/API/MediaStream) and (here)[https://developer.mozilla.org/en-US/docs/Web/API/Media_Streams_API]

**Comment by zhirzh** [comment]
webrtc also features media streams, which are meant for live stream (i.e., with getUserMedia).
Read more [here](https://developer.mozilla.org/en-US/docs/Web/API/MediaStream) and [here](https://developer.mozilla.org/en-US/docs/Web/API/Media_Streams_API)

**Comment by amki** [comment]
I know but this library doesn't support them so I can't handle them server-side.

**Comment by mitar** [comment]
+1 for the media streams support. Maybe that could be a compilation time switch?

**Comment by mitar** [comment]
It seems [simple-peer](https://github.com/feross/simple-peer) supports it?

**Comment by tjacobs** [comment]
+1 what library has mediastreams?

**Comment by aep** [comment]
Not actually handling media stuff in the node module makes alot of sense, but wouldn't it be sufficient to  just have it expose it as callbacks so that can be used to implement the actual media stream?

**Comment by mitar** [comment]
I am not really getting relation between this package and [simple-peer](https://github.com/feross/simple-peer), but it seems simple-peer support media streams?

**Comment by zycbobby** [comment]
@mitar I dont think so, simple-peer just take advantage of this project. And media stream API is only available on the browser

**Comment by t-mullen** [comment]
You can provide MediaStream to [media-recorder-stream](https://github.com/mafintosh/media-recorder-stream), pipe the recording into the datachannel, then reassemble a MediaSource with [media-source-stream](https://www.npmjs.com/package/media-source-stream).

Note that you will need to receive the entire recorder stream from start or the MediaSource won't be able to reassemble the video. (You can't start midway like a normal MediaConnection). But that shouldn't be a problem if you're careful with when you start recording.

[DEMO!](https://t-mullen.github.io/media-source-stream/)

**Comment by chuuuing** [comment]
for audio/video streaming you could use 
```
navigator.mediaDevices.getUserMedia({audio: true, video: true}).then((stream)=>{
const track = stream.getTracks()[0];
myWebRTC.addTrack(track, stream);
})
```
