### ISSUE TITLE
Check tools and library deps during install process

### ISSUE THREAD

**Issue by modeswitch** [node-webrtc/node-webrtc#157]
The build script should check for tools like `git` and `python`, as well as make sure that various library dependencies are available and report errors if they aren't. This should happen before any building starts and emit meaningful error messages.

**Comment by piranna** [comment]
Check for git & python should be better be done on node-gyp, maybe it's already available there and if not it should be done a pull-request...

**Comment by modeswitch** [comment]
@piranna Yeah, python is required for gyp anyway.

**Comment by modeswitch** [comment]
@piranna Is there a way to have node-gyp do this?

**Comment by piranna** [comment]
I don't know if it's doing it already, but it should. I think the best place is to add a script for their preinstall stage, I'm doing something similar on NodeOS but instead of checking for the tools and libraries I'm downloading and compiling them =<:*P
