### ISSUE TITLE
Receiving calls with audio/video using node-webrtc on node server.

### ISSUE THREAD

**Issue by azfx** [node-webrtc/node-webrtc#158]
I am using node-webrtc with onsip ( sipjs ) on a node server, and wondering if a webrtc call with audio/video can me made to the node peer. The intent is to record audio/video on the server side. I could not find enough info to determine if audio/video stream is supported or not in such configuration.

**Comment by modeswitch** [comment]
It isn't possible at this time using mediastreams; Only data channels are supported.

**Comment by cdcv** [comment]
@modeswitch do you have any suggestions regarding how to do this?  The goal is either to 
A) record the audio/video of a videochat session either directly on the node.js server, or to 
B) transfer the stream through the node.js server to another (non-node.js) server that is setup to do the recording.  
Do you have thoughts on:
1) Whether it would be possible to do A or B using data channels, or currently supported approaches
2) If mediastreams are required to do A&B, how much of a project it would be for us to add mediastreams to sipjs, and whether there is information available that we would need to do this.

**Comment by modeswitch** [comment]
If you can proxy the A/V data over a data channel, that might work. One possibility is to have one of the peers do the recording/mixing and then stream that to the server over a data channel.
