### ISSUE TITLE
Segmentation fault with node 0.12

### ISSUE THREAD

**Issue by xenyou** [node-webrtc/node-webrtc#164]
Segmentation fault  happened when accesing peer.html on the machine running bridge.js with node 0.12.

My environments: 
Mac OS X 10.10.2
node 0.12

FYI, node 0.10 is fine.

**Comment by modeswitch** [comment]
I don't have an OSX machine. Can you get a full stack trace?

**Comment by xenyou** [comment]
mm:node-webrtc xenyou$ node examples/bridge.js 
Server running at http://127.0.0.1:8080/
/peer.html
/dist/wrtc.js
/peer.js
ws connected
{ type: 'offer',
  sdp: 'v=0\r\no=- 321867104974075173 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=msid-semantic: WMS\r\nm=application 9 DTLS/SCTP 5000\r\nc=IN IP4 0.0.0.0\r\na=ice-ufrag:aE6p0bmsf0quYcH8\r\na=ice-pwd:WPsutumNeGVwC+FTjbky5AHS\r\na=ice-options:google-ice\r\na=fingerprint:sha-256 67:1B:D2:30:68:71:90:A9:19:BA:A9:F7:67:3F:AA:67:E9:40:AD:03:DD:66:96:EF:52:6D:9E:A8:41:2F:FE:9E\r\na=setup:actpass\r\na=mid:data\r\na=sctpmap:5000 webrtc-datachannel 1024\r\n' }
/favicon.ico
signaling state change: { type: 'signalingstatechange' }
{ type: 'answer',
  sdp: 'v=0\r\no=- 3288416599795643684 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=msid-semantic: WMS\r\nm=application 9 DTLS/SCTP 5000\r\nc=IN IP4 0.0.0.0\r\nb=AS:30\r\na=ice-ufrag:MLCqxqV40QuxoTyP\r\na=ice-pwd:o9qv+9gt1sn7VVK03AuJVpnC\r\na=fingerprint:sha-1 01:A7:57:E4:CC:82:2D:4C:93:93:45:0F:55:A2:5E:3A:17:01:6C:00\r\na=setup:active\r\na=mid:data\r\na=sctpmap:5000 webrtc-datachannel 1024\r\n' }
signaling state change: { type: 'signalingstatechange' }
ice connection state change: { type: 'iceconnectionstatechange' }
ice gathering state change: { type: 'icegatheringstatechange' }
awaiting data channels
ice gathering state change: { type: 'icegatheringstatechange' }
ice connection state change: { type: 'iceconnectionstatechange' }
ondatachannel reliable open
onopen
complete
onmessage: {}
Segmentation fault: 11
mm:node-webrtc xenyou$

**Comment by xenyou** [comment]
With node 0.12, it also aborted on Ubuntu 14.10.
FYI, node 0.10 is fine too.

```
/peer.html
ws connected
{ type: 'offer',
  sdp: 'v=0\r\no=- 5652935428804746780 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=msid-semantic: WMS\r\nm=application 9 DTLS/SCTP 5000\r\nc=IN IP4 0.0.0.0\r\na=ice-ufrag:/qTemhz65WjA6atS\r\na=ice-pwd:bOQEuyOAGoYHUVfmx5/d/9ts\r\na=ice-options:google-ice\r\na=fingerprint:sha-256 2B:36:3C:FA:29:13:B8:7C:21:C3:BF:78:79:A5:99:32:89:90:25:D4:83:D2:E7:68:F0:CD:E5:07:DF:76:E3:B7\r\na=setup:actpass\r\na=mid:data\r\na=sctpmap:5000 webrtc-datachannel 1024\r\n' }
signaling state change: { type: 'signalingstatechange' }
{ type: 'answer',
  sdp: 'v=0\r\no=- 3195511389444097912 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=msid-semantic: WMS\r\nm=application 9 DTLS/SCTP 5000\r\nc=IN IP4 0.0.0.0\r\nb=AS:30\r\na=ice-ufrag:FN7goHavd5g7/rF1\r\na=ice-pwd:vzzEWEyEqlwAvNytvaSbM1md\r\na=fingerprint:sha-1 93:96:74:24:AB:62:B3:C1:7B:5D:EB:C5:33:48:C7:CB:75:1B:B9:1A\r\na=setup:active\r\na=mid:data\r\na=sctpmap:5000 webrtc-datachannel 1024\r\n' }
signaling state change: { type: 'signalingstatechange' }
ice connection state change: { type: 'iceconnectionstatechange' }
ice gathering state change: { type: 'icegatheringstatechange' }
awaiting data channels
ice gathering state change: { type: 'icegatheringstatechange' }
ice connection state change: { type: 'iceconnectionstatechange' }
ondatachannel reliable open
onopen
complete
onmessage: {}
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
```

**Comment by modeswitch** [comment]
Thanks, I'll investigate. There were some changes in 0.12 that may be causing this.

**Comment by modeswitch** [comment]
I'm not seeing this crash on my machine. Is this happening on a clean build of node-webrtc with node-0.12?

**Comment by xenyou** [comment]
It reproduced again with another machine.
This time I installed it on clean Ubuntu 14.04 (EC2 64bit).

```
ubuntu@ip-172-31-1-233:~/hoge/node-webrtc$ node examples/bridge.js 
Server running at http://172.31.1.233:8080/
/peer.html
ws connected
{ type: 'offer',
  sdp: 'v=0\r\no=- 7425371630603557933 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=msid-semantic: WMS\r\nm=application 9 DTLS/SCTP 5000\r\nc=IN IP4 0.0.0.0\r\na=ice-ufrag:7c+f27+l+mkGwJFG\r\na=ice-pwd:JyMX7yQ1SSiVOY12OBckk08w\r\na=ice-options:google-ice\r\na=fingerprint:sha-256 EC:32:43:0C:ED:E4:FA:F9:A5:1F:7A:FB:BE:B9:CE:17:4C:E4:0B:12:80:9F:F4:9C:25:CD:67:20:E5:7E:FD:76\r\na=setup:actpass\r\na=mid:data\r\na=sctpmap:5000 webrtc-datachannel 1024\r\n' }
signaling state change: { type: 'signalingstatechange' }
{ type: 'answer',
  sdp: 'v=0\r\no=- 8665100527071000870 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=msid-semantic: WMS\r\nm=application 9 DTLS/SCTP 5000\r\nc=IN IP4 0.0.0.0\r\nb=AS:30\r\na=ice-ufrag:ucBKAKkA4Qk2RI/d\r\na=ice-pwd:c/54L2exJTPnYH0S5En+9rDj\r\na=fingerprint:sha-1 62:9E:2A:7B:54:58:D2:82:4B:68:C3:F9:33:26:97:EE:C9:70:35:79\r\na=setup:active\r\na=mid:data\r\na=sctpmap:5000 webrtc-datachannel 1024\r\n' }
signaling state change: { type: 'signalingstatechange' }
ice connection state change: { type: 'iceconnectionstatechange' }
ice gathering state change: { type: 'icegatheringstatechange' }
awaiting data channels
ice gathering state change: { type: 'icegatheringstatechange' }
ice connection state change: { type: 'iceconnectionstatechange' }
ondatachannel reliable open
onopen
complete
onmessage: {}
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
```

**Comment by modeswitch** [comment]
Does the unit test suite pass for you? (`npm test`)

**Comment by xenyou** [comment]
Yes. 

```
1..50
# tests 50
# pass  50

# ok
```
