### ISSUE TITLE
Failed to construct 'RTCIceCandidate': The 'candidate' property is not a string, or is empty.peer.js:159 ws.onmessage

### ISSUE THREAD

**Issue by xenyou** [node-webrtc/node-webrtc#165]
#150 still happens.

Chrome version is 40.0.2214.111.

https://github.com/js-platform/node-webrtc/issues/150

**Comment by remaininlight** [comment]
Also happening for me on Chrome 40.0.2214.115

**Comment by modeswitch** [comment]
Fixed. Verified in Chrome 40.0.2214.115 (64-bit) on Linux.
