### ISSUE TITLE
Failed to set remote answer sdp

### ISSUE THREAD

**Issue by xenyou** [node-webrtc/node-webrtc#166]
When running webbridge.js and accessing localhost:3000 with Chrome,
I got this error and onaddstream handler doesn't fire.

Uncaught Failed to set remote answer sdp: Session error code: ERROR_CONTENT. Session error description: Failed to set video send codecs..peerstream.js:57 logError

**Comment by modeswitch** [comment]
These tests rely on media stream functionality that has been removed. The tests are not gone as well.
