### ISSUE TITLE
Consider using NAN

### ISSUE THREAD

**Issue by DamonOehlman** [node-webrtc/node-webrtc#17]
Not sure if this will be of interest, but I know @rvagg built it to make writing native bindings to things more portable across node versions:

https://github.com/rvagg/nan

Additionally, it's worth noting that this was created to assist with the work Rod does with [leveldown](https://github.com/rvagg/node-leveldown) so it's been built and tested around a solid use case.

Just something to consider as I know the breadth of the underlying webrtc c++ library is pretty massive so anything that means writing less code is probably a good thing.

**Comment by rvagg** [comment]
Actually, it's **[ws](https://github.com/einaros/ws)** that gives NAN its hardest workout. Pretty much anyone that wants to use WebSockets with Node ends up installing ws. **[canvas](https://github.com/LearnBoost/node-canvas)** probably comes in second. **[zeromq](https://github.com/JustinTulloss/zeromq.node/pull/221)** is just waiting for Travis to get their act into gear with 0.11 before they merge in NAN to manage forward version compatibility.

**Comment by modeswitch** [comment]
Yeah, that seems reasonable. Not super high-priority at the moment, but a good step for improving portability.

**Comment by DamonOehlman** [comment]
Sure, I agree.  Just thought I'd point it out and let you know that Rod is super helpful if and when you do go down that path :)

**Comment by modeswitch** [comment]
Merged a pull from @kkoopa that fixes this.

**Comment by DamonOehlman** [comment]
Sweet - that's awesome :)
