### ISSUE TITLE
avoid the fork of libjingle as libwebrtc

### ISSUE THREAD

**Issue by guymguym** [node-webrtc/node-webrtc#174]
@modeswitch I took this from side topic to a separate issue

Forking an active project like libjingle is undesired.
You might already agree but just to make my point - the fork means I cannot pick a specific revision of libjingle in case of fast fixes, or go back to more stable revision, etc, and you as a maintainer have to do merges on sources that you didn't author (which is actually a very worrisome point from the perspective of a user of this project).

Can't this fork be avoided by taking only copy of the needed gyp's, and customise them to build just datachannels, and without unwanted deps, so that bin/build.js will just pull arbitrary selected revision from libjingle upstream and run the custom build?

Maintaining a copy of some build scripts seems much simpler than maintaining the whole fork.

**Comment by rosskukulinski** [comment]
For those not familiar with the node-webrtc build system, libwebrtc is downloaded and then built as a build dep: [https://github.com/js-platform/node-webrtc/blob/develop/bin/build.js#L12](here) and [https://github.com/js-platform/node-webrtc/blob/develop/bin/build.js#L160](here)

And the fork is stored here: [libwebrtc](https://github.com/js-platform/libwebrtc)

**Comment by modeswitch** [comment]
@guymguym 

> Forking an active project like libjingle is undesired.

That depends on what your goal is. It has advantages and drawbacks, to be sure. If you need an updated version of libjingle for some reason, you can build node-webrtc against it. The reasons for forking and removing a bunch of code are covered in other issues, so I won't rehash it here.

> Can't this fork be avoided by taking only copy of the needed gyp's, and customise them to build just datachannels, and without unwanted deps, so that bin/build.js will just pull arbitrary selected revision from libjingle upstream and run the custom build?

Feel free to make a pull request if you want to give it a try. This is just one approach.

In general, it shouldn't be too difficult to apply patches from upstream libjingle.

**Comment by guymguym** [comment]
@modeswitch thanks! i will give it a try soon and see if it works or not.
btw, how can I know which version of libjingle is currently merged into libwebrtc?

**Comment by modeswitch** [comment]
@guymguym The commit hashes are the same between repos, so you can check if a commit is in libwebrtc that way.
