### ISSUE TITLE
offerToCreateAudio is ignored

### ISSUE THREAD

**Issue by ibc** [node-webrtc/node-webrtc#177]
If I call to `createOffer()` with `options` as follows:

```
{
  offerToCreateAudio: 1,
  offerToCreateVideo: 1
}
```

It is totally ignored, no "audio" and "video" m lines are added (with "a=recvonly") and no local candidates are gathered at all. In fact the resulting SDP looks as follows:

```
v=0
o=- 2828113891054322321 2 IN IP4 127.0.0.1
s=-
t=0 0
a=msid-semantic: WMS
```

I've also tried using the old spec by passing `constraints` to the RTCPeerConnection instance as follows:

```
{
  mandatory: {
    OfferToReceiveAudio: true,
    OfferToReceiveVideo: true
  }
}
```

Same result. Nothing.

Which version of the Google WebRTC library does `node-webrtc` use? do I miss something?

**Comment by modeswitch** [comment]
Media streams are not supported. This is covered in more detail in other issues.

**Comment by ibc** [comment]
I suggest adding such a critical information into the README so people do not need to inspect so many closed issues in order to realize that media streams are not supported.
