### ISSUE TITLE
MediaStream is not defined in peerconnection.js

### ISSUE THREAD

**Issue by ibc** [node-webrtc/node-webrtc#179]
Clearly commented:

```
//var MediaStream               = require('./mediastream');
//var MediaStreamEvent          = require('./mediastreamevent');
```

but later:

``` javascript
  pc.onaddstream = function onaddstream(internalMS) {
    var ms = new MediaStream(internalMS);  // BUMP !

    that.dispatchEvent(new MediaStreamEvent('addstream', {stream: ms}));
  };
```

**Comment by modeswitch** [comment]
Media streams aren't supported, so this is dead code. I missed it during the last cleanup.

**Comment by modeswitch** [comment]
If you're inclined, please create a pull request for this.

**Comment by rainzhaojy** [comment]
Hi, I enabled MediaStream related codes and pass compiled, I want to stream local audio/video file to the browser side, any idea how to do it?

**Comment by modeswitch** [comment]
The calls into native code will fail because the native library doesn't include any of the code to implement media streams.

Have a look here: https://github.com/js-platform/node-webrtc/issues/156

**Comment by rainzhaojy** [comment]
Alan, I enabled the MediaStream codes and rebuild wrtc.node, please refer my fork (https://github.com/rainzhaojy/node-webrtc), but I still have no idea how to use MediaStream, is it possible to stream local video file? is libwebrtc from google (https://chromium.googlesource.com/external/webrtc)?

I make examples based on bridge.js/peer.html, removed data channels, call getUserMedia in peer.html and add the stream into PeerConnection, in bridge.js, it will answer the offer and create answer, but there is no video codec info in the sdp created by node-webrtc, what's wrong?

**Comment by modeswitch** [comment]
`node-webrtc` doesn't support media streams. It uses a modified version of Google's `libjingle`.

**Comment by ibc** [comment]
Don't take me wrong, but please: rename this project to `node-datachannels`.

**Comment by modeswitch** [comment]
@ibc I'm working on a pure-JS implementation that will be able to support media streams. I will not rename the project.

**Comment by ibc** [comment]
Great news then!

**Comment by rainzhaojy** [comment]
do you mean MediaStream over Data Channels discussed in #156? this means the browser side need handle media stream via data channels too, this may be not good practice. I think the typical use case of node-webrtc is that we use node-webrtc at server side and use standard js webrtc objects at browser side, we can modify the native codes to add some more functionalities, e.g. recording, webrtc proxy to another media server (my use case). Please explain the typical use case of node-webrtc if I am wrong.

**Comment by mitar** [comment]
I would also be interested in having MediaStream support with full libwebrtc library backing it. @modeswitch, I am curious, where is the current commented-out MediaStream code coming from? Was there a time when it was working and then you decided to simplify things? Or did you copy that node.js code from somewhere else and this is why is there?

**Comment by Joe-Palmer** [comment]
@modeswitch Is the pure-JS implementation that will be able to support media streams you mention going to part of this project? How is it coming along? Happy to help test...
