### ISSUE TITLE
Fake media streams

### ISSUE THREAD

**Issue by ibc** [node-webrtc/node-webrtc#180]
I've read that media streams won't be implemented in this project. But what about being able to generate a SDP offer with "m=audio/video" lines and "a=recvonly" (related to #177)?  node-webrtc may just ignore the RTC packets received.

This would be very useful for testing WebRTC servers.

**Comment by modeswitch** [comment]
I think this is out of scope.

**Comment by ibc** [comment]
Out of the scope of a project called "node-webrtc"? Perhaps if the project was named "node-datachannel".
