### ISSUE TITLE
Support pre-built binaries for iojs

### ISSUE THREAD

**Issue by modeswitch** [node-webrtc/node-webrtc#187]
`iojs` should be added to the travis config, and pre-built binaries should be created for it.

**Comment by rosskukulinski** [comment]
I'm testing node-webrtc against iojs on my Mac, submitting job to Travis here: https://travis-ci.org/yodlr/node-webrtc/builds/57358271

If all builds/tests pass, I'll submit a PR with a version bump.

**Comment by rosskukulinski** [comment]
(cc: @maxogden)

**Comment by modeswitch** [comment]
Some additional changes are needed to support IOJS. Any place we check `NODE_MODULE_VERSION` or `NODE_MINOR_VERSION` will need to be patched to check if we're running in IOJS.

**Comment by modeswitch** [comment]
This depends on #192
