### ISSUE TITLE
Unified version checks for Node and IOJS

### ISSUE THREAD

**Issue by modeswitch** [node-webrtc/node-webrtc#192]
We're relying on NODE_MODULE_VERSION and NODE_MINOR_VERSION checks for ArrayBuffer code in DataChannel. Those checks need to be unified (we should use NODE_MODULE_VERSION) and updated to work with IOJS.

**Comment by modeswitch** [comment]
Blocked on https://github.com/iojs/io.js/pull/1364

**Comment by modeswitch** [comment]
(CC @maxogden)

**Comment by max-mapper** [comment]
hmm that is unfortunate. I guess they are saying instead of checking for io.js you should check for specific features? do you know what the current differences are between node and IO from a feature standpoint that effect wrtc?

**Comment by modeswitch** [comment]
No idea. It's not easy to figure out either. Given the state that io.js is in, and my limited time, I don't think this is the best place to spend development effort.

**Comment by modeswitch** [comment]
@maxogden To be more specific, right now you have to check NODE_MODULE_VERSION against a lookup table to figure out whether you're running in Node, IOJS, or Atom. That's a terrible developer experience and that table has to be maintained, even if the native module isn't changing.

The approach that NW.js took, by renaming those flags seems to be the correct one. No one on the IO.js team has offered a reason why that's doesn't meet their needs. The result is that some Node.js modules loaded in IO.js may fail mysteriously.

**Comment by max-mapper** [comment]
@modeswitch I don't have much experience with node native addons, so apologies if this is a dumb question, but since this currently compiles fine under iojs and node right now, can't you just create a prebuilt for each ABI version that compiles correctly and call it done? Like what we do here: https://github.com/mafintosh/leveldown-prebuilt/releases

**Comment by modeswitch** [comment]
@maxogden Successful compilation doesn't imply that the runtime behavior is correct.

**Comment by feross** [comment]
I would love iojs support as well. It does compile fine, but segfaults when sending an `ArrayBuffer`. I discovered this while running the `simple-peer` test suite. If we run the `node-webrtc` and `simple-peer` tests and they all pass, runtime behavior is probably correct.
