### ISSUE TITLE
Refactor ArrayBuffer code

### ISSUE THREAD

**Issue by modeswitch** [node-webrtc/node-webrtc#193]
Shim ArrayBuffer API calls to handle different API versions. Right now we're using preprocessor macros sprinkled around `datachannel.*`. I'd like to see this done in a separate file to keep things tidy.

This also prepares us to support `iojs` when #192 is ready.

**Comment by guymguym** [comment]
:+1: Sounds right. 
Maybe after written and tested it would be a good contribution to [nan](https://github.com/rvagg/nan)

**Comment by guymguym** [comment]
Also consider handling #103 in the same refactor.
