### ISSUE TITLE
How to use isomorphically?

### ISSUE THREAD

**Issue by kevzettler** [node-webrtc/node-webrtc#197]
Hi i'm trying to use this in a webpack/browserify setup. I see that there is `/dist/wrtc.js` which is being used in the browser for all the examples. It looks like its some kind of polyfill. I'm wondering if I can just do `require('wrtc')` in my browser bundle and that will work or is `/dis/wrtc.js` required?

**Comment by max-mapper** [comment]
https://github.com/feross/simple-peer/blob/5790d7cf6cab493a0df17473adbc6179aca4162f/package.json#L10-L12

https://github.com/feross/simple-peer/blob/5790d7cf6cab493a0df17473adbc6179aca4162f/index.js#L14-L19

**Comment by kevzettler** [comment]
thanks @maxogden
