### ISSUE TITLE
fails to send large arraybuffers

### ISSUE THREAD

**Issue by LeoMcA** [node-webrtc/node-webrtc#202]
What it says in the title.

Testcase: https://gist.github.com/LeoMcA/a0f63e069ff10c641154

My output: 

```
~/Projects/simple-share-testcase node testcase.js      leo@leo-desktop 20:14:17
pc1: create offer
pc1: set local description
pc2: set remote description
pc2: create answer
pc2: set local description
pc1: set remote description
waiting
pc1: data channel open
pc1: sending 1000 byte buffer
pc1: sending 66529 byte buffer
pc1: sending 1000000 byte buffer
pc2: data channel open
pc2: received data
pc2: received data
pc2: received data
^C
~/Projects/simple-share-testcase                       leo@leo-desktop 20:14:26
```

Node version:

```
~/Projects/simple-share-testcase node -v               leo@leo-desktop 20:16:40
v0.12.2
~/Projects/simple-share-testcase                       leo@leo-desktop 20:16:42
```

**Comment by LeoMcA** [comment]
To clear up any confusion, the 'pc2: received data' line is printed when a buffer chunk is received, and node-webrtc seems to create a new chunk every 66529 bytes. So the three lines we see are from the 1000 byte buffer, and the 66529 byte buffer split into a 66528 byte chunk and a 1 byte chunk. We seem to never receive any data from the 1000000 byte buffer.

If, however, you were to do what I've done to get around this issue, then everything works fine and dandy:

``` javascript
for(var i = 0; i <= Buffer.length; i += 66528){
  dataChannel.send(new Uint8Array(Buffer.slice(i, i + 66528)));
}
```

**Comment by vmolsa** [comment]
http://webrtc.github.io/samples/src/content/datachannel/filetransfer/

**Comment by markandrus** [comment]
Based on experimental testing, current limits seem to be

```js
const maxOrderedAndReliableSize = 262528;  // bytes
const maxUnorderedAndUnreliableSize = 196896;  // bytes
```

node-webrtc v0.4.0-beta1 introduces RTCSctpTransport, and, in a future release of the webrtc.org code, the `maxMessageSize` property ought to be exposed. That should allow for checking

```js
pc.sctp.maxMessageSize;
```
