### ISSUE TITLE
npm install wrtc   error

### ISSUE THREAD

**Issue by hfmanly** [node-webrtc/node-webrtc#204]
error: Failed to connect to 2404:6800:4008:c01::52: Network is unreachable while accessing https://chromium.googlesource.com/chromium/tools/depot_tools.git/info/refs

fatal: HTTP request failed
ERROR: 128 null 

I find  the url https://chromium.googlesource.com/chromium/tools/depot_tools.git/info/refs is not exist

please help
thanks

**Comment by rosskukulinski** [comment]
@hfmanly Looks like you're using ipv6 to make the connection?  I don't know if googlesource.com has support for ipv6.  Do you have access to an ipv4 network to try?

I just did a clean build and was able to pull everything from googlesource.com

**Comment by hfmanly** [comment]
Thank you for your enthusiasm. My host can not access the url(https://chromium.googlesource.com/chromium/tools/depot_tools.git/info/refs) in China. so I use a VPS in U.S.A. it can access it, but another error comes , the full log is :

[root@cloud bin]# npm install wrtc
\
> wrtc@0.0.55 install /root/hftest/hfnodejs/node-v0.12.3-linux-x86/bin/node_modules/wrtc
> node-pre-gyp install --fallback-to-build

make: Entering directory `/root/hftest/hfnodejs/node-v0.12.3-linux-x86/bin/node_modules/wrtc/build'
  ACTION Run build script /dev/null
TARGET_ARCH=ia32 PLATFORM=linux CONFIGURATION=Release PYTHON=python MODULE_PATH=/root/hftest/hfnodejs/node-v0.12.3-linux-x86/bin/node_modules/wrtc/build/wrtc/
v0.0.55/Release/node-v14-linux-ia32: Preparing directories ... 
: Cloning depot_tools ... 
Initialized empty Git repository in /root/hftest/hfnodejs/node-v0.12.3-linux-x86/bin/node_modules/wrtc/third_party/depot_tools/.git/
remote: Sending approximately 14.01 MiB ...
remote: Counting objects: 819, done
remote: Finding sources: 100% (819/819)
remote: Total 819 (delta 76), reused 428 (delta 76)
Receiving objects: 100% (819/819), 2.77 MiB, done.
Resolving deltas: 100% (76/76), done.
: Cloning libwebrtc ... 
Initialized empty Git repository in /root/hftest/hfnodejs/node-v0.12.3-linux-x86/bin/node_modules/wrtc/third_party/libwebrtc/.git/
remote: Counting objects: 11018, done.
remote: Compressing objects: 100% (8730/8730), done.
remote: Total 11018 (delta 1804), reused 9930 (delta 1651), pack-reused 0
Receiving objects: 100% (11018/11018), 18.21 MiB | 6.30 MiB/s, done.
Resolving deltas: 100% (1804/1804), done.
Checking out files: 100% (10144/10144), done.
: Updating clang ... 
Trying to download prebuilt clang
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 23.3M  100 23.3M    0     0  14.3M      0  0:00:01  0:00:01 --:--:-- 18.9M
clang 218707 unpacked
: Generating build scripts ... 
Updating projects from gyp files...
: Building libwebrtc ... 
ninja: Entering directory `out/Release'
[3/323] CXX obj/webrtc/base/rtc_base_approved.timeutils.o
FAILED: ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/webrtc/base/rtc_base_approved.timeutils.o.d -DV8_DEPRECATION_WARNINGS -D_FILE_OF
FSET_BITS=64 -DCHROMIUM_BUILD -DCR_CLANG_REVISION=218707 -DTOOLKIT_VIEWS=1 -DUI_COMPOSITOR_IMAGE_TRANSPORT -DUSE_AURA=1 -DUSE_ASH=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_DEFAULT_RENDER_THEME=1 -DUSE_LIBJPEG_TURBO=1 -DENABLE_ONE_CLICK_SIGNIN -DENABLE_PRE_SYNC_BACKUP -DENABLE_REMOTING=1 -DENABLE_WEBRTC=1 -DENABLE_PEPPER_CDMS -DENABLE_CONFIGURATION_POLICY -DENABLE_NOTIFICATIONS -DDONT_EMBED_BUILD_METADATA -DENABLE_TASK_MANAGER=1 -DENABLE_EXTENSIONS=1 -DENABLE_PLUGINS=1 -DENABLE_SESSION_SERVICE=1 -DENABLE_THEMES=1 -DENABLE_AUTOFILL_DIALOG=1 -DENABLE_BACKGROUND=1 -DENABLE_GOOGLE_NOW=1 -DCLD_VERSION=2 -DENABLE_PRINTING=1 -DENABLE_BASIC_PRINTING=1 -DENABLE_PRINT_PREVIEW=1 -DENABLE_SPELLCHECK=1 -DENABLE_CAPTIVE_PORTAL_DETECTION=1 -DENABLE_APP_LIST=1 -DENABLE_SETTINGS_APP=1 -DENABLE_SUPERVISED_USERS=1 -DENABLE_MDNS=1 -DENABLE_SERVICE_DISCOVERY=1 -DENABLE_LOAD_COMPLETION_HACKS=1 -DV8_USE_EXTERNAL_STARTUP_DATA -DEXPAT_RELATIVE_PATH -DWEBRTC_MODULE_UTILITY_VIDEO -DWEBRTC_POSIX -DWEBRTC_LINUX -DUSE_GLIB=1 -DUSE_NSS=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -Igen -I../.. -fstack-protector --param=ssp-buffer-size=4 -Werror -pthread -fno-strict-aliasing -Wall -Wno-unused-parameter -Wno-missing-field-initializers -fvisibility=hidden -pipe -fPIC -Wno-reserved-user-defined-literal -momit-leaf-frame-pointer -mstack-alignment=16 -mstackrealign -fcolor-diagnostics -Wheader-hygiene -Wno-char-subscripts -Wno-unneeded-internal-declaration -Wno-covered-switch-default -Wstring-conversion -Wno-c++11-narrowing -Wno-deprecated-register -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wno-strict-overflow -Wthread-safety -msse2 -mfpmath=sse -mmmx -m32 -O2 -fno-ident -fdata-sections -ffunction-sections -funwind-tables -fno-exceptions -fno-rtti -fno-threadsafe-statics -fvisibility-inlines-hidden -Wsign-compare -std=gnu++11 -Wnon-virtual-dtor -Woverloaded-virtual  -c ../../webrtc/base/timeutils.cc -o obj/webrtc/base/rtc_base_approved.timeutils.o/bin/sh: ../../third_party/llvm-build/Release+Asserts/bin/clang++: cannot execute binary file
[3/323] CXX obj/webrtc/base/rtc_base_approved.checks.o
FAILED: ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/webrtc/base/rtc_base_approved.checks.o.d -DV8_DEPRECATION_WARNINGS -D_FILE_OFFSE
T_BITS=64 -DCHROMIUM_BUILD -DCR_CLANG_REVISION=218707 -DTOOLKIT_VIEWS=1 -DUI_COMPOSITOR_IMAGE_TRANSPORT -DUSE_AURA=1 -DUSE_ASH=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_DEFAULT_RENDER_THEME=1 -DUSE_LIBJPEG_TURBO=1 -DENABLE_ONE_CLICK_SIGNIN -DENABLE_PRE_SYNC_BACKUP -DENABLE_REMOTING=1 -DENABLE_WEBRTC=1 -DENABLE_PEPPER_CDMS -DENABLE_CONFIGURATION_POLICY -DENABLE_NOTIFICATIONS -DDONT_EMBED_BUILD_METADATA -DENABLE_TASK_MANAGER=1 -DENABLE_EXTENSIONS=1 -DENABLE_PLUGINS=1 -DENABLE_SESSION_SERVICE=1 -DENABLE_THEMES=1 -DENABLE_AUTOFILL_DIALOG=1 -DENABLE_BACKGROUND=1 -DENABLE_GOOGLE_NOW=1 -DCLD_VERSION=2 -DENABLE_PRINTING=1 -DENABLE_BASIC_PRINTING=1 -DENABLE_PRINT_PREVIEW=1 -DENABLE_SPELLCHECK=1 -DENABLE_CAPTIVE_PORTAL_DETECTION=1 -DENABLE_APP_LIST=1 -DENABLE_SETTINGS_APP=1 -DENABLE_SUPERVISED_USERS=1 -DENABLE_MDNS=1 -DENABLE_SERVICE_DISCOVERY=1 -DENABLE_LOAD_COMPLETION_HACKS=1 -DV8_USE_EXTERNAL_STARTUP_DATA -DEXPAT_RELATIVE_PATH -DWEBRTC_MODULE_UTILITY_VIDEO -DWEBRTC_POSIX -DWEBRTC_LINUX -DUSE_GLIB=1 -DUSE_NSS=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -Igen -I../.. -fstack-protector --param=ssp-buffer-size=4 -Werror -pthread -fno-strict-aliasing -Wall -Wno-unused-parameter -Wno-missing-field-initializers -fvisibility=hidden -pipe -fPIC -Wno-reserved-user-defined-literal -momit-leaf-frame-pointer -mstack-alignment=16 -mstackrealign -fcolor-diagnostics -Wheader-hygiene -Wno-char-subscripts -Wno-unneeded-internal-declaration -Wno-covered-switch-default -Wstring-conversion -Wno-c++11-narrowing -Wno-deprecated-register -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wno-strict-overflow -Wthread-safety -msse2 -mfpmath=sse -mmmx -m32 -O2 -fno-ident -fdata-sections -ffunction-sections -funwind-tables -fno-exceptions -fno-rtti -fno-threadsafe-statics -fvisibility-inlines-hidden -Wsign-compare -std=gnu++11 -Wnon-virtual-dtor -Woverloaded-virtual  -c ../../webrtc/base/checks.cc -o obj/webrtc/base/rtc_base_approved.checks.o/bin/sh: ../../third_party/llvm-build/Release+Asserts/bin/clang++: cannot execute binary file
[3/323] CXX obj/webrtc/base/rtc_base_approved.exp_filter.o
FAILED: ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/webrtc/base/rtc_base_approved.exp_filter.o.d -DV8_DEPRECATION_WARNINGS -D_FILE_O
FFSET_BITS=64 -DCHROMIUM_BUILD -DCR_CLANG_REVISION=218707 -DTOOLKIT_VIEWS=1 -DUI_COMPOSITOR_IMAGE_TRANSPORT -DUSE_AURA=1 -DUSE_ASH=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_DEFAULT_RENDER_THEME=1 -DUSE_LIBJPEG_TURBO=1 -DENABLE_ONE_CLICK_SIGNIN -DENABLE_PRE_SYNC_BACKUP -DENABLE_REMOTING=1 -DENABLE_WEBRTC=1 -DENABLE_PEPPER_CDMS -DENABLE_CONFIGURATION_POLICY -DENABLE_NOTIFICATIONS -DDONT_EMBED_BUILD_METADATA -DENABLE_TASK_MANAGER=1 -DENABLE_EXTENSIONS=1 -DENABLE_PLUGINS=1 -DENABLE_SESSION_SERVICE=1 -DENABLE_THEMES=1 -DENABLE_AUTOFILL_DIALOG=1 -DENABLE_BACKGROUND=1 -DENABLE_GOOGLE_NOW=1 -DCLD_VERSION=2 -DENABLE_PRINTING=1 -DENABLE_BASIC_PRINTING=1 -DENABLE_PRINT_PREVIEW=1 -DENABLE_SPELLCHECK=1 -DENABLE_CAPTIVE_PORTAL_DETECTION=1 -DENABLE_APP_LIST=1 -DENABLE_SETTINGS_APP=1 -DENABLE_SUPERVISED_USERS=1 -DENABLE_MDNS=1 -DENABLE_SERVICE_DISCOVERY=1 -DENABLE_LOAD_COMPLETION_HACKS=1 -DV8_USE_EXTERNAL_STARTUP_DATA -DEXPAT_RELATIVE_PATH -DWEBRTC_MODULE_UTILITY_VIDEO -DWEBRTC_POSIX -DWEBRTC_LINUX -DUSE_GLIB=1 -DUSE_NSS=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -Igen -I../.. -fstack-protector --param=ssp-buffer-size=4 -Werror -pthread -fno-strict-aliasing -Wall -Wno-unused-parameter -Wno-missing-field-initializers -fvisibility=hidden -pipe -fPIC -Wno-reserved-user-defined-literal -momit-leaf-frame-pointer -mstack-alignment=16 -mstackrealign -fcolor-diagnostics -Wheader-hygiene -Wno-char-subscripts -Wno-unneeded-internal-declaration -Wno-covered-switch-default -Wstring-conversion -Wno-c++11-narrowing -Wno-deprecated-register -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wno-strict-overflow -Wthread-safety -msse2 -mfpmath=sse -mmmx -m32 -O2 -fno-ident -fdata-sections -ffunction-sections -funwind-tables -fno-exceptions -fno-rtti -fno-threadsafe-statics -fvisibility-inlines-hidden -Wsign-compare -std=gnu++11 -Wnon-virtual-dtor -Woverloaded-virtual  -c ../../webrtc/base/exp_filter.cc -o obj/webrtc/base/rtc_base_approved.exp_filter.o/bin/sh: ../../third_party/llvm-build/Release+Asserts/bin/clang++: cannot execute binary file
ninja: build stopped: subcommand failed.
ERROR: 1 null 

make: *** [/dev/null] 错误 255
make: Leaving directory `/root/hftest/hfnodejs/node-v0.12.3-linux-x86/bin/node_modules/wrtc/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/hftest/hfnodejs/node-v0.12.3-linux-x86/bin/node_modules/wrtc/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 2.6.32-358.el6.i686
gyp ERR! command "/root/hftest/hfnodejs/node-v0.12.3-linux-x86/bin/node" "/root/hftest/hfnodejs/node-v0.12.3-linux-x86/bin/node_modules/wrtc/node_modules/node
-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/root/hftest/hfnodejs/node-v0.12.3-linux-x86/bin/node_modules/wrtc/build/wrtc/v0.0.55/Release/node-v14-linux-ia32/wrtc.node" "--module_name=wrtc" "--module_path=/root/hftest/hfnodejs/node-v0.12.3-linux-x86/bin/node_modules/wrtc/build/wrtc/v0.0.55/Release/node-v14-linux-ia32"gyp ERR! cwd /root/hftest/hfnodejs/node-v0.12.3-linux-x86/bin/node_modules/wrtc
gyp ERR! node -v v0.12.3
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/root/hftest/hfnodejs/node-v0.12.3-linux-x86/bin/node /root/hftest/hfnodejs/node-v0.12.3-linux-x86/bin/node_
modules/wrtc/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/root/hftest/hfnodejs/node-v0.12.3-linux-x86/bin/node_modules/wrtc/build/wrtc/v0.0.55/Release/node-v14-linux-ia32/wrtc.node --module_name=wrtc --module_path=/root/hftest/hfnodejs/node-v0.12.3-linux-x86/bin/node_modules/wrtc/build/wrtc/v0.0.55/Release/node-v14-linux-ia32' (1)node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/root/hftest/hfnodejs/node-v0.12.3-linux-x86/bin/node_modules/wrtc/node_modules/node-pre-gyp/lib/util
/compile.js:73:29)node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:1015:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
node-pre-gyp ERR! System Linux 2.6.32-358.el6.i686
node-pre-gyp ERR! command "node" "/root/hftest/hfnodejs/node-v0.12.3-linux-x86/bin/node_modules/wrtc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-
build"node-pre-gyp ERR! cwd /root/hftest/hfnodejs/node-v0.12.3-linux-x86/bin/node_modules/wrtc
node-pre-gyp ERR! node -v v0.12.3
node-pre-gyp ERR! node-pre-gyp -v v0.6.4
node-pre-gyp ERR! not ok 
Failed to execute '/root/hftest/hfnodejs/node-v0.12.3-linux-x86/bin/node /root/hftest/hfnodejs/node-v0.12.3-linux-x86/bin/node_modules/wrtc/node_modules/node-
gyp/bin/node-gyp.js build --fallback-to-build --module=/root/hftest/hfnodejs/node-v0.12.3-linux-x86/bin/node_modules/wrtc/build/wrtc/v0.0.55/Release/node-v14-linux-ia32/wrtc.node --module_name=wrtc --module_path=/root/hftest/hfnodejs/node-v0.12.3-linux-x86/bin/node_modules/wrtc/build/wrtc/v0.0.55/Release/node-v14-linux-ia32' (1)npm ERR! Linux 2.6.32-358.el6.i686
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "wrtc"
npm ERR! node v0.12.3
npm ERR! npm  v2.9.1
npm ERR! code ELIFECYCLE

npm ERR! wrtc@0.0.55 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wrtc@0.0.55 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the wrtc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls wrtc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/hftest/hfnodejs/node-v0.12.3-linux-x86/bin/npm-debug.log
[root@cloud bin]# 

how to do?
thanks

**Comment by hfmanly** [comment]
Thank you for your enthusiasm. My host can not access the url(https://chromium.googlesource.com/chromium/tools/depot_tools.git/info/refs) in China. so I use a VPS in U.S.A. it can access it
