### ISSUE TITLE
publish new version?

### ISSUE THREAD

**Issue by ralphtheninja** [node-webrtc/node-webrtc#210]
Please publish a new version of this for iojs support. Thanks!

**Comment by modeswitch** [comment]
Is iojs a thing anymore? Is it not merging back with node?

**Comment by ralphtheninja** [comment]
It's still a thing and it's merging back with node. I'm just asking for a new version since `nan` has been updated :)

**Comment by modeswitch** [comment]
Published.

**Comment by ralphtheninja** [comment]
Aaaaawesome! :)
