### ISSUE TITLE
Unknown architecture (armv7l) -- unable to run ninja.

### ISSUE THREAD

**Issue by zoudf** [node-webrtc/node-webrtc#213]
I have problem with running build.js on RP 2
===============Install ninja====================================
pi@raspberrypi ~ $ git clone https://github.com/martine/ninja.git
Cloning into 'ninja'...
remote: Counting objects: 8545, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 8545 (delta 1), reused 0 (delta 0), pack-reused 8542
Receiving objects: 100% (8545/8545), 1.85 MiB | 1.72 MiB/s, done.
Resolving deltas: 100% (6038/6038), done.
pi@raspberrypi ~ $ cd ninja
pi@raspberrypi ~/ninja $ ./configure.py --bootstrap
bootstrapping ninja...
warning: A compatible version of re2c (>= 0.11.3) was not found; changes to src/*.in.cc will not affect your build.

wrote build.ninja.
bootstrap complete.  rebuilding...
[24/24] LINK ninja
pi@raspberrypi ~/ninja $

==========webrtc=======================
pi@raspberrypi ~ $ git clone https://github.com/js-platform/node-webrtc
Cloning into 'node-webrtc'...
remote: Counting objects: 2356, done.
remote: Total 2356 (delta 0), reused 0 (delta 0), pack-reused 2356
Receiving objects: 100% (2356/2356), 550.94 KiB | 1022 KiB/s, done.
Resolving deltas: 100% (1380/1380), done.
pi@raspberrypi ~ $

===========Install webrtc========================
pi@raspberrypi ~/node-webrtc $ sudo npm install
/

> ws@0.4.32 install /home/pi/node-webrtc/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory '/home/pi/node-webrtc/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
make: Leaving directory '/home/pi/node-webrtc/node_modules/ws/build'
npm WARN cannot run in wd wrtc@0.0.56 node-pre-gyp install --fallback-to-build (wd=/home/pi/node-webrtc)
node-static-alias@0.1.3 node_modules/node-static-alias

minimist@0.0.8 node_modules/minimist

nopt@2.2.1 node_modules/nopt
└── abbrev@1.0.7

nan@1.8.4 node_modules/nan

tape@2.4.3 node_modules/tape
├── resumer@0.0.0
├── jsonify@0.0.0
├── inherits@2.0.1
├── deep-equal@0.2.2
├── defined@0.0.0
└── through@2.3.7

simple-peer@5.11.2 node_modules/simple-peer
├── get-browser-rtc@1.0.0
├── is-typedarray@1.0.0
├── inherits@2.0.1
├── hat@0.0.3
├── typedarray-to-buffer@3.0.3
├── once@1.3.2 (wrappy@1.0.1)
└── debug@2.2.0 (ms@0.7.1)

node-static@0.7.6 node_modules/node-static
├── mime@1.3.4
├── colors@1.1.2
└── optimist@0.6.1 (wordwrap@0.0.3)

fs-extra@0.18.4 node_modules/fs-extra
├── jsonfile@2.2.0
├── graceful-fs@3.0.8
└── rimraf@2.4.0 (glob@4.5.3)

grunt-tape@0.0.2 node_modules/grunt-tape
├── through@2.3.7
├── tape@2.3.3 (defined@0.0.0, resumer@0.0.0, deep-equal@0.1.2, jsonify@0.0.0, inherits@2.0.1)
└── faucet@0.0.0 (defined@0.0.0, sprintf@0.1.5, duplexer@0.1.1, minimist@0.0.5, through2@0.2.3, tap-parser@0.4.3)

grunt-contrib-jshint@0.8.0 node_modules/grunt-contrib-jshint
└── jshint@2.4.4 (console-browserify@0.1.6, exit@0.1.2, minimatch@0.4.0, underscore@1.4.4, shelljs@0.1.4, cli@0.4.5, htmlparser2@3.3.0)

grunt@0.4.5 node_modules/grunt
├── which@1.0.9
├── dateformat@1.0.2-1.2.3
├── eventemitter2@0.4.14
├── getobject@0.1.0
├── rimraf@2.2.8
├── colors@0.6.2
├── async@0.1.22
├── grunt-legacy-util@0.2.0
├── hooker@0.2.3
├── nopt@1.0.10 (abbrev@1.0.7)
├── exit@0.1.2
├── minimatch@0.2.14 (sigmund@1.0.1, lru-cache@2.6.4)
├── glob@3.1.21 (inherits@1.0.0, graceful-fs@1.2.3)
├── lodash@0.9.2
├── coffee-script@1.3.3
├── underscore.string@2.2.1
├── iconv-lite@0.2.11
├── findup-sync@0.1.3 (glob@3.2.11, lodash@2.4.2)
├── js-yaml@2.0.5 (argparse@0.1.16, esprima@1.0.4)
└── grunt-legacy-log@0.1.2 (grunt-legacy-log-utils@0.1.1, underscore.string@2.3.3, lodash@2.4.2)

node-gyp@1.0.3 node_modules/node-gyp
├── rimraf@2.4.0
├── graceful-fs@3.0.8
├── osenv@0.1.2 (os-tmpdir@1.0.1)
├── mkdirp@0.5.1
├── which@1.1.1 (is-absolute@0.1.7)
├── minimatch@1.0.0 (sigmund@1.0.1, lru-cache@2.6.4)
├── fstream@1.0.7 (inherits@2.0.1)
├── semver@4.3.6
├── tar@1.0.3 (inherits@2.0.1, block-stream@0.0.8)
├── glob@4.5.3 (inherits@2.0.1, once@1.3.2, inflight@1.0.4, minimatch@2.0.8)
├── npmlog@1.2.1 (ansi@0.3.0, are-we-there-yet@1.0.4, gauge@1.2.0)
└── request@2.58.0 (caseless@0.10.0, aws-sign2@0.5.0, forever-agent@0.6.1, stringstream@0.0.4, tunnel-agent@0.4.0, oauth-sign@0.8.0, isstream@0.1.2, extend@2.0.1, json-stringify-safe@5.0.1, combined-stream@1.0.5, node-uuid@1.4.3, qs@3.1.0, mime-types@2.0.14, bl@0.9.4, http-signature@0.11.0, tough-cookie@2.0.0, form-data@1.0.0-rc1, hawk@2.3.1, har-validator@1.8.0)

ws@0.4.32 node_modules/ws
├── tinycolor@0.0.1
├── options@0.0.6
├── commander@2.1.0
└── nan@1.0.0

node-pre-gyp@0.6.7 node_modules/node-pre-gyp
pi@raspberrypi ~/node-webrtc $

==========build webrtc====================================
pi@raspberrypi ~/node-webrtc $ sudo node bin/build.js
TARGET_ARCH=arm PLATFORM=linux CONFIGURATION=Release PYTHON=python MODULE_PATH=undefined
: Updating depot_tools ...
From https://chromium.googlesource.com/chromium/tools/depot_tools
- branch            master     -> FETCH_HEAD
  Already up-to-date.
  : Updating libwebrtc ...
  From https://github.com/js-platform/libwebrtc
- branch            master     -> FETCH_HEAD
  Already up-to-date.
  : Updating clang ...
  Clang already at 218707-12
  : Generating build scripts ...
  Updating projects from gyp files...
  ...: Building libwebrtc ...
  Unknown architecture (armv7l) -- unable to run ninja.
  No prebuilt ninja binary was found for this system.
  Try building your own binary by doing:
  cd ~
  git clone https://github.com/martine/ninja.git -b v1.5.3
  cd ninja && ./configure.py --bootstrap
  Then add ~/ninja/ to your PATH.
  ERROR: 1 null

pi@raspberrypi ~/node-webrtc $ echo $PATH
/home/pi/ninja:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games:/home/pi/depot_tools

**Comment by mdik** [comment]
Same here on a Cubietruck :-(

**Comment by markandrus** [comment]
Perhaps I have misread but it looks like you have run `bin/build.js` manually, rather than as part of the node-gyp steps (e.g., `node-pre-gyp install --fallback-to-build`). Nevertheless, I don't expect this to work on Raspberry PI yet.

**Comment by markandrus** [comment]
Hi, I know this is an old thread, but, as of [v0.3.3](https://github.com/node-webrtc/node-webrtc/releases/tag/v0.3.3), we now ship armv7l and arm64 binaries.
