### ISSUE TITLE
Out-of-order messaging data channel

### ISSUE THREAD

**Issue by lewispham** [node-webrtc/node-webrtc#219]
I wonder how can node-webrtc implement _out-of-order_ messaging via data channel (set `ordered : false` option) since TCP connection is order-guarantee?

**Comment by seemk** [comment]
WebRTC data channels may use DTLS over UDP, this is what I get when setting using unreliable data channels.

**Comment by modeswitch** [comment]
This module doesn't rely on Node's networking support.
