### ISSUE TITLE
Update to nan 2 for Node.js 4.0.0 compatibility.

### ISSUE THREAD

**Issue by ChALkeR** [node-webrtc/node-webrtc#223]
Adding to the list: https://github.com/nodejs/node/issues/2798.

**Comment by chrisprobst** [comment]
How soon will Node4 support arrive ? =)

**Comment by modeswitch** [comment]
As soon as someone makes a pull request. I'm extremely busy and I don't have much time to work on this project.

**Comment by daviddias** [comment]
This was done on https://github.com/js-platform/node-webrtc/pull/229, however, still no luck on Mac OS X
