### ISSUE TITLE
Build fails on Arch Linux

### ISSUE THREAD

**Issue by bogie** [node-webrtc/node-webrtc#227]
When generating build scripts npm install crashes with a cryptic:

> Error: spawn python ENOENT

As per your instructions I tried:

> npm config set python python2

Which did not resolve the problem entirely, I fixed it by manually creating a symbolic link in /usr/bin:

> ln -s /usr/bin/python2 /usr/bin/python

Obviously ncurses symbolic link has to be done as well:

> ln -s /usr/lib/libncurses.so.5 /usr/lib/libtinfo.so.5

Next I had to fix boringssl as explained in #221 and finally your library compiled.

**Comment by airstep** [comment]
Some update:

sudo ln -s /usr/lib/libncursesw.so.6.0 /usr/lib/libtinfo.so.5

But have this now:

../../chromium/src/third_party/boringssl/src/crypto/directory_posix.c:86:7: error: 'readdir_r' is deprecated [-Werror,-Wdeprecated-declarations]
