### ISSUE TITLE
Automatic coop test.

### ISSUE THREAD

**Issue by helloIAmPau** [node-webrtc/node-webrtc#23]
Hi @modeswitch, for my project node-rtc (https://github.com/helloIAmPau/node-rtc) I've written some scripts, using karma framework, to run compatibility test between node and browser automatically.

Let me know if you want something similar for your project.

**Comment by modeswitch** [comment]
Hey @helloIAmPau, there's some discussion about testing in #15, specifically around using tape and testling. You and @DamonOehlman should coordinate to avoid duplicating effort.

**Comment by DamonOehlman** [comment]
I'll definitely take a look at what you've done in your original project @helloIAmPau.  Let me get an initial pull request through on the tape + testling approach and we can discuss then.  I've personally found tape + testling to be exceptionally good at providing unit tests for libraries that can be used both in node and the browser.

With any luck we should still be able to karma (I haven't tried using tape + karma yet) but I think it should work ok...
