### ISSUE TITLE
Installation fails on Ubuntu 15.04 and NodeJS

### ISSUE THREAD

**Issue by stiller-leser** [node-webrtc/node-webrtc#230]
Hey,
I am trying to install the package via 'npm install' on NodeJS 4 on my Ubuntu system with all the dependencies installed. However I get this error right before the end (not using npm install wrtc but the build version):
[621/621] LINK wrtc_build
: Build complete

  TOUCH Release/obj.target/action_before_build.stamp
  CXX(target) Release/obj.target/wrtc/src/binding.o
In file included from ../src/datachannel.h:19:0,
                 from ../src/peerconnection.h:17,
                 from ../src/binding.cc:6:
../node_modules/nan/nan.h:261:25: error: redefinition of ‘template<class T> v8::Local<T> _NanEnsureLocal(v8::Local<T>)’
 NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                         ^
../node_modules/nan/nan.h:256:25: note: ‘template<class T> v8::Local<T> _NanEnsureLocal(v8::Handle<T>)’ previously declared here
 NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                         ^
../node_modules/nan/nan.h:661:13: error: ‘node::smalloc’ has not been declared
     , node::smalloc::FreeCallback callback
             ^
../node_modules/nan/nan.h:661:35: error: expected ‘,’ or ‘...’ before ‘callback’
     , node::smalloc::FreeCallback callback
                                   ^
../node_modules/nan/nan.h: In function ‘v8::Localv8::Object NanNewBufferHandle(char_, size_t, int)’:
../node_modules/nan/nan.h:665:50: error: ‘callback’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                  ^
../node_modules/nan/nan.h:665:60: error: ‘hint’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                            ^
../node_modules/nan/nan.h: In function ‘v8::Localv8::Object NanNewBufferHandle(const char_, uint32_t)’:
../node_modules/nan/nan.h:672:67: error: call of overloaded ‘New(v8::Isolate_, const char_&, uint32_t&)’ is ambiguous
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
../node_modules/nan/nan.h:672:67: note: candidates are:
In file included from ../node_modules/nan/nan.h:25:0,
                 from ../src/datachannel.h:19,
                 from ../src/peerconnection.h:17,
                 from ../src/binding.cc:6:
/home/kaj/.node-gyp/4.2.0/src/node_buffer.h:31:40: note: v8::MaybeLocalv8::Object node::Buffer::New(v8::Isolate_, v8::Localv8::String, node::encoding) <near match>
 NODE_EXTERN v8::MaybeLocalv8::Object New(v8::Isolate_ isolate,
                                        ^
/home/kaj/.node-gyp/4.2.0/src/node_buffer.h:31:40: note:   no known conversion for argument 3 from ‘uint32_t {aka unsigned int}’ to ‘node::encoding’
/home/kaj/.node-gyp/4.2.0/src/node_buffer.h:43:40: note: v8::MaybeLocalv8::Object node::Buffer::New(v8::Isolate_, char_, size_t) <near match>
 NODE_EXTERN v8::MaybeLocalv8::Object New(v8::Isolate\* isolate,
                                        ^
/home/kaj/.node-gyp/4.2.0/src/node_buffer.h:43:40: note:   no known conversion for argument 2 from ‘const char_’ to ‘char_’
In file included from ../src/datachannel.h:19:0,
                 from ../src/peerconnection.h:17,
                 from ../src/binding.cc:6:
../node_modules/nan/nan.h: In function ‘v8::Localv8::Object NanNewBufferHandle(uint32_t)’:
../node_modules/nan/nan.h:676:61: error: could not convert ‘node::Buffer::New(v8::Isolate::GetCurrent(), ((size_t)size))’ from ‘v8::MaybeLocalv8::Object’ to ‘v8::Localv8::Object’
     return node::Buffer::New(v8::Isolate::GetCurrent(), size);
                                                             ^
../node_modules/nan/nan.h: In function ‘v8::Localv8::Object NanBufferUse(char_, uint32_t)’:
../node_modules/nan/nan.h:683:12: error: ‘Use’ is not a member of ‘node::Buffer’
     return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
            ^
wrtc.target.mk:164: recipe for target 'Release/obj.target/wrtc/src/binding.o' failed
make: *_\* [Release/obj.target/wrtc/src/binding.o] Error 1
make: Leaving directory '/home/kaj/Studium/Semester7/bachelorthesis/slidesync-webrtc/app/assets/nodejs/node-webrtc/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/kaj/Studium/Semester7/bachelorthesis/slidesync-webrtc/app/assets/nodejs/node-webrtc/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.19.0-15-generic
gyp ERR! command "/usr/bin/nodejs" "/home/kaj/Studium/Semester7/bachelorthesis/slidesync-webrtc/app/assets/nodejs/node-webrtc/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/kaj/Studium/Semester7/bachelorthesis/slidesync-webrtc/app/assets/nodejs/node-webrtc/build/wrtc/v0.0.58/Release/node-v46-linux-x64/wrtc.node" "--module_name=wrtc" "--module_path=/home/kaj/Studium/Semester7/bachelorthesis/slidesync-webrtc/app/assets/nodejs/node-webrtc/build/wrtc/v0.0.58/Release/node-v46-linux-x64"
gyp ERR! cwd /home/kaj/Studium/Semester7/bachelorthesis/slidesync-webrtc/app/assets/nodejs/node-webrtc
gyp ERR! node -v v4.2.0
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/nodejs /home/kaj/Studium/Semester7/bachelorthesis/slidesync-webrtc/app/assets/nodejs/node-webrtc/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/kaj/Studium/Semester7/bachelorthesis/slidesync-webrtc/app/assets/nodejs/node-webrtc/build/wrtc/v0.0.58/Release/node-v46-linux-x64/wrtc.node --module_name=wrtc --module_path=/home/kaj/Studium/Semester7/bachelorthesis/slidesync-webrtc/app/assets/nodejs/node-webrtc/build/wrtc/v0.0.58/Release/node-v46-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/kaj/Studium/Semester7/bachelorthesis/slidesync-webrtc/app/assets/nodejs/node-webrtc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:818:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Linux 3.19.0-15-generic
node-pre-gyp ERR! command "/usr/bin/nodejs" "/home/kaj/Studium/Semester7/bachelorthesis/slidesync-webrtc/app/assets/nodejs/node-webrtc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/kaj/Studium/Semester7/bachelorthesis/slidesync-webrtc/app/assets/nodejs/node-webrtc
node-pre-gyp ERR! node -v v4.2.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.12
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/nodejs /home/kaj/Studium/Semester7/bachelorthesis/slidesync-webrtc/app/assets/nodejs/node-webrtc/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/kaj/Studium/Semester7/bachelorthesis/slidesync-webrtc/app/assets/nodejs/node-webrtc/build/wrtc/v0.0.58/Release/node-v46-linux-x64/wrtc.node --module_name=wrtc --module_path=/home/kaj/Studium/Semester7/bachelorthesis/slidesync-webrtc/app/assets/nodejs/node-webrtc/build/wrtc/v0.0.58/Release/node-v46-linux-x64' (1)

npm ERR! Linux 3.19.0-15-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.0
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! wrtc@0.0.58 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wrtc@0.0.58 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the wrtc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls wrtc
npm ERR! There is likely additional logging output above.

Any hint is greatly appreciated!

Cheers,
stiller-leser

**Comment by frankcash** [comment]
I too have this error on OSX with Node version `4.1.1` and NPM `2.14.4`

**Comment by stiller-leser** [comment]
For now you have to change back to NodeJS 0.12 - This works fine. Support for NodeJS 4 is in the works. The version I tried did not work yet. Have a look here: https://github.com/js-platform/node-webrtc/pull/229

They actually merged it 5 days ago. My last test was a week ago or so. Might wanna try the new version from GitHub and build it.

**Comment by markandrus** [comment]
This should have been fixed with the NAN update.
