### ISSUE TITLE
Skip update_clang

### ISSUE THREAD

**Issue by jamesamcl** [node-webrtc/node-webrtc#232]
Can we add an option to skip the clang update script?  This prevents me from installing wrtc on FreeBSD, and apparently Fedora 14 (#222).

I really don't need to update clang.

```
james@14CompSci099 /u/h/j/node-webrtc> clang --version
FreeBSD clang version 3.4.1 (tags/RELEASE_34/dot1-final 208032) 20140512 
Target: x86_64-unknown-freebsd10.2
Thread model: posix
```

**Comment by modeswitch** [comment]
`libwebrtc` requires a specific version of `clang`, which the script installs.
