### ISSUE TITLE
any plan on webrtc proxy?  

### ISSUE THREAD

**Issue by notedit** [node-webrtc/node-webrtc#24]
i want to broadcast the media stream to many others people, it need to multiplexe mediaStream,  so does this project have this plan?

**Comment by modeswitch** [comment]
Yeah, this is definitely on my list of things to support. Specifically, I'd like to implement the API in [this spec](http://www.w3.org/TR/mediacapture-streams/) so that ultimately you could mix together multiple sources and broadcast it out again as a single stream in some format, or record it.

**Comment by modeswitch** [comment]
Also, this will probably not be supported in the very first version, but hopefully soon after.

**Comment by notedit** [comment]
cool, is there  a timeline for this.  i am not familiar with c++, but i can do some test

**Comment by modeswitch** [comment]
I don't have a development roadmap yet. When I have time to sit down and do some planning I'll make it available as an issue so that everyone can comment, and then I'll link to it from the README when it's somewhat finalized.

**Comment by piranna** [comment]
Shouldn't this be developed as an independent project on top of node-webrtc
and get only on being API compatible with browsers?

**Comment by modeswitch** [comment]
@piranna yeah, I was speaking about support for such a proxy. The proxy itself would be part of another module I think.

**Comment by piranna** [comment]
Oh, ok, I see. This would means this external module would work on the
browser?

2013/10/25 Alan K notifications@github.com

> @piranna https://github.com/piranna yeah, I was speaking about support
> for such a proxy. The proxy itself would be part of another module I think.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/modeswitch/node-webrtc/issues/24#issuecomment-27069090
> .

## 

"Si quieres viajar alrededor del mundo y ser invitado a hablar en un monton
de sitios diferentes, simplemente escribe un sistema operativo Unix."
– Linus Tordvals, creador del sistema operativo Linux

**Comment by modeswitch** [comment]
Not completely sure what you mean, but if you're asking whether the media stream stuff I mentioned above should work with browser video and audio streams, the answer is yes.

**Comment by piranna** [comment]
No, I asked about a browser working as proxy using their implementation of
WebRTC.

2013/10/25 Alan K notifications@github.com

> Not completely sure what you mean, but if you're asking whether the media
> stream stuff I mentioned above should work with browser video and audio
> streams, the answer is yes.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/modeswitch/node-webrtc/issues/24#issuecomment-27071620
> .

## 

"Si quieres viajar alrededor del mundo y ser invitado a hablar en un monton
de sitios diferentes, simplemente escribe un sistema operativo Unix."
– Linus Tordvals, creador del sistema operativo Linux

**Comment by notedit** [comment]
i just close this issues.   @modeswitch you can let us know when you are starting work on this.

thx

**Comment by notedit** [comment]
any progress on this?

**Comment by modeswitch** [comment]
Sorry, not yet.
