### ISSUE TITLE
Need MediaStreamer related files of libwebrtc in master

### ISSUE THREAD

**Issue by abhilashsivan2604** [node-webrtc/node-webrtc#240]
Hi,
I am trying to add mediastream support on node-webrtc and as part of this activity I observed that all the media streamer related files have been removed from libwebrtc. Is there any easy way to make all those files available in the master?

**Comment by modeswitch** [comment]
I'm not planning on doing this, for reasons discussed in other issues. However, it's pretty straightforward to build against upstream libjingle if you want.
