### ISSUE TITLE
No support for Promise based API for RTCPeerConnection

### ISSUE THREAD

**Issue by FelixMcFelix** [node-webrtc/node-webrtc#243]
As detailed in the [W3C Spec](http://www.w3.org/TR/webrtc/#interface-definition), since December 5th 2014 the old callback-based methods have been designated as legacy and superseded by the newer Promise based specification.

If it's alright, I'd like to fork the project and attempt to implement these changes - it's a more convenient API to work with, and one of my projects relies on its existence at present.

**Comment by modeswitch** [comment]
No need to fork the project. I'm happy to review and merge your patch when it's done.

**Comment by FelixMcFelix** [comment]
@modeswitch Implemented. I've filed a pull request with the changes to RTCPeerConnection, it seems to be working just fine in my own project (which does use all modified methods).

**Comment by bfishman** [comment]
any idea why this hasn't yet been merged?

**Comment by alangibson** [comment]
This project is looking pretty dead; there haven't been any commits since Nov 2, 2015. 

@FelixMcFelix It looks like @silverbucket and @mdchoate have the most active forks at the moment. Have you tried submitting this to one of them?

**Comment by FelixMcFelix** [comment]
@alangibson That's a shame - I haven't yet approached any of the other forks of this repo. I'll propose a PR with one of these forks at some point.

**Comment by silverbucket** [comment]
Hi @alangibson and @FelixMcFelix - unfortunately the only reason I forked was to also submit a patch here which has still not been reviewed. I don't really have the capacity to maintain my own fork, but if you guys do find someone who is I will submit my patch there as well.

**Comment by alangibson** [comment]
Thanks for the heads-up @silverbucket. On second thought, it looks like @mdchoate only forked to make the build work on Windows. So there appears to be no actively maintained fork at this point.

I would volunteer, but I don't know a word of C++ and so I'd be limited to only the JS stuff.

**Comment by bfishman** [comment]
Here's a similar project. I'm having trouble building it at the moment, but it's under much more active development

https://github.com/vmolsa/webrtc-native

**Comment by modeswitch** [comment]
I'm very busy with my startup these days. As a result I don't have as much time for this project as I would like. Sorry for the inconvenience.

**Comment by Globik** [comment]
@bfishman  why windows project of webrtc-native writes that not support windows 32 bit? But I can see in their source files platform 32 is defined.
