### ISSUE TITLE
Segmentation fault when sending an RTCDataChannelMessageEvent over an RTCDataChannel

### ISSUE THREAD

**Issue by FelixMcFelix** [node-webrtc/node-webrtc#245]
Ran into this issue while testing out browser-server connectivity with an echo server.

Code should reproduce the error:

``` javascript
// Assuming the conductor library is being used to manage connections.

this.conductor.onconnection = conn => {
    conn.ondatachannel = dChan => {
        dChan.onmessage = (a) => {
            console.log(a);
            // Note that we are sending the event - NOT the data attached to the event.
            dChan.send(a);
        };
    };
};
```

Although encountered while working with my own library, my code doesn't modify any of the code related to sending - it's also a very odd, rookie-ish edge case. I've included some of the console output from its execution within my program.

``` bash
#...
Server bootstrap received message:
{ id: 'vBf1Zwt1oFHiirFRWekuZ82QY/JCwuKYCNn5hQ==',
  data:
   { candidate: 'candidate:2954523917 1 tcp 1518214911 192.168.1.141 0 typ host tcptype active generation 0',
     sdpMid: 'data',
     sdpMLineIndex: 0 },
  type: 'bstrap-ice' }
ICE candidate picked up by manager.
Successfully added ICE candidate to connection vBf1Zwt1oFHiirFRWekuZ82QY/JCwuKYCNn5hQ==
Send instruction given to server bootstrap.
Sending ICE candidate to client.
Received Channel from other partner.
RTCDataChannelMessageEvent { data: 'aaa' }
Segmentation fault (core dumped)
```

Sending MessageEvents from within browser code does not warrant the same response, the server prints output safely:

``` bash
RTCDataChannelMessageEvent { data: '[object MessageEvent]' }
```

I'm unsure if this occurs within the C++ backend or purely within the js frontend. Users can get around it by being careful for now.

**Comment by FelixMcFelix** [comment]
Should add, this is from running on Node 5.1.1 on Ubuntu 14.04.3 LTS.

**Comment by markandrus** [comment]
This should no longer be an issue. Calling RTCDataChannel's `send` method with something other than a string, Blob, or ArrayBuffer raises the following TypeError:

```
TypeError: Expected a Blob or ArrayBuffer
```
