### ISSUE TITLE
Support for media stream APIs

### ISSUE THREAD

**Issue by modeswitch** [node-webrtc/node-webrtc#25]
http://www.w3.org/TR/mediacapture-streams/

Create media streams for node that can send and receive video and audio.

**Comment by piranna** [comment]
Seems to me that this is not directly related with WebRTC, but instead on
getUserMedia() and similar, isn't it?

**Comment by modeswitch** [comment]
The PeerConnection API supports adding and removing streams, as well as offering audio and video capability. I would like these to be supported in the node module as well.

I don't see a reason to implement getUserMedia for node.

**Comment by piranna** [comment]
Ok, I agree then.

**Comment by notedit** [comment]
hi  modeswitch:

i just see this 

"
In Chrome 31 and above, a MediaStream from one RTCPeerConnection can be used as the input for another: there's a demo at simpl.info/multi. This can enable more flexible architectures, since it enables a web app to handle call routing by choosing which other peer to connect to
"

in these article http://www.html5rocks.com/en/tutorials/webrtc/infrastructure/

i think it it is easier to do stream  multiplexing.

**Comment by notedit** [comment]
any timeline for this issue?

**Comment by modeswitch** [comment]
Possibly over the next week or so, I think. There are a few use-cases here so I'd like to see this working.

**Comment by matbeedotcom** [comment]
+1
I need to support client stream -> server -> client stream

**Comment by kofd** [comment]
Need the media stream functionality so I've implemented mediastream.h and mediastream.cc, but I'm running into a few issues. I can't get node-webrtc to build right (without my additions) and I'm new to github so I'm not sure how to properly join the project

**Comment by modeswitch** [comment]
@kofd No worries! I've added you as a contributor and assigned this issue to you. I can also try and help you get things compiling; are you on a linux machine?

**Comment by kofd** [comment]
I'm running on Ubuntu 12.04, using ssh on an aws server. I've got it all set up for the most part, but I'm stuck when running:

$ node-gyp --debug rebuild 

The objects binding.o, peerconnection.o, and datachannel.o seem to be created just fine but, but after:

   ...
   CXX(target) Debug/obj.target/webrtc/src/datachannel.o
   SOLINK_MODULE(target) Debug/obj.target/webrtc.node

g++ gives a bunch of "No such file or directory" errors:

   g++: error: ../lib/libwebrtc/trunk/out/Debug/obj/talk/libjingle_peerconnection.a: No such file or directory
   ...
   g++: error: ../lib/libwebrtc/trunk/out/Debug/obj/webrtc/system_wrappers/source/libsystem_wrappers.a: No such file or directory
   make: **\* [Debug/obj.target/webrtc.node] Error 1

and I'm really not sure what to do after this point, especially since those files do exist

**Comment by kofd** [comment]
one thing I suspect to be the problem is that make has entered ~/node-webrtc/build, so ../lib/libwebrtc/ is actually ~/node-webrtc/lib/libwebrtc/, not ~/lib/libwebrtc/

**Comment by modeswitch** [comment]
First thing, can you make sure you're pulling from `develop` and not `libwebrtc`? That will give you the latest code. Also make sure that in `binding.gyp` you have `'libwebrtc_out%': '<(libwebrtc)/out/Release/obj',`.

**Comment by kofd** [comment]
I used the libwebrtc file structure for checking out webrtc (from the old readme file), but my git checkout is from the develop branch... so ~/node-webrtc/lib is currently empty

**Comment by modeswitch** [comment]
Can you try running `npm install`? You'll need to have `depot_tools` installed globally and in your path.

**Comment by kofd** [comment]
depot_tools is all fine, right now I'm trying to rebuild webrtc in ~/node-webrtc/lib/libwebrtc/trunk instead of ~/lib/libwebrtc. depot_tools is currently installed to ~/tools/depot_tools and it is in my path, gclient sync and runhooks all complete without error, and I'm about to use ninja to build the release and debug versions of peerconnection_client again...

... though it seems that npm install hangs on gclient_runhooks

**Comment by modeswitch** [comment]
So you're running `ninja -C lib/libwebrtc/trunk/out/Release` and getting errors?

**Comment by kofd** [comment]
I don't get errors with ninja, it looks like glient_runhooks just finished too (it just looked like it was hanging because the progress mechanism wasn't moving anymore).

**Comment by modeswitch** [comment]
OK, let me know if you run into more problems and I'll give help.

**Comment by kofd** [comment]
thanks, I think i've figured it out. If I get it to build I can do a unit test and commit the files.

**Comment by kofd** [comment]
I'm not sure what I'm doing wrong with committing. I call:

git push origin develop

and get

ERROR: Permission to modeswitch/node-webrtc.git denied to kofd.
fatal: The remote end hung up unexpectedly

**Comment by modeswitch** [comment]
@kofd You don't have push access to my repo. You'll first need to make a fork and push to that. Then make a pull request onto my repo and I'll merge it.

**Comment by kofd** [comment]
You mention that I should be using the develop branch, but my fork doesn't have one. I can't figure out why...

I've committed the files mediastream.h, mediastream.cc, mediastreamtrack.h, mediastreamtrack.cc to my libwebrtc branch and integrated them into the build, I'll commit the changes to peerconnection when I get a chance

**Comment by modeswitch** [comment]
@kofd https://github.com/kofd/node-webrtc/tree/develop

You can go into settings and change that to the default branch. You may want to check out some tutorials for git and github also.

**Comment by kofd** [comment]
I'm not sure how to implement automated testing for media streams because until we support the server-side creation of streams, the streams can only be initiated by receiving a stream from another source

**Comment by modeswitch** [comment]
Can you add whatever test you used to make sure it works? It can be a node script and a webpage, that's fine.

**Comment by modeswitch** [comment]
@kofd To add the tests, you can make more pushes to your branch and they'll be added to the pull request automatically.

**Comment by modeswitch** [comment]
@kofd I merged your patch, thanks for that! When you have a chance, make another pull request to add your test into `examples`.

**Comment by JessieAMorris** [comment]
So I've tried using your test on Debian Stable with the latest code. When running the stream tests, I get the error:

```
node: symbol lookup error: /home/jessie/node-webrtc/build/Release/webrtc.node: undefined symbol: vp8_idct_dequant_0_2x_sse2
```

It looks like this should be in the libvpx_asm_offset_vp8.a or one of the other libvpx files. Any idea on what I'm doing wrong? Other than that, it seems like the streaming API works correctly.

And for future questions and issues, do you guys have an IRC channel or something that I can be in?

**Comment by modeswitch** [comment]
@JessieAMorris i just set up a channel `#wrtc` on `irc.mozilla.org`

**Comment by modeswitch** [comment]
@kofd could you add some instructions for running the example you committed?

**Comment by JessieAMorris** [comment]
So it seems like the issue is with the link order of libvpx.a and libvpx_intrinsics_sse2.a

I have no clue how to go about fixing this right now.

**Comment by modeswitch** [comment]
Since there's only a small number of libraries, fiddling with the link order by hand is probably going to be easiest. Try moving `libvpx.a` after `libvpx_intrinsics_sse2.a`, that may fix it.

I ended up not having much time to look into this today. I should have some free cycles again on Friday.

**Comment by modeswitch** [comment]
@JessieAMorris There's a circular dep here:

```
libvpx.a:../../../gen/third_party/libvpx/idctllm_sse2.o:0000000000000000 T vp8_idct_dequant_0_2x_sse2
libvpx_intrinsics_sse2.a:source/libvpx/vp8/common/x86/libvpx_intrinsics_sse2.idct_blk_sse2.o:                 U vp8_idct_dequant_0_2x_sse2

libvpx.a:source/libvpx/vp8/encoder/libvpx.onyx_if.o:                 U vp8_variance_halfpixvar16x16_v_wmt
libvpx_intrinsics_sse2.a:source/libvpx/vp8/common/x86/libvpx_intrinsics_sse2.variance_sse2.o:0000000000000000 T vp8_variance_halfpixvar16x16_v_wmt
```

Should be fixed now.

**Comment by kofd** [comment]
@modeswitch Yeah, I'll get the latest version running on my dev env sometime this weekend and write it up

**Comment by kofd** [comment]
Sorry I haven't been able to write anything up, I've been getting the "gclient_runhooks failed: 2 null" error

**Comment by blakelapierre** [comment]
Checkout PR #136, updates the code to get remote MediaStream forwarding working.

**Comment by modeswitch** [comment]
Native backend won't support media streams.
