### ISSUE TITLE
How does node-webrtc handle WebRTC's multiple threads?

### ISSUE THREAD

**Issue by bfishman** [node-webrtc/node-webrtc#254]
According to some of the WebRTC API docs: 

```
WebRTC Native APIs use two globally available threads: the signaling thread and the worker thread. Depending on how the PeerConnection factory is created, the application can either provide those two threads or just let them be created internally.

Calls to the Stream APIs and the PeerConnection APIs will be proxied to the signaling thread, which means that an application can call those APIs from whatever thread.

All callbacks will be made on the signaling thread. The application should return the callback as quickly as possible to avoid blocking the signaling thread. Resource-intensive processes should be posted to a different thread.

The worker thread is used to handle more resource-intensive processes, such as data streaming.
```

How does this module handle such multi-threading, with node being 'natively' single-threaded?

**Comment by modeswitch** [comment]
Node isn't really single-threaded. Your JS runs in a single-threaded event loop (in V8), but native modules can create new threads and pass messages back and forth from the  main event loop.

If you want more details, go read about `libuv`, `V8`, and the `Node` source repo will show you how it all fits together. The code in this repo might helpful too, as it's a multi-threaded native module.
