### ISSUE TITLE
Unable to install on mac osx (10.11.3) node (5.1.1), npm (3.3.12)

### ISSUE THREAD

**Issue by shahraship** [node-webrtc/node-webrtc#256]
16640 verbose stack Error: wrtc@0.0.59 install: `node-pre-gyp install --fallback-to-build`
16640 verbose stack Exit status 1
16640 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
16640 verbose stack     at emitTwo (events.js:87:13)
16640 verbose stack     at EventEmitter.emit (events.js:172:7)
16640 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
16640 verbose stack     at emitTwo (events.js:87:13)
16640 verbose stack     at ChildProcess.emit (events.js:172:7)
16640 verbose stack     at maybeClose (internal/child_process.js:818:16)
16640 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
16641 verbose pkgid wrtc@0.0.59
16642 verbose cwd /Users/bla/Developer/proj/webkitserver
16643 error Darwin 15.3.0
16644 error argv "/usr/local/Cellar/node/5.1.1/bin/node" "/usr/local/bin/npm" "install"
16645 error node v5.1.1
16646 error npm  v3.3.12
16647 error code ELIFECYCLE
16648 error wrtc@0.0.59 install: `node-pre-gyp install --fallback-to-build`
16648 error Exit status 1
16649 error Failed at the wrtc@0.0.59 install script 'node-pre-gyp install --fallback-to-build'.
16649 error Make sure you have the latest version of node.js and npm installed.
16649 error If you do, this is most likely a problem with the wrtc package,
16649 error not with npm itself.
16649 error Tell the author that this fails on your system:
16649 error     node-pre-gyp install --fallback-to-build
16649 error You can get their info via:
16649 error     npm owner ls wrtc
16649 error There is likely additional logging output above.
16650 verbose exit [ 1, true ]

**Comment by JerryFox1** [comment]
got the same thing, any luck installing this?

**Comment by ivanjacobs** [comment]
same for me

/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObject.h:19:21: error: expected a type
- (id)copyWithZone:(nullable NSZone *)zone;
                  ^
  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObject.h:25:28: error: expected a type
- (id)mutableCopyWithZone:(nullable NSZone *)zone;
                         ^
  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObject.h:32:4: error: expected a type
- (nullable instancetype)initWithCoder:(NSCoder *)aDecoder; // NS_DESIGNATED_INITIALIZER
  ^
  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObject.h:53:4: error: expected a type
- (nullable id)replacementObjectForCoder:(NSCoder *)aCoder;
  ^
  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObject.h:54:4: error: expected a type
- (nullable id)awakeAfterUsingCoder:(NSCoder *)aDecoder NS_REPLACES_RECEIVER;
  ^
  In file included from ../../webrtc/base/iosfilesystem.mm:15:
  In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSPathUtilities.h:5:
  In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSString.h:9:
  In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSRange.h:5:
  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSValue.h:17:4: error: expected a type
- (nullable instancetype)initWithCoder:(NSCoder *)aDecoder NS_DESIGNATED_INITIALIZER;
  ^
  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSValue.h:30:42: error: expected a type
- (NSValue *)valueWithNonretainedObject:(nullable id)anObject;
                                       ^
  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSValue.h:31:12: error: unknown property attribute 'nullable'
  @property (nullable, readonly) id nonretainedObjectValue;
         ^
  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSValue.h:33:32: error: expected a type
- (NSValue *)valueWithPointer:(nullable const void *)pointer;
                             ^
  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSValue.h:34:12: error: unknown property attribute 'nullable'
  @property (nullable, readonly) void *pointerValue;
         ^
  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSValue.h:42:4: error: expected a type
- (nullable instancetype)initWithCoder:(NSCoder *)aDecoder NS_DESIGNATED_INITIALIZER;
  ^
  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSValue.h:81:38: error: expected a type
- (NSString *)descriptionWithLocale:(nullable id)locale;
                                   ^
  In file included from ../../webrtc/base/iosfilesystem.mm:15:
  In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSPathUtilities.h:5:
  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSString.h:12:23: error: expected ';' after @class
  @class NSData, NSArray<ObjectType>, NSDictionary<KeyType, ObjectType>, NSCharacterSet, NSURL, NSError, NSLocale;
                    ^
  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSString.h:12:24: error: cannot find protocol declaration for 'ObjectType'
  @class NSData, NSArray<ObjectType>, NSDictionary<KeyType, ObjectType>, NSCharacterSet, NSURL, NSError, NSLocale;
                     ^
  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSString.h:12:35: error: expected unqualified-id
  @class NSData, NSArray<ObjectType>, NSDictionary<KeyType, ObjectType>, NSCharacterSet, NSURL, NSError, NSLocale;
                                ^
  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSString.h:82:4: error: expected a type
- (nullable instancetype)initWithCoder:(NSCoder *)aDecoder NS_DESIGNATED_INITIALIZER;
  ^
  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSString.h:109:123: error: expected a type
- (NSComparisonResult)compare:(NSString *)string options:(NSStringCompareOptions)mask range:(NSRange)compareRange locale:(nullable id)locale; // locale arg used to be a dictionary pre-Leopard. We now accept NSLocale. Assumes the current locale if non-nil and non-NSLocale. nil continues to mean canonical compare, which doesn't depend on user's locale choice.
                                                                                                                        ^
  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSString.h:147:123: error: expected a type
- (NSRange)rangeOfString:(NSString *)searchString options:(NSStringCompareOptions)mask range:(NSRange)searchRange locale:(nullable NSLocale *)locale NS_AVAILABLE(10_5, 2_0);
                                                                                                                        ^
  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSString.h:151:37: error: expected a type
- (NSRange)rangeOfCharacterFromSet:(NSCharacterSet *)searchSet;
                                  ^
  fatal error: too many errors emitted, stopping now [-ferror-limit=]
  20 errors generated.
  [451/630] CXX obj/webrtc/system_wrappers/source/system_wrappers.sort.o
  ninja: build stopped: subcommand failed.
  ERROR: 1 null 

make: **\* [/dev/null] Error 255
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/ivanjacobs/Documents/development/socket.io-p2p/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/Cellar/node/6.2.0/bin/node" "/Users/ivanjacobs/Documents/development/socket.io-p2p/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/ivanjacobs/Documents/development/socket.io-p2p/node_modules/wrtc/build/wrtc/v0.0.59/Release/node-v48-darwin-x64/wrtc.node" "--module_name=wrtc" "--module_path=/Users/ivanjacobs/Documents/development/socket.io-p2p/node_modules/wrtc/build/wrtc/v0.0.59/Release/node-v48-darwin-x64"
gyp ERR! cwd /Users/ivanjacobs/Documents/development/socket.io-p2p/node_modules/wrtc
gyp ERR! node -v v6.2.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/6.2.0/bin/node /Users/ivanjacobs/Documents/development/socket.io-p2p/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/ivanjacobs/Documents/development/socket.io-p2p/node_modules/wrtc/build/wrtc/v0.0.59/Release/node-v48-darwin-x64/wrtc.node --module_name=wrtc --module_path=/Users/ivanjacobs/Documents/development/socket.io-p2p/node_modules/wrtc/build/wrtc/v0.0.59/Release/node-v48-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/ivanjacobs/Documents/development/socket.io-p2p/node_modules/wrtc/node_modules/node-pre-gyp/lib/util/compile.js:73:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:850:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
node-pre-gyp ERR! System Darwin 14.5.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/6.2.0/bin/node" "/Users/ivanjacobs/Documents/development/socket.io-p2p/node_modules/wrtc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/ivanjacobs/Documents/development/socket.io-p2p/node_modules/wrtc
node-pre-gyp ERR! node -v v6.2.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.4
node-pre-gyp ERR! not ok
