### ISSUE TITLE
chrome [Error: SessionDescription is NULL.]

### ISSUE THREAD

**Issue by shahraship** [node-webrtc/node-webrtc#257]
While trying to fetch a stream from chrome and passing the description to the server, gives error while trying to add remotedescription. Here is what the object looks like.

{ type: 'offer',
  sdp: 'v=0\r\no=- 9174124137721575408 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE audio video\r\na=msid-semantic: WMS HWOYkGSuKiGCPvw6psnYQqgdSedRk2D8IMH2\r\nm=audio 9 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 13 126\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:7ZLMedrftrVmMegw\r\na=ice-pwd:Rw8HlnMOoX8NEuWi+uZzNMAK\r\na=fingerprint:sha-256 F8:8A:68:F0:CA:7E:4E:47:13:44:0F:41:76:60:2D:C3:12:A1:F0:E3:89:00:3D:36:37:FE:0C:41:2A:8D:C9:B7\r\na=setup:actpass\r\na=mid:audio\r\na=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\na=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=recvonly\r\na=rtcp-mux\r\na=rtpmap:111 opus/48000/2\r\na=fmtp:111 minptime=10; useinbandfec=1\r\na=rtpmap:103 ISAC/16000\r\na=rtpmap:104 ISAC/32000\r\na=rtpmap:9 G722/8000\r\na=rtpmap:0 PCMU/8000\r\na=rtpmap:8 PCMA/8000\r\na=rtpmap:106 CN/32000\r\na=rtpmap:105 CN/16000\r\na=rtpmap:13 CN/8000\r\na=rtpmap:126 telephone-event/8000\r\na=maxptime:60\r\nm=video 9 UDP/TLS/RTP/SAVPF 100 101 116 117 96\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:7ZLMedrftrVmMegw\r\na=ice-pwd:Rw8HlnMOoX8NEuWi+uZzNMAK\r\na=fingerprint:sha-256 F8:8A:68:F0:CA:7E:4E:47:13:44:0F:41:76:60:2D:C3:12:A1:F0:E3:89:00:3D:36:37:FE:0C:41:2A:8D:C9:B7\r\na=setup:actpass\r\na=mid:video\r\na=extmap:2 urn:ietf:params:rtp-hdrext:toffset\r\na=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:4 urn:3gpp:video-orientation\r\na=sendrecv\r\na=rtcp-mux\r\na=rtpmap:100 VP8/90000\r\na=rtcp-fb:100 ccm fir\r\na=rtcp-fb:100 nack\r\na=rtcp-fb:100 nack pli\r\na=rtcp-fb:100 goog-remb\r\na=rtpmap:101 VP9/90000\r\na=rtcp-fb:101 ccm fir\r\na=rtcp-fb:101 nack\r\na=rtcp-fb:101 nack pli\r\na=rtcp-fb:101 goog-remb\r\na=rtpmap:116 red/90000\r\na=rtpmap:117 ulpfec/90000\r\na=rtpmap:96 rtx/90000\r\na=fmtp:96 apt=100\r\na=ssrc-group:FID 3066160426 3776889866\r\na=ssrc:3066160426 cname:4a9dQ/m6wb6A8szh\r\na=ssrc:3066160426 msid:HWOYkGSuKiGCPvw6psnYQqgdSedRk2D8IMH2 5b73a017-55fb-410a-bf60-407c43e3ec52\r\na=ssrc:3066160426 mslabel:HWOYkGSuKiGCPvw6psnYQqgdSedRk2D8IMH2\r\na=ssrc:3066160426 label:5b73a017-55fb-410a-bf60-407c43e3ec52\r\na=ssrc:3776889866 cname:4a9dQ/m6wb6A8szh\r\na=ssrc:3776889866 msid:HWOYkGSuKiGCPvw6psnYQqgdSedRk2D8IMH2 5b73a017-55fb-410a-bf60-407c43e3ec52\r\na=ssrc:3776889866 mslabel:HWOYkGSuKiGCPvw6psnYQqgdSedRk2D8IMH2\r\na=ssrc:3776889866 label:5b73a017-55fb-410a-bf60-407c43e3ec52\r\n' }

**Comment by mlgarrido** [comment]
I have the same error. +1

**Comment by benweet** [comment]
+1

**Comment by Globik** [comment]
And where can I look at your code? Do you use an examples/bridge.js or on your own? It is very intresting how to use this module wrtc without bridge.js

**Comment by bengesoff** [comment]
My googlings have led me to see that `UDP/TLS/RTP/SAVPF` could possibly yield an error - the newer `UDP/TLS` part might not be supported here 
https://bugs.chromium.org/p/webrtc/issues/detail?id=2796
http://stackoverflow.com/questions/33284549/nw-js-failed-to-parse-sessiondescription-failed-to-parse-audio-codecs-correctl
The [libwebrtc tree](https://github.com/js-platform/libwebrtc/tree/master/talk/app/webrtc) which provides a lot of the binary source files is very old and doesn't appear to work very well with the newer chrome versions.

**Comment by markandrus** [comment]
This should not be an issue anymore.
