### ISSUE TITLE
Document status of this project

### ISSUE THREAD

**Issue by alangibson** [node-webrtc/node-webrtc#260]
Can you please document the status of this project? 

It appears to be either on hiatus or dead since there have been no commits since Nov 2015.

**Comment by JerryFox1** [comment]
wondering about this too

**Comment by Cyberfit** [comment]
There are a lot of build issues that are unaddressed at the moment and there seems to be very little activity in the issues tracker.

Is there an actively developed alternative to this project? Is this project still alive?

**Comment by markandrus** [comment]
This project is still alive, in fact we are about to release an update that
fixes some deprecation warnings in Node v6.

One of the challenges is separating WebRTC build issues from node-webrtc
build issues. I am working on separating these two by setting up Linux, OS
X, and Windows machines for building and uploading WebRTC binaries we can
link against.

AFAIK, webrtc-native and electron are alternatives.

**Comment by Cyberfit** [comment]
That's very good news. I managed to get it working by finding an old binary that's lying around in the issues tracker and rolling back node to 0.10.45 but I'd much rather have it running on 6.x.

I quickly checked out webrtc-native and electron and they definitely seem subpar compared to node-webrtc (when it works).
