### ISSUE TITLE
Segfault when connecting with a peer in Firefox

### ISSUE THREAD

**Issue by josdejong** [node-webrtc/node-webrtc#261]
I get a segmentation fault when I connect a WebRTC peer in Firefox and in node.js
- When the peer in Firefox is the initiator, a connection is set up directly after that node.js crashes with a "Segmentation fault". The Firefox peer still thinks the connection is open after node.js has crashed.
- When the peer in node.js is the initator, the connection works fine. As soon as the Firefox peer disconnects though node.js crashes with a "Segmentation fault".

I'm running linux, node.js 5.7.1, Firefox 44.0.2, wrtc 0.0.59.

Any clue?

**Comment by michaelwoodson** [comment]
I think I ran into the same issue a few weeks ago.  I remember it depended on who the initiator was. From my notes, I ran segault-handler and got this stacktrace, (looks like it is related to setting up SSL so it makes sense that it depends on who is initiating):

```
PID 42762 received SIGSEGV for address: 0x0
0   segfault-handler.node               0x00000001016ececb _ZL16segfault_handleriP9__siginfoPv + 283
1   libsystem_platform.dylib            0x00007fff9c33aeaa _sigtramp + 26
2   ???                                 0x0000000000000000 0x0 + 0
3   wrtc.node                           0x000000010414ff4f _ZN3rtc13OpenSSLDigest13GetDigestNameEPK9env_md_stPSs + 15
4   wrtc.node                           0x000000010405e6cb _ZN6webrtc14StatsCollector23AddOneCertificateReportEPKN3rtc14SSLCertificateERKSs + 59
5   wrtc.node                           0x000000010405eb08 _ZN6webrtc14StatsCollector21AddCertificateReportsEPKN3rtc14SSLCertificateE + 232
6   wrtc.node                           0x000000010405d362 _ZN6webrtc14StatsCollector18ExtractSessionInfoEv + 1186
7   wrtc.node                           0x0000000104056937 _ZN6webrtc14PeerConnection5CloseEv + 23
8   wrtc.node                           0x000000010405b125 _ZThn8_N6webrtc8internal21SynchronousMethodCall9OnMessageEPN3rtc7MessageE + 21
9   wrtc.node                           0x000000010414d01d _ZN3rtc6Thread15ProcessMessagesEi + 125
10  wrtc.node                           0x000000010414cca6 _ZN3rtc6Thread6PreRunEPv + 134
11  libsystem_pthread.dylib             0x00007fff9d5c9c13 _pthread_body + 131
12  libsystem_pthread.dylib             0x00007fff9d5c9b90 _pthread_body + 0
13  libsystem_pthread.dylib             0x00007fff9d5c7375 thread_start + 13
```

I'm planning to move off of osx for development but haven't had a chance to test on a different platform yet.

Versions:
node-webrtc 0.0.59
osx 10.11.3
xcode 7.2 building against 6.4
node 5.3.0
npm 3.3.12
Didn't record FF version.

**Comment by NithyeshS** [comment]
Any update regarding this issue?

**Comment by markandrus** [comment]
Connecting to Firefox has been tested as part of CI for a while now. I've not seen this issue in CI, so I'm closing for now. If anyone has a repro example, feel free to reopen this or a new issue.
