### ISSUE TITLE
compile on raspberry pi b+ raspbian 4.1.19+ #858

### ISSUE THREAD

**Issue by dammianhr** [node-webrtc/node-webrtc#268]
i have this error when try to install wrtc. any idea?
node -v v4.2.1
npm -v 2.14.7

pi@raspberrypi:~/node-webrtc $ npm install
npm WARN package.json wrtc@0.0.59 license should be a valid SPDX license expression

> wrtc@0.0.59 install /home/pi/node-webrtc
> node-pre-gyp install --fallback-to-build

make: Entering directory '/home/pi/node-webrtc/build'
  ACTION Run build script /dev/null
TARGET_ARCH=arm PLATFORM=linux CONFIGURATION=Release PYTHON=python MODULE_PATH=/home/pi/node-webrtc/build/wrtc/v0.0.59/Release/node-v46-linux-arm
: Cloning depot_tools ... 
Cloning into 'depot_tools'...
POST git-upload-pack (205 bytes)
POST git-upload-pack (214 bytes)
remote: Counting objects: 1013, done
remote: Finding sources: 100% (1013/1013)
remote: Total 1013 (delta 126), reused 548 (delta 126)
Receiving objects: 100% (1013/1013), 3.07 MiB | 1.03 MiB/s, done.
Resolving deltas: 100% (126/126), done.
Checking connectivity... done.
: Cloning libwebrtc ... 
Cloning into 'libwebrtc'...
POST git-upload-pack (205 bytes)
POST git-upload-pack (214 bytes)
remote: Counting objects: 11018, done.
remote: Compressing objects: 100% (8730/8730), done.
remote: Total 11018 (delta 1803), reused 9934 (delta 1651), pack-reused 0
Receiving objects: 100% (11018/11018), 18.21 MiB | 63.00 KiB/s, done.
Resolving deltas: 100% (1803/1803), done.
Checking connectivity... done.
Checking out files: 100% (10144/10144), done.
: Updating clang ... 
Trying to download prebuilt clang
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 23.3M  100 23.3M    0     0   608k      0  0:00:39  0:00:39 --:--:--  920k
clang 218707 unpacked
: Generating build scripts ... 
Updating projects from gyp files...
..........: Building libwebrtc ... 
Unknown architecture (armv6l) -- unable to run ninja.
No prebuilt ninja binary was found for this system.
Try building your own binary by doing:
  cd ~
  git clone https://github.com/martine/ninja.git -b v1.7.1
  cd ninja && ./configure.py --bootstrap
Then add ~/ninja/ to your PATH.
ERROR: 1 null 

action_before_build.target.mk:13: recipe for target '/dev/null' failed
make: **\* [/dev/null] Error 255
make: Leaving directory '/home/pi/node-webrtc/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/pi/node-webrtc/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.1.19+
gyp ERR! command "/usr/local/bin/node" "/home/pi/node-webrtc/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/pi/node-webrtc/build/wrtc/v0.0.59/Release/node-v46-linux-arm/wrtc.node" "--module_name=wrtc" "--module_path=/home/pi/node-webrtc/build/wrtc/v0.0.59/Release/node-v46-linux-arm"
gyp ERR! cwd /home/pi/node-webrtc
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /home/pi/node-webrtc/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/pi/node-webrtc/build/wrtc/v0.0.59/Release/node-v46-linux-arm/wrtc.node --module_name=wrtc --module_path=/home/pi/node-webrtc/build/wrtc/v0.0.59/Release/node-v46-linux-arm' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/pi/node-webrtc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:818:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Linux 4.1.19+
node-pre-gyp ERR! command "/usr/local/bin/node" "/home/pi/node-webrtc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/pi/node-webrtc
node-pre-gyp ERR! node -v v4.2.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.27
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /home/pi/node-webrtc/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/pi/node-webrtc/build/wrtc/v0.0.59/Release/node-v46-linux-arm/wrtc.node --module_name=wrtc --module_path=/home/pi/node-webrtc/build/wrtc/v0.0.59/Release/node-v46-linux-arm' (1)

npm ERR! Linux 4.1.19+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! wrtc@0.0.59 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wrtc@0.0.59 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the wrtc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls wrtc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/node-webrtc/npm-debug.log

thaks for share!

**Comment by markandrus** [comment]
Hi @dammianhr, thanks for the report. I think we should try to get some Raspberry PI binaries available in the future. From what I have read, compiling WebRTC on Raspberry PI is difficult (impossible?) and cross-compiling is the way to go.

**Comment by markandrus** [comment]
I know this is an old thread, but as of [v0.3.3](https://github.com/node-webrtc/node-webrtc/releases/tag/v0.3.3), we ship armv7l and arm64 binaries. I don't know if your device is armv6l (unsupported for now) or armv7l, but it might work now.
