### ISSUE TITLE
Performance is not better than TCP?

### ISSUE THREAD

**Issue by SebastianNette** [node-webrtc/node-webrtc#273]
Hi Guys,

just a quick question regarding this repo. I noticed that the performance is just as bad as regular websockets, so I was wondering. is this an actual webrtc client or are you using websockets in the background?

All packets are ordered and no packet loss at all, feels just like websockets which can't be the purpose of this repo.. am I missing some settings?

**Comment by markandrus** [comment]
Hi @SebastianNette,

> is this an actual webrtc client or are you using websockets in the background?

This project provides an actual WebRTC client. In fact it links to the [webrtc.org](https://webrtc.org) implementation. It does not use WebSockets.

> All packets are ordered and no packet loss at all, feels just like websockets which can't be the purpose of this repo.. am I missing some settings?

DataChannel as you may know is SCTP, where order/reliability is configurable. Our bindings do not currently expose [the `ordered` property](https://developer.mozilla.org/en-US/docs/Web/API/RTCDataChannel/ordered) and default to ordered/reliable, but we would like to add this (pull requests welcome!).

**Comment by SebastianNette** [comment]
Thanks for the info, markandrus. :)

I'm fairly new to webrtc and after my tests yesterday, it really felt like tcp and had me a little confused.
I want to get something udp like, so I set the ordered property to false and the maxRetransmits to 0.

I will take a look into the bindings, maybe I can help out. :D

**Comment by melv-n** [comment]
So, right now any DataChannel opened through `node-webrtc` will have `ordered: true`? Is the same true if a client connects and creates the offer, thus defining DataChannels? If a client says `ordered: false`, will `node-webrtc` adhere? @markandrus  @SebastianNette

**Comment by melv-n** [comment]
@markandrus How challenging would it be for the bindings to expose the `ordered` property?

**Comment by markandrus** [comment]
Actually, I think I misspoke. We do appear to have [code for setting `ordered`](https://github.com/js-platform/node-webrtc/blob/3dd844d661b38475a471e65dd43f16a9ee265610/src/peerconnection.cc#L364), along with other properties. @SebastianNette @mirague have you tried calling `createDataChannel(label, { ordered: false })`?

**Comment by OpherV** [comment]
@SebastianNette Have you by chance tried to retest with @markandrus' suggestion? Can you report your results?

**Comment by getkey** [comment]
I can confirm setting `ordered` to `false` works however I have been unable to create unreliable data channels.
It's possible to create a data channel with `maxRetransmits` set to `0` and/or `maxPacketLifeTime` set to `0`  (at least in the browser, I haven't tried on Node.js), the resulting DataChannel object has `reliable` set to `false` which is to be expected.
 But in the tests I made I haven't seen any packet get dropped, even though the code seems to [be there](https://github.com/js-platform/node-webrtc/blob/v0.0.61/src/peerconnection.cc#L368) as well.

**Comment by OpherV** [comment]
@getkey Thanks for the info! Can you please elaborate on which tests have you tried?

**Comment by getkey** [comment]
Yes sure. I simulated conditions where 10% of packets get dropped by running `iptables -A OUTPUT -m statistic --mode random --probability 0.1 -j DROP`. I used the latest node-webrtc version from the trunk (f5d13d137a08d93b6bec48c82ef792f5df5b08b2), because v0.0.61 crashes for me.

Basically I connect a browser and a `node-webrtc` peer and open an unordered data channel. Then the browser sends a bunch of messages numbered from 0 to 99, and I display them in the console upon reception.
When 10% of packets are dropped, a few packets are do not come in order, otherwise not.

If you want you can reproduce my tests you can do so by:
* cloning my framework [enslavism](https://github.com/KordonBleu/enslavism/commit/cdc2fb15bc87bce0daf9adf10707e9d7cb597ead)
* copying `client/orderness-test.js` to `examples/userapp.js`
* [setting it up and running the example](https://github.com/KordonBleu/enslavism/tree/cdc2fb15bc87bce0daf9adf10707e9d7cb597ead#examples)

**Comment by Fr33maan** [comment]
I'm concerned by this issue as I would love to be able to use udp like transport in the browser.
@getkey, did you manage to understand wh1t was happening? Did you find another solution? Did you check that the browser was not simply sending packets one after each other or did you used multi threading via webworkers to send packets at the same time?

**Comment by getkey** [comment]
No I did not, I switched to [another library](https://github.com/KordonBleu/enslavism/commit/3a23485ad6a89c5eb69f5610d9d51bfa422ce6e8). The browser was indeed sending packets one after each other, I wasn't doing any multi-threading. Feel free to dig up and customize [my old tests](https://github.com/js-platform/node-webrtc/issues/273#issuecomment-267173582), but I abandoned this project in a year and a half ago now. Good luck! :wink:

**Comment by Fr33maan** [comment]
@getkey Dude the lib you made looks awesome ! I havn't decided yet which library I will use for webRTC, currently I'm building on top of webSockets hoping it will be fast enough.

**Comment by getkey** [comment]
Ha thanks! It was quite an ambitious project, and it, by itself, actually works. The weak link in the chain are the WebRTC libs, which were crashy and I don't think it has changed much unfortunately.

For your own sake I recommend keeping on building with WebSocket as long as you can and then only consider switching to WebRTC, or another technology that could pop up in the meantime (I've heard that browsers are looking into UDP-like sockets, but anyway I don't think something production-ready will come out very soon).

**Comment by blockspacer** [comment]
This might be helpful for threading: https://github.com/blockspacer/webrtc-datachannels
