### ISSUE TITLE
RTCDataChannel misses read-only properties

### ISSUE THREAD

**Issue by melv-n** [node-webrtc/node-webrtc#275]
According to the [RTCDataChannel spec](https://developer.mozilla.org/en-US/docs/Web/API/RTCDataChannel) we should be able to check (read-only) against certain properties on a channel. Right now almost none of these properties are exposed, apart from `binaryType`, `label`, `readyState` and `bufferedAmount`.

I'm particularly interested in reading the `ordered`, `maxRetransmits` and `maxPacketLifeTime` when a Channel is received through the `ondatachannel` event. This will allow us to "validate" the opened DataChannel on the answering Peer's side (important for our use-case).

@markandrus

**Comment by corbanbrook** [comment]
also missing `id` read only property on RTCDataChannel instance.

**Comment by markandrus** [comment]
These were merged into develop and coming in 0.1.0.
