### ISSUE TITLE
Expose `ordered` property on createDataChannel

### ISSUE THREAD

**Issue by melv-n** [node-webrtc/node-webrtc#276]
As mentioned in #273, right now we cannot set the `ordered` property (according to [the RTCDataChannel spec](https://developer.mozilla.org/en/docs/Web/API/RTCDataChannel)) when creating a DataChannel through [`createDataChannel`](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/createDataChannel). At the moment `ordered` defaults to `false` which limits the amount of use-cases for DataChannels.

It would be fantastic to have this property exposed as this allows for a more "udp-like" connection.

@markandrus

**Comment by markandrus** [comment]
@mirague as I mentioned in #273, I think I misspoke: we do appear to [have code for setting `ordered`](https://github.com/js-platform/node-webrtc/blob/3dd844d661b38475a471e65dd43f16a9ee265610/src/peerconnection.cc#L364), along with other properties.

Have you tried setting these? Are they not working for you?

**Comment by melv-n** [comment]
@markandrus I will test these soon; right now we have frozen some of our DataChannel development due to some limitations we found with our setup (https://github.com/js-platform/node-webrtc/issues/278)

**Comment by markandrus** [comment]
Support for this was merged into develop and will be released in 0.1.0.
