### ISSUE TITLE
NPM module should build correctly

### ISSUE THREAD

**Issue by modeswitch** [node-webrtc/node-webrtc#28]
NPM automatically runs the gyp file in the top-level project directory:

> If you have a file with a .gyp extension in the root of your package, then npm 
> will run the appropriate node-gyp commands automatically at install time.

As a first step, maybe it's best to just check all the external dependencies into the repository and not worry about gclient at all. For linux and darwin, that should mean that only the compile step is needed. Not sure how to support the build process on Windows.

**Comment by helloIAmPau** [comment]
The problem is gclient gets different libraries on mac and linux. What about executing gclient command in the gyp file?

**Comment by modeswitch** [comment]
@helloIAmPau I played around with that a few days ago but I couldn't get it to work properly. I could definitely use some help in this area. The preferred way of building native modules is to use a gyp file. Can we move the stuff from the Makefile over?

**Comment by modeswitch** [comment]
This should be fixed now. NPM is currently down so I'll finish testing it later.
