### ISSUE TITLE
attempting to run on centos 6.5...

### ISSUE THREAD

**Issue by grkblood13** [node-webrtc/node-webrtc#280]
Every attempt to get this to run on centos 6.5 x86_64 has ended badly. Does anyone know if there's a way to get this to work? Updating the OS in my case isn't really an option.

**Comment by Rush** [comment]
I tried to build it on centos 6 to address this problem but it seems even the build toolchain included in Chrome requires newer Glibc (2.15).

I was able to upgrade Python to the right version, Git and so on and so worth but it was to no avail due to that Glibc.
