### ISSUE TITLE
Newer version to address segaults

### ISSUE THREAD

**Issue by Rush** [node-webrtc/node-webrtc#282]
Segfaults are happening all over the place. Will there ever be a new version published to address this?

Perhaps updating the underlying library would make it better.

**Comment by bfishman** [comment]
I've had to shift over to electron webRTC on account of those. I know this is free software and everyone is donating their time so I'm not complaining, but did want to add my voice to the pile of those affected by the faults.

**Comment by Rush** [comment]
I on the other hand have implemented running node-webrtc inside a worker process. For starting one data channel and exitting the worker it's a perfect solution. Electron weighs a frickin' 100MB!

**Comment by markandrus** [comment]
@Rush @bfishman this is good feedback. @Rush, any chance you tried the most recent commits on master using the newer build of WebRTC? Still seeing segfaults with that? I'm hoping to setup some longer-running tests soon to shake more of these out.

**Comment by Rush** [comment]
@markandrus I did build a version using your scripts but it used that branch 50 commit. I had in plan trying against a newer one but before I do I'd like to be able to continue a build from a previously failed point... is there any chance you could modify the build scripts in order to accomodate that? Even though I have experience with makefiles, cmake and some ninja, the complexity of this Chromium build system kinda scares me.

**Comment by baadc0de** [comment]
Just in case: One of the instant segfaults is using non-RSA certs, which are a default on Chrome 52+. Forcing chrome to use RSA makes it go away.

https://developers.google.com/web/updates/2016/06/webrtc-ecdsa?hl=en

**Comment by markandrus** [comment]
Anyone who happens to still be following along (old issue, I know), please try most recent releases.
