### ISSUE TITLE
Issues with build scripts

### ISSUE THREAD

**Issue by Rush** [node-webrtc/node-webrtc#283]
@markandrus  I have found scripts/download-webrtc-libraries-and-headers.js to be very useful, thanks.

https://github.com/js-platform/node-webrtc/commit/ebab17ec41b8a58a965f74a6622e9377e205f7d2
- [ ] We need abiility to continue the build in case of errors
- [ ] Provide a mode where build files are not removed (so that one can experiment with editing the Chromium code)
- [ ] Provide instructions on how to use a custom toolchain (let's say, for Rasberry Pi)

**Comment by markandrus** [comment]
These are achievable now using node-cmake:

> We need abiility to continue the build in case of errors

Re-run with `./node_modules/.bin/cmake build`.

> Provide a mode where build files are not removed (so that one can experiment with editing the Chromium code)

node-cmake will leave the files in-place under `./build/external/libwebrtc/download`.

> Provide instructions on how to use a custom toolchain (let's say, for Rasberry Pi)

Described in the current README.md under "armv7l" and "arm64".
