### ISSUE TITLE
Confirmed Lab Setups?

### ISSUE THREAD

**Issue by RaggarDK** [node-webrtc/node-webrtc#288]
I've had some issues both building from source as well as installing using the package manager.
My latest issue is that of #281, but I only have limited size on my partition, so I would prefer not having to download Chromium. 
What Linux distros and versions have successfully been used to install node-webrtc without errors?

**Comment by markandrus** [comment]
Off-hand, I have tested with recent versions of Ubuntu and Fedora (x64), though I cannot recall exact version numbers. I would like to be able to point people to examples of the builds running on popular platforms, but I am not yet sure how best to do that—Dockerfiles? Some kind of Travis CI integration?
