### ISSUE TITLE
CPU usage should drop as soon as a connection is closed

### ISSUE THREAD

**Issue by manuguerra** [node-webrtc/node-webrtc#289]
For each new connection, there's an increase in CPU usage; currently, it only drops when the gc is triggered and the the `PeerConnection` destructor is called, which can happen quite a while after the connection is actually closed. For single sporadic connections it's fine, but it can be critical if we happen to have many connections in a short period of time.

As a workaround, I'm currently trying dereferencing the `jinglePeerConnection` and `jinglePeerConnectionFactory` pointers in the `Close` method, which seems to be working fine for me; CPU usage drops as soon as the connection is closed, as expected.
Is it a safe solution? Any suggestions?

[ _tested with Node 4.5 on Ubuntu 14, 32 and 64 bit, and Debian Wheezy 32 bit_ ]

**Comment by markandrus** [comment]
@manuguerra feel free to open a pull request and we can take a look at it. This seems like a reasonable change.

**Comment by mirague** [comment]
This sounds like a great improvement to the library, looking forward to see the PR @manuguerra

**Comment by melv-n** [comment]
This sounds like a great improvement. Could this be related to #278?

**Comment by manuguerra** [comment]
Hi @mirague, I'm not sure, do you have some system stats (specially CPU usage per process) from when you observed your service freezing? 
Even if it's not related, this issue should have an impact in your use case; as you're handling with many simultaneous connections, you'll want to free resources as soon as a connection is closed.

**Comment by melv-n** [comment]
@manuguerra As soon as the freeze happens (after closing a bunch of connections or opening too many) the process can shoot to 100% CPU usage after which the process hangs and then the CPU goes back to a low stable point of < 2% (process stays frozen). Sometimes a SEGFAULT is thrown.
