### ISSUE TITLE
Not getting server reflexive candidates when I give iceServers in the PeerConnection Constructor

### ISSUE THREAD

**Issue by ParikshitPrakash** [node-webrtc/node-webrtc#293]
For nodejs as the client (with wrtc module) , I am always getting candidates with local ip in the ice gathering stage when I am using a stun server.
But when I do the same thing (same stun server) keeping browser as client (without wrtc module) , I am getting server reflexive candiate in the ice gathering stage. 

Could someone help me out how to get server reflexive candidate with wrtc module?

**Comment by ParikshitPrakash** [comment]
More Details: 
Example:
From Browser:  In https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/,
If I give the stun server as  203.183.172.196:3478 ( got it from http://209.124.34.240:8090/display/KNOW/STUN+Servers) , I can get some candidates of type srflx.

When I repeat the same thing with wrtc, I am not getting any srflx candidates.
the code is as follows:

```
var RTCPeerConnection = require('..').RTCPeerConnection;
var RTCSessionDescription = require('..').RTCSessionDescription;

var config = {
    iceServers: [{url: "stun:203.183.172.196:3478"}]
};
var pc = new RTCPeerConnection(config,
    {
        'optional': []
    });

var sdpConstraints = {
    'OfferToReceiveAudio': false,
    'OfferToReceiveVideo': false
};

pc.onicecandidate = function (event) {
    //console.log(event);
    if (event.candidate) {
        console.log(event.candidate);
    }
};

var dataChannelParams = {ordered: false, maxRetransmits: 0};
var channel = pc.createDataChannel('sendDataChannel', dataChannelParams);
channel.binaryType = 'arraybuffer';
channel.onopen = function () {
    console.log('channel open');
};
channel.onclose = function () {
    console.log('channel close');
};

pc.createOffer(
    doSetLocalDesc,
    doHandleError, sdpConstraints);

function doSetLocalDesc(desc) {
    console.log(desc);
    pc.setLocalDescription(
        new RTCSessionDescription(desc)
    );
}
function doHandleError(error) {
    throw error;
}

setTimeout(function () {
    // channel.close();
    // channel = null;
    pc.close();
    // pc = null;
}, 10000);

```

**Comment by ryskov** [comment]
Right now the implementation doesnt respect the configuration object given to PeerConnection. I have an open pull request that implements what you are looking for.

Still a bit weird you are getting no reflexive candidates, since a STUN server is hardcoded in the current implementation.

https://github.com/js-platform/node-webrtc/pull/295

**Comment by ParikshitPrakash** [comment]
Thank you Ryskov! I am now getting server reflexive candidates with your code for the stun server 203.183.172.196:3478.

And coming to the original hardcoded stun server(stun:stun.l.google.com:19302) in the peerconnection.cc file, I didnt get any server reflexive candidate in the node. Even in browser, I didn't get any reflexive candidate for google stun server. May be, it all depends on the network I am connected to. 
So your unit test may not pass for all the cases. When I change the stun server to 203.183.172.196:3478 in your unit test, it successfully passed (got server reflexive candidate).

I don't know much about networking. May be someone can throw light on it.
Anyways, my requirement is fulfilled with your implementation.
Thanks a lot!

**Comment by markandrus** [comment]
Thanks for the report, @ParikshitPrakash; and thanks for the PR, @ryskov!

> Even in browser, I didn't get any reflexive candidate for google stun server. 

One thing I have observed, if you are answering and the answerer has already received some host candidates it can use, it may not gather any server reflexive candidates and complete ICE gathering early. I wonder if this could have been happening.
