### ISSUE TITLE
onSuccess is not a function

### ISSUE THREAD

**Issue by balupton** [node-webrtc/node-webrtc#301]
```
/Users/balupton/Projects/active/app-new/server/node_modules/wrtc/lib/peerconnection.js:379
      onSuccess(new RTCStatsResponse(internalRTCStatsResponse));
      ^

TypeError: onSuccess is not a function
    at /Users/balupton/Projects/active/app-new/server/node_modules/wrtc/lib/peerconnection.js:379:7
```

relevant code is https://github.com/js-platform/node-webrtc/blob/987b25ac43ba099f85c5a520bb64ccf0a03660be/lib/peerconnection.js#L381-L385

this is my server code:

``` javascript
'use strict'

const {send, sendError, json} = require('micro')
const Peer = require('simple-peer')
const wrtc = require('wrtc')
const cors = require('permissive-cors')()

const config = {}

const peer = new Peer({
	initiator: true,
	wrtc
})

peer.on('signal', (data) => {
	if ( data.type === 'offer' ) {
		config.offer = data
		console.log('generated offer')
	}
})

module.exports = function (req, res) {
	console.log('received request')
	cors(req, res, function () {
		console.log('loaded request')
		if ( req.url === '/peer-request' ) {
			if ( config.offer == null ) {
				sendError(req, res, new Error('offer not generated yet'))
			}
			else {
				send(res, 200, config.offer)
			}
		}
		else if ( req.url === '/peer-response') {
			json(req)
				.then(function (data) {
					peer.signal(data)
					send(res, 200, 'received')
				})
				.catch(function (error) {
					sendError(req, res, error)
				})
		}
		else {
			sendError(req, res, new Error('unknown route'))
		}
	})
}
```

**Comment by balupton** [comment]
the value of `onSuccess` is  `null`

**Comment by balupton** [comment]
culprit is https://github.com/feross/simple-peer/blob/v6.1.5/index.js#L441-L450

**Comment by balupton** [comment]
https://github.com/feross/simple-peer/pull/123 seems to have fixed it,

for others encountering the problem, set your dep to:

```
"simple-peer": "feross/simple-peer#202cd1d",
```

**Comment by daviddias** [comment]
It is solved now with simple-peer@6.2.0

Context: https://github.com/feross/simple-peer/issues/122

**Comment by balupton** [comment]
Shweet. Closing.

**Comment by nk015015** [comment]
### **TypeError: onSuccess is not a function**

import { firestore } from "../../firebase";

export const loadBanners = (onSuccess, onError) => {
return (dispatch, getState) => {
firestore
.collection("BANNERS")
.orderBy("index")
.get()
.then((querySnapshot) => {
let bannerdata = [];
if (!querySnapshot.empty) {
querySnapshot.forEach((doc) => {
bannerdata.push(doc.id, "=>", doc.data());
});
dispatch({ type: "LOAD_PAGE", payload: bannerdata });
onSuccess();
}
})
.catch((error) => {
console.log(error);
onError();
});
};
