### ISSUE TITLE
Build Problem 0.0.61 ARM7

### ISSUE THREAD

**Issue by isadounikau** [node-webrtc/node-webrtc#306]
Hello, I get problem with building wrtc for ARM7L
Works fine for desktop Linux (Ubuntu 16)

root@cl-som-imx6ul-sid:/test# npm install wrtc
-
> wrtc@0.0.61 install /test/node_modules/wrtc
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://node-webrtc.s3.amazonaws.com/wrtc/v0.0.61/Release/node-v46-linux-arm.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for wrtc@0.0.61 and node@4.7.2 (node-v46 ABI) (falling back to source compile with node-gyp) 
make: Entering directory '/test/node_modules/wrtc/build'
  ACTION Downloading WebRTC libraries and headers third_party/webrtc

> wrtc@0.0.61 download-webrtc-libraries-and-headers /test/node_modules/wrtc
> node scripts/download-webrtc-libraries-and-headers.js

Attempting to download WebRTC libraries and headers for platform "linux" and architecture "arm" from

  https://webrtc-libraries-and-headers.s3.amazonaws.com/v1/build/webrtc-50%2B49f7bd3.linux.arm.tar.gz

Binaries unavailable! Try building from source by setting BUILD_WEBRTC=1.

npm ERR! wrtc@0.0.61 download-webrtc-libraries-and-headers: `node scripts/download-webrtc-libraries-and-headers.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wrtc@0.0.61 download-webrtc-libraries-and-headers script.
npm ERR! This is most likely a problem with the wrtc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/download-webrtc-libraries-and-headers.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls wrtc
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.1.15-ne-shs-imx6ul+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "run" "download-webrtc-libraries-and-headers"
npm ERR! cwd /test/node_modules/wrtc
npm ERR! node -v v4.7.2
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

**Comment by KensakuKOMATSU** [comment]
I got same problem.

**Comment by ghost** [comment]
Hi,

You can follow these steps. https://github.com/js-platform/node-webrtc/issues/152

**Comment by markandrus** [comment]
FWIW, as of [v0.3.3](https://github.com/node-webrtc/node-webrtc/releases/tag/v0.3.3), we now ship binaries for armv7l and arm64. They're only tested with QEMU in CircleCI, so if you could, please test the pre-built binaries on a real device.
