### ISSUE TITLE
SIGSEGV error

### ISSUE THREAD

**Issue by GeneGenie** [node-webrtc/node-webrtc#308]
Good morning. I'm receiving segmentation fault during nodejs execution 

> PID 96850 received SIGSEGV for address: 0x70
0   segfault-handler.node               0x00000001047bd1d8 _ZL16segfault_handleriP9__siginfoPv + 280
1   libsystem_platform.dylib            0x00007fff965d952a _sigtramp + 26
2   ???                                 0x000000010b2458d3 0x0 + 4481898707
3   wrtc.node                           0x0000000107310382 _ZN6webrtc11DataChannel27OnTransportChannelDestroyedEv + 82
4   wrtc.node                           0x000000010731e928 _ZN6webrtc14PeerConnection22OnDataChannelDestroyedEv + 296
5   wrtc.node                           0x00000001073669ae _ZN6webrtc13WebRtcSessionD2Ev + 462
6   wrtc.node                           0x000000010736720e _ZN6webrtc13WebRtcSessionD0Ev + 14
7   wrtc.node                           0x000000010731d6f8 _ZN6webrtc14PeerConnectionD2Ev + 424
8   wrtc.node                           0x000000010733822e _ZN3rtc16RefCountedObjectIN6webrtc14PeerConnectionEED0Ev + 14
9   wrtc.node                           0x0000000107338204 _ZNK3rtc16RefCountedObjectIN6webrtc14PeerConnectionEE7ReleaseEv + 36
10  wrtc.node                           0x0000000107332bf8 _ZN6webrtc19PeerConnectionProxy9Release_sEv + 24
11  wrtc.node                           0x000000010732f175 _ZThn8_N6webrtc8internal21SynchronousMethodCall9OnMessageEPN3rtc7MessageE + 21
12  wrtc.node                           0x000000010744db2c _ZN3rtc6Thread3RunEv + 92
13  wrtc.node                           0x000000010744d7cd _ZN3rtc6Thread6PreRunEPv + 173
14  libsystem_pthread.dylib             0x00007fff9979a99d _pthread_body + 131
15  libsystem_pthread.dylib             0x00007fff9979a91a _pthread_body + 0
16  libsystem_pthread.dylib             0x00007fff99798351 thread_start + 13

Osx 10.11.5
Nodejs v7.7.4

Application logic is: Setup direct p2p between server and browser with data channel    on new socket client. 

```
io.on('connection', function (socket) {
    var pc = startRtcConnection()
    socket.on('ice', function (msg) {
        var message = JSON.parse(msg)
        if (message.desc) {
            var desc = message.desc;
            if (desc.type == "offer") {
                pc.setRemoteDescription(desc).then(function () {
                    return pc.createAnswer();
                })
                    .then(function (answer) {
                        return pc.setLocalDescription(answer);
                    })
                    .then(function () {
                        var str = JSON.stringify({"desc": pc.localDescription});
                        socket.emit("ice", str);
                    })
                    .catch(logError);
            }
        }
    });
});
function startRtcConnection() {
    var pc = new P2P(stunConfig);
    pc.ondatachannel = function (evt) {

        var channel = evt.channel;
        channel.addEventListener('onTransportChannelDestroyed',function(e){
            console.log("STATE",e)
        })
        var closed = false;
        channel.onclose = function () {
            closed= true
            channel.onmessage = null
            console.log("RTC DATA CHANNEL CLOSE")
        }
        channel.onerror = function (e) {
            closed= true
            channel.onmessage = null
            console.error("RTC DATA CHANNEL ERROR", e)
        }
        channel.onopen = function () {
            console.log("CHANNEL READY")
        };
        channel.onmessage = function (evt) {
           //some logic
            if (closed) return
            channel.send(JSON.stringify(response))
        };
    };
    return pc
}
````

Browser is always initiator.  Error happens on browser page refreshing

**Comment by markandrus** [comment]
Closing, as the referenced versions are quite old now.
