### ISSUE TITLE
Problem with Peerjs

### ISSUE THREAD

**Issue by pantrombka** [node-webrtc/node-webrtc#309]
I have a error:
```
/root/node_modules/peerjs/lib/util.js:234
      global.postMessage(messageName, '*');
             ^

TypeError: global.postMessage is not a function
    at Object.setZeroTimeoutPostMessage [as setZeroTimeout] (/root/node_modules/peerjs/lib/util.js:234:14)
    at Peer.disconnect (/root/node_modules/peerjs/lib/peer.js:420:8)
    at Socket.<anonymous> (/root/node_modules/peerjs/lib/peer.js:120:12)
    at Socket.emit (/root/node_modules/eventemitter3/index.js:71:35)
    at _http.onerror (/root/node_modules/peerjs/lib/socket.js:91:12)
    at dispatchEvent (/root/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
    at handleError (/root/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:533:10)
    at ClientRequest.errorHandler (/root/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:459:14)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)

```
And "my" code:
```
window = global;
window.BlobBuilder = require("BlobBuilder");
location = {protocol: 'http'};

BinaryPack = require("binary-pack");
XMLHttpRequest = require("xmlhttprequest").XMLHttpRequest;

var wrtc = require("wrtc");
RTCPeerConnection = wrtc.RTCPeerConnection;
RTCSessionDescription = wrtc.RTCSessionDescription;
RTCIceCandidate = wrtc.RTCIceCandidate;
WebSocket=require('ws')

require('peerjs/lib/exports.js');

        var peer = new Peer('x', {
            host: 'myip',
            port: 9000,
            path: '/myapp'
});


        peer.on('open', function(id) {
                console.log('My peer ID is: ' + id);
            });

```

**Comment by abardik** [comment]
setZeroTimeout uses postMessage which is ok for browsers, but it's undefined in nodejs. Just change setZeroTimeout to setTimeout(fn, 0) for node peerjs (lines 348 and 421), but leave setZeroTimeout for browser peerjs. It works for me.

**Comment by PeerAcc34** [comment]
Hi @abardik 

Thanks for your guidance.

I updated the code at lines 348 and 421 as suggested like so:

Lines near 348:
`Peer.prototype._delayedAbort = function(type, message) {
  var self = this;
   util.setTimeout(fn,0);
  // util.setZeroTimeout(function(){
  //   self._abort(type, message);
  // });
};`

Lines near 421:
`Peer.prototype.disconnect = function() {
  var self = this;
  util.setTimeout(fn,0);
  // util.setZeroTimeout(function(){
  //   if (!self.disconnected) {
  //     self.disconnected = true;
  //     self.open = false;
  //     if (self.socket) {
  //       self.socket.close();
  //     }
  //     self.emit('disconnected', self.id);
  //     self._lastServerId = self.id;
  //     self.id = null;
  //   }
  // });
};`

It was working for a while and sometime works on an erratic basis. However, when I run the code similar to @pantrombka I now regularly get the following error:

>   util.setTimeout(fn,0);
>       ^
> 
> TypeError: util.setTimeout is not a function

Is there any way to address this? The util library is required at the top of the peer module so there should be no issue in the peer module finding the setTimeout from the util module. 

 Any help would be much appreciated.

Thanks

**Comment by abardik** [comment]
Sure. Just use setTimeout, not util.setTimeout.

**Comment by PeerAcc34** [comment]
That worked @abardik. Thanks for your help!
