### ISSUE TITLE
Install on mac appears to fail

### ISSUE THREAD

**Issue by feross** [node-webrtc/node-webrtc#31]
With this message:

```
> wrtc@0.0.3 install /Users/feross/code/webtorrent/node_modules/wrtc
> node build.js

gclient_config
.
gclient_config failed: 127 null
wrtc@0.0.3 node_modules/wrtc
├── bindings@1.1.1
├── nan@0.4.4
└── node-gyp@0.10.10 (which@1.0.5, osenv@0.0.3, graceful-fs@2.0.1, rimraf@2.2.2, mkdirp@0.3.5, semver@2.1.0, nopt@2.1.2, minimatch@0.2.12, fstream@0.1.24, tar@0.1.18, glob@3.2.7, npmlog@0.0.6, request@2.27.0)
```

OS X 10.9. Node 0.10.22

**Comment by feross** [comment]
I installed with `npm install wrtc`

**Comment by modeswitch** [comment]
I haven't finished updating the docs yet ;P

You'll need set up `depot_tools` on your machine: http://www.chromium.org/developers/how-tos/install-depot-tools and re-run the install process.

**Comment by feross** [comment]
Okay, good to know. Eventually we should eliminate all external dependencies so you can just `npm install wrtc` and be done. :)

**Comment by modeswitch** [comment]
That would be nice, but it's necessary to have a build environment set up and `depot_tools` is part of that. I would prefer to have binary modules available for common platforms so that the checkout/compile stage is required only for rare cases.

**Comment by feross** [comment]
Can't the build step just `git clone depot_tools` and use it? Why does the user have to do it?

**Comment by modeswitch** [comment]
That only works for darwin and some linux distros. I suppose I can add a check for depot_tools and try downloading if that fails.

**Comment by modeswitch** [comment]
Yeah, I'll update `build.js` to do that.

**Comment by feross** [comment]
I believe this module (https://github.com/dcodeIO/ClosureCompiler.js) does something like that, but for the Java JRE.

**Comment by modeswitch** [comment]
Opened #32 to address the remaining issue here.
