### ISSUE TITLE
Can not get ice candidate of type relay

### ISSUE THREAD

**Issue by anastasiia-zolochevska** [node-webrtc/node-webrtc#311]
I have TURN server running. Works fine for webrtc web javascript app with the following config:

var pcConfig = {
  'iceServers': [
    {
      'url': 'stun:stun.l.google.com:19302'
    },
    {
      url: 'turn:xx.xx.xx.xx:3478',
      credential: '*',
      username: '*'
    }]
};

If the client is behind VPN (or if I just filter any candidates that don't contain "relay"), I get the following candidate of type relay and all of the messages go through turn server:
icecandidate event candidate info:  candidate:1047417019 1 udp 33562367 xx.xx.xx.xx 56894 typ relay raddr 52.232.28.249 rport 56368 generation 0 ufrag cBKV network-cost 50

Same configuration doesn't work for node application - I receive only candidates of type host and srflx. If I filter them, connection is not established. 

function onIceCandidate(event) {
  if (!event.candidate) return;
  if (event.candidate.candidate.indexOf("relay") != -1) {
    log('Relay candidate', event.candidate.candidate);
    sendMessage({
      type: 'candidate',
      candidate: event.candidate
    });
  }
  else {
    log('Dropping ice candidate', event.candidate.candidate);
  }
}

Did you test it with turn? Any idea why it's not working?

**Comment by isadounikau** [comment]
Yes, it works with TURN server
Check your NAT system. TURN server doesn't work properly inside Synchronised NAT

**Comment by isadounikau** [comment]
Try to use this service for testing your application connection with TURN server.
Numb is free service for TURN/STUN servers

http://numb.viagenie.ca/

**Comment by lecogiteur** [comment]
I have similar problem. Like @anastasiia-zolochevska, if I set `iceTransportPolicy` to relay, it doesn't work.

I use the example on loopback.

I change the RTCPeerConnection configuration for client and server by adding:

```json
{"iceServers":[{"username":"xxx","url":"turn:xxx.com:80?transport=tcp","credential": "xxx"}], "iceTransportPolicy": "relay"}
```
If I remove this from server, and change in client iceTransportPolicy to public it works.

The turn server work well. I have another webrtc application executed on my browser.

PS: The node application using node-webrtc is in docker container. 

With wireshirk I don't see stun request.

**Comment by markandrus** [comment]
It may make sense to update to the latest wrtc version and try again. Also, you must use `urls` instead of `url`, per the latest WebRTC spec.

**Comment by lecogiteur** [comment]
Thanks It's worked for me. You are right @markandrus . 
PS: In my browser twice are accepted `url` and `urls`
