### ISSUE TITLE
createDataChannel should not return undefined

### ISSUE THREAD

**Issue by t-mullen** [node-webrtc/node-webrtc#314]
This method should always return an RTCDataChannel object, or throw an error.

See https://www.w3.org/TR/webrtc/#dom-rtcpeerconnection-createdatachannel

[peerconnection.js Line 373](https://github.com/js-platform/node-webrtc/blob/develop/lib/peerconnection.js#L373)

**Comment by feross** [comment]
It looks like this is the correct way to handle unexpected issues. Return an already-closed channel:

<img width="808" alt="screen shot 2017-04-07 at 3 13 50 pm" src="https://cloud.githubusercontent.com/assets/121766/24823503/cc516042-1bb3-11e7-8fd8-255690ade1d6.png">

**Comment by markandrus** [comment]
Released in 0.1.1
