### ISSUE TITLE
binding.gyp fails

### ISSUE THREAD

**Issue by g00dnatur3** [node-webrtc/node-webrtc#315]
Why is this code in binding.gyp?

    {
      "target_name": "action_after_build",
      "type": "none",
      "dependencies": [ "<(module_name)" ],
      "copies": [
        {
          "files": [ "<(PRODUCT_DIR)/<(module_name).node" ],
          "destination": "<(module_path)"
        }
      ]
    }

looks out of place & actually could cause a failure if you run node-gyp

**Comment by markandrus** [comment]
Hi @g00dnatur3,

This project uses node-pre-gyp (in conjunction with node-gyp). If you take a look at [their README](https://github.com/mapbox/node-pre-gyp#2-add-a-new-target-to-bindinggyp), they suggest adding this line:

> A new target must be added to `binding.gyp` that moves the compiled `.node` module from `./build/Release/module_name.node` into the directory specified by `module_path`.

What do you mean by

> could cause a failure if you run node-gyp

? Are you experiencing issues?

Thanks,
Mark

**Comment by markandrus** [comment]
I'm closing this issue, since we've been using node-cmake for some time now and no longer have binding.gyp.
