### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by NithyeshS** [node-webrtc/node-webrtc#319]
I am using a fork of this repo [https://github.com/ssaroha/node-webrtc](https://github.com/ssaroha/node-webrtc) built with OpenSSL for ARM devices. I have been using it for the past few weeks and I noticed that the application memory increases as time progresses. Due to this the application fails to process(as it slows down) ICE connection checks on time and loses connectivity. I am not sure if this is an issue any body has encountered before or if it due to the building WebRTC with OpenSSL or if it an issue with the WebRTC version used. Any help regarding this is greatly appreciated.

**Comment by markandrus** [comment]
The biggest leak on RTCDataChannel should be fixed now in v0.1.2.
