### ISSUE TITLE
Error using wrtc in npm

### ISSUE THREAD

**Issue by spattnaik2311** [node-webrtc/node-webrtc#320]
The log: [npm_text.txt](https://github.com/js-platform/node-webrtc/files/1034343/npm_text.txt)

I am trying to install [Truffle][1] in my Ubuntu 16.10 system.
Before that I need to install node.js. The latest v8 is not supported. So I downloaded v7 and installed its `build-essential` tools. But while installing Truffle (`sudo npm install -g truffle`) I find an error saying:

> node-pre-gyp ERR! Tried to download(404):
> https://node-webrtc.s3.amazonaws.com/wrtc/v0.0.61/Release/node-v51-linux-ia32.tar.gz

> node-pre-gyp ERR! Pre-built binaries not found for wrtc@0.0.61 and
> node@7.10.0 (node-v51 ABI) (falling back to source compile with
> node-gyp)

And then, a moment later, this error pops up:

> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0
> (node_modules/truffle/node_modules/chokidar/node_modules/fsevents):

> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for
> fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current:
> {"os":"linux","arch":"ia32"}) 

> npm ERR! Linux 4.4.0-59-generic 
> npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "truffle" 
> npm ERR! node v7.10.0 
> npm ERR! npm  v4.2.0 
> npm ERR! code ELIFECYCLE 
> npm ERR! errno 1
> 
> npm ERR! wrtc@0.0.61 install: `node-pre-gyp install
> --fallback-to-build` npm ERR! Exit status 1
> 
> npm ERR!  Failed at the wrtc@0.0.61 install script 'node-pre-gyp
> install --fallback-to-build'. Make sure you have the latest version of
> node.js and npm installed. If you do, this is most likely a problem
> with the wrtc package, not with npm itself. Tell the author that this
> fails on your system:     node-pre-gyp install --fallback-to-build

Which version is supported by Yakkety? Should I revert to a previous version of Ubuntu?

  [1]: https://github.com/trufflesuite/truffle

**Comment by markandrus** [comment]
@GitSpree23 sorry it's been a while. I've released [v0.0.63](https://github.com/js-platform/node-webrtc/releases/tag/v0.0.63) which may fix this. If you still have problems, please re-open this issue. Thanks, Mark
