### ISSUE TITLE
Creating a new RTCPeerConnection is too slow (300-600ms)

### ISSUE THREAD

**Issue by franciscouzo** [node-webrtc/node-webrtc#330]
> start = process.hrtime(); new wrtc.RTCPeerConnection(); console.log(process.hrtime(start))
    [ 0, 327458037 ]

I'm running the 23a9352 commit that I built, with Node 8.3.0.

I will gladly provide more info if needed.

**Comment by nazar-pc** [comment]
For me it is 4ms on latest version of wrtc
