### ISSUE TITLE
Use datachannel only build of native webrtc

### ISSUE THREAD

**Issue by Zubnix** [node-webrtc/node-webrtc#334]
There is this good news:
https://groups.google.com/forum/?__s=obdrvn8g53z98ugdgkuz#!msg/discuss-webrtc/qDtSDxoNSII/69b6fAkxAQAJ

> Build WebRTC with DataChannel only
> webrtc::CreateModularPeerConnectionFactory() is available and it can be used to build WebRTC with DataChannel support only. It accepts MediaEngineInterface, CallFactoryInterface and RtcEventLogFactoryInterface as arguments. If the application knows it won't use certain modules, it can pass in null pointers for specific modules and omit the corresponding modules from its build. See an example of usage in webrtc:7613.

To build WebRTC with DataChannel support only:

```
// Create a peerconnection factory without media support.
CreateModularPeerConnectionFactory(network_thread,
worker_thread,
signaling_thread,
nullptr /MediaEngineInterface/,
nullptr /CallFactoryInterface/,
nullptr /*RtcEventLogFactoryInterface/);
// For native C++, depend on "peerconnection" without media instead of "libjingle_peerconnection"
deps = [ "pc:peerconnection" ]

// For ObjC wrapper, depend on the no_media version of PeerconnectionFactory.
deps = [ "peerconnectionfactory_no_media_factory" ]

// For Android wrapper, depend on the datachannel only version target.
deps = [
libjingle_peerconnection_datachannelonly_so
]
```

**Comment by markandrus** [comment]
I did something similar in [v0.0.63](https://github.com/js-platform/node-webrtc/releases/tag/v0.0.63), except

* I passed a FakeAudioDeviceModule, and
* [libwebrtc](https://github.com/aisouard/libwebrtc) still contains audio/video code, etc.

However, I think this might ease some of the pain from before? e.g., with XOpenDisplay.

**Comment by markandrus** [comment]
I don't think we will do this unless there are additional requests to ship such a build. Even then, we may not, as it would multiply our (already large) matrix of binaries we need to build by 2. Anyone interested, feel free to re-open.
