### ISSUE TITLE
implement onnegotiationneeded

### ISSUE THREAD

**Issue by devsnek** [node-webrtc/node-webrtc#335]
it would be really cool if this could be implemented, its strange that it isn't

**Comment by nazar-pc** [comment]
There is only one place where `simple-peer` uses detection for `node-webrtc`:
```javascript
  // HACK: wrtc doesn't fire the 'negotionneeded' event
  if (self.initiator && self._isWrtc) {
    self._pc.onnegotiationneeded()
  }
```

@markandrus, what is necessary to implement `onnegotiationneeded`, maybe something that needs to be requested from libwebrtc maintainers? #378 is a workaround in `node-webrtc` for workaround in `simple-peer` for this exact issue.

**Comment by markandrus** [comment]
I think this should be relatively straightforward to implement, not unlike the existing ICE connection state change event, ICE gathering state change event, and signaling state change event.

**Comment by markandrus** [comment]
I implemented this in https://github.com/js-platform/node-webrtc/pull/375.

**Comment by devsnek** [comment]
the sad thing is, i don't remember what i was doing in 2017 that i needed this :p

**Comment by nazar-pc** [comment]
@markandrus, thanks! Did you try to remove workaround already for simple-peer to make sure it works?

UPD: I saw workaround was dropped, great!
