### ISSUE TITLE
0.0.63 partially breaks simple-peer

### ISSUE THREAD

**Issue by nazar-pc** [node-webrtc/node-webrtc#339]
[simple-peer](https://github.com/feross/simple-peer) can't get remote IP and port after wrtc upgrade to 0.0.63 from 0.0.62 (https://github.com/nazar-pc/webtorrent-dht/issues/3).

The issue I found is that after opening data channel `getStats()` still returns `googCandidatePair` with `googActiveConnection: false`.

I'm not sure if I've mentioned correct pieces, but without `googActiveConnection: true` simple-peer doesn't fill corresponding information.

Here are related lines in simple-peer: https://github.com/feross/simple-peer/blob/e64fe5c459064ca941c90f8fb4aae241cd820cfd/index.js#L552-L634

And here is what `getStats()` item looks like at the time when it reaches `(item.type === 'googCandidatePair' && item.googActiveConnection === 'true') ||`:
```
{
	"googActiveConnection"    : "false",
	"bytesReceived"           : "157",
	"bytesSent"               : "0",
	"packetsSent"             : "0",
	"googReadable"            : "true",
	"requestsSent"            : "0",
	"consentRequestsSent"     : "0",
	"responsesSent"           : "1",
	"requestsReceived"        : "1",
	"responsesReceived"       : "0",
	"googChannelId"           : "Channel-data-1",
	"googLocalAddress"        : "192.168.1.2:55586",
	"localCandidateId"        : "Cand-gh513x9K",
	"googLocalCandidateType"  : "local",
	"googRemoteAddress"       : "192.168.1.2:51631",
	"remoteCandidateId"       : "Cand-LU2PJIBn",
	"googRemoteCandidateType" : "prflx",
	"googRtt"                 : "3000",
	"packetsDiscardedOnSend"  : "0",
	"googTransportType"       : "udp",
	"googWritable"            : "false",
	"type"                    : "googCandidatePair",
	"timestamp"               : 1511793755262.099
}
```

Interestingly, if I stop it at `self._connecting = true` for some time in Dev Tools's debugger, `googActiveConnection` gets flipped to `true` and everything works.

Looks like there is a timing issue somewhere, I'm not very familiar with this projects, but `googActiveConnection: false` seems odd when there is an active working `RTCDataChannel`.

**Comment by nazar-pc** [comment]
I see aisouard/libwebrtc is now used as dependency, maybe @aisouard can help figure out what is going wrong here?

**Comment by markandrus** [comment]
Hi @nazar-pc,

This is odd. I was unable to reproduce on macOS, but let me try on Windows and Linux. Can you clarify the platform you are using? Please check out the test code I am using below. I will look at simple-peer soon.

```js
// test.js
const assert = require('assert');
const { RTCPeerConnection } = require('wrtc');

async function test() {
  console.log('Creating RTCPeerConnections');
  const pc1 = new RTCPeerConnection();
  const pc2 = new RTCPeerConnection();

  console.log('Creating RTCDataChannel');
  const dc1 = pc1.createDataChannel('test');
  console.log('Created local RTCDataChannel');
  const dc2Promise = new Promise(resolve => pc2.ondatachannel = ({ channel }) => resolve(channel));

  [[pc1, pc2], [pc2, pc1]].forEach(([pc1, pc2]) => {
    pc1.onicecandidate = async ({ candidate }) => {
      if (candidate) {
        console.log('Candidate:\n', candidate.candidate);
        await pc2.addIceCandidate(candidate);
      }
    };
  });

  console.log('Creating offer');
  const offer = await pc1.createOffer();
  console.log('Created offer:\n' + offer.sdp);
  await Promise.all([
    pc1.setLocalDescription(offer),
    pc2.setRemoteDescription(offer)
  ]);

  console.log('Creating answer');
  const answer = await pc2.createAnswer();
  console.log('Creating answer:\n' + answer.sdp);
  await Promise.all([
    pc1.setRemoteDescription(answer),
    pc2.setLocalDescription(answer)
  ]);

  console.log('Waiting to receive remote RTCDataChannel');
  const dc2 = await dc2Promise;
  console.log('Recived remote RTCDataChannel');
  assert.equal(dc2.label, dc1.label);

  const activeConnections = await Promise.all([pc1, pc2].map(pc => new Promise(resolve => {
    const interval = setInterval(async () => {
      const response = await new Promise(resolve => pc.getStats(resolve));
      const reports = response.result();
      for (const report of reports) {
        if (report.type === 'googCandidatePair') {
          if (report.stat('googActiveConnection') === 'true') {
            resolve(report);
            clearInterval(interval);
          }
        }
      }
    }, 1000);
  })));

  console.log(activeConnections);

  pc1.close();
  pc2.close();
}

test().catch(error => {
  console.error(error);
  process.exit(1);
});
```

```
$ npm install wrtc

> wrtc@0.0.63 install /private/tmp/test-active-connection/node_modules/wrtc
> node-pre-gyp install --fallback-to-build

[wrtc] Success: "/private/tmp/test-active-connection/node_modules/wrtc/build/wrtc/v0.0.63/Release/node-v57-darwin-x64/wrtc.node" is installed via remote
npm WARN saveError ENOENT: no such file or directory, open '/private/tmp/test-active-connection/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/private/tmp/test-active-connection/package.json'
npm WARN test-active-connection No description
npm WARN test-active-connection No repository field.
npm WARN test-active-connection No README data
npm WARN test-active-connection No license field.

+ wrtc@0.0.63
added 195 packages in 8.623s

$ node test.js 
Creating RTCPeerConnections
Creating RTCDataChannel
Created local RTCDataChannel
Creating offer
Created offer:
v=0
o=- 327205652415529571 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE data
a=msid-semantic: WMS
m=application 9 DTLS/SCTP 5000
c=IN IP4 0.0.0.0
a=ice-ufrag:jpjT
a=ice-pwd:BZ8LyRj8CN1eemoGptoADHCh
a=fingerprint:sha-256 12:4B:B2:0B:8C:86:AF:E6:FC:21:14:02:7A:34:D1:6A:89:4C:20:06:05:FF:D1:FE:A9:17:03:B9:C9:65:17:50
a=setup:actpass
a=mid:data
a=sctpmap:5000 webrtc-datachannel 1024

Candidate:
 candidate:3363271197 1 udp 2122260223 10.20.69.9 61287 typ host generation 0 ufrag jpjT network-id 1 network-cost 50
Creating answer
Creating answer:
v=0
o=- 9211664464956126985 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE data
a=msid-semantic: WMS
m=application 9 DTLS/SCTP 5000
c=IN IP4 0.0.0.0
b=AS:30
a=ice-ufrag:I9jb
a=ice-pwd:6chtlSuNhJTdadD8r4kgATad
a=fingerprint:sha-256 3A:B0:31:B7:AA:ED:75:50:A3:2A:B9:7B:66:CF:FB:49:0E:3A:8F:31:89:76:C6:A6:4A:3E:AD:41:B2:53:8C:9F
a=setup:active
a=mid:data
a=sctpmap:5000 webrtc-datachannel 1024

Waiting to receive remote RTCDataChannel
Candidate:
 candidate:3363271197 1 udp 2122260223 10.20.69.9 62875 typ host generation 0 ufrag I9jb network-id 1 network-cost 50
Recived remote RTCDataChannel


[ RTCStatsReport { type: 'googCandidatePair', timestamp: 1511805088943.799 },
  RTCStatsReport { type: 'googCandidatePair', timestamp: 1511805088944.137 } ]
```

As you can see above, the test completes successfully when the active candidate pairs for both RTCPeerConnections have been identified.

**Comment by nazar-pc** [comment]
I'm on Ubuntu 18.04 with Node.js v9.2.0.
Your test seems to work for me too, but you're using `setInterval()`, while `simple-peer` relies on events instead.

**Comment by markandrus** [comment]
@nazar-pc good point! I just tweaked the script to invoke `getStats` based on "iceconnectionstatechange" and "datachannel" events. Interestingly, it doesn't work in Chrome 62 for me, either. See this JSFiddle: https://jsfiddle.net/x4yg03eL/

**Comment by markandrus** [comment]
@nazar-pc after skimming [webrtc-pc](https://w3c.github.io/webrtc-pc) and [webrtc-stats](https://w3c.github.io/webrtc-stats), there don't seem to be any hard guarantees around what is available in the (W3C-specced) `getStats` results in relation to the current state of the RTCPeerConnection. Granted, node-webrtc is still raising the legacy stats from Chrome, and not the W3C-specced stats, but the "googCandidatePair" stat and its "googActiveConnection" property roughly correspond to the [RTCIceCandidatePairStats](https://w3c.github.io/webrtc-stats/#candidatepair-dict*), the [RTCTransportStats](https://w3c.github.io/webrtc-stats/#transportstats-dict*), and the RTCTransportStats' [`selectedCandidatePairId`](https://w3c.github.io/webrtc-stats/#dom-rtctransportstats-selectedcandidatepairid) property. If I rewrite the JSFiddle to use these standard stats, the results are still non-deterministic: https://jsfiddle.net/q4zbpx3g/

I'd feel uncomfortable trying to re-implement the M50 behavior in node-webrtc, since it seems undefined with respect to the standard (which I'd like this project to move towards). What do you think about adding some code to simple-peer to poll (like `setInterval`) the `getStats` results?

**Comment by nazar-pc** [comment]
I think yes, tweaking simple-peer would be more appropriate, though getting stuff merged there would not be very easy.

Will work on simple-peer changes, appreciate your quick response and testing!

**Comment by markandrus** [comment]
@nazar-pc OK, thanks and no problem! If you want a review or feedback on the simple-peer changes, I'd be happy to help. Feel free to @-mention me. I want to see things continue working 🙏
