### ISSUE TITLE
gclient_config is not part of depot_tools

### ISSUE THREAD

**Issue by burg** [node-webrtc/node-webrtc#34]
I think you need to use `gclient config <stuff>` as `gclient_config` is not distributed with a new depot_tools checkout.

```
[burg@burg183 node-webrtc]# npm install

> wrtc@0.0.6 install /Users/burg/repos/node-webrtc
> node build.js

gclient_config
.
gclient_config failed: 127 null

```

**Comment by modeswitch** [comment]
Do you have depot_tools installed an in your path? What happens when you run `gclient` in your terminal?

**Comment by burg** [comment]
Yes, I do. `gclient` is a valid executable but `gclient_config` is not.

**Comment by modeswitch** [comment]
Npm is calling `build.js`, which runs

```
function gclient_config(callback)
{
  console.info("gclient_config");
  process.stdout.write('.');
  process.chdir(LIB_WEBRTC_DIR);
  child = exec("gclient config http://webrtc.googlecode.com/svn/trunk");
  child.on('exit', function(code, signal)
  {
    process.stdout.write('\n');
    if(0 === code && !signal)
    {
      console.log('gclient_config complete');
      gclient_sync(callback);
    }
    else
    {
      console.error('gclient_config failed:', code, signal);
    }
  });
}
```

It's calling `gclient config http://webrtc.googlecode.com/svn/trunk`. Can you try checking out the code from the github and running the gclient command in the `lib/libwebrtc` directory?

**Comment by modeswitch** [comment]
@burg Also, which platform are you on?

**Comment by modeswitch** [comment]
I'm not able to reproduce this. Please re-open and provide additional details if you're still having this problem.

**Comment by thanpolas** [comment]
@modeswitch i experience the same issue, i also just read #58 which may be related.

I'm on osx 10.9.1 (latest), depot tools last SHA is `d03893e 2014-01-30` and is in path.

`npm install` will produce the same exact error as @burg reported. When i run the command your script suggests:

```
gclient config http://webrtc.googlecode.com/svn/trunk
```

It run ok, nothing happened. I have the repo cloned and mingling... please advise.
