### ISSUE TITLE
Port Restriction Policy

### ISSUE THREAD

**Issue by njohnst** [node-webrtc/node-webrtc#354]
For my use-case I'd like to be able to restrict the range of ports that the ICE gatherer is able to generate local candidates from - I've seen a policy for this in Chrome (Google.Policies.Chrome::WebRtcUdpPortRange).

Would it be possible to add this feature?
I'm not exactly sure where the binaries come from / what is possible via the bindings...

I'd appreciate it if someone could point me in the right direction, I'm willing to implement this myself.

Thank you,
Nicholas

**Comment by markandrus** [comment]
I think we could expose this as a non-standard option on RTCConfiguration.

**Comment by njohnst** [comment]
I appreciate it.  I will look into native webrtc to see where this would be implemented

**Comment by njohnst** [comment]
Added the feature in a fork - RTCConfiguration option called "customPortRange" that takes a string in the format "<MIN_PORT>-<MAX_PORT>" (e.g. "customPortRange: '1234-2345'")

https://github.com/njohnst/node-webrtc/tree/port-restriction

EDITED:
There is currently no way to use the same UDP port for more than one client, I'm looking at a fix for this

Cheers

**Comment by njohnst** [comment]
Allowing multiple clients on the same UDP port would require a major rewrite of the native code and is not feasible (AFAIK), thus I've just focused on the port range restriction in my PR.
