### ISSUE TITLE
peer.addIceCandidate throws Error: Failed to set ICE candidate.

### ISSUE THREAD

**Issue by PMLMonteiro** [node-webrtc/node-webrtc#355]
#Hello.

I am trying to use this library in a node server that receives streams from a browser. I am using this server as the signaling server as well.
When I receive candidates signals from the browser I do "peer.addIceCandidate" of the candidate that is signalled.
However, the code throws "Error: Failed to set ICE candidate.".

Am I doing something wrong or is this a bug?

Thanks!

**Comment by kblockdev** [comment]
Hi 
Do you have any idea why
Build error, can't install (red flag)
Node-pre-gyp ERR! Tried to download return 404

**Comment by markandrus** [comment]
Hi @PMLMonteiro, any chance you are adding the “null” candidate that signals end-of-ice-candidates? Mind sharing some code?

@kblockdev this is expected if you try to install a version on a platform that binaries are unavailable for. If you share the full logs, it should explain why. Mind opening a separate issue?

**Comment by kblockdev** [comment]
@markandrus thanks #356 opened

**Comment by PMLMonteiro** [comment]
@markandrus thanks for your response.

I just feel like I am messing with the correct "flow" of events.
First off, I have a button in my "frontend" in which I click to start the stream, which executes the following code:
`navigator.getUserMedia({video: true, audio: true}, mediaStream => {
      this.refs.myVideo.srcObject = mediaStream;

      this.setState({
        myStream : mediaStream
      });
      if(!this.state.myPc.addTrack) this.state.myPc.addStream(mediaStream);
      else mediaStream.getTracks().forEach(track => this.state.myPc.addTrack(track, mediaStream));

      this.state.myPc.createOffer().then(this.gotLocalDescription);`

And I create the offer after I get the tracks.
The offers triggers a signaling message to my signaling server (remember it is the same to which I want to send my stream to):

`gotLocalDescription(offer) {
    this.state.myPc.setLocalDescription(offer).then(() => {
      this.state.mySocket.emit('offer', offer);
    });
  }`

On my server, when I receive the offer I set my server's peer remote description to that, create an answer, set that answer to my server's peer local description and finally emit the answer to the frontend:
`client.on('offer', data => {
    return clients[client.test_server_id].peer.setRemoteDescription(data).then(() => {
      return clients[client.test_server_id].peer.createAnswer().then((answer) => {
        return clients[client.test_server_id].peer.setLocalDescription(answer).then(() => {
          return client.emit('answer', answer);
        });
      });
    });
  });`

In my frontend, when my socket gets an "answer" event it triggers a callback function that will set the frontend's peer remote description to that answer like this: 
`socket.on('answer', this.gotRemoteDescription);`

Where:
`  gotRemoteDescription(answer) {
    this.state.myPc.setRemoteDescription(answer).then(() => {
      console.log('success');
    });
  }`

Am I doing something wrong so far? What should happen after this?

Thanks a lot!

**Comment by markandrus** [comment]
@PMLMonteiro everything you described sounds fine so far. What does your code for handling the "icecandidate" event look like? Somewhere you should have code like

```js
myPc.onicecandidate = ({ candidate }) => { /* ... */ }
```

or

```js
myPc.addEventListener('icecandidate', ({ candidate }) => { /* ... */ })
```

Also, what does you code for calling `addIceCandidate` look like? e.g.

```js
myPc.addIceCandidate(candidate)
```

**Comment by PMLMonteiro** [comment]
Thanks again for your support!

After I create the peer connection on the server, I pass it all the event listeners. The onicecandidate looks like this, so that I can send the ice candidate to the other peer:
`peer.onicecandidate = (candidate) => {
    clients[id].client.emit('candidate', candidate.candidate);
  };`

And my addIceCandidate is being called on a message event of socket.io as follows, so that I can addIceCandidates that arrive:
`client.on('candidate', data => {clients[client.test_server_id].peer.addIceCandidate(data)});`

On the front end I have the same, that is, when I receive a onicecandidate event I send it through the signaling server, like follows:
`onIceCandidate(event) {
    if(event.candidate !== null) // not sure if we need to keep this or not
      this.state.mySocket.emit('candidate', event.candidate);
  }`

And when I get a signalled ice candidate, I do:
`gotSignalledIceCandidate(candidate) {
    if(candidate != null)
      this.state.myPc.addIceCandidate(candidate);
  }`

Please also note that I am not starting any stream on the server. My intention is to create an SFU of sorts.

Thanks a lot!

**Comment by markandrus** [comment]
Thanks for sharing, @PMLMonteiro. So I believe your error is because you are adding the "null" ICE candidate that signals end-of-candidates. Your front-end code has the check for the null ICE candidate:

```js
if(event.candidate !== null)
```

but not the backend. Please add the null check, and I think things should work.

**Comment by PMLMonteiro** [comment]
Ok, so I added the check and I still get nothing on the "onaddstream" listener in the server side. :x

I added some logs and, as it turns out, I am receiving two ICE candidates on the server side, one for audio and other for video (I am using both in my stream). On the client side, I am receiving only one, audio. I think I can also guarantee that the descriptions are being passed correctly between the two sides.

Any idea as to why I am not getting the onaddstream listener triggered? I am using Chrome and I know that WebRTC recently changed the onaddstream and addStream to ontrack and addTrack, which are not supported by Chrome (as far as I know).

All the help you can provide is greatly appreciated.

**Comment by markandrus** [comment]
> Ok, so I added the check and I still get nothing on the "onaddstream" listener in the server side. :x

"onaddstream" will not fire on the server because it is not implemented (yet) in this library. There is some talk about supporting it—and I'd like to, but it's not implemented yet.

**Comment by PMLMonteiro** [comment]
Many thanks for your answer.

What about ontrack? Is it implemented?
Would it be possible to contribute for that implementation?

**Comment by PMLMonteiro** [comment]
One more thing. If that is not implemented, how does the library handle streams?

**Comment by markandrus** [comment]
> the library handle streams?

The library does not currently handle MediaStreams at all. It is RTCDataChannel-focused ATM.

**Comment by PMLMonteiro** [comment]
Would it be possible for me to contribute to it so that it does? Or, if that is not possible, could you please point me in the right direction as to where can I change the library so that is can handle streams?

**Comment by markandrus** [comment]
Yes, it would be possible. I will try to create an issue with the relevant requirements and at-mention you plus some other interested contributors.

**Comment by PMLMonteiro** [comment]
Great, thank you very much!
Can this be done quickly? I am sorry but I am really keen into getting this going.

Thanks a lot for your continued support.

**Comment by markandrus** [comment]
There is limited support for ontrack in the most recent releases. Closing
