### ISSUE TITLE
Build error.

### ISSUE THREAD

**Issue by kblockdev** [node-webrtc/node-webrtc#356]
Build error, can't install.
Node-pre-gyp ERR! Tried to do

**Comment by markandrus** [comment]
Please share logs and we can triage

**Comment by kblockdev** [comment]
@markandrus Sir thanks

 here is the logs

 Ubuntu 16.10 (GNU/Linux 4.8.0-22-generic i686)

node-pre-gyp ERR! Tried to download(undefined): https://node-webrtc.s3.amazonaws.com/wrtc/v0.0.63/Release/node-v59-linux-ia32.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for wrtc@0.0.63 and node@9.2.1 (node-v59 ABI, glibc) (falling back to source compile with node-gyp)
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/med/ccli/node_modules/wrtc/build'
gyp ERR! System Linux 4.8.0-22-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/med/ccli/node_modules/wrtc/build/wrtc/v0.0.63/Release/node-v59-linux-ia32/wrtc.node" "--module_name=wrtc" "--module_path=/home/med/ccli/node_modules/wrtc/build/wrtc/v0.0.63/Release/node-v59-linux-ia32"
gyp ERR! cwd /home/med/ccli/node_modules/wrtc
gyp ERR! node -v v9.2.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/med/ccli/node_modules/wrtc/build/wrtc/v0.0.63/Release/node-v59-linux-ia32/wrtc.node --module_name=wrtc --module_path=/home/med/ccli/node_modules/wrtc/build/wrtc/v0.0.63/Release/node-v59-linux-ia32' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/med/ccli/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:159:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:943:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
node-pre-gyp ERR! System Linux 4.8.0-22-generic
node-pre-gyp ERR! command "/usr/local/bin/node" "/home/med/ccli/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/med/ccli/node_modules/wrtc
node-pre-gyp ERR! node -v v9.2.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/med/ccli/node_modules/wrtc/build/wrtc/v0.0.63/Release/node-v59-linux-ia32/wrtc.node --module_name=wrtc --module_path=/home/med/ccli/node_modules/wrtc/build/wrtc/v0.0.63/Release/node-v59-linux-ia32' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"ia32"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wrtc@0.0.63 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wrtc@0.0.63 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/med/.npm/_logs/2018-02-09T08_24_27_265Z-debug.log

**Comment by markandrus** [comment]
@kblockdev you are using Node 9. Since node-webrtc 0.0.63 only has pre-built binaries for Node 4–8, your `npm install` falls back to building from source with node-gyp. node-gyp needs to create a build directory (`mkdir build`), but for some reason doesn't have permission to (`EACCES: permission denied`). You have 3 options for remedying this:

1. Continue using node-webrtc 0.0.63, but downgrade to Node 8.
2. Continue using node-webrtc 0.0.63 with Node 9, but fix the permissions issue and ensure you have g++ and the necessary tools for node-gyp to build from source.
3. Use node-webrtc 0.0.66 with Node 9.

Options 1 and 3 should give you pre-built binaries, making `npm install`s fast. Option 2 will build from source, making `npm install` slow. By the way, is there any reason you want to use node-webrtc 0.0.63?

Thanks,
Mark

**Comment by kblockdev** [comment]
@markandrus Sir thank you for your help

For the version node-webrtc 0.0.63 it's from this repo https://github.com/seanjameshan/blockchain-cli/blob/master/package-lock.json

But, still can't start the app due to the build error in wrtc
trying your solution number 3 to install node-webrtc 0.0.66 with Node 9 by editing the package-lock json file but no luck, got some errors again here is the log

$ sudo npm install -g wrtc

> wrtc@0.0.66 install /usr/local/lib/node_modules/wrtc
> node scripts/install.js

Searching for a pre-built wrtc binary
node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/wrtc/build'
node-pre-gyp ERR! System Linux 4.8.0-22-generic
node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/wrtc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build=false"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/wrtc
node-pre-gyp ERR! node -v v9.2.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
EACCES: permission denied, mkdir '/usr/local/lib/node_modules/wrtc/build'
Unable to install a pre-built wrtc binary; falling back to ncmake
Running ncmake configure
Error creating directory "build".
Unable to create build directory
Running ncmake build
Project is not configured, Run 'configure' command first
Built wrtc
+ wrtc@0.0.66
updated 1 package in 68.095s

PS : g++ and node-gyp installed.

thank you sir.

Kai.

**Comment by nazar-pc** [comment]
The easiest thing for you in this case would be to downgrade to Node 8, especially since it is LTS and at the same time request mentioned project to upgrade to newer version of wrtc if possible.
