### ISSUE TITLE
Make sure allocated memory is properly freed

### ISSUE THREAD

**Issue by modeswitch** [node-webrtc/node-webrtc#36]
I avoided dealing with this so that I could get things working quickly. There are a bunch of places where memory is allocated but not freed.

Also need to make sure that memory for C++ objects is freed when the corresponding JS objects are cleaned up.

**Comment by wouldgo** [comment]
If you need an help I'm interested in resolving this issue (I agree with you that is quite a critical issue).

**Comment by piranna** [comment]
At my company (kurento.org) a colleague is working with the WebRTC Android bindings and it's having the same issues regarding to freeing resources, seems to be a problem on libWebrtc itself.

**Comment by modeswitch** [comment]
There are a few spots where I know memory needs to be freed (they should be marked), but for the most part this is a tedious task involving valgrind. It might be best to start with a stability test so that we can verify that this runs for a long time while creating many new connections/channels and destroying them.

**Comment by modeswitch** [comment]
I've cleaned up a few of the big issues. Closing this, and I'll open new issues for specific instances as I find them.
