### ISSUE TITLE
Invalid pointer when using downloaded libraries and headers on linux x86_64

### ISSUE THREAD

**Issue by williamberman** [node-webrtc/node-webrtc#365]
node version: 8.9.4 and 9.5.0
os version: Ubuntu 16.04
node-webrtc: develop head and f8a0891 (the ref cooresponding with the release of 0.67)
arch: x86_64

Running npm test with a wrtc.node compiled from the provided downloaded libraries results in

TAP version 13
\# create a peer connection
ok 1 created 
\# createOffer function implemented
ok 2 implemented
\# can call createOffer
*** Error in `node': free(): invalid pointer: 0x00007fd35401b578 ***
======= Backtrace: =========
etc..

The same occurs when manually building the headers and archive from aisouard/libwebrtc against branch-heads/57

The tests complete when using the provided wrtc.node binary with one failure
not ok 86 gotReflective === true

I will eventually need to cross compile to arm, and would like to be able to manually compile to x86_64 first which is why using the precompiled wrtc.node is not satisfactory for me.

**Comment by markandrus** [comment]
Hi, what version of g++ are you using? I have a feeling this issue is do to building with a version newer than g++-4.8 and not setting `_GLIBCXX_USE_CXX11_ABI`. I think you can either define `_GLIBCXX_USE_CXX11_ABI` or run

```
export CC=gcc-4.8
export CXX=g++-4.8
```

before rebuilding (`./node_modules/.bin/ncmake rebuild`) and it should work.

**Comment by markandrus** [comment]
> not ok 86 gotReflective === true

This test needs to be made more robust.

**Comment by williamberman** [comment]
Great that fixed it thank you so much!

**Comment by williamberman** [comment]
Could I add a pull request to add this to the readme?

**Comment by markandrus** [comment]
@williamberman yes please!
