### ISSUE TITLE
Add support for Node 10

### ISSUE THREAD

**Issue by markandrus** [node-webrtc/node-webrtc#399]
Process should be the same as adding support for previous Node versions:

1. Add the Node version to the `.travis.yml` and `appveyor.yml`
2. Try to build
3. Fix any v8/Nan issues
4. Do a release

This only gets complicated if 2. and 3. reveal unexpected weirdness.

**Comment by nazar-pc** [comment]
Compilation fails with:
```
/web/github/detox-core/node_modules/wrtc/src/converters/webrtc.cc:756:106: error: no matching function for call to ‘v8::Function::NewInstance(int, v8::Local<v8::Value> [2])’
   auto response = static_cast<Local<Value>>(Nan::New(RTCStatsResponse::constructor)->NewInstance(2, cargv));
                                                                                                          ^
In file included from /web/github/detox-core/node_modules/wrtc/build/node/v10.0.0/include/node.h:63:0,
                 from /web/github/detox-core/node_modules/nan/nan.h:51,
                 from /web/github/detox-core/node_modules/wrtc/src/converters/webrtc.h:17,
                 from /web/github/detox-core/node_modules/wrtc/src/converters/webrtc.cc:8:
```

There are also warnings, but not sure if they are important.

**Comment by markandrus** [comment]
I think we need to convert that and other constructor calls to use `Nan::NewIntance` (like in the “Factory of wrapped objects example” [here](https://github.com/nodejs/nan/blob/master/doc/object_wrappers.md)).

**Comment by markandrus** [comment]
@nazar-pc would you be interested in trying the conversion and adding Node 10 support? I think, instead of

```c++
Nan::New(RTCStatsResponse::constructor)->NewInstance(2, cargv)
```

we may just need to do this:

```c++
Nan::NewInstance(Nan::New(RTCStatsResponse::constructor), 2, cargv).ToLocalChecked()
```

**Comment by markandrus** [comment]
https://github.com/js-platform/node-webrtc/releases/tag/v0.1.4
