### ISSUE TITLE
[wrtc 0.1.4] - Installation from source failed due to a missing file

### ISSUE THREAD

**Issue by jb00ster** [node-webrtc/node-webrtc#400]
Hi, i'm trying to work from source so i've done the commands 
`git clone https://github.com/js-platform/node-webrtc.git`
`cd node-webrtc`
`npm install`
then i'm getting this error 

> Searching for a pre-built wrtc binary
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: 404 status code downloading tarball https://node-webrtc.s3.amazonaws.com/wrtc/v0.1.4/Release/node-v57-linux-x64.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (/home/rch/projects/node-webrtc/node_modules/node-pre-gyp/lib/install.js:118:27)
node-pre-gyp ERR! stack     at emitOne (events.js:121:20)
node-pre-gyp ERR! stack     at Request.emit (events.js:211:7)
node-pre-gyp ERR! stack     at Request.onRequestResponse (/home/rch/projects/node-webrtc/node_modules/request/request.js:1074:10)
node-pre-gyp ERR! stack     at emitOne (events.js:116:13)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:211:7)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:551:21)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:115:23)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:440:20)
node-pre-gyp ERR! stack     at emitOne (events.js:116:13)
node-pre-gyp ERR! System Linux 4.10.0-28-generic
node-pre-gyp ERR! command "/usr/local/bin/node" "/home/rch/projects/node-webrtc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build=false"
node-pre-gyp ERR! cwd /home/rch/projects/node-webrtc
node-pre-gyp ERR! node -v v8.11.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
404 status code downloading tarball https://node-webrtc.s3.amazonaws.com/wrtc/v0.1.4/Release/node-v57-linux-x64.tar.gz

when i try to get the file directly from the link in my browser i get an error

am i doing something wrong ?
thanks

**Comment by markandrus** [comment]
Hi @jb00ster,

This should be expected. Since v0.1.4 is not yet released, node-pre-gyp tries to fetch binaries for your particular configuration (Node 8 on 64-bit Linux), but fails with a 404. That is OK, because the next step in the install script falls back to building from source with node-cmake. If you share the rest of your logs, I believe we will see this.

Mark

**Comment by jb00ster** [comment]
Hi @markandrus thanks for your replay,
here is the entire logs; i got a build failed at the end, thanks for your help 

> rch@rch-VirtualBox:~/projects/node-webrtc$ npm install

> uws@9.14.0 install /home/rch/projects/node-webrtc/node_modules/uws
> node-gyp rebuild > build_log.txt 2>&1 || exit 0


> travis-multirunner@4.4.1 postinstall /home/rch/projects/node-webrtc/node_modules/travis-multirunner
> node bin/travis-sync


> wrtc@0.1.4 install /home/rch/projects/node-webrtc
> node scripts/install.js

> Searching for a pre-built wrtc binary
> node-pre-gyp ERR! install error 
> node-pre-gyp ERR! stack Error: 404 status code downloading tarball https://node-webrtc.s3.amazonaws.com/wrtc/v0.1.4/Release/node-v57-linux-x64.tar.gz
> node-pre-gyp ERR! stack     at Request.<anonymous> (/home/rch/projects/node-webrtc/node_modules/node-pre-gyp/lib/install.js:118:27)
> node-pre-gyp ERR! stack     at emitOne (events.js:121:20)
> node-pre-gyp ERR! stack     at Request.emit (events.js:211:7)
> node-pre-gyp ERR! stack     at Request.onRequestResponse (/home/rch/projects/node-webrtc/node_modules/request/request.js:1074:10)
> node-pre-gyp ERR! stack     at emitOne (events.js:116:13)
> node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:211:7)
> node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:551:21)
> node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:115:23)
> node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:440:20)
> node-pre-gyp ERR! stack     at emitOne (events.js:116:13)
> node-pre-gyp ERR! System Linux 4.10.0-28-generic
> node-pre-gyp ERR! command "/usr/local/bin/node" "/home/rch/projects/node-webrtc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build=false"
> node-pre-gyp ERR! cwd /home/rch/projects/node-webrtc
> node-pre-gyp ERR! node -v v8.11.1
> node-pre-gyp ERR! node-pre-gyp -v v0.6.39
> node-pre-gyp ERR! not ok 
> 404 status code downloading tarball https://node-webrtc.s3.amazonaws.com/wrtc/v0.1.4/Release/node-v57-linux-x64.tar.gz
> Unable to install a pre-built wrtc binary; falling back to ncmake
> Running ncmake configure
> CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
>   CMake 3.6 or higher is required.  You are running version 3.5.1
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/home/rch/projects/node-webrtc/build/CMakeFiles/CMakeOutput.log".
> Unable to configure project
> Running ncmake build
> make: *** No targets specified and no makefile found.  Stop.
> Build failed
> Built wrtc
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.2 (node_modules/fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> 
> added 913 packages in 23.176s

i will try to update my Cmake version and make a retry

**Comment by markandrus** [comment]
> CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
CMake 3.6 or higher is required. You are running version 3.5.1

Please try installing CMake 3.6 or newer.

**Comment by jb00ster** [comment]
@markandrus thanks for your help
indeed i was missing the good version of CMake, after upgrading it, the installation works fine 
thanks
