### ISSUE TITLE
How to make this work with zeit/pkg?

### ISSUE THREAD

**Issue by Zentendo** [node-webrtc/node-webrtc#404]
How to make this work with https://github.com/zeit/pkg? I put the wrtc.node, webrtc.lib, webrtc.exp files into the same file as the compiled .exe (Windows) and it still says Unable to find native module when I run it.

zeit/pkg works with nanomsg C bindings: https://github.com/nickdesaulniers/node-nanomsg and ZeroMQ C++ bindings: https://github.com/zeromq/zeromq.js/

**Comment by markandrus** [comment]
node-webrtc looks up the location of wrtc.node using [lib/binding.js](https://github.com/js-platform/node-webrtc/blob/develop/lib/binding.js). The contents of that file are

```js
module.exports = require('node-cmake')('wrtc', true);
```

So we're using node-cmake to lookup wrtc.node. node-cmake's lookup logic is [here](https://github.com/cjntaylor/node-cmake/blob/dev/index.js). I'm not sure if/how it works with zeit/pkg.

**Comment by Zentendo** [comment]
Hi @markandrus,

Thanks for the advice. I was able to get it to work by changing `bindings.js` to this relative path:
```module.exports = require('../build/Release/wrtc.node');```

The only workaround for now seems to be for me to fork this repo and pull any updates from the main repo. Do you have any suggestions in how I might be able to avoid doing that?

**Comment by markandrus** [comment]
> The only workaround for now seems to be for me to fork this repo and pull any updates from the main repo. Do you have any suggestions in how I might be able to avoid doing that?

It'd be nice to avoid this.

> Thanks for the advise. I was able to get it to work by changing `bindings.js` to this relative path:
`module.exports = require('../build/Release/wrtc.node');`

Do you mind explaining how to setup or sharing an example app that uses node-webrtc and pkg? I'm wondering what the directory structure looks like. One thing we could maybe do is fallback to the `require` method you shared if node-cmake fails. But understanding how the directory should look would help

**Comment by Zentendo** [comment]
Sure. My test case was as simple as possible:

`npm install -g pkg`
`npm init`
`npm install wrtc`
Create `index.js`
Copy and paste this example into `index.js` https://github.com/js-platform/node-webrtc/blob/develop/examples/ping-pong-test.js
Replace `var webrtc = require('..');` in that example with `var webrtc = require('wrtc');`
Test with `node index.js`
Only change to wrtc required is replacing `binding.js` to `module.exports = require('../build/Release/wrtc.node');`. The `build` folder was not built by cmake but wrtc just pulling the latest binary automatically.
Then run:
`pkg index.js --target node8-win-x64,` (Change ``--target`` to whichever target you're on if you're not using Windows.)
Run the built binary file in your console.

**Comment by markandrus** [comment]
OK, I'll see about supporting it. Since we typically know where we place the Debug or Release `.node`, we can probably use the paths directly. Thanks.

**Comment by markandrus** [comment]
Support for this is added in 0.3.4, released today
