### ISSUE TITLE
Dropping support  for Node 4, 5 & 7 in 0.2.x

### ISSUE THREAD

**Issue by markandrus** [node-webrtc/node-webrtc#408]
Node 4, 5 & 7 have been EOL-ed as of 2018-04-30, 2016-06-30, and 2017-06-30 (see [nodejs/Release](https://github.com/nodejs/Release) for more info). I'd like to drop support for these, as node-webrtc's build matrix is already

```
7 Node releases (Node 4–10) × 3 platforms (Linux, macOS & Windows) = 21 build jobs
```

I've also got both branch and PR builds enabled on Travis CI and Appveyor (I should probably change this), which means theres really 21 × 2 build jobs. Cutting these 3 EOL-ed releases will reduce the number of build jobs to

```
4 Node releases (Node 6 & 8–10) × 3 platforms (Linux, macOS & Windows) = 12 build jobs
```

I'd drop support in 0.2.x. Any objections?

**Comment by nazar-pc** [comment]
And related to that, specify up to date max version of Node.js supported (or better list all supported explicitly) in `package.json`'s `engines`. Currently it says everything beyond Node.js v4, which might not be true in future and users should at least get a warning about this from NPM.
