### ISSUE TITLE
DataChannel .send InvalidStateError

### ISSUE THREAD

**Issue by Avol** [node-webrtc/node-webrtc#417]
I'm sending 24 packets per second and sometimes closed state doesn't fire before my send event happens. I did a check for a ready state right before sending the packet within my application, but on some rare occasions I get this error anyhow. The exception handler doesn't prevent a crash, so the whole application goes down. Could this be simple-peers fault not wrtc's? Any workarounds for this? I'm currently adding a readyState check inside of the lib to check if that helps, will report on if it helped. 

```
try {
		if (internalDC.readyState == 'open')
			internalDC.send(data);
    } catch (error) {
      // TODO(mroberts): Start using the domexception library.
      if (error.message.match(/InvalidStateError/)) {
        error.code = 11;
        error.name = 'InvalidStateError';
      }
      throw error;
    }
```

```
/usr/src/app/node_modules/wrtc/lib/datachannel.js:100
      throw error;
      ^

InvalidStateError: InvalidStateError
    at RTCDataChannel.send (/usr/src/app/node_modules/wrtc/lib/datachannel.js:93:18)
    at Peer.send (/usr/src/app/node_modules/simple-peer/index.js:243:17)
    at SCMoveAll (/usr/src/app/src/networking/outgoing.js:245:20)

```

**Comment by markandrus** [comment]
It sounds like this is working as expected.

> The `send()` method is overloaded to handle different data argument types. When any version of the method is called, the user agent MUST run the following steps:
>
> 1. Let _channel_ be the `RTCDataChannel` object on which data is to be sent.
>
> 2. If _channel_'s [[ReadyState]] slot is not `open`, throw an `InvalidStateError`.
>
> &hellip;

"close" may fire in the next tick, so you can't just rely on the event. You should also check `readyState`. For example, try the following in a browser:

```js
var pc = new RTCPeerConnection();
var dc = pc.createDataChannel('foo');
console.log(dc.readyState);
dc.onclose = () => console.log('event fired');
dc.close();
console.log(dc.readyState);
```

You should see

```
connecting
closed
event fired
```

I'll close this for now. If you're still having issues, please reopen.
