### ISSUE TITLE
Offer official windows support.

### ISSUE THREAD

**Issue by kofd** [node-webrtc/node-webrtc#42]
As long as this project remains in the scope of a relay server or a data channel this may not be necessary, but if this api exposes a mechanism for streaming video from a remote server there are definite use cases for offering the ability to capture and stream applications from a windows instance.

**Comment by modeswitch** [comment]
My intent has always been to support Windows, but for the moment focus is on Linux in the early stage. I agree, there are clear use-cases for Windows.

**Comment by guymguym** [comment]
:+1:

**Comment by modeswitch** [comment]
I don't have access to a Windows machine, so a contributor who can work on this is needed.

**Comment by kanecko** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

**Comment by feross** [comment]
Just wanted to let ya'll know that [WebTorrent](https://github.com/feross/webtorrent) is depending on `wrtc` so that node users can seed torrents to web peers over WebRTC. So, there is a use case for using the data channel on windows – p2p protocols based on webrtc that have non-browser clients.

Another awesome project using `wrtc` (through `simple-peer`) is [webcat](https://github.com/mafintosh/webcat) by @mafintosh. Windows support makes sense here too :-)

**Comment by rosskukulinski** [comment]
@feross neither @modeswitch or I have easy access to a Windows machine -- do you or @mafintosh have access to Windows to help with this?

**Comment by modeswitch** [comment]
I would love to add Windows support. The major effort is updating the libwebrtc build process (which might end up just working) and changing the build script in this project to handle it.

As @rosskukulinski mentioned, I don't have a Windows machine and Travis doesn't offer automated tests for Windows either. I'm happy to mentor anyone who wants to take this on though.

**Comment by guymguym** [comment]
you can easily setup a windows VM on your Mac using virtualbox - windows images were published freely for the sake of IE multiplatform testing - https://www.modern.ie/en-us/virtualization-tools

**Comment by No9** [comment]
@modeswitch OK just ran into this at work
I have had a working chrome build on windows so this should be possible and I should be able to put some "official" work hours into it next week :)

**Comment by alaa-eddine** [comment]
+1 for windows support here :)
I just added webRTC support to my RPC library (https://github.com/Ezelia/eureca.io) which is very useful for people who want to implement multiplayer servers (as WebRTC can use UDP). for now webRTC is only supported on linux.

I have an old windows box too, I started working on a windows support but still having issues to get a working chromium build.

**Comment by rosskukulinski** [comment]
Once we have a working windows build, I'll go ahead and automate the builds using http://www.appveyor.com/.  OSS projects are free with them and can build node c++ addons.

**Comment by modeswitch** [comment]
@rosskukulinski Is it possible to do all the builds (Windows, Darwin and Linux) on appveyor?

**Comment by rosskukulinski** [comment]
@modeswitch nope -- they're Windows only :-/

**Comment by alaa-eddine** [comment]
Will try to build webrtc on windows tonight, last time it took me 4hours to fetch chromium with a failing build in the end :D 
is there any way to do it faster ? :D

**Comment by vmolsa** [comment]
@alaa-eddine No there is no way to make it faster but Webrtc team has reduced chromium dependencies. But for start check https://github.com/vmolsa/webrtc-native. windows  build is now working on x64 platform in Release mode.

**Comment by alaa-eddine** [comment]
@vmolsa : well maybe it's related, because I'm trying hard to get it working using ninja build system but it keep failing at the very final steps... I was trying to build it for x86.

anyway, it's a good news that you managed to get a native windows build working :) ! 
are you planing to provide a native build for node-webrtc or you're keeping it as a separate project ?

**Comment by vmolsa** [comment]
@alaa-eddine That project is aimed only using latest version of nodejs and webrtc so it's not compatible with previous versions of node. But it would be nice if node-webrtc have windows support also.

**Comment by r0144** [comment]
I would like to use wrtc for Windows but it looks like it's not supported yet as this issue is still open.  Also since the last comment is from April, I'm assuming I should avoid trying to use wrtc on Windows for now.  This looks like a great project though and I want to use it.  I'm a little new to Node so please confirm and let me know if I need to focus my efforts on the Linux platform instead.  Thanks.

**Comment by RangerMauve** [comment]
Any chances of integrating with webrtc-native, or maybe porting code from it to this project?

**Comment by Globik** [comment]
@vmolsa  but I can see in the sources of webrtc-native that windows32 is define in there. Or am I wrong?

**Comment by vmolsa** [comment]
@Globik webrtc-native supports Windows, Linux, OSX and ARM (beaglebone, rasperry PI) soon..

**Comment by Globik** [comment]
@r0144  Linux platform apriori is the best. Most server side high technologies are under linux and free BSD. Practical for server coding. As for wrtc it would be only nice on laptop on windows with training purposes for prototype webapp developing.

**Comment by Globik** [comment]
@vmolsa  I simply wonder if any chance to compile webrtc-native on the 32 bit windows machiene.

**Comment by vmolsa** [comment]
@Globik referring [this page](https://chromium.googlesource.com/chromium/src/+/master/docs/windows_build_instructions.md), it's not possible.  

> You must have Windows 7 x64 or later. x86 OSs are unsupported.

**Comment by markandrus** [comment]
The challenge to leveraging Appveyor for Windows builds is building WebRTC itself. If we can separate out building WebRTC from node-webrtc, we can easily use Appveyor to precompile node-webrtc binaries for Windows (see #272 for an example).

**Comment by melv-n** [comment]
We, too, are interested to see Windows supported!

**Comment by echeese** [comment]
wrtc installed fine for me on Windows. With regards to 32 bit Windows, it should be possible to run wrtc, just not build. I have built the webrtc libraries for both 32 and 64 bit windows just fine.
