### ISSUE TITLE
How can I dump a stream to disk?

### ISSUE THREAD

**Issue by k1tzu** [node-webrtc/node-webrtc#421]
I've tried to do it with RecordRTC library. But it's not working server-side.
Is it possible to do it natively within node-webrtc?

**Comment by t-mullen** [comment]
RecordRTC relies on the MediaRecorder API, which is only in browsers.

Currently there is no way to access MediaStream data with this library.

**Comment by k1tzu** [comment]
Ok but what is MediaStream from a perspective of node-webrtc? Is it a tcp stream containing some encoded video data? Is it possible to just dump that traffic to file?

**Comment by t-mullen** [comment]
Media data is sent as SRTP data. You could probably intercept and dump it if you managed to decrypt.

Implementing the Audio/VideoTrackSink classes and exposing them somehow, along with the AddSink method on the MediaStreamTrack is probably the way to go as far as getting raw audio/video data though.

**Comment by markandrus** [comment]
As of [v0.3.5](https://github.com/node-webrtc/node-webrtc/releases/tag/v0.3.5), you can get access to raw I420 video frames. https://github.com/node-webrtc/node-webrtc/issues/478 will track the addition of audio APIs, but please note any solutions here are for fun/hacking around. They may not be performant, complete, or offer synchronization.

**Comment by markandrus** [comment]
As of [v0.3.6](https://github.com/node-webrtc/node-webrtc/releases/tag/v0.3.6), you can get access to audio samples via RTCAudioSink.

**Comment by tylerlong** [comment]
@markandrus Could you please show a sample of turning RTCAudioSink input to a audio file (such as audio.mp3) ?
