### ISSUE TITLE
AudioDeviceModule is leaking

### ISSUE THREAD

**Issue by sebas642** [node-webrtc/node-webrtc#429]
The `AudioDeviceModule` created in the `PeerConnectionFactory` is leaking. That wouldn't be too bad if it was leaking memory only, but it is leaking threads as well and CPU usage is going up over time.

This can be easily observed by running the following:
```javascript
'use strict';

var RTCPeerConnection = require('..').RTCPeerConnection;

setInterval(() => {
  const pc = new RTCPeerConnection();
  pc.close();
  global.gc();
  console.log('## ok');
}, 1000);
```
`$ node --expose-gc test/create-close.js`:

Looking at the process information, we see the number of threads growing over time:
`$ watch "grep Threads /proc/`pgrep -f node.*create-close.js`/status"`

The threads grow twice as fast if `WEBRTC_WIN` is not defined.

**Comment by sebas642** [comment]
One issue is that the AudioDeviceModule is not unreffed after being passed to `webrtc::CreatePeerConnectionFactory()`. The following change fixes that:
```patch
diff --git a/src/peerconnectionfactory.cc b/src/peerconnectionfactory.cc
index 573e2a9..ca0750a 100644
--- a/src/peerconnectionfactory.cc
+++ b/src/peerconnectionfactory.cc
@@ -84,6 +84,7 @@ PeerConnectionFactory::PeerConnectionFactory(Maybe<AudioDeviceModule::AudioLayer
           nullptr);
   assert(_factory);
 
+  audioDeviceModule->Release();
   _networkManager = std::unique_ptr<rtc::NetworkManager>(new rtc::BasicNetworkManager());
   _socketFactory = std::unique_ptr<rtc::PacketSocketFactory>(new rtc::BasicPacketSocketFactory(_workerThread.get()));
```
With that change, the leak is gone when `WEBRTC_WIN` is defined, but it's still leaking when using  the `FakeAudioDevice`.

**Comment by markandrus** [comment]
Off the top of my head, I guess the `node_webrtc::PeerConnectionFactory` should delete the `FakeAudioDevice` in its destructor? I'm surprised we need the `Release` call for the `WEBRTC_WIN` case, though. Unfortunately, I am about to go on vacation for two weeks, so I won't be able to dig in for a while. I do appreciate your recent work here.

**Comment by sebas642** [comment]
I now see that `FakeAudioDeviceModule` doesn't implement `AddRef()`/`Release()` so that explains why   the `FakeAudioDevice` is still leaking.

I guess you're right and it should be deleted in the destructor of the `PeerConnectionFactory`. Or implement `AddRef()`/`Release()` in `FakeAudioDevice()`.

**Comment by sebas642** [comment]
@markandrus Any chance you will push out a new release with this fix soon? The leak is quite bad with the CPU usage going up after each connection.

Thanks

**Comment by markandrus** [comment]
Hi @sebas642, I will release it today.
