### ISSUE TITLE
Expose DeviceManager and MediaSource/MediaTrack construction, so media can be streamed from devices

### ISSUE THREAD

**Issue by kofd** [node-webrtc/node-webrtc#43]
The cricket API already implements mechanisms for creating streams from attached devices, files, windows, and desktops. This is partially exposed in chrome via getUserMedia(). It would be useful to provide an interface for streaming graphically intensive applications to lightweight peers or providing remote-desktop functionality.

**Comment by piranna** [comment]
Nice suggestion, but I think streams should be generated by other modules.
I believe there's already a Node.js version of getUserMedia(), by the way...

Send from my Samsung Galaxy Note II

**Comment by kofd** [comment]
If you could show me where getUserMedia() is implemented in node, I'd be grateful, I can't find anything other than non-implemented github projects whose goal is to eventually offer that support. 

How would we ensure that the mediasource objects created by the other modules would be compatible with our RTCPeerConnection objects? From what I can tell, unless they also link to our exact build of webrtc and have their own instance of webrtc::PeerConnectionFactoryInterface, it would be impossible to use as a MediaStream object, meaning that we would need to send any video directly through the data channel.

**Comment by piranna** [comment]
We are implementing the WebRTC API on the server side, as far as they
follow the WebRTC or the MediaSource API too there shouldn't be any
problems. Anyway we (and they) could implement support for Node.js stream
API, but this should be a low-priority task or also better an independent
project.

Send from my Samsung Galaxy Note II

**Comment by kofd** [comment]
I guess then I should adjust my implementation of MediaStream and MediaStreamTrack, when PeerConnection unwraps their objects it winds up with our c++ wrapper for the webrtc::MediaStreamInterface object, so it wouldn't be compatible with other libraries. The two libraries would still need to have the c++ libjingle binaries built from the same revision even if it were passing around the same object, but other than that I think I can make it work.

**Comment by modeswitch** [comment]
getUserMedia() is out of scope for this project, I think.

@kofd Is it reasonable to have the MediaStreams API work with node streams? At that point we're dealing with binary data and it's on the application to make sure the stream is usable.

**Comment by kofd** [comment]
For the most part, thats the intent of this issue, to allow for any sort of stream to be turned into a MediaStream object. From what I've found, cricket supports the above mechanisms for creating mediacapturers, so those are tools we might want to make available. We might be able to implement a mediacapturer specifically for creating mediasources from node streams, and that might be the most productive thing we can implement when it comes to streams. The main issue seems to be that theres no obvious way to construct the MediaStream object from data without exposing the cricket::DeviceManager factory for media capturers and the webrtc::PeerConnection factory for MediaStreams and MediaTracks

**Comment by kofd** [comment]
After looking into node's Stream API, it doesn't appear to be designed to send media as media. If it does send media, it appears to be completely agnostic to the data's structure and encoding, simply sending a raw data buffer. It would take a considerable amount of work and assumptions about the users of this API to implement any useful media adapters on top of the libjingle libraries. The only thing that seems doable in a reasonable amount of time is to implement getUserMedia(). Its too bad that its outside of the scope of the project, seeing how its so tightly integrated with WebRTC in libjingle.

**Comment by 1N50MN14** [comment]
+1 getUserMedia(), it's actually the main reason I looked into this project hoping it would be there, I was disappointed when it wasn't. kofd is right, imho.

**Comment by loyd** [comment]
I'm confused. Is it possible to stream video? I have a lot of frames h264 (or VP8) and want to stream it to client. The only way is using WebRTC (or rather, MediaStream), but I have not found an example of using node-webrtc for it. Any ideas?

**Comment by kofd** [comment]
The code for the Media Stream API is tightly bound with the code for WebRTC in the libjingle library. They are designed to work in tight concert on a browser and likely aren't compatible on the C++ layer with other implementations. We could implement the Media Constraints API and getUserMedia in this project and allow for streaming from a window, desktop, file, or camera using the current libjingle libraries, or we could create another project that depends on this one which implements these systems. The libjingle libraries have been implemented with chrome support in mind, so most of their implementations are centered around webcams and desktop sharing. I don't believe that they support individual audio channels specific to an application either. This opens up the potential problem of needing to design additional C++ adapters if more advanced features are needed.

**Comment by piranna** [comment]
I don't like the idea of broad the purpose of the module, but if the functionality is already on the library, then it would be a waste don't allow to use it, so +1 for me if that's the case. Another issue is how streams would be added, I'm not sure if W3C streams API and Node.js streams API are compatible and interoperable (this would be great), but also I don't know of any Node.js media library. I know there's a getUserMedia module for Node.js, but I don't know how it works nor used it before, so could be useless.

**Comment by modeswitch** [comment]
Backend won't support media streams.
