### ISSUE TITLE
getStats() node-webrtc

### ISSUE THREAD

**Issue by olivier51235** [node-webrtc/node-webrtc#430]
Hello, 

When i try to apply getStats() on my peerconnection variable, i have something like :

`[ RTCStatsReport { type: 'googLibjingleSession', timestamp: 1536073130843.269 },
  RTCStatsReport { type: 'googTrack', timestamp: 1536073130843.269 },
  RTCStatsReport { type: 'googCertificate', timestamp: 1536073130843.269 },
  RTCStatsReport { type: 'googComponent', timestamp: 1536073130843.269 },
  RTCStatsReport { type: 'ssrc', timestamp: 1536073130843.269 },
  RTCStatsReport { type: 'VideoBwe', timestamp: 1536073130843.269 },
  RTCStatsReport { type: 'googCertificate', timestamp: 1536073130843.269 },
  RTCStatsReport { type: 'googCandidatePair', timestamp: 1536073130843.269 },
  RTCStatsReport { type: 'localcandidate', timestamp: 1536073130843.269 },
  RTCStatsReport { type: 'remotecandidate', timestamp: 1536073130843.269 } ]`

Can someone tells me if node-webrtc supports statistics methods to check parameters such as 'packetsReceived', 'packetsLost'... Thanks

**Comment by jb00ster** [comment]
Hi, 
here is an example on how i'm actually getting stats from the peer connection
you can remove the filter to get all types

```javascript
pc.getStats(function(report) {
	const stats = {}
	report.result()
		.filter(el => el.type === 'ssrc') // remove filter to get other types
		.map(el => {
			stats.timestamp = el.timestamp;
			/* get all stats values of the element*/
			el.names().forEach(name => {
				stats[name] = el.stat(name);
			})
		});
	// example of network quality threshold check
	// googJitterBufferMs < 200 ms
	// packetsLost/packetsReceived < .15 (15% of loss)
	logStats(stats);
}, function(err) {
	console.error(err)
});
```
i found this [article ](https://testrtc.com/webrtc-internals-parameters/)very interesting

**Comment by markandrus** [comment]
#446 includes changes to support the standards-compliant `getStats` implementation.
