### ISSUE TITLE
H264 Support

### ISSUE THREAD

**Issue by jb00ster** [node-webrtc/node-webrtc#431]
Hi, 
i want to know how to enable h264 Support in this module to support iOS clients, because i see no h264 codec in the sdp answer of the server 
should i build the libwebrtc with some option to enable this codec ? 
i've found a flag **use_objc_h264** but i don't know how to use it yet
any help would be welcome
PS: i have installed the node-webrtc on a linux server to record clients video stream, it works fine except for iOS clients

**Comment by k1tzu** [comment]
I have the same problem. pc.setRemoteDescription on nodejs says "Failed to set remote offer sdp: Session error code: ERROR_CONTENT." trying to process SDP from Safari.

**Comment by jb00ster** [comment]
Hello, I ended up finding the way to activate the h264

you have to build the libwebrtc module with **proprietary codecs enabled**
the libwertc is built wihout the proprietary codes by default (may be because of license issue?) 
so please make attention to this comment from the libwebrtc source code : 

> CHECK THE OPENH264, FFMPEG AND H.264 LICENSES/PATENTS BEFORE BUILDING

it'll take you a long time to build it (git clone command will generate ~8go of data) 

so in [the build instructions](https://github.com/js-platform/node-webrtc#build), you will have to add GN_EXTRA_ARGS in the cmake command
``` Bash 
cmake -DWEBRTC_BRANCH_HEAD=refs/branch-heads/60  -DGN_EXTRA_ARGS='proprietary_codecs=1 ffmpeg_branding="Chrome"' ..
```
or if it doesn't work for some reason you could try to add the flags directly in the file `libwebrtc/CMakeModules/Gn.cmake ` 

i hope it will help you

**Comment by k1tzu** [comment]
thank you a lot - it worked!

**Comment by encounter** [comment]
`GN_EXTRA_ARGS` doesn't appear to exist anymore, here's what worked for me on the latest version:
```
./node_modules/.bin/ncmake rebuild -- -DGN_GEN_ARGS='proprietary_codecs=true ffmpeg_branding="Chrome"'
```

**Comment by anteeek** [comment]
Can anyone share how long it took to build it on their pc? I'm 30 minutes into it and wondering if that's even feasible on local machine since it's already 11GB
UPDATE: it took a little bit over 1 hour, feel free to ping me if you need help

**Comment by JonasPrimbs** [comment]
Is H264 still supported on Windows?
When compiling it with the rtc_use_h264=true parameter, I get a compiler error that refers to bugs.webrtc.org/9213#c13. It says that the MSVC throws compiler errors and thus they disabled H264 support to "fix" that issue.

**Comment by Luhari** [comment]
I have the same problem.
I understand that it's not viable option for you to choose option 1 or 2 ([from ](https://groups.google.com/g/discuss-webrtc/c/cfkPPq5nvNE)  and thus you have fixed it disabling H264.
But is there a way to locally get the ffmpeg needed, like would I be able to use locally the last version of Chromium that supported MSCV (if so, how do I achieve it)? Or a workaround to enable H264?

**Comment by naki2** [comment]
Hi, I need to enable H264 too. Has anyone found a workaround? Or should I open a new issue about this?

**Comment by jb00ster** [comment]
Hello, 
you can enabled h264 support by adding rtc_use_h264 to GN_GEN_ARGS 
you can do it by modifying the CmakeLists file : 
https://github.com/node-webrtc/node-webrtc/blob/685aa433623b9bf98e8c7c0124e7864e01b883e6/CMakeLists.txt#L129-L132
you have to add new line with rtc_use_h264=true
hope this will help you

**Comment by abhemanyus** [comment]
> Hello, you can enabled h264 support by adding rtc_use_h264 to GN_GEN_ARGS you can do it by modifying the CmakeLists file :
> 
> https://github.com/node-webrtc/node-webrtc/blob/685aa433623b9bf98e8c7c0124e7864e01b883e6/CMakeLists.txt#L129-L132
> 
> you have to add new line with rtc_use_h264=true
> hope this will help you

I followed the following steps from https://github.com/node-webrtc/node-webrtc/blob/develop/docs/build-from-source.md
1. Clone the repository
2. cd into it
3. Add `rtc_use_h264=true` to GN_GEN_ARGS within CMakeLists.txt
4. Run `SKIP_DOWNLOAD=true npm install`
5. Run `./node_modules/.bin/ncmake configure`
6. Run `./node_modules/.bin/ncmake configure --release`
7. Run `npm pack`
8. cp the tarball to my project directory, and add it in the package.json as `"wrtc": "file:wrtc-0.4.7-dev.tgz"`
9. Run `npm i`
10. Got error installing package. I've attached the error log.
[2022-12-06T12_54_34_212Z-debug-0.log](https://github.com/node-webrtc/node-webrtc/files/10166655/2022-12-06T12_54_34_212Z-debug-0.log)

I am probably doing something very wrong here, since this is my first time building a npm package from source.
