### ISSUE TITLE
Multiple DataChannels?

### ISSUE THREAD

**Issue by piranna** [node-webrtc/node-webrtc#440]
I'm trying to create multiple DataChannels before the initial `offer` and waiting for the `negotiationneeded` event to send them to the other peer, but when it gets dispatched, `localDescription` only has info for the first of the two DataChannels. Maybe `wrtc` only support to create just one DataChannel? My app depends heavily on create potentially a lof of them, I would be able to multiplex them but code would get more complex... :-/

**Comment by markandrus** [comment]
Hi @piranna 

> but when it gets dispatched, `localDescription` only has info for the first of the two DataChannels. Maybe `wrtc` only support to create just one DataChannel?

Are you looking at the `m=application` lines and expecting to see one for each DataChannel? There should only ever be one. Per JSEP, [4.1.5. createDataChannel](https://tools.ietf.org/html/draft-ietf-rtcweb-jsep-24#section-4.1.5):

>    All data channels on a given PeerConnection share the same SCTP/DTLS
>    association and therefore the same m= section, so subsequent creation
>    of data channels does not have any impact on the JSEP state.

**Comment by piranna** [comment]
> Are you looking at the `m=application` lines and expecting to see one for each DataChannel? There should only ever be one.

Yes and no... the returned SDP only has a single entry, and according to your quote, multiple DataChannels are multiplexed over a single socket the same way it's dictated in the WebSockets spec, that's cool :-) The problem is that I only get a single `open` or `datachannel` events dispatched, the one for the first DataChannel but not for the second one... :-( Is that the expected behaviour? Seems strange...

**Comment by markandrus** [comment]
@piranna very interesting. What you describe is not the expected behavior. We should write a test for this and add it to [`test/`](https://github.com/js-platform/node-webrtc/tree/develop/test). It should fail, and that should help us identify and implement the fix.

**Comment by piranna** [comment]
Ok, fake alarm. Your comment about a single `m=application` entry got me inspired about maybe looking in the bad place, since I'm creating a DataChannel for signaling of the next ones so need to check it in two places, and effectively I was checking just only on the sended SDPs. After adding traces in both places, I can confirm that both the signaling and data DataChannels are correctly created, so I'll close this issue :-)

Anyway, maybe it would be an interesting example to be added... So far I have been trying to experiment with https://gist.github.com/keroserene/9103784 just when you sended your answer, so maybe would be nice to make it work with `wrtc` in Node.js, isn't it?
