### ISSUE TITLE
Use Blob as default binaryType

### ISSUE THREAD

**Issue by piranna** [node-webrtc/node-webrtc#441]
https://github.com/js-platform/node-webrtc/blob/b90647300311e8228fed8333e9564f27716e0c66/src/datachannel.cc#L68

The spec says binaryType must be Blob by default, but it's being set arrayBuffer instead, so it needs to be changed.

**Comment by markandrus** [comment]
Thanks, @piranna. This change is blocked on https://github.com/js-platform/node-webrtc/issues/363 — please weigh in with your thoughts on how best to support Blob there.

**Comment by piranna** [comment]
Thanks! I'll do it :-)
