### ISSUE TITLE
Data channels created with Firefox 63 do not work

### ISSUE THREAD

**Issue by bugnano** [node-webrtc/node-webrtc#444]
Since Firefox 63 has switched to a newer version of the SCTP SDP draft (see https://blog.mozilla.org/webrtc/how-to-avoid-data-channel-breaking/ ), the data channels created in Firefox do not work with node-webrtc version 0.2.1.

There are no errors reported neither by Firefox, nor node-webrtc, and the communication stops after node-webrtc creates the answer.

SDP offer by Firefox:
v=0\r\no=mozilla...THIS_IS_SDPARTA-63.0 4189360314203899506 0 IN IP4 0.0.0.0\r\ns=-\r\nt=0 0\r\na=sendrecv\r\na=fingerprint:sha-256 DA:8A:82:85:C7:41:3B:38:1B:78:FB:84:F7:FF:1B:21:28:82:A8:E5:00:E4:FC:5C:F6:70:FB:1D:E4:81:82:AD\r\na=group:BUNDLE 0\r\na=ice-options:trickle\r\na=msid-semantic:WMS *\r\nm=application 9 UDP/DTLS/SCTP webrtc-datachannel\r\nc=IN IP4 0.0.0.0\r\na=sendrecv\r\na=ice-pwd:7d6fa8fd92707c1f8b62be23c447ffc2\r\na=ice-ufrag:25549086\r\na=mid:0\r\na=setup:actpass\r\na=sctp-port:5000\r\na=max-message-size:1073741823\r\n

SDP answer by node-webrtc:
v=0\r\no=- 4514525847984750385 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=msid-semantic: WMS\r\nm=application 0 UDP/DTLS/SCTP webrtc-datachannel\r\nc=IN IP4 0.0.0.0\r\na=mid:0\r\na=sctp-port:5000\r\n

After node-webrtc sends the SDP answer to Firefox, nothing happens.

**Comment by markandrus** [comment]
Thanks for the report. I confirmed it myself. #445 and the pending v0.3.0 release should resolve this.
