### ISSUE TITLE
Missing RTCPeerConnection.onicecandidateerror handler and associated types

### ISSUE THREAD

**Issue by paulmedynski** [node-webrtc/node-webrtc#449]
RTCPeerConnection appears to be missing the onicecandidateerror event handler and its associated types, as defined here:

http://w3c.github.io/webrtc-pc/#dom-rtcpeerconnection-onicecandidateerror

Is this omitted on purpose, just an oversight, or in the works?

**Comment by markandrus** [comment]
It's not added yet, because I'm not sure the webrtc.org code supports it yet. Also, for all major browsers, `'onicecandidateerror' in RTCPeerConnection.prototype === false`. That being said, I'm not against adding a stub for it. There may be some additional web-platform-test(s) we can pass with it.

**Comment by paulmedynski** [comment]
Heh, yes I discovered that browsers don't seem to have implemented it either.  I've added a Node and browser stub that gets my tests passing, so it's good enough for me.

I just discovered this report:

https://wpt.fyi/results/webrtc

Fancy!  I'll reference that going forward.

**Comment by markandrus** [comment]
Also, in case you didn't know already, you can run the same browser tests (depending on how recently we've updated in node-webrtc) using

```sh
npm run wpt:init  # setup wpt git submodule
npm run wpt:test  # run wpt tests
```

The file [`test/web-platform-tests/to-run.yaml`](https://github.com/node-webrtc/node-webrtc/blob/develop/test/web-platform-tests/to-run.yaml) controls which tests are expected to pass, and which tests may fail. Tests which may fail are not executed, and the YAML includes an optional description as to why it fails. This machinery is borrowed from [jsdom](https://github.com/jsdom/jsdom).

**Comment by markandrus** [comment]
Implementing as part of https://github.com/node-webrtc/node-webrtc/pull/580
