### ISSUE TITLE
ARM64/aarch64 wrtc.node

### ISSUE THREAD

**Issue by zsmweb** [node-webrtc/node-webrtc#457]
Is there someone compiled the  wrtc.node for arm64/aarch64?Please share your binary!

**Comment by markandrus** [comment]
We have armv7l building in CircleCI now, but we aren't yet publishing binaries, pending a node-pre-gyp issue. I'd like us to add arm64 next. If anyone wants to try, #450 shows how @doganmurat updated CMakeLists.txt for armv7l support, and #453 shows the addition of armv7l builds to CircleCI.

**Comment by markandrus** [comment]
I think we can start publishing arm64 binaries immediately (AFAICT, it's only armv6l/armv7l that are affected by the node-pre-gyp issue).

**Comment by zsmweb** [comment]
But i can't find arm64 binaries in this site(https://node-webrtc.s3.amazonaws.com/) yet! I hope you can share your locally compiled binaries!Thanks!

**Comment by markandrus** [comment]
@zsmweb, that is because our CI is neither building nor publishing arm64 binaries yet. Please, you or someone else, have a try at updating the files I described above. I will happily review and merge a PR. I cannot look into it myself for a while.

**Comment by zsmweb** [comment]
@markandrus Thanks for your fast response!
I'll try my best to do it！

**Comment by zsmweb** [comment]
https://github.com/zsmweb/node-webrtc/commit/b6063a12371ad188b13562043c2c4591c8eea04d
Successfull build arm64 binaries

**Comment by markandrus** [comment]
@zsmweb Awesome! Mind opening a PR?

**Comment by markandrus** [comment]
I've just published [v0.3.3](https://github.com/node-webrtc/node-webrtc/releases/tag/v0.3.3), which includes binaries for armv7l and arm64 (thanks so much for @doganmurat and @zsmweb's help). They're only tested with QEMU in CircleCI, so if you could, please test the pre-built binaries on a real device.
