### ISSUE TITLE
Searching for a pre-built wrtc binary on windows 10 , after npm install im getting the error  

### ISSUE THREAD

**Issue by siddu177** [node-webrtc/node-webrtc#465]
here logs 
Searching for a pre-built wrtc binary
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: 404 status code downloading tarball https://node-webrtc.s3.amazonaws.com/wrtc/v0.3.4-dev/Release/node-v57-win32-x64.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (C:\Users\Lenovo\workSpace\node-webrtc\node_modules\node-pre-gyp\lib\install.js:139:27)
node-pre-gyp ERR! stack     at emitOne (events.js:121:20)
node-pre-gyp ERR! stack     at Request.emit (events.js:211:7)
node-pre-gyp ERR! stack     at Request.onRequestResponse (C:\Users\Lenovo\workSpace\node-webrtc\node_modules\request\request.js:1066:10)
node-pre-gyp ERR! stack     at emitOne (events.js:116:13)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:211:7)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:543:21)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:112:17)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:440:20)
node-pre-gyp ERR! stack     at emitOne (events.js:116:13)
node-pre-gyp ERR! System Windows_NT 10.0.17134
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Lenovo\\workSpace\\node-webrtc\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build=false"
node-pre-gyp ERR! cwd C:\Users\Lenovo\workSpace\node-webrtc
node-pre-gyp ERR! node -v v8.11.3
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
404 status code downloading tarball https://node-webrtc.s3.amazonaws.com/wrtc/v0.3.4-dev/Release/node-v57-win32-x64.tar.gz
Unable to install a pre-built wrtc binary; falling back to ncmake
Running ncmake configure -g "Visual Studio 15 2017 Win64"
CMake binary could not be found. Please verify your PATH.
C:\Users\Lenovo\workSpace\node-webrtc\scripts\install.js:51
    throw new Error('ncmake configure failed for wrtc');
    ^

Error: ncmake configure failed for wrtc
    at build (C:\Users\Lenovo\workSpace\node-webrtc\scripts\install.js:51:11)
    at download (C:\Users\Lenovo\workSpace\node-webrtc\scripts\install.js:40:5)
    at Object.<anonymous> (C:\Users\Lenovo\workSpace\node-webrtc\scripts\install.js:67:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wrtc@0.3.4-dev install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wrtc@0.3.4-dev install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Lenovo\AppData\Roaming\npm-cache\_logs\2018-12-21T07_25_17_400Z-debug.log

C:\Users\Lenovo\workSpace\node-webrtc>npm install -g node-gyp
C:\Users\Lenovo\AppData\Roaming\npm\node-gyp -> C:\Users\Lenovo\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js
+ node-gyp@3.8.0
updated 1 package in 6.075s

C:\Users\Lenovo\workSpace\node-webrtc>npm install

> wrtc@0.3.4-dev install C:\Users\Lenovo\workSpace\node-webrtc
> node scripts/install.js

Searching for a pre-built wrtc binary
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: 404 status code downloading tarball https://node-webrtc.s3.amazonaws.com/wrtc/v0.3.4-dev/Release/node-v57-win32-x64.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (C:\Users\Lenovo\workSpace\node-webrtc\node_modules\node-pre-gyp\lib\install.js:139:27)
node-pre-gyp ERR! stack     at emitOne (events.js:121:20)
node-pre-gyp ERR! stack     at Request.emit (events.js:211:7)
node-pre-gyp ERR! stack     at Request.onRequestResponse (C:\Users\Lenovo\workSpace\node-webrtc\node_modules\request\request.js:1066:10)
node-pre-gyp ERR! stack     at emitOne (events.js:116:13)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:211:7)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:543:21)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:112:17)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:440:20)
node-pre-gyp ERR! stack     at emitOne (events.js:116:13)
node-pre-gyp ERR! System Windows_NT 10.0.17134
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Lenovo\\workSpace\\node-webrtc\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build=false"
node-pre-gyp ERR! cwd C:\Users\Lenovo\workSpace\node-webrtc
node-pre-gyp ERR! node -v v8.11.3
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
404 status code downloading tarball https://node-webrtc.s3.amazonaws.com/wrtc/v0.3.4-dev/Release/node-v57-win32-x64.tar.gz
Unable to install a pre-built wrtc binary; falling back to ncmake
Running ncmake configure -g "Visual Studio 15 2017 Win64"
CMake binary could not be found. Please verify your PATH.
C:\Users\Lenovo\workSpace\node-webrtc\scripts\install.js:51
    throw new Error('ncmake configure failed for wrtc');
    ^

Error: ncmake configure failed for wrtc
    at build (C:\Users\Lenovo\workSpace\node-webrtc\scripts\install.js:51:11)
    at download (C:\Users\Lenovo\workSpace\node-webrtc\scripts\install.js:40:5)
    at Object.<anonymous> (C:\Users\Lenovo\workSpace\node-webrtc\scripts\install.js:67:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wrtc@0.3.4-dev install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wrtc@0.3.4-dev install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Lenovo\AppData\Roaming\npm-cache\_logs\2018-12-21T07_26_32_584Z-debug.log

**Comment by markandrus** [comment]
Hi, it looks like you’re trying to install 0.3.4-dev, and not the latest release, which is 0.3.3. Binaries are only available for releases. Did you by any chance clone this repo and try to run `npm install`? Doing so—on a non-release, such as the current `develop` branch—is going to build from source.

**Comment by markandrus** [comment]
I’ll close this issue now. If you’re still having trouble feel free to reopen or open a new issue. Best, Mark
