### ISSUE TITLE
Don't use "npm publish" script

### ISSUE THREAD

**Issue by piranna** [node-webrtc/node-webrtc#47]
According to https://npmjs.org/doc/misc/npm-scripts.html#NOTE-INSTALL-SCRIPTS-ARE-AN-ANTIPATTERN, npm publish script shouldn't be used, specially if we are using .gyp files.

**Comment by modeswitch** [comment]
Agreed, but I'm not fond of writing .gyp files so I wrote a build.js script instead that needs to be invoked. It's platform-specific work so using `prepublish` is not an option.

I'm open to alternative suggestions, or accepting a pull request with a nice .gyp file to replace build.js.

**Comment by modeswitch** [comment]
Closing this since we're going to use grunt going forward.
