### ISSUE TITLE
Creating MediaStreams in Node.js from non-browser sources

### ISSUE THREAD

**Issue by snowfrogdev** [node-webrtc/node-webrtc#471]
I have a simple Node.js server. Using the dgram module, I'm receiving video feed from a Tello drone thru UDP. It is in raw H.264. Using the node-webrtc package I am able to establish an RTCPeerConnection between my server and a client web browser. I have tested it with a simple message passing RTCDataChannel.

It looks like node-webrtc now as some support for MediaStream but I am unclear as to how I would go about creating a MediaStream or Track, in Node.js, from various non browser sources, such as the video feed coming in over UDP from my Tello.

My question is this: How can I package the video feed coming in from the drone into a MediaStream that is compatible with RTCPeerConnection so that I can send it to a client browser?

**Comment by markandrus** [comment]
Hi @Neoflash1979,

For your project, I think it would be better for you to consider a different library or a different approach. First of all, this library does not have programmatic media APIs yet—the currently bound APIs are effectively mocks of the browser APIs.

Second, you might consider doing [something like Zoom does](https://webrtchacks.com/zoom-avoids-using-webrtc/): since you already have H.264 frames coming in over UDP, you might just send the out over RTCDataChannels or WebSockets.

I hope this can help you,
Mark

**Comment by snowfrogdev** [comment]
@markandrus Thanks for the suggestion. Can I just say that I never thought video was this complicated. I mean, I've been beating my head against the wall for over a week now and there are a bunch of concepts that aren't very easy to grok and it's the first time I come across a topic where I find there is a lack of clear sources of information online. 

I had already figured that my best option was to send the stream using an RTCDataChannel (using your library for that, so thanks). I'm using the Media Source Extension APIs with some very limited "success". Do you know of a discussion forum, chat or any other kind of source where folks who deal with the MSE hang out? I could really use some help. Here are my current challenges, I know this may be a little out of scope for your library but any hint you can give me will be appreciated. I'm getting desperate.

- Can't get MP4 to play in the video tag. Just for test purposes I've tried saving my Tello UDP feed to an MP4 file 'ffmpeg -i udp://0.0.0.0:11111 -na -vcodec copy output.mp4'. I can read the file on my computer. But when I stream it trough the DataChannel and into the SourceBuffer, I'm not getting video on screen. I get no errors and I am using 'video/mp4; codecs="avc1.4D4028, mp4.40.2"' for the SourceBuffer.
- Tried the same thing but this time saved the stream to webm/vp9. It worked! Both on my computer and also when streaming the file to the browser's SourceBuffer.
- So naturally the next step was to see if I could stream it live from my Tello and I got it to 'work', which is to say that I do get a video on screen but the latency is CRAAAAAAZZZZY, we're talking like 10 seconds between what my Tello captures and what is being displayed on screen and I have no idea what is causing that.

Like I said, any help, hints, guidance you can provide will be deeply appreciated. I'm getting very frustrated. This is taking way too much time to get to work.

**Comment by markandrus** [comment]
> I'm using the Media Source Extension APIs with some very limited "success". Do you know of a discussion forum, chat or any other kind of source where folks who deal with the MSE hang out?

Sorry, I do not know.

Regarding latency, I'm not sure what causes that. The chunked-video-over-RTCDataChannel/WebSocket approach will definitely be slower than sending RTP, though. Have you measured each component in the chain? E.g., how long does it take to create a video chunk on the device? How long does it take to reach the server? How long does it take to reach the browser? How long does it take to start playing in the &lt;video&gt; element?

**Comment by markandrus** [comment]
As of [v0.3.5](https://github.com/node-webrtc/node-webrtc/releases/tag/v0.3.5), there is some limited support for pushing raw I420 frames. You could experiment with this, but I don't consider it a production ready solution—it is just for fun. You mention you receive H.264 frames, so if you wanted to use this you'd still need to decode at the server, which may be too slow.

**Comment by ericwooley** [comment]
What v0.3.5 brings looks like it's like 90% of the way to what I'm looking for. 

I'm creating bots for my app, and I would love to add the ability to stream from a video/audio file. I have been experimenting with trying to get streams from ffmpeg, but I haven't been successful yet. I'm kind of a scrub when it comes to video codecs/data. 

My ideal scenario would be to open a readStream from a webm file and convert it to a media stream. 

Do you have any recommendations for how you would approach that?

**Comment by 0xMishell** [comment]
> What v0.3.5 brings looks like it's like 90% of the way to what I'm looking for.
> 
> I'm creating bots for my app, and I would love to add the ability to stream from a video/audio file. I have been experimenting with trying to get streams from ffmpeg, but I haven't been successful yet. I'm kind of a scrub when it comes to video codecs/data.
> 
> My ideal scenario would be to open a readStream from a webm file and convert it to a media stream.
> 
> Do you have any recommendations for how you would approach that?

Trying to do same for now with any results. Cant just stream video in Nodejs through simple-peer.
