### ISSUE TITLE
Add support for setting MediaStreamTrack.enabled

### ISSUE THREAD

**Issue by taylorhoward92** [node-webrtc/node-webrtc#475]
I need the ability to mute peers from the server side. Imagine an audio bridge where only one peer is allowed to be heard at a time. The [recommended way to do this ](https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack/enabled)would be to use: `MediaStreamTrack.enabled = false`. Currently setting this property has no effect (read-only). Is support for setting this property currently being worked on? Would it be a large piece of work to implement?

**Comment by markandrus** [comment]
I think it should not be hard, but I haven't looked into it. Maybe we can do it for the next release

**Comment by taylorhoward92** [comment]
What are the guidelines for contributing to this repo? If you could point be in the right direction in regards to how this would work at a high level I can have a look into implementing it.

**Comment by markandrus** [comment]
I recommend first

1. Checkout the code.
2. Ensure you can build it.
3. Run the tests. Validate that they pass.

If that works, you should be OK to start making changes. I do my development with [CLion](https://www.jetbrains.com/clion/)—which has good CMake support—and vim, but you could use anything you like. C++ code is in `src/`, JavaScript code is in `lib/`, and tests are in `test/`. There should be existing examples of setters in other C++ files you can copy. I think, roughly, you'll want to

1. Hook up the setter in `mediastreamtrack.cc`. It doesn't have to do anything yet.
2. Identify the API on `webrtc::MediaStreamTrackInterface` (or whatever the appropriate class is) for updating the `enabled` property.
3. Invoke that API in your setter. Sometimes you have to invoke WebRTC APIs on particular threads. If you invoke it on the wrong thread, the debug build will let you know (by failing an `assert`).
4. Add a test for `enabled`. For example, if you set `enabled`, getting `enabled` should return the set value.

I think Step 2 is really the mysterious part and the reason we don't have that feature yet. I think I looked into it briefly but didn't know which API to invoke. Also, my development cycle is basically,

1. Edit the code.
2. Run `./node_modules/.bin/ncmake build` (or let CLion do this for me).
3. Run the test I'm working on (or let CLion's debug feature do this for me).

**Comment by taylorhoward92** [comment]
Thanks for the tips. I've implemented the functionality and created a test as suggested. Code is building and tests are passing. I also did a functional test by disabling the MediaStreamTrack in the loopback server example to confirm black pixels and no audio. Are you able to add me as a contributor so I can push my branch and create a PR?

**Comment by markandrus** [comment]
Thanks, @taylorhoward92. Since you requested, I have added you as a collaborator (although it should be possible to fork the repo and open a PR from a fork, as well). Please note that 1. the CircleCI and Appveyor environments have access to S3 credentials for pushing binaries, so please do not leak these (e.g., by accidentally printing the environment); 2. please do not alter any tags, releases, etc. Looking forward to your contribution. —Mark

**Comment by markandrus** [comment]
I'll release this along with the Programmatic Video APIs in 0.3.5 this week.

**Comment by taylorhoward92** [comment]
Great! Thanks again for helping with the implementation.
