### ISSUE TITLE
doesn't support v21 SCTP offer, giving malformed answer in Firefox 65.0 

### ISSUE THREAD

**Issue by kevzettler** [node-webrtc/node-webrtc#483]
A detailed discussion of the issue can be found at:
https://stackoverflow.com/questions/54466865/firefox-webrtc-signaling-domexception-failed-to-parse-sdp

When Firefox receives an `answer` from `wrtc` it Throws the following error:
```
Failed to parse SDP: SDP Parse Error on line 6:  No webrtc-datachannel token in m= media line, parse failed.
```

this is with `wrtc@0.3.5`

firefox `65.0`

**Comment by markandrus** [comment]
I’m on vacation without a laptop for a few days, so I can’t really dig in here right now. If you’re using the latest wrtc, which binds the same version of WebRTC in Chrome 71, then it would be useful if you or anyone else interested in this issue compared the behavior between wrtc and Chrome 71. It would be easy to write a minimal test that calls `setRemoteDescription` with the given Firefox-generated offer, then calls `createAnswer` with wrtc and asserts some things about the resulting wrtc-generates answer. Even better if the test runs against both Chrome and wrtc

**Comment by nils-ohlmeier** [comment]
As a Firefox maintainer I can provide the additional information that in Firefox 63 (see release notes https://wiki.mozilla.org/Media/WebRTC/ReleaseNotes/63) we started to emit SDP format for data channels according to a more recent version of the SCTP draft. Chrome is able to parse this new format since a long time and will answer with the correct new format if it receives such a new offer from Firefox. But Chrome has started to emit the new format itself yet.

According to https://stackoverflow.com/questions/54466865/firefox-webrtc-signaling-domexception-failed-to-parse-sdp/54498255#54498255 wrtc fails to parse the offer format from Firefox and rejects the data channel.

**Comment by markandrus** [comment]
Thanks @nils-ohlmeier. The strange thing is I thought we fixed this already (issue #444, fixed in #445, released in v0.3.0).

**Comment by markandrus** [comment]
@kevzettler can you please `rm -rf node_modules` and then run `npm install` again? I have a feeling you have an old binary installed.

**Comment by markandrus** [comment]
Relevant WebRTC issue: 
https://bugs.chromium.org/p/webrtc/issues/detail?id=9484

**Comment by markandrus** [comment]
Something else which is interesting: we run a “bridge test” in CircleCI between wrtc and Firefox stable. Check out this result from a [recent run](https://circleci.com/gh/node-webrtc/node-webrtc/3329). It shows the correct behavior, which differs from the bug report.

```
RTCSessionDescription {
  type: 'offer',
  sdp:
   'v=0\r\no=mozilla...THIS_IS_SDPARTA-65.0 6593627091618990593 0 IN IP4 0.0.0.0\r\ns=-\r\nt=0 0\r\na=fingerprint:sha-256 49:DF:26:55:9F:C7:8C:02:B7:8C:DB:77:8D:B8:22:8B:1B:BB:6F:49:FB:E3:E1:21:04:A9:DC:82:B6:4D:73:71\r\na=group:BUNDLE 0\r\na=ice-options:trickle\r\na=msid-semantic:WMS *\r\nm=application 9 UDP/DTLS/SCTP webrtc-datachannel\r\nc=IN IP4 0.0.0.0\r\na=sendrecv\r\na=ice-pwd:dc41ee3676f68c15f81f04ca0c4b4913\r\na=ice-ufrag:9e4062b4\r\na=mid:0\r\na=setup:actpass\r\na=sctp-port:5000\r\na=max-message-size:1073741823\r\n' }
(webrtcsdp.cc:2960): Ignored line: a=sendrecv
(webrtcsdp.cc:1760): AddSctpDataCodec: Got SCTP Port Number 5000
(webrtcsdp.cc:2960): Ignored line: a=max-message-size:1073741823
(p2ptransportchannel.cc:494): Set backup connection ping interval to 25000 milliseconds.
(p2ptransportchannel.cc:503): Set ICE receiving timeout to 2500 milliseconds
(p2ptransportchannel.cc:510): Set ping most likely connection to 0
(p2ptransportchannel.cc:517): Set stable_writable_connection_ping_interval to 2500
(p2ptransportchannel.cc:530): Set presume writable when fully relayed to 0
(p2ptransportchannel.cc:539): Set regather_on_failed_networks_interval to 300000
(p2ptransportchannel.cc:558): Set receiving_switching_delay to 1000
(dtlssrtptransport.cc:60): Setting RTCP Transport on 0 transport 0
(dtlssrtptransport.cc:65): Setting RTP Transport on 0 transport 5403a190
(p2ptransportchannel.cc:442): Received remote ICE parameters: ufrag=9e4062b4, renomination disabled
(peerconnection.cc:3540): Session: 7727852343090653422 Old state: kStable New state: kHaveRemoteOffer
(peerconnection.cc:4792): Local and Remote descriptions must be applied to get the SSL Role of the SCTP transport.
signaling state change: { type: 'signalingstatechange' }
(peerconnection.cc:5426): 0 is not ready to use the remote candidate because the local or remote description is not set.
(peerconnection.cc:5426): 0 is not ready to use the remote candidate because the local or remote description is not set.
(peerconnection.cc:5426): 0 is not ready to use the remote candidate because the local or remote description is not set.
(peerconnection.cc:5426): 0 is not ready to use the remote candidate because the local or remote description is not set.
(peerconnection.cc:4814): Local and Remote descriptions must be applied to get the SSL Role of the session.
{ sdp:
   'v=0\r\no=- 7727852343090653422 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0\r\na=msid-semantic: WMS\r\nm=application 9 UDP/DTLS/SCTP webrtc-datachannel\r\nc=IN IP4 0.0.0.0\r\nb=AS:30\r\na=ice-ufrag:RjvS\r\na=ice-pwd:A/o1SjUS84sdAiDzJLCkh5lM\r\na=ice-options:trickle\r\na=fingerprint:sha-256 9F:47:73:39:88:FF:70:62:4A:BD:4A:E5:7D:1B:32:D8:0B:57:F7:16:E6:01:E3:D7:1C:50:12:6C:AD:EC:A4:60\r\na=setup:active\r\na=mid:0\r\na=sctp-port:5000\r\n',
  type: 'answer' }
```

**Comment by kevzettler** [comment]
ok, think I did have a bad binary installed. Pretty sure I wiped `node_modules` a few times while troubleshooting though.  Thanks @markandrus apologies for the false alarm

**Comment by markandrus** [comment]
No worries! Thanks everyone for prompt responses.
