### ISSUE TITLE
npm install error: Unable to extract header archive checksum

### ISSUE THREAD

**Issue by scaret** [node-webrtc/node-webrtc#491]
Hi I got this error after `npm install`:

```
Running ncmake configure
-- Downloading: https://nodejs.org/download/release/v10.15.2/SHASUMS256.txt
CMake Error at NodeJS.cmake:293 (message):
  Unable to extract header archive checksum
Call Stack (most recent call first):
  CMakeLists.txt:269 (nodejs_init)


-- Configuring incomplete, errors occurred!
See also "/home/ubuntu/node-webrtc/build/CMakeFiles/CMakeOutput.log".
See also "/home/ubuntu/node-webrtc/build/CMakeFiles/CMakeError.log".
Unable to configure project
/home/ubuntu/node-webrtc/scripts/install.js:51
    throw new Error('ncmake configure failed for wrtc');
```

My Cmake version is latest 3.13.4. I've tried on Ubuntu and CentOS, and got the same error. I'm pretty sure my https connection is not hijacked.

I had a look at `NodeJS.cmake` and I guess the problem is a regular expression matching on a checksum string. I failed to workaround it because of too much checksum related expressions in the file.

**Comment by jb00ster** [comment]
Hello, i used to get this error when i was behind a proxy

**Comment by scaret** [comment]
Default cmake does not support SSL download, so it fails to download the checksum file.
Reinstall cmake with OpenSSL will solve the problem.
```
./bootstrap --system-curl
make
sudo make install
```
