### ISSUE TITLE
`RTCDataChannel` is missing `maxPacketLifeTime` property

### ISSUE THREAD

**Issue by albrow** [node-webrtc/node-webrtc#492]
Instances of `RTCDataChannel` appear to be missing the [`maxPacketLifeTime` property](https://developer.mozilla.org/en-US/docs/Web/API/RTCDataChannel/maxPacketLifeTime).

### Steps to reproduce

Run the following code:

```js
const wrtc = require('wrtc');
const pc = new wrtc.RTCPeerConnection();
const dc = pc.createDataChannel('data', {maxPacketLifeTime:42});
console.log(dc.maxPacketLifeTime);
// > undefined
```

The value of `maxPacketLifeTime` should be `42` but it is `undefined`.

**Comment by markandrus** [comment]
You're right. We should add it in [datachannel.js](https://github.com/node-webrtc/node-webrtc/blob/develop/lib/datachannel.js#L48) and [datachannel.cc](https://github.com/node-webrtc/node-webrtc/blob/develop/src/datachannel.cc#L294).
