### ISSUE TITLE
Support SCTP data channels

### ISSUE THREAD

**Issue by modeswitch** [node-webrtc/node-webrtc#5]
Blocked by https://code.google.com/p/webrtc/issues/detail?id=2279.

**Comment by piranna** [comment]
This means there's currently DataChannel support or not?

**Comment by modeswitch** [comment]
There's RTP data channel support, but those aren't standard-compliant and won't interoperate with firefox.

**Comment by piranna** [comment]
Then I think I'll wait until SCTP DataChannels are available, this will
give me some more time to improve my own project :-)

**Comment by fuson** [comment]
Interoperability with chrome is enough for me, cause we use node-webkit for client side. Will it be work?

**Comment by piranna** [comment]
I don't know, but it should: Chromium is still using RTP DataChannels by
default up to v30.

2013/10/16 Aleksey Mihailiuk notifications@github.com

> Interoperability with chrome is enough for me, cause we use node-webkit
> for client side. Will it be work?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/modeswitch/node-webrtc/issues/5#issuecomment-26417554
> .

## 

"Si quieres viajar alrededor del mundo y ser invitado a hablar en un monton
de sitios diferentes, simplemente escribe un sistema operativo Unix."
– Linus Tordvals, creador del sistema operativo Linux

**Comment by fuson** [comment]
I hope it will work, cause if google chrome (and node-webkit for sure) will not work with google webrtc... it will be VERY strange :) I'm in waiting for a buildable state of this library :)

**Comment by modeswitch** [comment]
It should be buildable now (though I'm getting segfaults after updating libjingle :/). Please let me know if you're having build problems.

**Comment by fuson** [comment]
Look at Issue #10 pls about build issue on mac.

**Comment by modeswitch** [comment]
Started working on this now. It's non-trivial.

**Comment by andrenatal** [comment]
Let me know how can I help.

**Comment by modeswitch** [comment]
@andrenatal someone else has taken on the upstream bug while I finish off some other work.

**Comment by feross** [comment]
@modeswitch excellent news -- glad that the upstream folks see this as a priority.

**Comment by kofd** [comment]
I noticed in datachannel.js that the implementation of DataChannel._queueOrRun(obj) makes references to this._getPC(). Is this causing errors?

**Comment by modeswitch** [comment]
@kofd No. I don't think that code is used anymore for data channels.

**Comment by taterbase** [comment]
Forgive my ignorance, it seems the issue has been closed on the jingle project. What is preventing this issue from being closed on this project?

**Comment by modeswitch** [comment]
SCTP data channels are still unsupported in libjingle, blocked by this: https://code.google.com/p/webrtc/issues/detail?id=2253

**Comment by taterbase** [comment]
Thank you for the clarification!

**Comment by modeswitch** [comment]
A patch was just submitted that enables SCTP data channels. I'll update the code here to use them.

https://code.google.com/p/webrtc/source/detail?r=5459

**Comment by piranna** [comment]
I see it before, I'm anxious about this (my boss is interested on this
project :-) )

Send from my Samsung Galaxy Note II

**Comment by modeswitch** [comment]
Fixed. Bridge/peer example updated.

**Comment by taterbase** [comment]
Really hate to be _that_ guy but this deserves a serious :thumbsup:. Thanks for the hard work!

**Comment by danzel** [comment]
Thanks @modeswitch :) :clap:
