### ISSUE TITLE
`npm install` and `npm test` fails with `Symbol not found` error.

### ISSUE THREAD

**Issue by JessieAMorris** [node-webrtc/node-webrtc#50]
Howdy,

I'm currently on OSX Mavericks and I get the following error after building the node-webrtc library with `npm install` and running `npm test`:

```
jessie@Jessies-MacBook-Pro:~/jive/node-webrtc$ npm test

> wrtc@0.0.6 test /Users/jessie/jive/node-webrtc
> node examples/test.js


/Users/jessie/jive/node-webrtc/node_modules/bindings/bindings.js:83
        throw e
              ^
Error: dlopen(/Users/jessie/jive/node-webrtc/build/Release/webrtc.node, 1): Symbol not found: __ZN6webrtc25MediaConstraintsInterface10kValueTrueE
  Referenced from: /Users/jessie/jive/node-webrtc/build/Release/webrtc.node
  Expected in: dynamic lookup

    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at bindings (/Users/jessie/jive/node-webrtc/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/Users/jessie/jive/node-webrtc/lib/peerconnection.js:1:96)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

I've tried searching around for this error or any clues to its meaning but have come up with nothing useful so far.

Any ideas as to what is causing this and how I can either:
1) Fix it
2) Work around it

**Comment by modeswitch** [comment]
Sorry you're having issues. I haven't been able to offer much support for darwin at the moment (I work almost exclusively on linux). There are likely missing library deps in the build for your platform.

A quick way around would be to try on a linux machine. If that's not an option, and you're feeling brave, you could try figuring out which deps are missing and add them to the gyp file. If you're interested I can give you some pointers on how to go about doing that.

**Comment by JessieAMorris** [comment]
I'm currently giving this a shot on a Debian machine. Though my whole team is currently on Darwin, so I'd prefer to get this working correctly on OSX if possible.

I have found the MediaConstraintsInterface at https://chromium.googlesource.com/external/libjingle/+/master%5E/talk/app/webrtc/mediaconstraintsinterface.cc but I'm not sure exactly how that all ties in with the gyp and what not.

I'm much better at Makefiles than Gyp, so I might need a bit of assistance from you.

**Comment by modeswitch** [comment]
I usually resort to using `llvm-nm` to locate the missing symbols and add whatever object file defines them. You can try adding missing libraries to the end of the list for darwin (there are two lists, one for linux as well), but you may need to play with the link order if things still don't work. You probably won't need to touch other parts of the gyp file.

Unfortunatley, we're stuck with gyp files... _grouphug_

**Comment by modeswitch** [comment]
This has been resolved.

**Comment by apiece** [comment]
Sorry, I am using wrtc 0.0.9, and experience the same issue when running test.js, bridge.js, etc.

**Comment by apiece** [comment]
I was using "npm install wrtc" for the installation.  Would that be the reason?

**Comment by modeswitch** [comment]
@apiece are you trying this on a linux machine?

**Comment by apiece** [comment]
@modeswitch. On Mac OS 10.9.1 (Mavericks)

**Comment by modeswitch** [comment]
OK, so only linux is really support right now. There are some other contributors working on OSX support, but since I don't have a Mac I'm not able to help much. Full OSX support is part of the second milestone, to be done after I make a stable release for linux.

**Comment by apiece** [comment]
Understood.  Thanks for the clarification.

**Comment by markandrus** [comment]
I hit this same problem with `__ZN6webrtc25MediaConstraintsInterface10kValueTrueE`. But the symbol appears in `libjingle_peerconnection.a`, which is included in the OS X branch of `binding.gyp`.

```
$ nm ./third_party/libwebrtc/trunk/out/Release/libjingle_peerconnection.a |
    grep __ZN6webrtc25MediaConstraintsInterface10kValueTrueE 
0000a602 S __ZN6webrtc25MediaConstraintsInterface10kValueTrueE
```

Still investigating.

EDIT: Setting verbose mode, it looks like `ld` isn't linking a number of files, e.g.

```
ld: warning: ignoring file
../third_party/libwebrtc/trunk/out/Release/obj/../libjingle_peerconnection.a, file
was built for archive which is not the architecture being linked (x86_64):
../third_party/libwebrtc/trunk/out/Release/obj/../libjingle_peerconnection.a
```

**Comment by modeswitch** [comment]
@markandrus The missing symbols may be in listed libraries, but if they are linked in the wrong order the symbols won't be picked up.

**Comment by markandrus** [comment]
@modeswitch In this case, it appears to be because of an architecture mismatch (see #92).

With some fudging, I built `webrtc.node` for i386 and linked against the 32-bit WebRTC libraries. Attempting to run the tests with the 32-bit version of Node then resolved the missing symbol `__ZN6webrtc25MediaConstraintsInterface10kValueTrueE` error, but complained about `_CERT_CertificateTemplate` (I expect this is because I didn't have a 32-bit version of nss to link to). 

Ideally, though, everything would build for x86_64.
