### ISSUE TITLE
Failing to build - can't parse wrtc.node

### ISSUE THREAD

**Issue by andymikulski** [node-webrtc/node-webrtc#502]
I'm trying to use the [webtorrent-hybrid](https://github.com/webtorrent/webtorrent-hybrid) package. Upon building my code, I'm hit with the error below. It seems there is an issue around the `wrtc.node` binary file, but I'm having a hard time pinning down what is wrong. Everything appears fine when installing the package (which uses wrtc as a dependency), building throws the error. I'm using Webpack with a `node` target, if that makes any difference.

I've attempted building on Windows as well as my Debian VPS, but both spit back the same error. I'm wondering if I'm missing a required dependency or something. Examining `wrtc.node` shows that it _is_ a binary file with contents, so I think npm is pulling the precompiled binary correctly, but I could be wrong.

Any help would be hugely appreciated! Thank you!

```
WARNING in ../node_modules/wrtc/lib/binding.js
Module not found: Error: Can't resolve '../build/Debug/wrtc.node' in '/root/wb9/server/node_modules/wrtc/lib'
 @ ../node_modules/wrtc/lib/binding.js
 @ ../node_modules/wrtc/lib/index.js
 @ ../node_modules/webtorrent-hybrid/lib/global.js
 @ ../node_modules/webtorrent-hybrid/index.js
 @ ./main.ts

ERROR in ../node_modules/wrtc/build/Release/wrtc.node 1:0
Module parse failed: Unexpected character ' (1:0)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ../node_modules/wrtc/lib/binding.js 6:19-56
 @ ../node_modules/wrtc/lib/index.js
 @ ../node_modules/webtorrent-hybrid/lib/global.js
 @ ../node_modules/webtorrent-hybrid/index.js
 @ ./main.ts
```

**Comment by markandrus** [comment]
Hi @andymikulski,

It looks like Webpack or some TypeScript-related tooling is trying to parse the `wrtc.node` file as if it were JavaScript, TypeScript, an ESM module, I’m not sure. I could look into this tomorrow, but maybe this could help you find the solution?

Mark

**Comment by andymikulski** [comment]
You're totally right, Mark. I tested with a plain JavaScript file outside of Webpack and it built successfully. Using a workaround to compile with Webpack but ignore the `wrtc.node` file proved unsuccessful; the code _did_ build, but would fail to run. Taking the compilation step out (read: not using Webpack) seemed to let me run the code and use the package accordingly.

I'm assuming there is some sort of Webpack config setting to work this out, but @markandrus feel free to close this issue if you'd like! Thank you!

**Comment by markandrus** [comment]
@andymikulski nice to hear you narrowed down the issue 👍 if you do find a workaround, could you please post back here? I wonder, were you able to try either of these?

- https://github.com/webpack-contrib/node-loader
- https://github.com/ushu/node-addon-loader

I will close the issue for now.

Best,
Mark

**Comment by rushairer** [comment]
@andymikulski   Did  you find a workaround ?  Thanks.

**Comment by rushairer** [comment]
@andymikulski 

Use node-loader to fix it.

https://github.com/webpack-contrib/node-loader

```json
module: {
        rules: [
         .....,
        {
            test: /\.node$/i,
            use: 'node-loader',
        }]
    }
```

**Comment by regnaio** [comment]
This workaround using `webpack-node-externals` worked for me. See the section under _webpack-back.config.js_

https://medium.com/code-oil/webpack-javascript-bundling-for-both-front-end-and-back-end-b95f1b429810

**Comment by operatorLyu** [comment]
I added a node-loader in webpackfile.js and the error disapeared, but when I use the API exported in index.js, it is undefined and error in browser console. Is there anyone know about this?
