### ISSUE TITLE
RTCAudioSource and RTCVideoSource

### ISSUE THREAD

**Issue by Lokomojo** [node-webrtc/node-webrtc#511]
I'm very keen to use node-webrtc as an audio and video source for a webcam on a raspberry pi.

Docs seem to be a little thin on the ground, but is there some example of how to use createTrack with RTCVideoSource and RTCAudioSource?  I've seen a few usages but no indication of how to specify codec or anything like that..

**Comment by markandrus** [comment]
Hi @TomMettam,

Please take a look at the examples here: https://github.com/node-webrtc/node-webrtc-examples

Specifying codecs would be done during negotiation with the RTCPeerConnection APIs. The nonstandard RTCAudioSource/RTCVideoSource APIs (and their *Sink variants) introduced by this package deal with raw I420 video frames and raw audio samples.

If you have any issues, feel free to reopen this issue or an issue on the examples repo.
