### ISSUE TITLE
No examples in 0.3.7

### ISSUE THREAD

**Issue by anshul-kai** [node-webrtc/node-webrtc#512]
What happened to the examples with the 0.3.7 update?

**Comment by anshul-kai** [comment]
Nevermind! Found them under `https://github.com/node-webrtc/node-webrtc-examples`. Perhaps a mention of this in the documentation would be nice?

**Comment by markandrus** [comment]
Hi @a-koka,

Thanks for writing in. There's a link to the examples on the GitHub README.md, but its not on the NPM package page right now. The next release should have it.

> node-webrtc provides Node.js bindings to WebRTC M73. You can write Node.js applications that use RTCDataChannels with it. Some MediaStream APIs are supported. For examples, see [node-webrtc-examples](https://github.com/node-webrtc/node-webrtc-examples).

Anywhere else you think we should mention it?

Best,
Mark

**Comment by anshul-kai** [comment]
Thanks for your response @markandrus. I now see that README.md does have a link to the examples. I somehow missed it the first time around. Would it make sense to make it a category in README.md so that it's very clear where to find the examples?

Just a suggestion. Feel free to close this issue.

Thanks again!

**Comment by markandrus** [comment]
> Would it make sense to make it a category in README.md so that it's very clear where to find the examples?

Yes, I'm thinking of revamping the README.md soon. I'll keep this in mind.

Thanks!
