### ISSUE TITLE
Add pre-built binaries for node 12 on x86-64

### ISSUE THREAD

**Issue by superboss224** [node-webrtc/node-webrtc#515]
Hi, I know that we can build wrtc from source when pre-built binaries doesn't exist, but it seems to take more than 17 GB to download build tools and build material, so it overloaded my 20 GB x86-64 debian 9 VPS, and i have to rollback to node 11 to use wrtc, please could you make pre-built binaries for an x64 Debian 9 device with node 12.

Thanks

**Comment by markandrus** [comment]
Hi @superboss224,

Thanks for writing in. Yes, I'll make Node 12 available, probably in v0.4.x, as soon as #507 lands (which should be this week, hopefully). Please follow #506 for updates.

Best,
Mark
