### ISSUE TITLE
Add node-webrtc to nodejs/citgm

### ISSUE THREAD

**Issue by markandrus** [node-webrtc/node-webrtc#518]
node-webrtc is now dependent on N-API version 3. It would be good for us to add it to [nodejs/citgm](https://github.com/nodejs/citgm) so that we can ensure future Node.js releases do not break us.

- [x] Merge #519 
- [x] Release v0.4.0 (we just have v0.4.0-beta1 right now)
- [x] [Open a PR from node-webrtc/citgm to nodejs/citgm](https://github.com/nodejs/citgm/compare/master...node-webrtc:add-node-webrtc?expand=1)

**Comment by Tackyshot** [comment]
what the timeline for this? I'm currently getting errors that I'm 90% sure are related to this issue, specifically this: `dyld: lazy symbol binding failed: Symbol not found: _napi_open_callback_scope`

**Comment by markandrus** [comment]
Hi @Tackyshot,

Can you please share a little bit more about these errors? For example, are you using v0.4.0-beta? Did you build from source? If so, what commit? Using Node/Electron? What version? What platform?

Thanks!
Mark

**Comment by Tackyshot** [comment]
Hi @markandrus,

My version is v0.4.0-beta.
I did an `npm i wrtc --save` to install it into my project dir.
I'm using Node v8.10.0 (latest version supported by AWS to my knowledge).
I'm currently running on MacOSX (latest) for testing, but the production version will be a Raspbian OS LITE (also latest) for an IOT project.

the following error occurs after invoking `peer.signal(data)` where data is a webrtc offer sent from the initializer through a Socket.IO web socket message.

this is the error:
```
dyld: lazy symbol binding failed: Symbol not found: _napi_open_callback_scope 
  Referenced from: /path/to/project/dir/node_modules/wrtc/build/Release/wrtc.node
  Expected in: flat namespace

dyld: Symbol not found: _napi_open_callback_scope
  Referenced from: /path/to/project/dir/node_modules/wrtc/build/Release/wrtc.node
  Expected in: flat namespace
```

this is the initializer:
```javascript
import io from 'socket.io-client';
import Peer from 'simple-peer';
import Messages from '../state/messages';

export default class P2PHelper {
  constructor(initiator = true) {
    this.socket = io();
    this.peer = new Peer({initiator: initiator, trickle: false});

    this.peer.on('error', err => console.log('error', err));

    this.peer.on('signal', (data) => {
      //immediately send connection request if you're the initiator
      if(initiator) this.socket.emit('peer-con-req', data);
      else console.log("on signal event", JSON.parse(data));
    });

    this.peer.on('connect', () => {
        console.log("Successfully Connected to peer");
    });

    this.peer.on('data', data => {
      // do some state modification here
      Messages.addMessage(JSON.stringify(data), 'left');
    });
  }

  sendMsg(msg) {
    Messages.addMessage(msg, 'right');
    this.peer.send(msg);
  }
}
```

this is the invitee:
```javascript
import io from 'socket.io-client';
import Peer from 'simple-peer';
import wrtc from 'wrtc';

let socket = io("http://localhost:3000", {
  transports: ['websocket']
});
let peer = new Peer({initiator: false, wrtc: wrtc});

socket.on('peer-msg', function (data) {
  console.log('From a peer %s', data.textVal);
});

socket.on('peer-con-req', (data) => {
  console.log('connection request:', typeof data);
  console.log(data);

  peer.signal(JSON.stringify(data));
});

peer.on('error', err => console.log('peer error:', err));

peer.on('signal', (data) => {
  console.log("on signal event", JSON.parse(data));
  // peer.signal(data);
});

peer.on('connect', () => {
  console.log("Successfully Connected to peer");
});

peer.on('data', data => {
  console.log("PEER DATA RECEIVED");
  console.log(JSON.stringify(data));
});
```

Sorry for the long post, but I figured you might want all the information that I have

Thank you!

**Comment by markandrus** [comment]
I believe the problem is that your Node is too old. Check out the engines field in package.json for the exact version of 8 supported.

**Comment by markandrus** [comment]
I have retracted my PR to nodejs/citgm: https://github.com/nodejs/citgm/pull/726 —  Unfortunately I do not have time to support it at this time.
