### ISSUE TITLE
We have an IRC channel

### ISSUE THREAD

**Issue by modeswitch** [node-webrtc/node-webrtc#52]
FYI @DamonOehlman @helloIAmPau @kofd @piranna 

`#wrtc` on `irc.mozilla.org` ([link](irc://irc.mozilla.org:6697/wrtc))

I'll update the docs to direct people there for support and development.

**Comment by DamonOehlman** [comment]
Nice :)

I really should spend more time on IRC...

**Comment by thanpolas** [comment]
why not freenode?
