### ISSUE TITLE
Add support for RTCSctpTransport

### ISSUE THREAD

**Issue by markandrus** [node-webrtc/node-webrtc#522]
Support in M74, so we should expose it.

---

- [x] `transport` — #521
- [x] `state` — #521
- [x] "statechange" — #521
- [x] `maxMessageSize` *
- [x] `maxChannels` *

\* It looks like M74 always returns `null` for these.

**Comment by lin7sh** [comment]
Thanks for supporting the newest feature, BTW RTCSctpTransport is [enable by default](https://www.chromestatus.com/feature/5847754483957760) by Chrome 76

**Comment by markandrus** [comment]
`maxMessageSize` is no longer `null`, at least as of M79. https://github.com/node-webrtc/node-webrtc/pull/580
