### ISSUE TITLE
Audio Stream bad quality?

### ISSUE THREAD

**Issue by KeySeeDev** [node-webrtc/node-webrtc#526]
Hi, i would like to make a peer->server connection to stream audio.
Was trying the examples to see how it will work, but there is some quality problem.
I changed the **audio-video-loopback** example like so
```
function beforeOffer(peerConnection) {
  const audioTransceiver = peerConnection.addTransceiver('audio');
  return Promise.all([
    audioTransceiver.sender.replaceTrack(audioTransceiver.receiver.track)
  ]);
}
module.exports = { beforeOffer };
```
...and replaced in client.js the video tag with an audio tag.
The audio is choppy and the overall quality is very bad. 
What we are trying to obtain is something like this:
```
Peer to server to peer schema ( ^.^)♪
                                         / --> 🔊 WebRTC Client 1
🎤 WebRTC Capture ---\       The       / --> 🔊 WebRTC Client 2
🎤 WebRTC Capture ----    Raspberry    ---> 🔊 WebRTC Client ...
🎤 WebRTC Capture ---/   Pi 3 Server   \ --> 🔊 WebRTC Client 20
                                         \ --> 🔊 WebRTC Client 21
```
Is there any solution or a better example? Thanks!

For more info: https://stackoverflow.com/questions/55996884/webrtc-stream-one-to-many-through-node-js-server

**Comment by markandrus** [comment]
Hi @StarStep,

Do you notice this issue in any of the other audio examples? What hardware do you test with?

Also, I recommend you do not use node-webrtc to relay to multiple clients. It won’t scale well. Instead, I think you should use an SFU (selective forwarding unit). Perhaps mediasoup or a similar project can work well.

Mark

**Comment by pradeep538** [comment]
could you please share example for accessing media side. video/audio not work for me. here is my code.
const { RTCPeerConnection, RTCIceCandidate, RTCSessionDescription, MediaStream, getUserMedia } = require('wrtc');
const { RTCAudioSink, RTCVideoSource, RTCAudioSource } = require('wrtc').nonstandard;
process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';
var servers = {
    'iceServers': [
        { 'urls': 'stun:stun.services.mozilla.com' },
        { 'urls': 'stun:stun.l.google.com:19302' },
        { 'urls': 'stun:stun.l.google.com:19302' },
        { 'urls': 'stun:stun1.l.google.com:19302' },
        { 'urls': 'stun:stun2.l.google.com:19302' },
        { 'urls': 'stun:stun3.l.google.com:19302' },
        { 'urls': 'stun:stun4.l.google.com:19302' }]
};
const WebSocket = require('ws');
var configuration;
var vApp = {};
vApp.socket = null;
vApp.peer_connections = {};
vApp.session_id = '0-0';
vApp.self_id = 0;
vApp.url = 'wss://' + "0.0.0.0" + ':4443'; //hiding the private IP
vApp.name = "WebApp"
vApp.local_stream;
vApp.keepalive_cnt = 0;
vApp.socket = new WebSocket(vApp.url);
vApp.initialize = function () {
    configuration = { "iceServers": [{ "url": "stun:stun.l.google.com:19302" }] };
    vApp.socket = new WebSocket(vApp.url);
    vApp.socket.onopen = function () {
        console.log("wss connect success...");
        vApp.self_id = vApp.getRandomUserId();
        let message = {
            type: 'new',
            user_agent: "nodewebrtc" + '/' + 1.0,
            name: vApp.name,
            id: vApp.self_id,
        }
        vApp.send(message);
        vApp.wsKeepaliveTimeoutId = setInterval(vApp.keepAlive, 12000);
    };

    vApp.socket.onmessage = function (e) {

        var parsedMessage = JSON.parse(e.data);

        console.info('on message: {\n    type = ' + parsedMessage.type + ', \n    data = ' + JSON.stringify(parsedMessage.data) + '\n}');

        switch (parsedMessage.type) {
            case 'invite':
                vApp.onInvite(parsedMessage);
                break;
            case 'ringing':
                vApp.onRinging(parsedMessage);
                break;
            case 'offer':
                vApp.onOffer(parsedMessage);
                break;
            case 'answer':
                vApp.onAnswer(parsedMessage);
                break;
            case 'candidate':
                vApp.onCandidate(parsedMessage);
                break;
            case 'peers':
                vApp.onPeers(parsedMessage);
                break;
            case 'leave':
                vApp.onLeave(parsedMessage);
                break;
            case 'bye':
                vApp.onBye(parsedMessage);
                break;
            case 'keepalive':
                console.log('keepalive response!');
                break;
            default:
                console.error('Unrecognized message', parsedMessage);
        }
    };

    vApp.socket.onerror = function (e) {
        console.log('onerror::' + JSON.stringify(e));
    }

    vApp.socket.onclose = function (e) {
        console.log('onclose::' + JSON.stringify(e));
    }
}


vApp.keepAlive = function () {
    vApp.send({ type: 'keepalive', data: {} });
    console.log('Sent keepalive ' + ++vApp.keepalive_cnt + ' times!');
}
vApp.getLocalStream = function (type) {
    return new Promise((pResolve, pReject) => {
        var constraints = { audio: true, video: true };
        getUserMedia(constraints)
            .then(function (mediaStream) {
                pResolve(mediaStream);
            }).catch((err) => {
                console.log(err.name + ": " + err.message);
                pReject(err);
            }
            );
    });
}
vApp.getRandomUserId = function () {
    var num = "";
    for (var i = 0; i < 6; i++) {
        num += Math.floor(Math.random() * 10);
    }
    return num;
}
vApp.send = function (data) {
    console.log("Sending data====>", data)
    vApp.socket.send(JSON.stringify(data));
}

vApp.invite = function (peer_id, media) {
    vApp.session_id = vApp.self_id + '-' + peer_id;
    vApp.getLocalStream(media).then((stream) => {
        vApp.local_stream = stream;
        vApp.createPeerConnection(peer_id, media, true, stream);
        //vApp.emit('localstream', stream);
        console.log("LOCAL STREAM AVAILABLE");
        //this.emit('new_call', this.self_id, this.session_id);
        console.log("NEW CALL")
    });
}
vApp.bye = function () {
    let message = {
        type: 'bye',
        session_id: vApp.session_id,
        from: vApp.self_id,
    }
    vApp.send(message);
}
vApp.createOffer = function (pc, id, media) {
    pc.createOffer(function (desc) {
        console.log('createOffer: ', desc.sdp);
        pc.setLocalDescription(desc, () => {
            console.log('setLocalDescription', pc.localDescription);
            let message = {
                type: 'offer',
                to: id,
                media: media,
                description: pc.localDescription,
                session_id: vApp.session_id,
            }
            vApp.send(message);
        }, vApp.logError);
    }, vApp.logError);
}
vApp.createPeerConnection = function (id, media, isOffer, localstream) {
    var pc = new RTCPeerConnection(servers);
    vApp.peer_connections["" + id] = pc;
    /* vApp.getLocalStream(media).then((stream) => {
        vApp.local_stream = stream;
        //vApp.createPeerConnection(peer_id, media, true, stream);
        //vApp.emit('localstream', stream);
        console.log("LOCAL STREAM AVAILABLE");
        //this.emit('new_call', this.self_id, this.session_id);
        console.log("NEW CALL")
    }); */

    pc.onicecandidate = (event) => {
        console.log('onicecandidate', event);
        if (event.candidate) {
            let message = {
                type: 'candidate',
                to: id,
                candidate: event.candidate,
                session_id: vApp.session_id,
            }
            vApp.send(message);
        }
    };

    pc.onnegotiationneeded = () => {
        console.log('onnegotiationneeded');
        /*  localstream.getTracks().forEach(function (track) {
             pc.addTrack(track, localstream)
         }) */
    }

    pc.oniceconnectionstatechange = (event) => {
        console.log('oniceconnectionstatechange', event);
        /* if (event.iceConnectionState === 'connected') {
            //vApp.createDataChannel(pc);
        } */

    };
    pc.onsignalingstatechange = (event) => {
        console.log('onsignalingstatechange', event);
    };

    pc.ontrack = (event) => {
        console.log('onaddstream', event);
        //this.emit('addstream', event.stream);
        console.log("STREAM ADDED")
        /* event.getTracks().forEach(function (track) {
            const sink = new RTCAudioSink(track);
        }); */
        if (event.track.kind == 'audio') {
            console.log('AUDIO SINK')
            //const sink = new RTCAudioSink(event.track);
            const stream = new MediaStream()
            stream.addTrack(event.track)
        }
    };

    pc.onremovestream = (event) => {
        console.log('onremovestream', event);
        //this.emit('removestream', event.stream);
        console.log("STREAM REMOVED")
    };

    /* getUserMedia({ audio: true, video: true }).then(function (localstream) {
        localstream.getTracks().forEach(track => pc.addTrack(track, localstream));
    }).catch((err) => {
        console.log(err.name + ": " + err.message);
    }); */
    const audioTransceiver = pc.addTransceiver('audio');
  return Promise.all([
    audioTransceiver.sender.replaceTrack(audioTransceiver.receiver.track)
  ]);
    /* const videoSource = new RTCVideoSource();
    const videoTrack = videoSource.createTrack();
    const audioSource = new RTCAudioSource();
    const audioTrack = audioSource.createTrack();
    const videoTransceiver = pc.addTransceiver(localVideoTrack);
    const audioTransceiver = pc.addTransceiver(localAudioTrack); */
    //pc.addStream(localstream);

    if (isOffer)
        vApp.createOffer(pc, id, media);
    return pc;
}
vApp.onPeers = function (message) {
    var data = message.data;
    console.log("peers = " + JSON.stringify(data));
    //this.emit('peers', data, this.self_id);   
}
vApp.onOffer = function (message) {
    var data = message.data;
    var from = data.from;
    console.log("data:" + data);
    var media = data.media;
    vApp.session_id = data.session_id;
    //this.emit('new_call', from, this.session_id);
    console.log("NEW CALL FROM ===>", from);


    //const transceiver = p.addTransceiver(track);
    vApp.getLocalStream(media).then((stream) => {
        vApp.local_stream = stream;
        //this.emit('localstream', stream);
        var pc = vApp.createPeerConnection(from, media, false, stream);
        console.log("LOCAL STREAM", pc)

        if (pc && data.description) {
            //console.log('on offer sdp', data);
            pc.setRemoteDescription(new RTCSessionDescription(data.description), () => {
                if (pc.remoteDescription.type == "offer")
                    pc.createAnswer((desc) => {
                        console.log('createAnswer: ', desc);
                        pc.setLocalDescription(desc, () => {
                            console.log('setLocalDescription', pc.localDescription);
                            let message = {
                                type: 'answer',
                                to: from,
                                description: pc.localDescription,
                                session_id: vApp.session_id,
                            }
                            vApp.send(message);
                        }, vApp.logError);
                    }, vApp.logError);
            }, vApp.logError);
        }
    });
}
vApp.onAnswer = function (message) {
    var data = message.data;
    var from = data.from;
    var pc = null;
    if (from in vApp.peer_connections) {
        pc = vApp.peer_connections[from];
    }
    if (pc && data.description) {
        //console.log('on answer sdp', data);
        pc.setRemoteDescription(new RTCSessionDescription(data.description), () => {
        }, vApp.logError);
    }
}
vApp.onCandidate = function (message) {
    var data = message.data;
    var from = data.from;
    var pc = null;
    if (from in vApp.peer_connections) {
        pc = vApp.peer_connections[from];
    }
    if (pc && data.candidate) {
        pc.addIceCandidate(new RTCIceCandidate(data.candidate));
    }
}
vApp.onLeave = function (message) {
    var id = message.data;
    console.log('leave', id);
    var peerConnections = vApp.peer_connections;
    var pc = peerConnections[id];
    if (pc !== undefined) {
        pc.close();
        delete peerConnections[id];
        //this.emit('leave', id);
        console.log("LEAVE", id);
    }
    if (vApp.local_stream != null) {
        vApp.closeMediaStream(vApp.local_stream);
        vApp.local_stream = null;
    }
}
vApp.onBye = function (message) {
    var data = message.data;
    var from = data.from;
    var to = data.to;
    console.log('bye: ', data.session_id);
    var peerConnections = this.peer_connections;
    var pc = peerConnections[to] || peerConnections[from];
    if (pc !== undefined) {
        pc.close();
        delete peerConnections[to];
        //this.emit('call_end', to, this.session_id);
        console.log("CALL END")
    }
    if (vApp.local_stream != null) {
        vApp.closeMediaStream(vApp.local_stream);
        vApp.local_stream = null;
    }
    vApp.session_id = '0-0';
}
vApp.logError = function (error) {
    console.log("logError", error);
}
vApp.closeMediaStream = function (stream) {
    if (!stream)
        return;

    let tracks = stream.getTracks();

    for (let i = 0, len = tracks.length; i < len; i++) {
        tracks[i].stop();
    }
}
vApp.initialize();
