### ISSUE TITLE
Please provide example for WebRTC as client video/audio chat app with user media access.

### ISSUE THREAD

**Issue by pradeep538** [node-webrtc/node-webrtc#527]
I have written the app as we do in browser but video / audio not going to remote and also from remote , SDP and ice candidates are exchanging properly.but same code in browser is working fine,please help

**Comment by markandrus** [comment]
Please see https://github.com/node-webrtc/node-webrtc-examples for examples of producing/consuming media using the non-standard APIs or to request/submit new examples.

Please also note that `getUserMedia` in node-webrtc doesn't produce any media.
