### ISSUE TITLE
Memory leak is found (v0.4.0)

### ISSUE THREAD

**Issue by webarchymeta** [node-webrtc/node-webrtc#528]
It is found that the latest version (0.4.0) leaks memory slowly during (long) data streaming at the receiving end, leading to complete freeze of a small device (Linux, arm64). Instead of fluctuate around a fixed memory usage, as it does in pre-0.4.0 versions, the memory used increases with time ...

The sending party seems to be ok.

**Comment by markandrus** [comment]
Thank you, @webarchymeta. Do you only send strings, or do you send binary data? Taking a look [here](https://github.com/node-webrtc/node-webrtc/blob/v0.4.0/src/interfaces/rtc_data_channel.cc#L171), I think this usage of `Napi::String::New` leaks `message`:

```cpp
auto str = Napi::String::New(env, message, size);
```

**Comment by markandrus** [comment]
Compare [the implementation in 0.3.7](https://github.com/node-webrtc/node-webrtc/blob/v0.3.7/src/datachannel.cc#L157). We use a `std::unique_ptr` which ensures once `message` goes out of scope (in the string case) it's released.

**Comment by markandrus** [comment]
I think we should just delete `message` in the string branch or use a `std::unique_ptr` from the get-go.

**Comment by markandrus** [comment]
v0.4.1 is released.  Please let me know if it's fixed.

**Comment by webarchymeta** [comment]
Our solution has multiple channels, for signaling/sync and bulk data, the former is transferred in string form and the later is in binary. It looks you have both cases dealt with, 

I will perform a few tests it later ...

**Comment by webarchymeta** [comment]
It does not solve the problem, it seems to be consuming the memory even faster!

**Comment by markandrus** [comment]
That's quite odd&hellip; but thanks for testing it out! I will take a closer look soon. If you have a minimal test case I could run, that would help me track it down. If you track it down and could share a PR, I'd also be grateful.

Best,
Mark

**Comment by markandrus** [comment]
Oops, did not mean to close again.

**Comment by webarchymeta** [comment]
My C++-fu is getting rusty and my (network) environment prevent me from downloading directly from Google related sites. So it's hard for me to contribute PRs directly here ...

I had a look at your patch:
```
    char* message = new char[size];
    memcpy(reinterpret_cast<void*>(message), reinterpret_cast<const void*>(buffer.data.data()), size);
    auto array = Napi::ArrayBuffer::New(env, message, size, [](Napi::Env, void* buffer) {
      delete[] static_cast<char*>(buffer);
    });
```
Shouldn't we delete `message` inside the finalizer of the `array` object? `buffer` should be taken care of by it caller instead? As I said, it been a while that I didn't use C++, I could be wrong ...

**Comment by markandrus** [comment]
Although I named the parameter passed to the ArrayBuffer's finalizer `buffer`, it is in fact `message`.

**Comment by webarchymeta** [comment]
forget about the above comment, I was thinking in functional programing way (closure) :-)

**Comment by webarchymeta** [comment]
after recent tests, it appears that the memory usage of the current version 0.4.3 stabilizes at higher level than the previous one and do not grow further ...
