### ISSUE TITLE
Recieving empty tracks in ontrack event

### ISSUE THREAD

**Issue by VGeorgiev1** [node-webrtc/node-webrtc#531]
Using the `pc.addTrack()` function on the client side of my app results on receiving an empty event object when using the `pc.ontrack` hook on my backend. The connection seem to be made correctly as well as the negotiation. Are there any considerations i must be aware when using the ontrack hook like thetiming when i call `pc.addtrack` on the client or im just doing something else wrong?

**Comment by markandrus** [comment]
Hi @VGeorgiev1, thanks for writing.

We have tests for `ontrack` in `test/mediastream.js` ([here](https://github.com/node-webrtc/node-webrtc/blob/v0.4.1/test/mediastream.js#L196)), `test/rtcrtpreceiver.js` ([here](https://github.com/node-webrtc/node-webrtc/blob/v0.4.1/test/rtcrtpreceiver.js#L120) and [here](https://github.com/node-webrtc/node-webrtc/blob/v0.4.1/test/rtcrtpreceiver.js#L124)), and `test/rtcrtpsender.js` ([here](https://github.com/node-webrtc/node-webrtc/blob/v0.4.1/test/rtcrtpsender.js#L113)). These tests ensure basic functionality, so I'm not sure what could be off in your use case. The `ontrack` event should include the following properties:

- `type`
- `track`
- `receiver` *
- `streams` *
- `transceiver` *

In the C++, the parameters marked with an asterisk are first passed up to JavaScript [here](https://github.com/node-webrtc/node-webrtc/blob/v0.4.1/src/interfaces/rtc_peer_connection.cc#L187) for Plan B and [here](https://github.com/node-webrtc/node-webrtc/blob/v0.4.1/src/interfaces/rtc_peer_connection.cc#L205) for Unified Plan. Then, the JavaScript code [here](https://github.com/node-webrtc/node-webrtc/blob/v0.4.1/lib/peerconnection.js#L23) constructs the actual event object that gets dispatched (via `dispatchEvent`).

When you say "empty event object", what properties do you see missing?

> Are there any considerations i must be aware when using the ontrack hook like thetiming when i call `pc.addtrack` on the client or im just doing something else wrong?

Hard to answer without knowing more, but your `ontrack` handler ought to be installed before negotiating, certainly before calling `setRemoteDescription`. Also, keep in mind v0.4.x defaults to Unified Plan, whereas v0.3.x defaulted to Plan B. For certain negotiations, this is important.

* If you share SDPs, this might also allow tracking down the issue.
* You could also compare the `ontrack` event to results queried from `getReceivers` both 1. in the `ontrack` callback, and 2. after `setRemoteDescription` resolves.

**Comment by VGeorgiev1** [comment]
By empty i mean that all properties of the event object are there but all of them are empty objects. Its bizzare because i cant find example of similar problem even with normal browser2browser connection so i dont know where to look up for the problem. I deffinitely install the handler before negotiating. The logic of my app follows like this:

1. Creating the RTCPeerConnection on the backend
2. Define the ontrack handler
3. Add transceivers to the object just like in the audio-video-callback example. 
4. Create a local offer and apply it.
5. Notify the client and a new RTCPeerConnection is created there and then all the gathered  tracks get added with addTrack.
6. Sending the localDescription of the backend RTCPeerConnection the the client where it gets applied.
7. The front-end creates an answer and it gets send to the backend where it gets applied.

There might be something wrong with that order that im using but the lack of info for the same strange behaviour is killing me. Thanks in advance for the answer!

Here is the genereated answer from the client after adding the tracks: 
v=0

o=- 3318336601913283495 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 1
a=msid-semantic: WMS S1ggGNgkm8QdOzGHhC6jndNO1OmRucXkZMCj
m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 127 124 125
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:jqeH
a=ice-pwd:75tjLLQnzXg4qFwaLoC78FIJ
a=ice-options:trickle
a=fingerprint:sha-256 30:56:5D:29:A4:1E:4F:3D:7A:79:7A:98:BA:32:92:09:9A:52:72:1F:B5:D7:4C:69:A6:67:A1:2D:21:43:52:5F
a=setup:active
a=mid:0
a=extmap:14 urn:ietf:params:rtp-hdrext:toffset
a=extmap:13 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:12 urn:3gpp:video-orientation
a=extmap:2 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:11 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=extmap:8 http://tools.ietf.org/html/draft-ietf-avtext-framemarking-07
a=extmap:9 http://www.webrtc.org/experiments/rtp-hdrext/color-space
a=extmap:3 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:5 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
a=sendrecv
a=msid:S1ggGNgkm8QdOzGHhC6jndNO1OmRucXkZMCj c1570505-d5d0-43ef-bf14-10ab14c8de8a
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtpmap:98 VP9/90000
a=rtcp-fb:98 goog-remb
a=rtcp-fb:98 transport-cc
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=fmtp:98 profile-id=0
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=98
a=rtpmap:100 VP9/90000
a=rtcp-fb:100 goog-remb
a=rtcp-fb:100 transport-cc
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=fmtp:100 profile-id=2
a=rtpmap:101 rtx/90000
a=fmtp:101 apt=100
a=rtpmap:127 red/90000
a=rtpmap:124 rtx/90000
a=fmtp:124 apt=127
a=rtpmap:125 ulpfec/90000
a=ssrc-group:FID 3746757915 4124293471
a=ssrc:3746757915 cname:5plDAjxZjDDTjgA0
a=ssrc:4124293471 cname:5plDAjxZjDDTjgA0
m=audio 9 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 13 110 112 113 126
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:jqeH
a=ice-pwd:75tjLLQnzXg4qFwaLoC78FIJ
a=ice-options:trickle
a=fingerprint:sha-256 30:56:5D:29:A4:1E:4F:3D:7A:79:7A:98:BA:32:92:09:9A:52:72:1F:B5:D7:4C:69:A6:67:A1:2D:21:43:52:5F
a=setup:active
a=mid:1
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:3 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:5 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
a=recvonly
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:112 telephone-event/32000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000

And here is the generated offer from the server:

v=0
o=- 8890671136747615618 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 1
a=msid-semantic: WMS
m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 127 124 125
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:k1Cv
a=ice-pwd:CrHY4Ez2w3wdEtK1dA8HiXNR
a=ice-options:trickle
a=fingerprint:sha-256 52:75:95:5C:BB:A5:BD:59:30:E8:B4:DA:7B:48:47:84:EA:20:1C:F2:81:6A:10:77:1F:36:92:C2:F6:E7:E6:EC
a=setup:actpass
a=mid:0
a=extmap:14 urn:ietf:params:rtp-hdrext:toffset
a=extmap:13 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:12 urn:3gpp:video-orientation
a=extmap:2 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:11 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=extmap:8 http://tools.ietf.org/html/draft-ietf-avtext-framemarking-07
a=extmap:9 http://www.webrtc.org/experiments/rtp-hdrext/color-space
a=extmap:3 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:5 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
a=sendrecv
a=msid:- 65a29eee-bcfa-41b7-8642-7747b44ea429
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtpmap:98 VP9/90000
a=rtcp-fb:98 goog-remb
a=rtcp-fb:98 transport-cc
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=fmtp:98 profile-id=0
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=98
a=rtpmap:100 VP9/90000
a=rtcp-fb:100 goog-remb
a=rtcp-fb:100 transport-cc
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=fmtp:100 profile-id=2
a=rtpmap:101 rtx/90000
a=fmtp:101 apt=100
a=rtpmap:127 red/90000
a=rtpmap:124 rtx/90000
a=fmtp:124 apt=127
a=rtpmap:125 ulpfec/90000
a=ssrc-group:FID 2513410819 473479136
a=ssrc:2513410819 cname:KeJS95vwOkub6JGa
a=ssrc:2513410819 msid:- 65a29eee-bcfa-41b7-8642-7747b44ea429
a=ssrc:2513410819 mslabel:-
a=ssrc:2513410819 label:65a29eee-bcfa-41b7-8642-7747b44ea429
a=ssrc:473479136 cname:KeJS95vwOkub6JGa
a=ssrc:473479136 msid:- 65a29eee-bcfa-41b7-8642-7747b44ea429
a=ssrc:473479136 mslabel:-
a=ssrc:473479136 label:65a29eee-bcfa-41b7-8642-7747b44ea429
m=audio 9 UDP/TLS/RTP/SAVPF 111 103 104 9 102 0 8 106 105 13 110 112 113 126
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:k1Cv
a=ice-pwd:CrHY4Ez2w3wdEtK1dA8HiXNR
a=ice-options:trickle
a=fingerprint:sha-256 52:75:95:5C:BB:A5:BD:59:30:E8:B4:DA:7B:48:47:84:EA:20:1C:F2:81:6A:10:77:1F:36:92:C2:F6:E7:E6:EC
a=setup:actpass
a=mid:1
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:3 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:5 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
a=sendrecv
a=msid:- bcf9b4b9-55d9-4476-bcb0-6ddbd930db5f
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:102 ILBC/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:112 telephone-event/32000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000
a=ssrc:136532040 cname:KeJS95vwOkub6JGa
a=ssrc:136532040 msid:- bcf9b4b9-55d9-4476-bcb0-6ddbd930db5f
a=ssrc:136532040 mslabel:-
a=ssrc:136532040 label:bcf9b4b9-55d9-4476-bcb0-6ddbd930db5f

And the event argument  passed on ontrack callback look like this 
`{ type: 'track',
  track: MediaStreamTrack {},
  receiver: RTCRtpReceiver {},
  streams: [ MediaStream {} ],
  transceiver: RTCRtpTransceiver {} }`

**Comment by VGeorgiev1** [comment]
@markandrus I still can't resolve this problem. Do you have any idea what might be causing it?

**Comment by VGeorgiev1** [comment]
Okey now i found out that all `addIceCandidate` on the server side fail with no given reason - `[Error: Failed to set ICE candidate.]` and im missing the `null` candidate both on the client and the server side. Still, even every single candidate fail the `iceConnectionState` becomes `completed`

**Comment by markandrus** [comment]
Hi @VGeorgiev1, the object you pasted from the `ontrack` callback looks correct. What makes you think it’s incorrect? I see the MediaStreamTrack, the RTCRtpReceiver, a MediaStream, and an RTCRtpTransceiver. If you were to check that RTCRtpTransceiver’s `sender` and `receiver` properties, these should equal the RTCRtpSender and RTCRtpReceiver objects in the event. If you check the RTCRtpReceiver’s `track`, it should equal the MediaStreamTrack in the event. If you check the MediaStream's `getTracks()` method, it should include the MediaStreamTrack from the event as well.

**Comment by VGeorgiev1** [comment]
@markandrus 
When i `console.log` the track received from the example `audio-video-callback` i get something like this: `{ type: 'track',
  track:
   MediaStreamTrack {
     muted: false,
     readyState: 'live',
     kind: 'audio',
     id: '267d2e2c-4e36-4cbe-839f-7cf0a53e5e70',
     enabled: true },
  receiver:
   RTCRtpReceiver {
     rtcpTransport: null,
     transport: RTCDtlsTransport { state: 'new' },
     track:
      MediaStreamTrack {
        muted: false,
        readyState: 'live',
        kind: 'audio',
        id: '267d2e2c-4e36-4cbe-839f-7cf0a53e5e70',
        enabled: true } },
  streams:
   [ MediaStream { active: true, id: 'WLRSYCP2OhZMYcM3RNixVyVqMUp4rXraNIYz' } ],
  transceiver:
   RTCRtpTransceiver {
     currentDirection: 'sendrecv',
     direction: 'sendrecv',
     stopped: false,
     receiver:
      RTCRtpReceiver {
        rtcpTransport: null,
        transport: [RTCDtlsTransport],
        track: [MediaStreamTrack] },
     sender:
      RTCRtpSender {
        rtcpTransport: null,
        transport: [RTCDtlsTransport],
        track: null },
     mid: '0' } }` 

but in my case when i `console.log()` my track every single of the properties are just empty objects.

**Comment by markandrus** [comment]
The node-webrtc-examples project is still on v0.3.x, IIRC. The latest version of node-webrtc is v0.4.1. Between v0.3.x and v0.4.x, we moved from ES5-style classes to ES6-style classes. Getters on ES6-style classes are non-enumerator, so they don’t show up when you log the object. This is why you don’t see them, but it doesn’t mean they aren’t there. Please check the properties and you should see they are not empty.

**Comment by VGeorgiev1** [comment]
Okey redirecting the tracks to a different users seems to work but i still cant get them to deliver actuall sound or video which is really odd.

**Comment by markandrus** [comment]
Where are you trying to deliver sound/video from? Please keep in mind that node-webrtc’s `getUserMedia` returns MediaStreamTracks that—although they can be added to an RTCPeerConnection—do not produce audio/video. Also, node-webrtc does not playback audio. If you want to produce/consume audio/video in node-webrtc, use the nonstandard RTCAudioSink/RTCAudioSource, etc.

**Comment by VGeorgiev1** [comment]
Im trying to send audiotrack obtained by the browser to many viewer browsers via node-webrtc. I fixed my problem by rewriting some code...i guess i had a mistake somwehre around all the synchronization but it finally works. Thanks for the support!

**Comment by markandrus** [comment]
Great, you’re welcome and good luck 👍🏼 BTW, you may want to consider using an SFU instead of node-webrtc for your use case. An SFU ought to be more performant since it shouldn’t have to decode/re-encode media.
