### ISSUE TITLE
How to send H264 to Mediastream

### ISSUE THREAD

**Issue by baptistemanson** [node-webrtc/node-webrtc#533]
Hi all,

We want to display a H.264 video stream with low latency in the browser.
 
- A security camera provides us a raw H.264 stream that we can listen to with node. 
- We then forward this raw H.264 stream with node-webrtc from node to a browser client.
- The browser client listens to the on("stream") webrtc event and set a <video /> tag src as the stream to display it.
 

Is it possible with node-webrtc? We couldn't find the correct API endpoints to do so.

**Comment by anshul-kai** [comment]
Look at #514 @baptistemanson. You need to enable H264 in `CMakeLists.txt` but as you will notice, it has issues and doesn't work reliably. Although #514 talks about 540p, I'm noticing that this happens on other standard resolutions like 720p as well.

**Comment by baptistemanson** [comment]
Thanks!

**Comment by figamore** [comment]
> Hi all,
> 
> We want to display a H.264 video stream with low latency in the browser.
> 
> * A security camera provides us a raw H.264 stream that we can listen to with node.
> * We then forward this raw H.264 stream with node-webrtc from node to a browser client.
> * The browser client listens to the on("stream") webrtc event and set a
> 
> Is it possible with node-webrtc? We couldn't find the correct API endpoints to do so.

Did you ever figure this out?
