### ISSUE TITLE
TCP candidates do not connect correctly

### ISSUE THREAD

**Issue by Joe-Palmer** [node-webrtc/node-webrtc#534]
In our setup, we get an answer with the following candidates:

```
a=candidate:1 1 udp 2013266431 50.145.21.54 50057 typ host
a=candidate:2 1 tcp 1015021823 50.145.21.54 0 typ host tcptype active
a=candidate:3 1 tcp 1010827519 50.145.21.54 50006 typ host tcptype passive
```

Only TCP is available so `wrtc` tries to connect on port 50006 but the stream never starts. This is what I see in Wireshark repeated over and over:

![image](https://user-images.githubusercontent.com/1328310/58084286-7e028400-7bb2-11e9-87b8-74fe0820fdb0.png)

If I use my firewall to block TCP on the port range then it works fine using TURN over port 3478.

I also see these UDP connection attempts which fail as expected:

![image](https://user-images.githubusercontent.com/1328310/58086030-bce60900-7bb5-11e9-9c6e-e32284511d20.png)

Are TCP candidates supported? If so, they are not working properly for me. If not, they preventing the TURN fallback as connection is being partially established.

**Comment by markandrus** [comment]
This would be some issue in the webrtc.org code/or something about the host node-webrtc is deployed. Have you tried with recent wrtc builds? We're on M79 now.
