### ISSUE TITLE
napi.h not found

### ISSUE THREAD

**Issue by anshul-kai** [node-webrtc/node-webrtc#535]
Tried compiling the latest code with both node 11 and 12 with no luck. Fails with the following error:

`node-webrtc-develop/src/binding.cc:8:10: fatal error: 'node-addon-api/napi.h' file not found`

Am I missing a system dependency or is my cmake out of date?

**Comment by markandrus** [comment]
Can you share the output of doing a fresh `git clone` and then `npm install`?

**Comment by anshul-kai** [comment]
Looks like this is an issue with my customizations. The project compiles fine with a fresh git clone.
