### ISSUE TITLE
Record Video/Audio Stream

### ISSUE THREAD

**Issue by jrpedrianes** [node-webrtc/node-webrtc#537]
Hello,

Is it possible to record an incoming stream? how can we do this? I'm trying to figure out how to do it, but I can't find a correct solution.

**Comment by d19900819** [comment]
I'm trying, too. RTCAudioSink and RTCVideoSink are inefficient.

**Comment by mayank** [comment]
@d19900819 can you share how the data coming in the sink can be converted to a video?

**Comment by mayank** [comment]
@jrpedrianes I have tried, store the frames buffer coming in `RTCVideoSink` into a file with extension `.yuv` then use `ffmpeg` to convert `.yuv` to the desired format, I would prefer `.webm` format.

**Comment by jrpedrianes** [comment]
@mayank 👍 do you know what is the audio format if we use RTCAudioSink?, anyway, I was looking for a more "raw" solution, to avoid the transcoding, store the Video and Audio (VP8/ACC) without any process (only removing the RTP protocol)

**Comment by omnipotentuser** [comment]
@jrpedrianes You are thinking of a container. You need to use a container such as MP4 to write to file. It does not transcode, but simply organizes the stream into chunks for storing.

**Comment by jrpedrianes** [comment]
Yes, I want a mp4 with the video but I don’t know how to do that with node-webrtc, Do you have an example how to do that?

**Comment by omnipotentuser** [comment]
I don't have an example. Im sorry. But I do plan on getting started on that
soon perhaps we can get somewhere. I am thinking of ffmpeg to listen to
streams and packetize it. Much like how we use media track  to connect
screen for screensharing.

**Comment by tzvc** [comment]
That would be really awesome to have, happy to help if needed

**Comment by cracker0dks** [comment]
I'm interested as well and found this lib: https://www.npmjs.com/package/wrtc-to-ffmpeg 
Seems to work, but only on linux and fixed stream resolution. 
They use RTCAudioSink and RTCVideoSink... 

Edit: Git Repo is here: https://github.com/t-mullen/wrtc-to-ffmpeg

Edit2: 
This woks for me with this lib:
```
var track = stream.getVideoTracks()[0];
    if (track) {
        const input = await w2f.input(track)
        var f = FFmpeg().input(input.url)             // add our input
            .inputOptions(input.options)  // specify the input options
            .on('start', function () {
                console.log("START")
            })
            .on('error', function (err) {
                console.log('An error occurred: ' + err.message);
            })
            .on('end', function () {
                console.log('Processing finished !');
            })
            .output('./public/test.mp4')
            .run();

        console.log("HERE WE GO")

    }
```
The video is running a little to fast (for me) because the framerate is fixed to 30fps

**Comment by omnipotentuser** [comment]
Looks fantastic, will check it out more later. Thanks!

**Comment by markandrus** [comment]
@jrpedrianes 

> @mayank 👍 do you know what is the audio format if we use RTCAudioSink?, anyway, I was looking for a more "raw" solution, to avoid the transcoding, store the Video and Audio (VP8/ACC) without any process (only removing the RTP protocol)

You would probably be better served by a proper media server or a different library unless/until someone has a plan for https://github.com/node-webrtc/node-webrtc/issues/544. Even then, I'm not convinced you'd get the performance expected versus a tuned solution.

@t-mullen's wrtc-to-ffmpeg is cool and a great example—however there are some issues with the RTCVideoSink/RTCAudioSink APIs exposed by node-webrtc which cause synchronization issues, performance issues, etc.

Anyway, I think the original question here has been answered to some degree&hellip; so I will close the issue 🙃
