### ISSUE TITLE
Allow MediaStreamTrack and PeerConnection from different version of node-webrtc

### ISSUE THREAD

**Issue by scaret** [node-webrtc/node-webrtc#538]
when adding track to peer connection, node-webrtc will judge whether track is an instance of wrtc.MediaStreamTrack.

In my project, MediaStreamTrack and PeerConnection comes from different packages, both of wich relys on node-webrtc. AddTrack will fail if they come from different node-webrtc package/version.

**Comment by markandrus** [comment]
Hi @scaret, unfortunately I do not see a safe way to allow this. Can you update the packages you depend on to use the same version of wrtc instead?

**Comment by scaret** [comment]
Sure. I passed the `node-webrtc` library as parameter to both modules.
