### ISSUE TITLE
Set up TravisCI for node-webrtc

### ISSUE THREAD

**Issue by modeswitch** [node-webrtc/node-webrtc#54]
Initially it can run a sanity check.

**Comment by piranna** [comment]
I agree. We could also set to use specific commits of libwebrtc intead of
latest version so we can be sure what versions are tested to work
successfully.

2014/1/23 Alan K notifications@github.com

> Initially it can run a sanity check.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/js-platform/node-webrtc/issues/54
> .

## 

"Si quieres viajar alrededor del mundo y ser invitado a hablar en un monton
de sitios diferentes, simplemente escribe un sistema operativo Unix."
– Linus Tordvals, creador del sistema operativo Linux

**Comment by modeswitch** [comment]
I'm reluctant to do that at this point since we still need sctp support, which hasn't even landed yet. Once we have all the features required for 1.0, I'm happy to import a specific version of libjingle into this project and update it only as necessary.

**Comment by piranna** [comment]
I'm not saying to dispatch a 1.0 version, just link to a libwebrtc stable
one. When SCTP support lands there, we can update the revision id and fetch
a newer one. It's just to be sure that when you type npm install everybody
fetch a working version and all fetch the same one to help debugging.

2014/1/23 Alan K notifications@github.com

> I'm reluctant to do that at this point since we still need sctp support,
> which hasn't even landed yet. Once we have all the features required for
> 1.0, I'm happy to import a specific version of libjingle into this project
> and update it only as necessary.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/js-platform/node-webrtc/issues/54#issuecomment-33127064
> .

## 

"Si quieres viajar alrededor del mundo y ser invitado a hablar en un monton
de sitios diferentes, simplemente escribe un sistema operativo Unix."
– Linus Tordvals, creador del sistema operativo Linux

**Comment by modeswitch** [comment]
@piranna Just opened #55

**Comment by piranna** [comment]
Ok, cool :-)

2014/1/23 Alan K notifications@github.com

> @piranna https://github.com/piranna Just opened #55https://github.com/js-platform/node-webrtc/issues/55
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/js-platform/node-webrtc/issues/54#issuecomment-33127612
> .

## 

"Si quieres viajar alrededor del mundo y ser invitado a hablar en un monton
de sitios diferentes, simplemente escribe un sistema operativo Unix."
– Linus Tordvals, creador del sistema operativo Linux

**Comment by DamonOehlman** [comment]
If the merge of #63 goes well (which also closes #15) then this should be trivial :)

**Comment by modeswitch** [comment]
This is blocked I think on #29

**Comment by modeswitch** [comment]
It turns out this is probably necessary for building binary modules in the first place. My machine has new versions of glibc that cause the module to be unusable on some other distributions.

**Comment by modeswitch** [comment]
This is working now for Linux.
