### ISSUE TITLE
error downloading pre-built binaries for docker node:12 image

### ISSUE THREAD

**Issue by imgntn** [node-webrtc/node-webrtc#542]
if i try to install node-webrtc w/ `npm install` on the `node:12` docker image, 

```
node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: 404 status code downloading tarball https://node-webrtc.s3.amazonaws.com/wrtc/v0.3.7/Release/node-v72-linux-x64.tar.gz
```
https://node-webrtc.s3.amazonaws.com/wrtc/v0.3.7/Release/node-v72-linux-x64.tar.gz gives a "no such key error"

falling back to node:10 works

thanks!

**Comment by markandrus** [comment]
Hi, Node 12 support was added in v0.4.0—please update to the latest version.

**Comment by imgntn** [comment]
oh, okay.  got it, thanks!
