### ISSUE TITLE
Failed to set remote offer sdp: Failed to set remote video description send parameters

### ISSUE THREAD

**Issue by phamtai93** [node-webrtc/node-webrtc#543]
I build and ran a simple streaming app on windows 10 x64 (run as a server app on nodejs, not browser), node version 10.16.0 . I try to set remote description:
`this._pc.setRemoteDescription(jsep)` 
jsep is object that I recieved from the server (a janus webrtc server):
{
   "type": "offer",
   "sdp": "
      v=0
      o=- 1562756130962919 1 IN IP4 192.168.1.24
      s=Mountpoint 1965
      t=0 0
      a=group:BUNDLE video
      a=msid-semantic: WMS janus
      m=video 9 UDP/TLS/RTP/SAVPF 98
      c=IN IP4 192.168.1.24
      a=sendonly
      a=mid:video
      a=rtcp-mux
      a=ice-ufrag:IJ0F
      a=ice-pwd:37dxX8Jhy4PcYhGiWNag6b
      a=ice-options:trickle
      a=fingerprint:sha-256 F1:7B:9F:87:70:DC:93:2D:DE:E5:7B:0B:15:60:AD:D5:A4:08:9D:B0:36:6B:B1:B4:92:6F:7E:D3:94:F1:30:67
      a=setup:actpass
      a=rtpmap:98 H264/90000
      a=fmtp:98 profile-level-id=42E01F;packetization-mode=1;sprop-parameter-sets=Z2QAMqw0yAJIDb/wFuAgICgAAB9AAAYah0MAHoQAA9BRd5caGAD0IAAegou8uFA=,aO44MA==
      a=rtcp-fb:98 nack
      a=rtcp-fb:98 nack pli
      a=rtcp-fb:98 goog-remb
      a=ssrc:1257499188 cname:janusvideo
      a=ssrc:1257499188 msid:janus janusv0
      a=ssrc:1257499188 mslabel:janus
      a=ssrc:1257499188 label:janusv0
      a=candidate:1 1 udp 2013266431 192.168.1.24 53177 typ host
      a=candidate:2 1 udp 2013266430 172.19.0.1 44075 typ host
      a=candidate:4 1 udp 503316991 192.168.1.24 63194 typ relay raddr 192.168.1.24 rport 53177
      a=candidate:5 1 udp 1677722111 192.168.1.24 44075 typ srflx raddr 172.19.0.1 rport 44075
      a=candidate:6 1 udp 503316990 192.168.1.24 57334 typ relay raddr 172.19.0.1 rport 44075
      a=end-of-candidates
"
}

I got an error: "Failed to set remote offer sdp: Failed to set remote video description send parameters." . I researched on gg but can not resolve it.

**Comment by markandrus** [comment]
Looks like the only video codec sent by Janus was H.264:

```sdp
m=video 9 UDP/TLS/RTP/SAVPF 98
...
a=rtpmap:98 H264/90000
```

node-webrtc is not distributed with H.264 support. You would have to build from source yourself with H.264 enabled to be able to apply this SDP. You could try sending VP8 instead.
