### ISSUE TITLE
Get VP8 format from video instead of frames.

### ISSUE THREAD

**Issue by mayank** [node-webrtc/node-webrtc#544]
Can you implement the encoder given with chromium to directly return vp8 video as currently, I am storing the frames into YUV frames and video size is large.
Video encoder code is here.

https://chromium.googlesource.com/webm/libvpx/+/master/examples/simple_encoder.c

**Comment by markandrus** [comment]
I haven't looked closely, but I think this is the idea behind "insertable streams". Unclear to me if using insertable streams would let us skip the decode entirely. Maybe we can solve this borrowing techniques from Chrome. See https://github.com/node-webrtc/node-webrtc/issues/629

**Comment by mayank** [comment]
no worries, I have migrated the code to mediasoup.

**Comment by markandrus** [comment]
Nice 👍
