### ISSUE TITLE
Please provide documentation how to configure remote signaling server

### ISSUE THREAD

**Issue by sagimann** [node-webrtc/node-webrtc#545]
I've successfully set up a node server serving both the server and client, as in the examples. But nowhere in the examples do I see how the client and server signal each other. I tried splitting the client and server "peers" into other machines, but in order for them to communicate with each other, they need to go through a signaling server which is somehow implicitly used in node-webrtc. I would like to see how I can deploy it separately and have both client and server codes connect to it.

**Comment by markandrus** [comment]
Thank you for the suggestion; however, I think that's outside the scope of this project. Everyone does things a bit differently (JSON over WebSocket, REST, etc.). I also think there's good material already out there on the subject. That being said, there's a toy example [here](https://github.com/node-webrtc/node-webrtc-examples#rtcpeerconnection-negotiation) in the node-webrtc-examples project. If you think of a way to improve the documentation, I'd be willing to accept a PR.
