### ISSUE TITLE
WebRTC broadcast server?

### ISSUE THREAD

**Issue by eanders-ms** [node-webrtc/node-webrtc#550]
Hello. Would this library be good for building a WebRTC broadcast service? Where the service consumes WebRTC streams from some clients, and republishes them for multiple other clients to consume. Thanks!

**Comment by markandrus** [comment]
Hi 👋 I do not recommend you use this project for that. Instead, you'd want an SFU. Some open source options include [mediasoup](https://mediasoup.org/) and [Jitsi Videobridge](https://jitsi.org/jitsi-videobridge/).
