### ISSUE TITLE
Question: is node-webrtc support encode video source use GPU？

### ISSUE THREAD

**Issue by raiscui** [node-webrtc/node-webrtc#554]
when I use RTCVideoSource , I didn't see using the GPU.

**Comment by hugomallet** [comment]
Hi,

I’m interested in hardware acceleration too. Is it possible to enable GPU decoding / encoding ?

**Comment by ghost** [comment]
Hello. I am also interasted.

**Comment by felicemarra** [comment]
me too

**Comment by markandrus** [comment]
Closing this issue in favor of #606. Please see my comment there: https://github.com/node-webrtc/node-webrtc/issues/606#issuecomment-612582991
