### ISSUE TITLE
Can I use "getUserMedia" at nodejs server side?

### ISSUE THREAD

**Issue by DajieGuo** [node-webrtc/node-webrtc#557]
I want to get mediastream from my rspberry pi4 from usb camera.
But I can't get any video at web side.
Should I do something at server side to trigger it start transfering?
Now I only add a video track at serverside but nothing at web side,
do I need also add a track at webside?
![image](https://user-images.githubusercontent.com/42426502/65491043-dccd6680-dee0-11e9-8692-36ec786b7f5a.png)

![image](https://user-images.githubusercontent.com/42426502/65491148-13a37c80-dee1-11e9-955b-e2817d5816de.png)

**Comment by DajieGuo** [comment]
I add video track at web, but it still not start transfer video from usb camera

**Comment by DajieGuo** [comment]
@markandrus Help

**Comment by DajieGuo** [comment]
Help me
Is it implemented? @markandrus @modeswitch @piranna @helloIAmPau

**Comment by mneundorfer** [comment]
I guess the [changelog](https://github.com/node-webrtc/node-webrtc/blob/9927738ddf6fd6e0e25e5b49d977b25ce0bbbacc/CHANGELOG.md#getusermedia) answers your question...

> This release adds limited getUserMedia support. You can create audio and video MediaStreamTracks; however, the resulting MediaStreamTracks do not capture any media.

**Comment by piranna** [comment]
How can custom media be provided?

**Comment by markandrus** [comment]
@DajieGuo as @mneundorfer points out, `getUserMedia` in node-webrtc doesn't produce MediaStreamTracks that actually send anything. There are, however, some nonstandard APIs (primarily just for experimenting with) which can send audio and video.

@piranna 

> How can custom media be provided?

Please check out the sections on [Programmatic Video](https://github.com/node-webrtc/node-webrtc/blob/develop/CHANGELOG.md#programmatic-video) and [Programmatic Audio](https://github.com/node-webrtc/node-webrtc/blob/develop/CHANGELOG.md#programmatic-audio) in the CHANGELOG.md. There are also examples in the [node-webrtc/node-webrtc-examples](https://github.com/node-webrtc/node-webrtc-examples) project (video-compositing and sine-wave, for example). There are also some tests in [test/rtcvideosource.js](https://github.com/node-webrtc/node-webrtc/blob/develop/test/rtcvideosource.js) and [test/rtcaudiosource.js](https://github.com/node-webrtc/node-webrtc/blob/develop/test/rtcaudiosource.js).

@DajieGuo to your original question, if you want the Raspberry Pi to transmit the video from the USB camera using node-webrtc, you would have to somehow get access to the video frames from the USB camera (perhaps with a different Node library) and then manually feed them into the RTCVideoSource provided by this library; however, I don't think you'd get very good performance. You may want to look for a different solution.
