### ISSUE TITLE
WebRTC M77 or later?

### ISSUE THREAD

**Issue by JonathanLennox** [node-webrtc/node-webrtc#559]
Chrome is now up to WebRTC M77 on its stable releases (and M78 on beta and M79 on canary).  Is there intention to keep node-webrtc in sync?

**Comment by markandrus** [comment]
I welcome any PRs to keep the project up to date with respect to Chrome.
Unfortunately I personally don’t have time to actively work on this right
now. Bumping the dep should be straightforward from the CMakeLists.txt, and
then tweak any C++ code as necessary.

**Comment by Borjis131** [comment]
+1! I'm trying to compile WebRTC M77 for armv7. AFAIK node-webrtc only uses libwebrtc.a from WebRTC, is that true?

**Comment by markandrus** [comment]
As of wrtc 0.4.3 we are now on M79.

> AFAIK node-webrtc only uses libwebrtc.a from WebRTC, is that true?

We also link to `libc++`, `libc++abi`, and `libpeerconnection.a`. See [here](https://github.com/node-webrtc/node-webrtc/blob/82a88fc0ad5f34ca4e52b0fd85235c8ef4c2de0c/CMakeLists.txt#L178).
