### ISSUE TITLE
Use Grunt?

### ISSUE THREAD

**Issue by piranna** [node-webrtc/node-webrtc#56]
If we start to add tasks like browserify to the toolchain as talked on issue #51, maybe we could start to use a task manager like Grunt or similar instead of custom-made scripts.

**Comment by modeswitch** [comment]
Agreed.

**Comment by wouldgo** [comment]
Can I now verify all the .js files with jshint again, linting them?

**Comment by modeswitch** [comment]
Yep.

**Comment by modeswitch** [comment]
Fixed.

**Comment by piranna** [comment]
I think this should be re-open and not closed until both bin/clean.sh and bin/build.sh are removed and integrated inside Gruntfile.js and/or build.gyp

**Comment by wouldgo** [comment]
I agree with @DamonOehlman as reported [here](https://github.com/js-platform/node-webrtc/pull/68#issuecomment-34717129): the aim of grunt is on developer part, those scripts are used for installing the module.

Bye.

**Comment by piranna** [comment]
My proposal to use grunt was to recude failure surface. I agree with that comment, but current build is dificult, so I still think we should use grunt everywhere. Another thing is if we have pre-compiled binaries easily installable with a simple script, so not-usual builds can be done changuing to "developer mode".
