### ISSUE TITLE
How Do I Use This?

### ISSUE THREAD

**Issue by DakotaLarson** [node-webrtc/node-webrtc#560]
I hate to be so general, but I am a little lost. I am hoping to use wrtc to connect an unreliable data channel between client and server. I am using numb: http://numb.viagenie.ca/ for a STUN / TURN server and messaging between the client and server with fetch. I have been combing through docs here, MDN, and elsewhere.

What steps do I take and in what order when trying to connect a channel between Node 12.x and Chrome?

Currently I am running:
Client creates offer
Client sets local description
Client gathers Ice candidates
Client sends ice candidates and offer to server via Fetch
Server instantiates connection
Server adds all client sent Ice Candidates
Server sets remote description (the offer)
Server creates answer
Server sets local description (the answer)
Server responds to fetch with answer.

I believe I am missing the server generating its own Ice Candidates and somehow finding a match. I imagine a lot of that is internal, but I still need to start that process somehow...

Thoughts? Am I on the right track here?

Also, please let me know if there is a better medium to raise elementary questions like this.

**Comment by DakotaLarson** [comment]
Of course I find a solution mere minutes after raising an issue. For those who find this in the future, I created a MVP that could be a helpful starting point: https://github.com/DakotaLarson/WebRTC-Minimal-Server/tree/c510cd86ff22ee406c9768c7d8907fd41bb6225f This link is to the initial commit as I may add abstractions in the future which would hamper readability.

@markandrus You seem pretty active here. What are your thoughts on a wiki including a minimal implementation? I found this very challenging due to the lack of resources available online. MDN is very chatty, and I couldn't find any succinct blogs detailing usage of wrtc.

**Comment by yuanzhanghu** [comment]
check webRTC.js in https://github.com/yuanzhanghu/p2p-mapping

**Comment by markandrus** [comment]
@DakotaLarson 

> @markandrus You seem pretty active here. What are your thoughts on a wiki including a minimal implementation? I found this very challenging due to the lack of resources available online. MDN is very chatty, and I couldn't find any succinct blogs detailing usage of wrtc.

I'm open to it. Maybe links out to projects rather than duplicating a minimal implementation? Or maybe a minimal implementation under the node-webrtc Github org? I'm not sure if there are permissions on the wiki or not—if it's open feel free to create a page.
