### ISSUE TITLE
support  fieldtrials  

### ISSUE THREAD

**Issue by notedit** [node-webrtc/node-webrtc#563]

**Comment by taylorhoward92** [comment]
@notedit can you elaborate?

**Comment by notedit** [comment]
webrtc support fieldtrials.  we can use filedtrials to change many webrtc's default settings.

https://github.com/notedit/webrtc-clone/blob/m76/system_wrappers/include/field_trial.h

**Comment by markandrus** [comment]
TBH, from past experience, I've not been a fan of field trials or the various things that could cause the webrtc.org code within Chrome to do something unexpected. Currently, I think we should not support this.

However, for your request here, I am wondering, what would it mean to expose field trials in node-webrtc? What sort of API do you expect?

**Comment by notedit** [comment]
```
   NSDictionary *trials = @{

                 @"WebRTC-Bwe-InjectedCongestionController": @"Enabled",

    };

    RTCInitFieldTrialDictionary(trials);

```

This is how i used in objective-c

**Comment by markandrus** [comment]
Thanks for elaborating, @notedit — rather than introduce a general field trial API, I think we should consider explicitly exposing any that might be relevant in the future. I will close this issue ATM.
