### ISSUE TITLE
Support for mediaStream MediaRecorder in node

### ISSUE THREAD

**Issue by generalomosco** [node-webrtc/node-webrtc#564]
Is there anyway of recording the mediaStreamTracks onTrack event containing the video and audio merged together to able to stream it directly to rtmp using ffmpeg just like MediaRecorder on client side?
Thanks

**Comment by generalomosco** [comment]
What is wrong with this query using input stream buffer scope from [https://github.com/t-mullen/wrtc-to-ffmpeg/blob/master/src/index.js](url). 

The issue is that, the video speed is very high out of the audio sync to the way the rtmp downstream always buff waiting for next stream data after playing previous stream data of about 20sec in just 5sec faster while the audio inside play normal but also stopped after video awaiting buff.

Here is the command line.
`ffmpeg -vsync cfr -f rawvideo -c:v rawvideo -fflags nobuffer -s 320x240 -pix_fmt yuv420p -i unix:./socket-bin/1.sock -f s16le -ar 48k -ac 1 -fflags nobuffer -i unix:./socket-bin/2.sock -flags +global_header -acodec libfdk_aac -vsync 1 -vcodec libx264 -r 25 -b:v 4000k -pix_fmt yuv420p -preset superfast -tune zerolatency -threads 0 -crf 25 -fflags nobuffer -shortest -f flv rtmps://url.com/xxxxx`

While this is the log.
![image](https://user-images.githubusercontent.com/17610332/67037128-3bbb7f80-f11d-11e9-9829-e566a3c38619.png)


![image](https://user-images.githubusercontent.com/17610332/67036787-87215e00-f11c-11e9-94ea-a13975e59fc5.png)

**Comment by cracker0dks** [comment]
had the same problem. Try using: `-use_wallclock_as_timestamps 1` (as ffmpg attr) for the video. 
Required because we have raw frames without timestamp but a variable frame rate... so when we use the system time to "place the frames" we get everything synced.

**Comment by markandrus** [comment]
I think the MediaRecorder API goes a step too far out beyond the core WebRTC APIs (and supporting MediaStream APIs) that node-webrtc aims to support. I think we will not implement it. There are workarounds, like the library linked, although synchronization issues may remain a problem.
