### ISSUE TITLE
Calling .getVideoTracks on a media stream that has no video tracks causes a segfault.

### ISSUE THREAD

**Issue by JessieAMorris** [node-webrtc/node-webrtc#57]
Title pretty much says it all.

When you call pc.getRemoteStreams()[0].getVideoTracks() on a stream that has no video tracks, it segfaults, quite wonderfully.

**Comment by piranna** [comment]
Good thing to add as a test case... :-)

Send from my Samsung Galaxy Note II

**Comment by modeswitch** [comment]
This part of the API has been removed.
