### ISSUE TITLE
How to connect 2 browser clients in video-compositing example?

### ISSUE THREAD

**Issue by Glunky** [node-webrtc/node-webrtc#573]
Hi!
In video-compositing example we exchange data only between 1 browser client. What should i do to detect second connection and only then produce connection? So that 1st browser client get  stream from second browser client and 2nd browser client get stream from 1st browser client? Please, provide any idea or information to do that.

**Comment by Glunky** [comment]
> Hi!
> In video-compositing example we exchange data only between 1 browser client. What should i do to detect second connection and only then produce connection? So that 1st browser client get stream from second browser client and 2nd browser client get stream from 1st browser client? Please, provide any idea or information to do that.

**Comment by markandrus** [comment]
Answered here: https://github.com/node-webrtc/node-webrtc-examples/issues/7
