### ISSUE TITLE
npm install failing with gclient_sync failed: 1 null

### ISSUE THREAD

**Issue by mparisi76** [node-webrtc/node-webrtc#58]
When I run npm install, it does all of the dep downloads and then the following is output:

> wrtc@0.0.7 install /Users/matt/work/nextgen/studioGit/mp-studio/node_modules/wrtc
> node bin/build.js

depot_tools
.
depot_tools complete
gclient_config
.
gclient_config complete
gclient_sync
.............................................................................................................................................................................................................................................................................................................................................................
gclient_sync failed: 1 null
wrtc@0.0.7 node_modules/wrtc
├── bindings@1.1.1
├── nan@0.4.4
└── node-gyp@0.10.10 (which@1.0.5, osenv@0.0.3, graceful-fs@2.0.1, rimraf@2.2.6, mkdirp@0.3.5, semver@2.1.0, nopt@2.1.2, minimatch@0.2.14, npmlog@0.0.6, fstream@0.1.25, glob@3.2.8, tar@0.1.19, request@2.33.0)
$

I've tried uninstalling and installing again but still same output. Any idea why this is happening?

Thanks.

**Comment by modeswitch** [comment]
Which platform are you on?

**Comment by mparisi76** [comment]
MAC 10.6.8

I did attempt to build webrtc first using the instructions found here: http://www.webrtc.org/reference/getting-started

Not sure if that would cause something to be out of whack.

Then I did more research and found that I could use npm and since I'd like to use webrtc in a node.js SPA, I thought that would work out really well.

**Comment by mparisi76** [comment]
Oh, and I have XCode 3.2.6 installed.

**Comment by modeswitch** [comment]
I haven't officially added support for osx yet. That said, I'm surprised it's failing during sync. Can you jump into `node_modules/wrtc/third_party/libwebrtc/` and run `gclient sync` and see what you get?

**Comment by mparisi76** [comment]
Ok, that took a while, I'm not sure what to post here so I'll just do the tail end of the output:

Hook '/usr/bin/python trunk/tools/clang/scripts/update.py --mac-only' took 3040.51 secs

________ running '/usr/bin/python trunk/build/win/setup_cygwin_mount.py --win-only' in '/Users/matt/work/nextgen/studioGit/mp-studio/node_modules/wrtc/third_party/libwebrtc'

________ running '/usr/bin/python trunk/build/gyp_chromium --depth=trunk trunk/all.gyp -Dextra_gyp_flag=0' in '/Users/matt/work/nextgen/studioGit/mp-studio/node_modules/wrtc/third_party/libwebrtc'
Generating gyp files from GN...
Traceback (most recent call last):
  File "trunk/build/gyp_chromium", line 309, in <module>
    if not RunGN(supplemental_includes):
  File "trunk/build/gyp_chromium", line 258, in RunGN
    return subprocess.call(args) == 0
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/subprocess.py", line 444, in call
    return Popen(_popenargs, *_kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/subprocess.py", line 595, in **init**
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/subprocess.py", line 1106, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Error: Command /usr/bin/python trunk/build/gyp_chromium --depth=trunk trunk/all.gyp -Dextra_gyp_flag=0 returned non-zero exit status 1 in /nextgen/studioGit/mp-studio/node_modules/wrtc/third_party/libwebrtc
$

Hope that helps.

**Comment by piranna** [comment]
I was having just the same error on LinuxMint 16

2014/1/24 mparisi76 notifications@github.com

> Ok, that took a while, I'm not sure what to post here so I'll just do the
> tail end of the output:
> 
> Hook '/usr/bin/python trunk/tools/clang/scripts/update.py --mac-only' took
> 3040.51 secs
> 
> ________ running '/usr/bin/python trunk/build/win/setup_cygwin_mount.py
> --win-only' in
> '/Users/matt/work/nextgen/studioGit/mp-studio/node_modules/wrtc/third_party/libwebrtc'
> 
> ________ running '/usr/bin/python trunk/build/gyp_chromium --depth=trunk
> trunk/all.gyp -Dextra_gyp_flag=0' in
> '/Users/matt/work/nextgen/studioGit/mp-studio/node_modules/wrtc/third_party/libwebrtc'
> Generating gyp files from GN...
> Traceback (most recent call last):
> File "trunk/build/gyp_chromium", line 309, in
> if not RunGN(supplemental_includes):
> File "trunk/build/gyp_chromium", line 258, in RunGN
> return subprocess.call(args) == 0
> File
> "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/subprocess.py",
> line 444, in call
> return Popen(_popenargs, *_kwargs).wait()
> File
> "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/subprocess.py",
> line 595, in _init_
> errread, errwrite)
> File
> "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/subprocess.py",
> line 1106, in _execute_child
> raise child_exception
> OSError: [Errno 2] No such file or directory
> Error: Command /usr/bin/python trunk/build/gyp_chromium --depth=trunk
> trunk/all.gyp -Dextra_gyp_flag=0 returned non-zero exit status 1 in
> /Users/matt/work/nextgen/studioGit/mp-studio/node_modules/wrtc/third_party/libwebrtc
> $
> 
> Hope that helps.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/js-platform/node-webrtc/issues/58#issuecomment-33255909
> .

## 

"Si quieres viajar alrededor del mundo y ser invitado a hablar en un monton
de sitios diferentes, simplemente escribe un sistema operativo Unix."
- Linus Tordvals, creador del sistema operativo Linux

**Comment by piranna** [comment]
Seems there's a bug on the depot tools:

https://groups.google.com/forum/#!topic/discuss-webrtc/Y7DQL_YpueE
https://code.google.com/p/webrtc/issues/detail?id=2790

**Comment by modeswitch** [comment]
I'm leaning more in favour of source controlling all our deps.

**Comment by piranna** [comment]
What do you mean? Local copy of all deps on our repo?

2014-01-27 Alan K notifications@github.com

> I'm leaning more in favour of source controlling all our deps.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/js-platform/node-webrtc/issues/58#issuecomment-33399157
> .

## 

"Si quieres viajar alrededor del mundo y ser invitado a hablar en un monton
de sitios diferentes, simplemente escribe un sistema operativo Unix."
– Linus Tordvals, creador del sistema operativo Linux

**Comment by modeswitch** [comment]
Yeah, something like that. If we also have prebuilt binaries for common platforms then it won't be so bad.

**Comment by piranna** [comment]
+1, compiling times are really long, but I admit a huge part of this time
is downloading... We can check about having local copies of the code and
tools and if the time/size is still huge, go for prebuilt binaries.

2014-01-27 Alan K notifications@github.com

> Yeah, something like that. If we also have prebuilt binaries for common
> platforms then it won't be so bad.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/js-platform/node-webrtc/issues/58#issuecomment-33410773
> .

## 

"Si quieres viajar alrededor del mundo y ser invitado a hablar en un monton
de sitios diferentes, simplemente escribe un sistema operativo Unix."
– Linus Tordvals, creador del sistema operativo Linux

**Comment by mparisi76** [comment]
I just tried this again and it got a little further. 

npm install wrtc made it all the way to:

ninja_build
..................................................................................
ninja_build failed: 1 null

Anything I can do here to debug this?

Thanks.

**Comment by modeswitch** [comment]
In `third_party/libwebrtc`, run `ninja -C trunk/out/Release` and see what you get.

**Comment by mparisi76** [comment]
I had quite a long FAIL trace so I will post the very end of it: 

SyntaxError: invalid syntax
[3/2735] LIBTOOL-STATIC libtest.a, POSTBUILDS
FAILED: rm -f libtest.a && ./gyp-mac-tool filter-libtool libtool  -static -o libtest.a obj/webrtc/test/libtest/helpers/libtest.bit_flip_encryption.o obj/webrtc/test/libtest/helpers/libtest.random_encryption.o
  File "./gyp-mac-tool", line 507
    return {k: self._ExpandVariables(data[k], substitutions) for k in data}
                                                               ^
SyntaxError: invalid syntax
[3/2735] CC obj/third_party/opus/src/celt/opus.celt_encoder.o
ninja: build stopped: subcommand failed.
$ 

Let me know if you'd like the other info as well.

**Comment by mparisi76** [comment]
Not sure if this helps. It was in npm-debug.log

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/0.10.21/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'test' ]
2 info using npm@1.3.11
3 info using node@v0.10.21
4 error Error: ENOENT, open '/work/nextgen/studioGit/mp-studio/node_modules/wrtc/third_party/libwebrtc/package.json'
5 error If you need help, you may report this log at:
5 error     http://github.com/isaacs/npm/issues
5 error or email it to:
5 error     npm-@googlegroups.com
6 error System Darwin 10.8.0
7 error command "/usr/local/Cellar/node/0.10.21/bin/node" "/usr/local/bin/npm" "test"
8 error cwd /work/nextgen/studioGit/mp-studio/node_modules/wrtc/third_party/libwebrtc
9 error node -v v0.10.21
10 error npm -v 1.3.11
11 error path /work/nextgen/studioGit/mp-studio/node_modules/wrtc/third_party/libwebrtc/package.json
12 error code ENOENT
13 error errno 34
14 verbose exit [ 34, true ]

**Comment by modeswitch** [comment]
Closing. Please track build failures in #72 for now.
