### ISSUE TITLE
NodeJS 13 support missing at package.json

### ISSUE THREAD

**Issue by fjorgemota** [node-webrtc/node-webrtc#587]
Hey. First, thanks for the project! 

I saw at README and on [this commit](https://github.com/node-webrtc/node-webrtc/commit/d00b1013a2275b4f93d12d396cdf24b35ed85970) that this project *should*, at least in theory, support Node 13.

However, the [`package.json`](https://github.com/node-webrtc/node-webrtc/blob/1d62feb51bf3e44ebd79a715ab424f1e22b98552/package.json#L29) accepts only up to NodeJS 12. Could you please update the `package.json` with the correct information?

Thanks!

**Comment by markandrus** [comment]
Thanks for catching that! I’ll make sure to add it before completing the
next release.

**Comment by fjorgemota** [comment]
No problems!

I would love to help by sending a PR but unfortunately I was not even able to compile using the Build from Source tutorial on my Arch Linux installation..so..yeah.

Thanks again for the work on the project! :)

**Comment by markandrus** [comment]
This has been added in v0.4.3, just released a moment ago.

>  I was not even able to compile using the Build from Source tutorial on my Arch Linux installation..so..yeah.

Would like to be able to solve this one, maybe via some experimentation in a Dockerfile? Unfortunately, there are some things I don' have the time to dive into.

> Thanks again for the work on the project! :)

yw! :-)

**Comment by fjorgemota** [comment]
> Would like to be able to solve this one, maybe via some experimentation in a Dockerfile? Unfortunately, there are some things I don' have the time to dive into.

I think I can try to help with that!

I'll look into that problem soon.
