### ISSUE TITLE
Rollback is not supported

### ISSUE THREAD

**Issue by ghost** [node-webrtc/node-webrtc#589]
RTCSdpType "rollback" type is not supported by node-webrtc.

**Comment by markandrus** [comment]
Chrome 79, whose webrtc.org checkout current versions of node-webrtc are based on, doesn't either.

<img width="566" alt="Screen Shot 2020-01-11 at 11 55 26 AM" src="https://user-images.githubusercontent.com/359154/72203238-4ad67300-3469-11ea-9ee4-0a2db4efab86.png">

That being said, node-webrtc behaves slightly differently. For comparison:

<img width="409" alt="image" src="https://user-images.githubusercontent.com/359154/72203264-96891c80-3469-11ea-8971-a4d9492694f9.png">

Per WebRTC [Issue 980875: setRemoteDescription() with "rollback"](https://bugs.chromium.org/p/chromium/issues/detail?id=980875), it looks like some of the necessary functionality will be landing in M80, although it also looks like there are some bugs to shake out.

**Comment by markandrus** [comment]
I'm releasing this today as part of v0.4.5. We got this once we updated to M81.
