### ISSUE TITLE
v0.3.x prebuilt missing

### ISSUE THREAD

**Issue by remingtonc** [node-webrtc/node-webrtc#596]
Hi wrtc, I have some projects that depended on v0.3.5 of wrtc but node-pre-gyp isn't resolving them any more. v0.4.0+ seem to have prebuilts - any chance there are prebuilts living somewhere that simply aren't in the node-pre-gyp S3 bucket? Compilation from source is being painful, and the prebuilts are obviously very handy.

```
Searching for a pre-built wrtc binary
node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: 404 status code downloading tarball https://node-webrtc.s3.amazonaws.com/wrtc/v0.3.5/Release/node-v72-darwin-x64.tar.gz
```

**Comment by remingtonc** [comment]
Ah looks like it was due to nodejs version being recent - using nodejs 10 resolved the issue and prebuilt was found.

**Comment by kosso** [comment]
This issue is still present when using Node v10.20.1, 12.16.3 and 14.2.0 (latest).

`node-pre-gyp ERR! stack Error: 404 status code downloading tarball https://node-webrtc.s3.amazonaws.com/wrtc/v0.4.5-dev/Release/linux-x64.tar.gz`

**Comment by markandrus** [comment]
@kosso the URL you shared mentions `v0.4.5-dev`. We never release `-dev` suffixed releases, nor has `v0.4.5` currently been released. (You can see releases by running `npm view wrtc versions`.) You will only get a pre-built binary if you install a proper release, e.g., `npm install wrtc`. You seem to have a dependency on (or to be trying to install) the git repository.
