### ISSUE TITLE
Getting still-encoded data

### ISSUE THREAD

**Issue by toschlog** [node-webrtc/node-webrtc#600]
Is is possible to get the still-encoded data that's being sent over the PeerConnection?  I'm sending the data I recieve to a Murmur server that wants it Opus encoded.  I think the data is being sent over UPD with Opus encoding, so it seems a shame to have it decoded and then encoded again so I can send it to Murmur.

My code is like this:

  new RTCAudioSink(peerConnection.addTransceiver('audio').receiver.track).ondata = data => {
    //Opus encode data.samples
    //Create packet
    //Send to Murmur server
  }

I think my question is the same as https://github.com/node-webrtc/node-webrtc/issues/593 but I'm not sure.

Thanks!

**Comment by markandrus** [comment]
Yes, it’s the same. Closing in favor of #593
