### ISSUE TITLE
Multichannel opus / multiopus

### ISSUE THREAD

**Issue by ssharp2001** [node-webrtc/node-webrtc#603]
I've been able to get multichannel opus available in the SDP offer from an application using node-webrtc, my question is does the browser support multichannel audio with opus (considering a compatible audio output device exists)?  

The Chromium WebRTC code for builtin_audio_encoder_factory.cc creates a factory with an advertised AudioEncoderOpus and a NotAdvertised AudioEncoderMultiChannelOpus.  The builtin_audio_decoder_factory.cc has the same.

example from built_in_audio_encoder_factory:
return CreateAudioEncoderFactory<
   #if WEBRTC_USE_BUILTIN_OPUS
       AudioEncoderOpus, NotAdvertised<AudioEncoderMultiChannelOpus>,
   #endif

I've been able to create encoder and decoder factories for the backend of our app that removes the NotAdvertised and am now able to get an SDP offer with opus/48000/2, multiopus/48000/6 (5.1) and multiopus/48000/8 (7.1) from the server.  I have code that is multiplexing the channels into the AudioSource.

I am having issues with the browsers possibly supporting the multichannel audio.  Is there anyone in this forum that has successfully streamed multichannel opus with a WebRTC application using node-webrtc as a library in a node.JS application?  The application is streaming local files to the client using WebRTC PeerConnections using a source for video and source for audio.

Thanks in advance,

Scott

**Comment by markandrus** [comment]
Hi, this is a kind of a question about webrtc.org source code in general, rather than node-webrtc. I will close this issue. Maybe it could be discussed on discuss-webrtc or another forum instead.

**Comment by ssharp2001** [comment]
And update, I got back to working on it and was able to get 5.1 and 7.1 output channels in both Chrome and Edge.

**Comment by david511** [comment]
@ssharp2001 would you mind sharing how you got 5.1 and 7.1 output channels working in chrome?

**Comment by ssharp2001** [comment]
David,

Basically you need to munge the SDP for the offer and answer to force multiopus/48000/6 or multi opus/48000/8 with the following lines

offer.sdp = offer.sdp.replace("opus/48000/2","multiopus/48000/6").replace("useinbandfec=1", "channel_mapping=0,4,1,2,3,5; num_streams=4; coupled_streams=2;maxaveragebitrate=510000;minptime=10;useinbandfec=1");

offer.sdp = offer.sdp.replace("opus/48000/2","multiopus/48000/8").replace("useinbandfec=1", "channel_mapping=0,6,1,2,3,4,5,7;num_streams=8;coupled_streams=0;maxaveragebitrate=510000;minptime=10;useinbandfec=1");


You will then have to push data like in the example audio source.js.  

I can give you more details next week if you'd like to connect up.

**Comment by david511** [comment]
@ssharp2001 Thanks for the reply back, I would definitely like to talk further about this.

I have an audio stream with 8 channels over webrtc coming in and playing on an html audio element. I am creating a mediaStream object (https://developer.mozilla.org/en-US/docs/Web/API/MediaStream) from the incoming track. If I edit the SDP offer and answer with "multiopus/48000/8" will that prevent the mediaStream object from downmixing incoming 7.1 to stereo? I am struggling to figure out a way to access each individual audio channel in the browser.

Also do you have a link to the source.js example?

Any more details on this would be very much appreciated. Thank you!

**Comment by ssharp2001** [comment]
Yes, "multiopus/48000/8" will prevent the browser from down mixing 7.1 to 2 channels (stereo).

In the node-webrtc-example repo, there is a rtcaudiosourcesinewave.js file that will demonstrate how to encode the audio buffer.
