### ISSUE TITLE
Any way to mix audio streams to do a MCU server?

### ISSUE THREAD

**Issue by felicemarra** [node-webrtc/node-webrtc#607]
Hi, I'm trying to do a MCU server with nodejs. I'm able to mix video feeds but I have problems with audio because I receive all audio chunks from the peers and now I need to understand how I can mix it. I'm in pure node, not browser.. so I can't use node web audio api. 

I found a library "web-audio-engine" to have an audio context. 
https://www.npmjs.com/package/web-audio-engine

So I use "web-audio-stream" to make a stream with the chunks connectable to the audio engine. 
https://www.npmjs.com/package/web-audio-stream

the problem is... with webrtc I get 10ms of Int16 audio. web-audio-engine works in Float32 and it send me back 23ms of audio... so I need to have back 10ms Int 16.. how can I do it? 

I'm lost in audio translation ;)

**Comment by vaishnavnamboodirim** [comment]
Hi, did u find the solution to do that. I am also facing the same problem
