### ISSUE TITLE
Why maxListeners warning? 

### ISSUE THREAD

**Issue by savsofts** [node-webrtc/node-webrtc#622]
Application has only event event listener on server side 
broadcaster.emit('newBroadcast', {
    audioTrack,
    videoTrack
  });
But why i am getting maxiListners warning???

**Comment by markandrus** [comment]
AFAICT, you are referring to an example in the [node-webrtc-examples repository](https://github.com/node-webrtc/node-webrtc-examples). Please open issues for examples on that repository, not this one. As to why you are getting the warning, please check Node's documentation for `EventEmitter.defaultMaxListeners` [here](https://nodejs.org/api/events.html#events_eventemitter_defaultmaxlisteners). Probably you have more than 10 "viewers" in the example application, in which case you have 10 "newBroadcast" event listeners. The listeners are added [here](https://github.com/node-webrtc/node-webrtc-examples/blob/master/examples/viewer/server.js#L14) and removed [here](https://github.com/node-webrtc/node-webrtc-examples/blob/master/examples/viewer/server.js#L22).

If you want to raise the max listeners, the EventEmitter documentation has instructions how; however, I also don't recommend you use that example for any serious application, especially with more than 10 users. You won't get good performance, and should probably consider using a proper SFU or MCU instead.
