### ISSUE TITLE
node-webrtc with browser RTCPeerConnection [question]

### ISSUE THREAD

**Issue by florinmiu** [node-webrtc/node-webrtc#628]
Hello, 
I'd like to implement a node-webrtc app which serves basic audio to browser based RTCPeerConnection (for testing purposes). The offer starts from browser, the node-webrtc answer. Both peers have an audio transceiver attached. The audio source in the node-webrtc it's set from an example (taken fro here https://github.com/node-webrtc/node-webrtc/releases)
```
    const source = new RTCAudioSource();
    const track = source.createTrack();
    this.rtc.addTransceiver(track);
    const sink = new RTCAudioSink(track); 
    const sampleRate = 8000;
    const samples = new Int16Array(sampleRate / 100);  // 10 ms of 16-bit mono audio
    const data = {
      samples,
      sampleRate
    };
    
    const interval = setInterval(() => {
      // Update audioData in some way before sending.
      source.onData(data);
    });
    
    sink.ondata = data => {
      console.log('---')
      // Do something with the received audio samples.
      // never get here ...
    };
```
The connection is established ok, (there are also some data channels, which works ok) but I receive no audio in browser (the audio track from the audio transceiver receiver is muted). Also, I expect in the browser's rtc connection an 'ontrack' event, which never comes.
Any clues?

**Comment by markandrus** [comment]
If you haven't already, please try comparing to some of the audio examples in the [node-webrtc-examples](https://github.com/node-webrtc/node-webrtc-examples) repository.

**Comment by florinmiu** [comment]
I did, the sine wave example, which is closed to my situation, works ok. But there are some differences. In the browser I start the rtc using the browser rtc connection interface, with an audio transceiver attached to it, and this makes the offer. In the server I use the node rtc connection, with an audio transceiver also, which has an audio track on it (like in the code above) and after the rtc connection is established I expect the browser transceiver.receiver to receive the audio send by the server transceiver.sender. This does not happen. Is there any sample/test with a node rtc connection paired with a browser native rtc connection? On May 16, 2020 13:30, Mark Roberts <notifications@github.com> wrote:
If you haven't already, please try comparing to some of the audio examples in the node-webrtc-examples repository.

**Comment by markandrus** [comment]
You can also check the loopback example. It's establishing a connection between the browser and Node in order to retransmit the browser's audio and video back to itself.

**Comment by florinmiu** [comment]
I've managed to solve the problem. Instead:
```
    const source = new RTCAudioSource();
    const track = source.createTrack();
    this.rtc.addTransceiver(track);
```
I've used:
```
    const source = new RTCAudioSourceSineWave();
    const track = source.createTrack();
    const ms = new MediaStream(track);
    this.rtc.addTrack(track, ms);
```
This works ok for me. The MediaStream was needed because in the client (in browser) I need a stream to be connected to an audio element. Replacing addTransceiver with addTrack was the real trick, this way I receive in the client the rtc connection 'ontrack' event and attach the track's stream to the audio element (also I've used the sine wave generator to hear the audio).
Thanks for this great library, now I can test my app really nice.

**Comment by snnz** [comment]
addTrack uses stream's id only; it is not necessary to add a track to the stream on the sending side. You could also achieve the same with
 `this.rtc.addTransceiver(track, { streams: [ new Mediastream() ]});`

**Comment by piranna** [comment]
Not tested, but I think you don't need the stream at all, just only attach the track to a MediaStream in the receiver end. Streams are mostly like containers to ensure all tracks added to it are sync'ed. Since you are sending a single track, you don't need to sync it with anything else, just only wrap it in a MediaStream so it can be used with the `audio` tag in the browser.
