### ISSUE TITLE
Running test.js after building complains about missing symbols

### ISSUE THREAD

**Issue by wouldgo** [node-webrtc/node-webrtc#64]
Hi,
I planned to use your module inside my project (just for referece https://github.com/wouldgo/hubba).
After a successful building phase, as you suggest, I ran the test.js as sanity check and I got this error:

```
node node_modules/wrtc/examples/test.js 

/home/dario/git/hubba/node_modules/wrtc/node_modules/bindings/bindings.js:83
        throw e
              ^
Error: /home/dario/git/hubba/node_modules/wrtc/build/Release/webrtc.node: 
undefined symbol: CERT_CertificateTemplate
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at bindings (/home/dario/git/hubba/node_modules/wrtc/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/home/dario/git/hubba/node_modules/wrtc/lib/peerconnection.js:1:96)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

I looked for a reference to the c++ lib that defines the missing symbol (maybe I'm wrong but it seems a linker issue) and I didn't find anything.

Do you have any suggestion to resolve this issue?

Thanks.
Best Regards,

Dario.

**Comment by wouldgo** [comment]
Sorry for my github mobile incapacity (closing was a touching fault). I want to reply adding that I'm on Ubuntu Linux 12.04 LTS. :-)

**Comment by wouldgo** [comment]
I did some researches and it seems that `CERT_CertificateTemplate`, I'm not sure, is related to the libnss3 library.

Anyway I installed via apt-get that package but the error didn't disappear. I found some posts that state for symlinking the library into /usr/lib but also that option doesn't bring me any solution or change...

**Comment by modeswitch** [comment]
Missing symbols are due to latest upstream libjingle. I have a fix on my machine, but I need to fix data channels as well.

@piranna since this patch will also bring sctp data channels, I'm up for locking the sync revision to something reasonable.

**Comment by piranna** [comment]
That are good news to me, this way I could use it on my projects (webp2p.io)
and my work (kurento.org) :-) I can be able to test it for DataChannels.

Send from my Samsung Galaxy Note II

**Comment by wouldgo** [comment]
Hi again,

cloning the repo now and doing a manual build give me some results.

I saw https://github.com/js-platform/node-webrtc/blob/984deddf3bbf5f7ca872e026e9d9316d1949072b/binding.gyp#L136

Can be that linker option to node-gyp resolving te test.js fail?

**Comment by modeswitch** [comment]
No, that won't fix the problem. I pushed a patchset up yesterday that should fix any remaining linker problems, however I'm tracking down a potential bug in libjingle that's breaks data channels.

**Comment by modeswitch** [comment]
I think this is fixed now.

**Comment by wouldgo** [comment]
Yest the missing symbols was fixed with that line reported in my previous comment.
