### ISSUE TITLE
Question: One broadcaster and many viewers (broadcast/viewer example) video reencoding?

### ISSUE THREAD

**Issue by joeflateau** [node-webrtc/node-webrtc#640]
With a single broadcaster and many viewers, such as the broadcast/viewer example, is the video encoded once by the broadcaster and that bytestream forwarded on to all viewers? Or does node-webrtc decode that broadcast and encode it for each individual viewer?

**Comment by markandrus** [comment]
It encodes for each individual viewer. It's the same as using, e.g., Chrome. node-webrtc cannot be used to build an SFU.

**Comment by joeflateau** [comment]
Thank you @markandrus
