### ISSUE TITLE
All ice connection states set to failed after a few minutes of successful connections

### ISSUE THREAD

**Issue by juslesan** [node-webrtc/node-webrtc#643]
Hello,

I've ran into an issue where all local webRTC connections on a machine (tested on macOS, ubuntu 18) are set to failed if there are hundreds of local connections. The application logic is running with nodejs. I ran in to this issue after scaling up [network emulator](https://github.com/coreemu/core) performance testing. The same problem exists even after extracting the webRTC connection logic from the rest of the application code. More specifically this issue appears even without the presence of a network emulator when running the extracted logic locally. A repository with the application's extracted webRTC logic can be found [here](https://github.com/streamr-dev/extracted-webrtc).

In the extracted logic it's possible to launch as many nodes as possible by using the run.js script. The script first runs a signaller that is used to set up negotiated connections between nodes. The goal of the signaller is to set 4 webrtc connections between all nodes. Basically this means that there are 4 * n connections, where n is the amount of nodes. So for example by running 100 nodes there should be approximately 400 connections. Data channels are set up fo each connection and small chunks of data are pushed through the connections periodically.

Initially, when running 100 nodes all of the ~400 connections and dataChannels are established. Then for a few minutes the nodes send data through all of their data channels successfully. Then suddenly all of the ice connection states start to be changed and end up being set to failed.  The nodes run as separate processes so it is interesting that all of the connections fail. This problem cannot be fixed with reconnection logic as it leads to an infinite loop.

Is this behaviour expected if there are too many local webRTC peer connections? In the final product I may need a single computer to be able to run thousands of remote webRTC connections. Could this issue be related to the [application logic](extracted-webrtc) or could the issue be relation the connection limits of webRTC? My understanding is that the limitation for webrtc connections on a single machine (outside of browser) should be 65k. Is it possible that the connection limit of this library reassembles the browser limitations of ~256 or is it possible that the implementation does not support maintaining hundreds of webrtc connections on a single machine?

Thank you!

**Comment by juslesan** [comment]
As an update, I ran into the same issue with failing connections after deploying high amounts of nodes between two cloud based machines. In this experiment all connections were formed between the two machines. So the issue seems to be somehow related to the amount of webRTC PeerConnections on a single machine.

However, I have been able to run hundreds of stable connections on browser without any issues. So the problem seems to be related strictly to running the library in native environments. I would still need the ability to run hundreds of stable connections outside of browser so I'm looking forward to any insights!

Thanks!

**Comment by markandrus** [comment]
Hi @juslesan 

> My understanding is that the limitation for webrtc connections on a single machine (outside of browser) should be 65k.

Where do you get 65k from? Although I think that in some cases TCP candidates could be used, most of the time the ICE connection will use UDP. IIUC, the ~65k connection limit often mentioned between client and server applies to a single client with respect to a TCP server. I think the theoretical limit should be extremely high but would practically be limited by, e.g., performance. I can't claim this library or the underlying Chrome-/webrtc.org-based implementations could do so much.

> More specifically this issue appears even without the presence of a network emulator when running the extracted logic locally. A repository with the application's extracted webRTC logic can be found here.

Thanks very much for sharing a reproducible example. I've taken a look, but not yet run it myself.

> Initially, when running 100 nodes all of the ~400 connections and dataChannels are established. Then for a few minutes the nodes send data through all of their data channels successfully. Then suddenly all of the ice connection states start to be changed and end up being set to failed. The nodes run as separate processes so it is interesting that all of the connections fail.

Interesting. They're all running as separate processes, but on the same machine, right? Here's one hypothesis (not checked) based on something I think I remember seeing a long time ago: if you're running these processes on the same machine, could they be using up all the CPU and competing with each other's networking threads? WebRTC's ICE connections (excluding ice-lite implementations) perform "consent checks". That is, in the scenario you describe above, if indeed you have ~400 connections, there are at least ~800 consent requests (which in turn require responses) being performed every ~30 s. Maybe this is tolerable, IDK, but I seem to remember at least one case a long time ago where I saw an implementation fail to handle the ICE connectivity checks when the CPU was fully utilized. This could be verified by taking a packet capture and inspecting with Wireshark.

> As an update, I ran into the same issue with failing connections after deploying high amounts of nodes between two cloud based machines. In this experiment all connections were formed between the two machines. So the issue seems to be somehow related to the amount of webRTC PeerConnections on a single machine.

Interesting, I'm still curious about CPU usage on the individual machines.

> However, I have been able to run hundreds of stable connections on browser without any issues. So the problem seems to be related strictly to running the library in native environments. I would still need the ability to run hundreds of stable connections outside of browser so I'm looking forward to any insights!

I think that—if you're using Chrome, for example—the browser-based tests may be sharing a networking stack (and associated threads) that would normally be duplicated if you're launching multiple Node.js processes (and so I'm still curious about CPU utilization). I'm curious, too, if you'd get different results with a single Node.js process handling N connections (1 x N) versus N Node.js processes handling 1 connection each (N x 1).

Finally, I'd suggest potentially exploring other WebRTC libraries—like [pion](https://github.com/pion/webrtc), [aiortc](https://github.com/aiortc/aiortc), or [rawrtc](https://github.com/rawrtc/rawrtc)—as these libraries ought to be optimized for server to server usage. node-webrtc is just bindings to the Chrome/webrtc.org implementation of WebRTC, and so it implements ICE rather than ICE-lite. The former makes sense for browsers, clients, etc., but the latter may be more appropriate and more performant for your use case.

**Comment by markandrus** [comment]
I ran `node run.js --nodes 50` and after 5 minutes I still had no failed ICE connections. CPU looked OK (using `htop`):

<img width="927" alt="image" src="https://user-images.githubusercontent.com/359154/87881141-901ac500-c9f7-11ea-8a44-d6dca25fc025.png">

With 100 nodes, still no failures after 5 minutes:

<img width="950" alt="image" src="https://user-images.githubusercontent.com/359154/87881251-5eeec480-c9f8-11ea-8a99-377979fe2464.png">

Going big, with 400 nodes. Still no failures after 5 minutes, although CPU is getting high and my system is not very responsive:

<img width="953" alt="image" src="https://user-images.githubusercontent.com/359154/87881544-3bc51480-c9fa-11ea-83fb-2ea1bb215b7a.png">

I don't want to push it too much further on my end, but maybe you could share some more about, e.g. CPU and maybe do a packet capture?

**Comment by juslesan** [comment]
Hi @markandrus !

> I ran node run.js --nodes 50 and after 5 minutes I still had no failed ICE connections. CPU looked OK (using htop):

Did you check the logs for failed states after any of these runs? The processes do not actually crash as the connection states are set to failed so you wouldn't see this by monitoring htop. There is also some noicy metrics logging going on which I disabled now for clarity. I updated the repository to allow clearer and more reliable centralised logging by running:

```node run.js --nodes 256 --log-to-file true```

The logs are written to a node.log file by default and you can then easily find the failed states with (this should not be needed as the failed states or other errors should remain at the bottom of the log file):

```cat node.log | grep failed```

> I don't want to push it too much further on my end, but maybe you could share some more about, e.g. CPU

Here's a snapshot of a 256 node run in htop:

<img width="1221" alt="Screenshot 2020-07-20 at 17 47 28" src="https://user-images.githubusercontent.com/17498529/87951339-1ba45c80-cab1-11ea-8581-cc38fcc35153.png">

The cpu usage seems reasonable but the load average is quite high, so there definitely would be some thread blocking going on. The load average clearly spikes in 30 second intervals also. However, with 128 nodes the load average seems more reasonable and yet the connections still fail with local runs on Ubuntu 18. Although, it takes around 3 times longer than with 256 nodes, even 32 nodes fail after a sufficient amount of time:

<img width="1221" alt="Screenshot 2020-07-20 at 17 52 55" src="https://user-images.githubusercontent.com/17498529/87952215-3d521380-cab2-11ea-89ce-7e52850da4c5.png">


> Interesting. They're all running as separate processes, but on the same machine, right? Here's one hypothesis (not checked) based on something I think I remember seeing a long time ago: if you're running these processes on the same machine, could they be using up all the CPU and competing with each other's networking threads? WebRTC's ICE connections (excluding ice-lite implementations) perform "consent checks". That is, in the scenario you describe above, if indeed you have ~400 connections, there are at least ~800 consent requests (which in turn require responses) being performed every ~30 s. Maybe this is tolerable, IDK, but I seem to remember at least one case a long time ago where I saw an implementation fail to handle the ICE connectivity checks when the CPU was fully utilized. This could be verified by taking a packet capture and inspecting with Wireshark.

I created a version where a single process runs all of the peer connections between two machines. With this version I was able to run 256 connections for ~20 minutes until the connections failed. Running more than this is a bit difficult due to the single threaded nature of Nodejs. I'll attempt to run 100 connections over night as it seems to have a very low cpu usage compared to 256. I'll report back with the results tomorrow. The code for this experiment can be found [here](https://github.com/streamr-dev/extracted-webrtc/tree/two_machine_single_process/dual_machine). 

I haven't ran packet capturing yet but I'll get to it ASAP and update with any results.

Thanks for the response!!

**Comment by juslesan** [comment]
I finished the experiments with the single process version between two machines. It seems that the connections were still failing even when running 32 connections. There was not much cpu being used during the <100 connection experiments so I would expect that this rules out concerns about cpu.

I also generated some log files that should further clarify the issue. There is a log file for a 200 process, 800 connection, single machine run + a log file of one machine from a 256 connection dual machine experiment including a Wireshark packet capture file. In both of these runs the connections were set to failed suddenly after succesful connections and data channels were created. The connection states being set to failed can be seen at the tails of the log files. 

I haven't analysed the packet capture much myself but it seems clear that the STUN protocol traffic stops as the connections are set to failed. The log files can be found [here](https://github.com/streamr-dev/extracted-webrtc/tree/master/logs).

Hopefully this information helps with the issue on your end!

Thanks

**Comment by juslesan** [comment]
Hello,

After doing some experimentation with Nodejs 14 it turns out that the issue seems to be fixed by upgrading to it on Ubuntu 18. It seems that the issue is mainly present on ubuntu 18 with Nodejs 10 and 12, as I was not able to reproduce the problem with Ubuntu 20. Nodejs 14 also seems to significantly improve the performance with MacOS.
