### ISSUE TITLE
Issue : No audio send Opus samples from FFmpeg to RTCAudioSource 

### ISSUE THREAD

**Issue by RealAlphabet** [node-webrtc/node-webrtc#647]
Hi,

I use the `fluent-ffmpeg` library in native mode to send encoded mp3 files as an opus stream to peers.

The documentation of `RTCAudioSource` is a little vague regarding the sending of samples. So I tried to do as I thought.

I'm receiving a MediaStreamTrack with `pc.ontrack` as well as audio data according to `chrome://webrtc-internals`. Unfortunately, no sound is playing.

    const { RTCAudioSource } = require('wrtc').nonstandard;

    const source = new RTCAudioSource();
    const track = source.createTrack();

    // When a client connect ...

    peerConnection.addTransceiver(track, {
        direction: 'sendonly'
    });

    // Play stream

    ffmpeg(`database/${song.src}`)
        .format('opus')
        .audioCodec('libopus')
        .addOutputOption('-page_duration 10000')
        .audioChannels(2)
        .audioFrequency(48000)
        .native()
        .pipe()
        .on('end', resolve)
        .on('data', ({ buffer }) => {
            let samples = new Uint8Array(1920);
            samples.set(new Uint8Array(buffer));

            source.onData({
                samples,
                sampleRate: 48000,
                bitsPerSample: 16,
                channelCount: 2,
                numberOfFrames: 48000 / 100
            });
        });

Also, I haven't found a way to debug a webrtc audio stream. If you know how, I'm interested.
Thanks in advance for your help !

**Comment by markandrus** [comment]
Hi @OnceDot,

> Unfortunately, no sound is playing.

This could mean many things: the code to play the resulting MediaStream client-side might be incorrect; the ICE connection between the client and the server might not be connected; the actual audio you're transmitting could be incorrect. Can you please try to narrow the issue down? A first step might be to validate that the [node-webrtc-examples](https://github.com/node-webrtc/node-webrtc-examples) project works for you. Then, you could try extending, e.g., the sine wave example (or a similar example) to use your `ffmpeg` integration. Keep in mind, RTCAudioSource expects the "raw" (un-encoded) audio samples.  I don't know the `ffmpeg` APIs you're using above, but if the "data" callback you're getting is giving you Opus-encoded audio data, it will not work.

**Comment by RealAlphabet** [comment]
Thanks for your reply,

Indeed, it came from my misunderstanding of WebRTC. I didn't know it handled encoding but it makes sense now when I think about SDP.

For those who have the problem. **There is a bug on Chromium, the stream must be attached to the `srcObject` property of an audio tag, even if the tag isn't in the dom and was created with createElement. Otherwise, no sound will be produced.**

    webrtc(this.ws).then(({ connection, stream }) => {
        let audio = document.createElement('audio');
        audio.srcObject = stream;

        this.connection = connection;
        this.context = new AudioContext();

        this.gainNode = this.context.createGain();
        this.gainNode.connect(this.context.destination);
        this.gainNode.gain.value = 1;

        this.analyser = this.context.createAnalyser();
        this.analyser.connect(this.gainNode);
        this.analyser.minDecibels = -80;

        this.source = this.context.createMediaStreamSource(stream);
        this.source.connect(this.analyser);
    }).catch(console.error);

This fixed the blank sound problem. Now, I heard noise and it came from the fact that I encoded the opus stream myself. **WebRTC already takes care of encoding the audio stream for you**. 

This problem made me realize that you don't need to debug the sound. If you don't hear anything despite everything is well connected and you receive data, it is inevitably that the problem comes from the client side.

    let buffer = new Uint8Array(48000);
    let bufferIndex = 0;

    ffmpeg(`database/${song.src}`)
        .format('s16le')
        .audioCodec('pcm_s16le')
        .addOutputOption('-page_duration 1')
        .audioChannels(2)
        .audioFrequency(48000)
        .native()
        .pipe()
        .on('end', resolve)
        .on('data', e => {
            let data = new Uint8Array(e);

            buffer.set(data, bufferIndex);
            bufferIndex += data.length;

            while (bufferIndex >= 1920) {
                source.onData({
                    samples,
                    sampleRate: 48000,
                    bitsPerSample: 16,
                    channelCount: 2,
                    numberOfFrames: 48000 / 100
                });

                buffer.set(buffer.slice(1920));
                bufferIndex -= 1920;
            }
        });

Actually everything works except when a second client joins the stream. At this time, the first client no longer receives data. If the first client reconnect, the second client no longer receives data etc..

I hovered over the code of the chromium WebRTC library and haven't found the problem yet. But, if I use one AudioSource for each client the problem doesn't arise.

I would like to use only one Audio Source to encode the sound only once and send it to all other clients. That make sense especially if you plan to broadcast the same audio stream.

I tried from the browser and it's indeed possible to share a single audio stream for several peer connections. Maybe it come from the `RTCAudioSource::OnData` function. Do you have any idea ?

**Comment by guest271314** [comment]
Am working on similar projects, e.g., https://github.com/w3c/webrtc-pc/issues/2570. 

Also encountered the Chromium bug relevant to `MediaStream` needing to be attached to an `HTMLMediaElement` https://bugs.chromium.org/p/chromium/issues/detail?id=952700.

Does the ```ffmpeg(`database/${song.src}`)``` work when the source is a PulseAudio device, for example `alsa_output.pci-0000_00_1b.0.analog-stereo.monitor`?

**Comment by abardik** [comment]
Any updates on audio multicast? I have the same problem with a single AudioSource for more than one PeerConnection. VideoSource works fine, I can send it to multiple peers at the same time.

**Comment by denysloshkarev** [comment]
Yep, I see the same issue with the multicast of one AudioSource. It always work properly on last connected PeerConnection.

@markandrus Could you a little explain it? Or put the link to any docs that could explain it?

**Comment by RealAlphabet** [comment]
> Yep, I see the same issue with the multicast of one AudioSource. It always work properly on last connected PeerConnection.
> 
> @markandrus Could you a little explain it? Or put the link to any docs that could explain it?

**Need to be checked in the WebRTC code**

It seems that a source is re-encoded for each participant, separately, because SDP defines for each separate connection the codecs and quality to be used.

@abardik can you try to connect multiple clients to your video server and monitor CPU usage please ?
If the CPU usage is still the same, it is most likely a library issue.

**Comment by abardik** [comment]
@RealAlphabet When I send local microphone or speakers, it seems like every client adds around 0.5% of CPU usage to my stream server. I didn't try a lot of them, but 5 clients at a time. The same with local webcam - up to +1% per client. But when I send a remote desktop, it takes around 50% for the first client, then 75% for the second, and finally 100% after the third client is connected. So, yes, it seems like every client takes additional resources from media server to separately encode a stream. Moreover, I use fmedia instead of ffmpeg for audio sources, and the topic issue exists too for this media library - after next client is connected all existing clients have no audio anymore. There are no issues (except of 100% CPU usage for remote desktop) for video streams which are going from ffmpeg.

**Comment by RealAlphabet** [comment]
Sorry i'm late, thanks for your answer @abardik.

**This appears to be an intended behavior of WebRTC, one unique encoding and decoding context per peer.**

It would be a great feature to be able to share an encoding context with multiple clients based on the same SDP audio / video settings to save resources.

**I will mark the issue closed since the problem is not coming from the librairie itself.**

I will try to play with WebRTC to see if it is still possible to share an encoding context between two peers. If I manage to do it, I will send a pull request.

Thanks for your time and contribution !
