### ISSUE TITLE
DataChannel.send performance issues

### ISSUE THREAD

**Issue by hughp-abq** [node-webrtc/node-webrtc#648]
I have found that sending messages via data channels is taking quite a long time - is there something I'm doing wrong here?

For an RTCPeerConnection, calling datachannel.send() function takes approximately 0,2ms (200-300 microseconds) of blocking execution time for each call.

This achieves a maximum throughput of around 4000 sends per second, with any payload of message (tested from a short string to 2056 bytes of array buffer)

For comparison purposes, the golang webrtc implementation 'pion' achieves more like 90000 messages per second for exactly the same function (create a RTCPeerConnection, create a data channel, and send messages via that channel).

The chrome profiler shows that a majority of the execution time is spent on 'RTCVideoSource' which is strange since I have not added any video tracks to the RTCPeerConnection. As the package uses C++ addons, I am unable to analyze this performance further to find out what is causing this performance issue.

The below screenshot shows the time it takes to send messages to 100 peers (the peers.forEach loops through an array of RTCPeerConnections and simply calls peer.dataChanel.send('This is a message'). Even with 1 peer, the send() function seems to take around the same amount of time (+/- maybe 50%)

Note: I am running my script in a node v10 environment and using the --inspect option when running the node command. The performance is the same with node v12.16.3.

![image](https://user-images.githubusercontent.com/63043915/87862375-3a86df80-c947-11ea-9e97-4dac5d188055.png)

Source code used for this test
Also, I have tried implementations with the client in a separate process to the server, to eliminate the factor of having to load the client and server peers in one process - but it makes no difference.

```
const wrtc = require('wrtc');

class ServerPeer {
  constructor() {
    this.pc = new wrtc.RTCPeerConnection({
      iceServers: [],
    })
    this.client = new Client((candidate) => {
      this.pc.addIceCandidate(candidate);
    }, (answer) => {
      this.pc.setRemoteDescription(answer);
    });
    this.dataChannel = this.pc.createDataChannel('data', {
      ordered: false,
      maxRetransmits: 0,
    });

    this.channelOpen = false;

    this.dataChannel.onopen = (event) => {
      console.log(event);
      this.channelOpen = true;
    }
  }

  async makeOffer() {
    const offer = await this.pc.createOffer();
    this.pc.setLocalDescription(offer);
    this.client.onOffer(offer);
    this.pc.onicecandidate = (event) => {
      if (event.candidate) {
        this.client.onCandidate(event.candidate);
      }
    }
  }

  async waitForDataChannel() {
    if (!this.channelOpen) {
      await new Promise(res => setTimeout(res, 100));
      return await this.waitForDataChannel();
    }
  }
}


class Client {
  constructor(onIceCandidate, onAnswer) {
    this.onIceCandidateCb = onIceCandidate;
    this.dataChannelOpen = false;
    this.waitForDataChannel = this.waitForDataChannel.bind(this)
    this.onOffer = this.onOffer.bind(this);
    this.pc = new wrtc.RTCPeerConnection({
      iceServers: [],
    });
    this.pc.onicecandidate = (event) => {
      if (event.candidate) {
        this.onIceCandidateCb(event.candidate);
      } else {
        console.log('all candidates received');
      }
    }
    this.onAnswer = onAnswer;
  }

  async onOffer(offer) {
    const self = this;
    this.pc.ondatachannel = event => {
      console.log('Data channel is created!');
      event.channel.onopen = function () {
        console.log('Data channel is open and ready to be used.');
        self.dataChannelOpen = true;
        console.log(self.dataChannelOpen);
        event.channel.onmessage = (event) => {
          // console.log('got event', event);
        }
      };
    };
    this.pc.onconnectionstatechange = event => {
      console.log('Connection state:', this.pc.connectionState);
    }
    this.pc.setRemoteDescription(offer);
    const answer = await this.pc.createAnswer();
    await this.pc.setLocalDescription(answer);
    this.onAnswer(answer);
  }

  async onCandidate(candidate) {
    await this.pc.addIceCandidate(candidate);
  }

  async waitForDataChannel() {
    if (!this.dataChannelOpen) {
      await new Promise(res => setTimeout(res, 100));
      return await this.waitForDataChannel();
    }
  }
}

async function test() {
  const peers = [];
  for (let i = 0; i < 100; i++) {
    const server = new ServerPeer();

    await server.makeOffer();

    await server.waitForDataChannel();

    peers.push(server);
  }

  let sentCount = 0;


  setInterval(() => {
    console.log('Amount sent', sentCount);
    sentCount = 0;
  }, 1000);

  function sendMessages() {
    peers.forEach(peer => {
      peer.dataChannel.send('This is a message!');
      ++sentCount;
    })
    setImmediate(sendMessages)
  }

  sendMessages();
}

test();

```

**Comment by markandrus** [comment]
Hi @hughp-abq,

> For comparison purposes, the golang webrtc implementation 'pion' achieves more like 90000 messages per second for exactly the same function (create a RTCPeerConnection, create a data channel, and send messages via that channel).

Can you please compare to Chrome/Chromium? node-webrtc is just a wrapper around Chrome/Chromium's implementation, whereas pion is its own implementation. I would be curious to know if we introduce significant latency on top of what Chrome/Chromium itself.

> The chrome profiler shows that a majority of the execution time is spent on 'RTCVideoSource' which is strange since I have not added any video tracks to the RTCPeerConnection. 

That is indeed strange. I would expect it to be a bug in the profiling?

**Comment by hughp-abq** [comment]
> Hi @hughp-abq,
> 
> Can you please compare to Chrome/Chromium? node-webrtc is just a wrapper around Chrome/Chromium's implementation, whereas pion is its own implementation. I would be curious to know if we introduce significant latency on top of what Chrome/Chromium itself.
> 

@markandrus Thanks for the reply, I didn't actually know this project used the chrome implentation underneath. I tried out the same code in the browser (except using chrome's RTCPeerConnection instead of wrtc, and using setTimeout instead of setImmediate) and got about the same results, which indicates that the performance is limited by chrome's implementation. Also, the 'RTCVideoSource' function shown in the screnshot does not appear when profiling in chrome.

Therefore this isn't an issue with the package itself, but more an issue for chrome, so I will close this issue as I don't think it is actionable at this point in time.

On a side note, I would imagine that chrome's implenentation is not really designed for sending more than 6000 messages a second, as that would be very strange use case inside a browser. However, if you were to use this package for server-side mass broadcasting messages (e.g. for multiplayer games or realtime collaborative apps), it falls a bit short in performance.

It could be intresting to experiment with multiple worker threads to see how much that would increase throughput on a server, but my initial guess is that the cpu load wouldn't be worth it compared to using a different implementation, for example in golang.
