### ISSUE TITLE
how can I get Video Stream from remote with RTCVideoSink?

### ISSUE THREAD

**Issue by HyperClockUp** [node-webrtc/node-webrtc#655]
As example code shows, I use addTrack like:
`stream.getTracks().forEach(track => {
        this.RTCPeerConnection.addTrack(track, stream);
 })`

And in server side, i can send text by ondatachannel, and the connectState shows that server connect to front end successfully, but when I use RTCVideoSink as:
`
const videoTransceiver = RTCServer.addTransceiver('video');
const videoSink = new RTCVideoSink(videoTransceiver.receiver.track);
videoSink.addEventListener("frame",()=>{
    console.log("I got frame msg');
})
`
but nothing happened.

btw, i create an instance PeerConnection at the time when server start firstly, and then I do addTransceiver and new RTCVideoSink, will my creating server instance( RTCVideoSink ) before my addTrack in front-end make the promblem?
plz help, thank you!!

**Comment by markandrus** [comment]
Sorry, I do not know what's wrong with your setup. I recommend you try the [video-compositing-example](https://github.com/node-webrtc/node-webrtc-examples/tree/master/examples/video-compositing) in node-webrtc-examples. It should show the feature working. Perhaps you can use that as a starting point.

> btw, i create an instance PeerConnection at the time when server start firstly, and then I do addTransceiver and new RTCVideoSink, will my creating server instance( RTCVideoSink ) before my addTrack in front-end make the promblem?

No, it shouldn't. You `addTransceiver` at the server, this gives you a receiver object with a remote MediaStreamTrack on it. You can do whatever you like with that. If the front-end starts sending you video over that receiver, you will receive frames.
