### ISSUE TITLE
service hang every 20 connections

### ISSUE THREAD

**Issue by rootSectornet** [node-webrtc/node-webrtc#657]
i  create video conference , and i use this project for help routing all stream from each client. but every server have 18 more connection my service always hang dan every connection will diconnected.

i don't know what is wrong in my code

[this my code repository](https://github.com/rootSectornet/video_conference.git
)

I would love if you could tell me what was wrong

**Comment by rootSectornet** [comment]
@janza @arlolra @substack @cjb  i need your help please

**Comment by markandrus** [comment]
Sorry, @rootSectornet — I cannot provide support for individual projects in the GitHub issue tracker.
