### ISSUE TITLE
Support for node15

### ISSUE THREAD

**Issue by mullerivan** [node-webrtc/node-webrtc#658]
any chance to use this module with node 15?
 **npm i on simple-peer**
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'wrtc@0.4.6',
npm WARN EBADENGINE   required: {
npm WARN EBADENGINE     node: '^8.11.2 || ^10.0.0 || ^11.0.0 || ^12.0.0 || ^13.0.0 || ^14.0.0'
npm WARN EBADENGINE   },
npm WARN EBADENGINE   current: { node: 'v15.0.1', npm: '7.0.3' }
npm WARN EBADENGINE }
npm ERR! code 1
npm ERR! path /root/simple-peer/node_modules/wrtc
npm ERR! command failed
npm ERR! command sh -c node scripts/download-prebuilt.js
npm ERR! /bin/sh: 1: node-pre-gyp: not found

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-10-27T18_54_18_808Z-debug.log

**cat  /root/.npm/_logs/2020-10-27T18_54_18_808Z-debug.log**
2909 info run fsevents@1.2.13 install node_modules/fsevents node install.js
2910 info run wrtc@0.4.6 install node_modules/wrtc node scripts/download-prebuilt.js
2911 info run fsevents@1.2.13 install { code: 0, signal: null }
2912 timing build:run:install:node_modules/fsevents Completed in 44ms
2913 info run wrtc@0.4.6 install { code: 1, signal: null }
2914 timing reify:rollback:createSparse Completed in 0ms
2915 timing reify:rollback:retireShallow Completed in 0ms
2916 timing command:install Completed in 15229ms
2917 verbose stack Error: command failed
2917 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:63:27)
2917 verbose stack     at ChildProcess.emit (node:events:327:20)
2917 verbose stack     at maybeClose (node:internal/child_process:1048:16)
2917 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:288:5)
2918 verbose pkgid wrtc@0.4.6
2919 verbose cwd /root/swarm/simple-peer2
2920 verbose Linux 4.19.0-12-amd64
2921 verbose argv "/usr/bin/node" "/usr/bin/npm" "i"
2922 verbose node v15.0.1
2923 verbose npm  v7.0.3
2924 error code 1
2925 error path /root/swarm/simple-peer2/node_modules/wrtc
2926 error command failed
2927 error command sh -c node scripts/download-prebuilt.js
2928 error /bin/sh: 1: node-pre-gyp: not found
2929 verbose exit 1

**Comment by markandrus** [comment]
Yes, I believe we just need to update the engines property in package.json. There shouldn't be any reason we can't run in Node 15, since we target N-API.

**Comment by mullerivan** [comment]
Thanks for your time! and for this nice project  :+1:

**Comment by mullerivan** [comment]
any chance to include this on the last  version?

**Comment by lephleg** [comment]
That would be great indeed

**Comment by piranna** [comment]
I've create #675 so we can make it future prove. Can we get this merged and published?

**Comment by markandrus** [comment]
FYI, I just shipped wrtc@0.4.7 with @piranna's PR to change `engines` to a range. This means, installing wrtc for Node 15 shouldn't complain about `engines`; however, I believe there may be a bug in NPM 7 — installing wrtc depends on an install script having access to a dependency, node-pre-gyp. When I did a test install of wrtc@0.4.7 using Node 15 and NPM 7, the install failed because the install script didn't have access to node-pre-gyp. So I think there's still additional work, either in the form of a workaround for wrtc or a bug fix for NPM (if indeed this is an NPM bug). I do not have time to look closely myself in the coming weeks.

**Comment by piranna** [comment]
What versions of Node.js and npm are you using? I remember seeing something similar, but with latests ones it was fixed, maybe can you try with `npm install -g npm`? :-)

**Comment by markandrus** [comment]
@piranna do you have a version which is working? here is what i tried. doesn't seem to work with npm@7.3.0:

```
$ node -v
v15.5.1

$ npm -v
7.3.0

$ npm install
npm ERR! code 1
npm ERR! path /private/tmp/test/node_modules/wrtc
npm ERR! command failed
npm ERR! command sh -c node scripts/download-prebuilt.js
npm ERR! /bin/sh: node-pre-gyp: command not found

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mroberts/.npm/_logs/2021-01-11T10_26_35_081Z-debug.log
```

```
$ cat package.json 
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "wrtc": "0.4.7"
  }
}
```

**Comment by piranna** [comment]
Same versions as you, but not using it as a dependency, but instead running `npm install` in node-webrtc project and later using a simbolic link in `node_modules` pointing to it. Maybe you are right that's a npm bug... We could be sure about that by moving back to Node.js 14 and upgrading npm alone.

**Comment by piranna** [comment]
I've been able to install `node-webrtc` with latest Node.js 15.6.0, that includes npm 7.4.0. I think it could be related to [the upgrade of `node-gyp` to 7.1.2](https://github.com/npm/cli/commit/5d9df83958d3d5e6d8acad2ebabfbe5f3fd23c13), or something similar.

We can close this issue.

**Comment by piranna** [comment]
Another option would be to update the `engines` Node.js range to `^10 && <15 || ^15.6`...

**Comment by DePasqualeOrg** [comment]
I'm getting an error when I try to install this package:

```
npm ERR! command failed
npm ERR! command sh -c node scripts/download-prebuilt.js
npm ERR! /bin/sh: node-pre-gyp: command not found
```

How can I solve this?

**Comment by dmaretskyi** [comment]
For PNPM i was able to make it install with this hook:
```javascript
function readPackage(packageJson, context) {

  if (packageJson.name === 'wrtc') {
    delete packageJson.dependencies['node-pre-gyp']
    packageJson.dependencies['@mapbox/node-pre-gyp'] = "1.0.3"
  }

  return packageJson;
}
```

**Comment by DePasqualeOrg** [comment]
Thanks, I was able to get it to work by first manually installing `node-pre-gyp` and then uninstalling it after `node-webrtc` installed.

**Comment by danieltanfh95** [comment]
> Thanks, I was able to get it work work by first manually installing `node-pre-gyp` and then uninstalling it after `node-webrtc` installed.

same for node 16

**Comment by duvallj** [comment]
See https://github.com/node-webrtc/node-webrtc/pull/765
