### ISSUE TITLE
Working stun only between two browsers, doesn't work with node-webrtc except with turn

### ISSUE THREAD

**Issue by TheGJ** [node-webrtc/node-webrtc#664]
Hi,

Sorry for the title, I don't know how to name it. First, thanks your for the package!

However I run into an issue. I try to code a simple ping pong example from scratch, without this package, from two différent IPs and two browers (Chrome), just with a stun server, and it was working at 6ms for a round trip. Which amazed me by the way.

I try to make the same code, same two machines, same stun, with one of the client using this repo, with nodejs, can't make it work. But it does if you add a turn server (resulting in a ping around 22ms).

Any ideas why the same code, same machines, doesn't work without turn server on nodejs but with Chrome it runs smoothly just with a stun? Is there any port I need to open to let nodejs use udp port? Seems weird to me that Chrome has more permissions than nodejs. I'm using Win10.

Thanks for the help!

**Comment by benoitmercusot** [comment]
Hi TheGJ,

not related to your issue (sorry) but i can't figure out how / where to add a stun server in the exemples scripts :/
All my tests are then working only locally. I hope you can help me :)

Benoit

**Comment by markandrus** [comment]
Sorry, I cannot help troubleshoot such issues.
