### ISSUE TITLE
Tape tests help

### ISSUE THREAD

**Issue by wouldgo** [node-webrtc/node-webrtc#67]
Hi again,

I forked this repository yesterday to rewrite the building/cleaning scripts and to introduce grunt in the development (as reported in issue #56).

The building script seems good but, when I introduced tape in the default task, it complains for 5/6 failures (I don't understand why sometimes 5 and sometimes 6).
I can't really understand where they came out from (probably I'm too fool for tape testing suite).

Since my aim is a pull request for these functionalities, but some tests are failed, could you please help me to understand the meaning of this output?
![grunt-with-tape](https://f.cloud.github.com/assets/1098882/2120675/936ba160-91bf-11e3-8db9-97870fd2f558.png)
This is the [Gruntfile.js](https://github.com/wouldgo/node-webrtc/blob/develop/Gruntfile.js) (the funny thing is that grunt wrote down _"Done, without erorrs"_  :cake: ).

Thanks,
Dario.

**Comment by piranna** [comment]
You can make the pull-request and update it later, this way we can help you with your progress. Unluckily gclient sync always fails to me, so I couldn't be able to check it :-/ If you have random error they could be due to race conditions due to async operations. Regarding to grunt, it says everything is alright because you didn't told him there was an error, put anything as parameter of the grunt.done() function on the tape testing task.

**Comment by modeswitch** [comment]
@wouldgo Yeah, please make a pull request and I can help you out in there.

@piranna What sync errors are you still having?

**Comment by piranna** [comment]
@modeswitch from a git update copy and after removing the third_party folder this is what I get on the console on several consecutives executions of `npm install`:

```
[piranna@Latitude:~/Dropbox/Proyectos/node-webrtc]
 > npm install

> wrtc@0.0.9 install /home/piranna/Dropbox/Proyectos/node-webrtc
> node bin/build.js

depot_tools
.depot_tools not required
gclient_config
.
gclient_config complete
gclient_sync
...............................................................................................................................................................................................................
gclient_sync failed: 1 null

[piranna@Latitude:~/Dropbox/Proyectos/node-webrtc]
 > npm install

> wrtc@0.0.9 install /home/piranna/Dropbox/Proyectos/node-webrtc
> node bin/build.js

depot_tools
.depot_tools not required
gclient_config
.
gclient_config complete
gclient_sync
.................................................................................
gclient_sync failed: 1 null

[piranna@Latitude:~/Dropbox/Proyectos/node-webrtc]
 > npm install

> wrtc@0.0.9 install /home/piranna/Dropbox/Proyectos/node-webrtc
> node bin/build.js

depot_tools
.depot_tools not required
gclient_config
.
gclient_config complete
gclient_sync
....
gclient_sync complete
gclient_runhooks
....
gclient_runhooks failed: 1 null
```

**Comment by modeswitch** [comment]
@piranna I moved your issue to #72. Let's track all the build failures there.

**Comment by modeswitch** [comment]
This is done now.
