### ISSUE TITLE
Dependency node-pre-gyp is deprecated, @mapbox/node-pre-gyp should be used instead

### ISSUE THREAD

**Issue by greatest-ape** [node-webrtc/node-webrtc#682]
https://www.npmjs.com/package/node-pre-gyp : "Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future"

https://github.com/mapbox/node-pre-gyp#readme : On Feb 9th, 2021 @mapbox/node-pre-gyp@1.0.0 was released. Older, unscoped versions that are not part of the @mapbox org are deprecated and only @mapbox/node-pre-gyp will see updates going forward.

**Comment by Unknow1002** [comment]
Please use:
` 
npm uninstall node-pre-gyp --save
npm install @mapbox/node-pre-gyp --save
`
To upgrade your version, for more information, please go to:
https://github.com/mapbox/node-pre-gyp

**Comment by Unknow1002** [comment]
> https://www.npmjs.com/package/node-pre-gyp : "Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future"
> 
> https://github.com/mapbox/node-pre-gyp#readme : On Feb 9th, 2021 @mapbox/node-pre-gyp@1.0.0 was released. Older, unscoped versions that are not part of the @mapbox org are deprecated and only @mapbox/node-pre-gyp will see updates going forward.

Please use these command to update your version of node-pre-gyp to receive updates otherwise you can't receive updates as you didn't update your version to latest version

Command:
`
npm uninstall node-pre-gyp --save
`
`
npm install @mapbox/node-pre-gyp --save
`

For more information, please go to:
[https://github.com/mapbox/node-pre-gyp](url)

**Comment by greatest-ape** [comment]
Yeah, but that is a change that should be done in this repo, not by everybody using it.

**Comment by thesacredcoder** [comment]
> > https://www.npmjs.com/package/node-pre-gyp : "Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future"
> > https://github.com/mapbox/node-pre-gyp#readme : On Feb 9th, 2021 @mapbox/node-pre-gyp@1.0.0 was released. Older, unscoped versions that are not part of the @mapbox org are deprecated and only @mapbox/node-pre-gyp will see updates going forward.
> 
> Please use these command to update your version of node-pre-gyp to receive updates otherwise you can't receive updates as you didn't update your version to latest version
> 
> Command:
> `npm uninstall node-pre-gyp --save`
> `npm install @mapbox/node-pre-gyp --save`
> 
> For more information, please go to:
> [https://github.com/mapbox/node-pre-gyp](url)

Even after running these commands globallly, I am having the same issues. Can you suggest a way-around?

**Comment by swayamtest** [comment]
> `npm install @mapbox/node-pre-gyp --save`

Pretty much still the case. Is there any workaround?

**Comment by swayamtest** [comment]
> > > https://www.npmjs.com/package/node-pre-gyp : "Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future"
> > > https://github.com/mapbox/node-pre-gyp#readme : On Feb 9th, 2021 @mapbox/node-pre-gyp@1.0.0 was released. Older, unscoped versions that are not part of the @mapbox org are deprecated and only @mapbox/node-pre-gyp will see updates going forward.
> > 
> > 
> > Please use these command to update your version of node-pre-gyp to receive updates otherwise you can't receive updates as you didn't update your version to latest version
> > Command:
> > `npm uninstall node-pre-gyp --save`
> > `npm install @mapbox/node-pre-gyp --save`
> > For more information, please go to:
> > [https://github.com/mapbox/node-pre-gyp](url)
> 
> Even after running these commands globallly, I am having the same issues. Can you suggest a way-around?

This is still the case, is there any work around as of yet?

**Comment by soseki-angfa** [comment]
I could fixed by follwing command.

`npm config set python　/usr/bin/python3.8`

The reason why I was getting above error was I have 3 pythons, for example, python2.7, python3 and python3.8.
node-gyp says we need Python v3.7, v3.8, v3.9, or v3.10 and npm try to install using python2.7.
Therefore, I got error.
Regards,

**Comment by gregholst** [comment]
> I could fixed by follwing command.
> 
> `npm config set python　/usr/bin/python3.8`
> 
> The reason why I was getting above error was I have 3 pythons, for example, python2.7, python3 and python3.8. node-gyp says we need Python v3.7, v3.8, v3.9, or v3.10 and npm try to install using python2.7. Therefore, I got error. Regards,

Worked for me, just with little different configuration (on MacOS)
```
npm config set python /Library/Frameworks/Python.framework/Versions/3.9/bin/python3
```

Update for newer npm versions: https://stackoverflow.com/questions/74522956/python-is-not-a-valid-npm-option
