### ISSUE TITLE
Cannot require wrtc.node which I build self on ubuntu20.04

### ISSUE THREAD

**Issue by bertonwalker-cn** [node-webrtc/node-webrtc#688]
It throw an error in  require('../build/Release/wrtc.node');

internal/modules/cjs/loader.js:1122
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: dlopen(/Users/zhangwenbo/qjob/node-webrtc-examples/node_modules/wrtc/build/Release/wrtc.node, 1): no suitable image found.  Did find:
	/Users/zhangwenbo/qjob/node-webrtc-examples/node_modules/wrtc/build/Release/wrtc.node: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
	/Users/zhangwenbo/qjob/node-webrtc-examples/node_modules/wrtc/build/Release/wrtc.node: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
    at Module.load (internal/modules/cjs/loader.js:928:32)

To support H264 , I found a way for `./node_modules/.bin/ncmake rebuild -- -DGN_GEN_ARGS='proprietary_codecs=true ffmpeg_branding="Chrome"'`
And then, I flow the build-from-source.md to download source code to build self.
I replace the /node_module//build/wrtc.node  in node-webrtc-examples project. It does`t work. Throw an error ↑

By the way . The wrtc.node from npm is 20.1MB. But the wrtc.node which I build is 34.3MB. I think it must got sth wrong .

Here is the environments:
node: 14.15.1
GCC: gcc version 9.3.0
cmake: 3.12.4
python: 2.7.18
gcc: 9.3.0
system: Linux VM-0-3-ubuntu 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
ubuntu version: 20.04

Do i build any thing wrong ? 

Thanks for support !

**Comment by OlliePugh** [comment]
Would be great to know how you resolved this
