### ISSUE TITLE
v0.4.7 prebuilt missing with nodejs version 14.16.0

### ISSUE THREAD

**Issue by MichaelMlytics** [node-webrtc/node-webrtc#693]
Hi wrtc,when I was running the command (npm install wrtc) and I got these error message:
```shell
npm ERR! command failed
npm ERR! command sh -c node scripts/download-prebuilt.js
npm ERR! 404 status code downloading tarball https://node-webrtc.s3.amazonaws.com/wrtc/v0.4.7/Release/darwin-arm64.tar.gz
```

It seems like there is no resource on  the AWS s3 bucket?

My environment:
1. Node.js version is 14.16.0.
2.npm version is 7.9.0.

Please take a look for me.Thanks.

**Comment by alew3** [comment]
Just had the same issue, not sure if they have builds for Mac on the ARM platform. Going to try and build it from sources.

**Comment by Mokette** [comment]
Hello !

Just had the same issue with node.js 14.17

error on install : 
```
npm install
npm ERR! code 1
npm ERR! path /home/antoine/projects/klood/front/node_modules/wrtc
npm ERR! command failed
npm ERR! command sh -c node scripts/download-prebuilt.js

```

And the complete error from the npm debug.log file
```
71 timing reifyNode:node_modules/wrtc/node_modules/webidl-conversions Completed in 23ms
72 timing reifyNode:node_modules/wrtc/node_modules/domexception Completed in 23ms
73 timing reify:unpack Completed in 24ms
74 timing reify:unretire Completed in 0ms
75 timing build:queue Completed in 1ms
76 info run wrtc@0.4.7 install node_modules/wrtc node scripts/download-prebuilt.js
77 info run wrtc@0.4.7 install { code: 1, signal: null }
78 timing reify:rollback:createSparse Completed in 9ms
79 timing reify:rollback:retireShallow Completed in 1ms
80 timing command:install Completed in 1985ms
81 verbose stack Error: command failed
81 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
81 verbose stack     at ChildProcess.emit (events.js:375:28)
81 verbose stack     at maybeClose (internal/child_process.js:1055:16)
81 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
82 verbose pkgid wrtc@0.4.7
83 verbose cwd /home/antoine/projects/klood/front
84 verbose Linux 5.8.0-59-generic
85 verbose argv "/snap/node/4812/bin/node" "/usr/local/bin/npm" "install"
86 verbose node v14.17.1
87 verbose npm  v7.18.1
88 error code 1
89 error path /home/antoine/projects/klood/front/node_modules/wrtc
90 error command failed
91 error command sh -c node scripts/download-prebuilt.js
92 verbose exit 1
```

My environment; 
 - Node.js v14.17.1
 - npm v7.18.1

Thanks by advance if anyone could help :)

Have a nice day.

Regards,

edit after testing : I don't understand why it won't install, i've tried to install it on my other computer (not my laptop) with the same node.js environment and it works as expectd, the wrtc package install is good ! and still can't install it on my laptop :/
really don't know what happened

**Comment by draeder** [comment]
Possibly related to #695, and #703, if you're using a Mac.

**Comment by Mokette** [comment]
Hi,
not using a mac, i'm on Ubuntu ;)

and here the return of `lsb_release -a`

Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal

don't know why it works on one install, and doesn't work on another !
i may have a mising dependencies anywhere but i really don't know which :(

**Comment by draeder** [comment]
Yeah, I wasn't sure. It's a problem that needs to be fixed and is holding up my projects.

**Comment by duvallj** [comment]
See https://github.com/node-webrtc/node-webrtc/pull/766
