### ISSUE TITLE
Use Grunt instead of Make

### ISSUE THREAD

**Issue by modeswitch** [node-webrtc/node-webrtc#7]
Grunt is easier to support cross-platform. It can run node-gyp and unit tests.

**Comment by piranna** [comment]
It should be used instead npm package.json prepublish script instead.

**Comment by modeswitch** [comment]
Yeah, that might be a better option. I'm mainly concerned that the module can build on all platforms.

**Comment by helloIAmPau** [comment]
I used the preinstall schema. Once published, by typing `npm install node-webrtc` all deps will be compiled on the destination machine automatically. The Makefile is used to automatize the process. I choosed "make" just because it is present on all machines.

**Comment by piranna** [comment]
According to
https://npmjs.org/doc/misc/npm-scripts.html#NOTE-INSTALL-SCRIPTS-ARE-AN-ANTIPATTERN,
the correct way to do it is using a .gyp file, that will compile on the
target platform when doing npm install.

Also, according to https://npmjs.org/doc/json.html#name, the module name
shouldn't have the word "node" on it, because it's assumed it's a Node.js
module.

2013/10/16 Pasquale Boemio notifications@github.com

> I used the preinstall schema. Once published, by typing npm install
> node-webrtc all deps will be compiled on the destination machine
> automatically. The Makefile is used to automatize the process. I choosed
> "make" just because it is present on all machine.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/modeswitch/node-webrtc/issues/7#issuecomment-26396242
> .

## 

"Si quieres viajar alrededor del mundo y ser invitado a hablar en un monton
de sitios diferentes, simplemente escribe un sistema operativo Unix."
– Linus Tordvals, creador del sistema operativo Linux

**Comment by modeswitch** [comment]
@helloIAmPau Makefiles aren't portable on Windows without a unix environment of some kind. Grunt runs in node, which is a prerequisite anyway. Not critical for the moment though.

@piranna does that apply for compiling native modules as well? That's something that's built for a target arch.

**Comment by piranna** [comment]
> @piranna https://github.com/piranna does that apply for compiling
> native modules as well? That's something that's built for a target arch.
> 
> I think so, we are compiling the module and if there's no linkable shared
> libraries that can be used, I think they should be included and maybe also
> compiled, too... :-/ Is libwebrtc available as a .so anywhere? That would
> be a solution, require it and/or maybe generate it as a side proyect... :-)

## 

"Si quieres viajar alrededor del mundo y ser invitado a hablar en un monton
de sitios diferentes, simplemente escribe un sistema operativo Unix."
– Linus Tordvals, creador del sistema operativo Linux

**Comment by modeswitch** [comment]
For right now, it's better to build from source. I suppose I could build a .so, but not for windows or mac, and not for every architecture.

**Comment by piranna** [comment]
Ok, it's fine for me.

2013/10/16 Alan K notifications@github.com

> For right now, it's better to build from source. I suppose I could build a
> .so, but not for windows or mac, and not for every architecture.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/modeswitch/node-webrtc/issues/7#issuecomment-26440597
> .

## 

"Si quieres viajar alrededor del mundo y ser invitado a hablar en un monton
de sitios diferentes, simplemente escribe un sistema operativo Unix."
– Linus Tordvals, creador del sistema operativo Linux

**Comment by modeswitch** [comment]
@helloIAmPau I disabled the install scripts because they clobbered my existing build. We can re-enable them later though.
