### ISSUE TITLE
"onframe" never fires

### ISSUE THREAD

**Issue by potmat** [node-webrtc/node-webrtc#715]
I have code that looks like this:

```
const connection = new WebRtcConnection(uuidv4(), {});

connection.on('track', (trackInfo: any) => {
    switch (trackInfo.track.kind) {
        case 'audio':
            const audioSink = new RTCAudioSink(trackInfo.track);
            audioSink.addEventListener('data', () => {
                console.log('audio data'); //this line will be hit
            });
            break;
        case 'video':
            const videoSink = new RTCVideoSink(trackInfo.track);
            videoSink.addEventListener('frame', () => {
                console.log('video data'); //this line will not be hit
            });
            break;
    }
});

const offer = await connection.doOffer();

<code to get answer here>

await connection.applyAnswer({
    type: 'answer',
    sdp: <response sdp goes here>
});
```

The WebRtcConnection object is basically a copy/paste of this:  https://github.com/node-webrtc/node-webrtc-examples/blob/master/lib/server/connections/webrtcconnection.js except that 

1. It emits the 'track' event when the underlying RTCPeerConnection object does the same.
2. The offer it creates is an offer to receive audio and video.

There appear to be no negotiation problems, and the audio data seems to be coming through fine.  However, the 'frame' event of the video sink never fires.

I have tried this on MacOS (intel CPU) and Arm64 (r-pi), with Node 12 and 14.  Is there any 'error' event or anything similar that could help me understand why?

**Comment by joinwen** [comment]
I also encounter this problem, how to solve it
