### ISSUE TITLE
Building Error for MacOs Monterey(12.1) M1 Arm architecture

### ISSUE THREAD

**Issue by CO0Ki3** [node-webrtc/node-webrtc#718]
I faced an error while installing node-webrtc to test communication with my media server.

***
co0ki3@doggohyonuiiMac node-webrtc % ./node_modules/.bin/ncmake build
[3/117] Performing download step (git clone) for 'project_depot_tools'
'src'에 복제합니다(Clone to 'src')...
_I don't know how it is printed in the English terminal🥲_

HEAD의 현재 위치는 2fddb956 [git recipe_module] Add tags flag for fetch
[11/117] Performing download step (git clone) for 'project_catch2'
'src'에 복제합니다(Clone to 'src')...

HEAD의 현재 위치는(HEAD's current location is) a1cdff4f raspigcd - opensource-users
[18/117] Performing download step for 'project_libwebrtc'
FAILED: external/libwebrtc/stamp/project_libwebrtc-download /Users/co0ki3/workspace/node-webrtc/build/external/libwebrtc/stamp/project_libwebrtc-download 
cd /Users/co0ki3/workspace/node-webrtc/build/external/libwebrtc/download && /opt/homebrew/Cellar/cmake/3.22.2/bin/cmake -E env DEPOT_TOOLS=/Users/co0ki3/workspace/node-webrtc/build/external/depot_tools/src PLATFORM=darwin WEBRTC_REVISION=branch-heads/4280 /Users/co0ki3/workspace/node-webrtc/scripts/download-webrtc.sh && /opt/homebrew/Cellar/cmake/3.22.2/bin/cmake -E touch /Users/co0ki3/workspace/node-webrtc/build/external/libwebrtc/stamp/project_libwebrtc-download

export PATH=$DEPOT_TOOLS:$PATH

gclient config --unmanaged --spec 'solutions=[{"name":"src","url":"https://webrtc.googlesource.com/src.git"}]'
depot_tools update failed. Conflict in /Users/co0ki3/workspace/node-webrtc/build/external/depot_tools/src
fatal: invalid upstream 'origin/master'
__Platform mac-arm64 is not supported by the CIPD client bootstrap: there's no pinned SHA256 hash for it in the *.digests file.__
WARNING: Your metrics.cfg file was invalid or nonexistent. A new one will be created.

gclient sync --shallow --no-history --nohooks --with_branch_heads -r ${WEBRTC_REVISION} -R
depot_tools update failed. Conflict in /Users/co0ki3/workspace/node-webrtc/build/external/depot_tools/src
fatal: invalid upstream 'origin/master'
__Platform mac-arm64 is not supported by the CIPD client bootstrap: there's no pinned SHA256 hash for it in the *.digests file.__

________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://webrtc.googlesource.com/src.git --depth=1 /Users/co0ki3/workspace/node-webrtc/build/external/libwebrtc/download/_gclient_src_kBpxTC' in '/Users/co0ki3/workspace/node-webrtc/build/external/libwebrtc/download'
Cloning into '/Users/co0ki3/workspace/node-webrtc/build/external/libwebrtc/download/_gclient_src_kBpxTC'...
remote: Finding sources: 100% (7836/7836)           
remote: Total 7836 (delta 609), reused 3983 (delta 609)        
Receiving objects: 100% (7836/7836), 32.54 MiB | 16.56 MiB/s, done.
Resolving deltas: 100% (609/609), done.
Error: Command 'cipd ensure -log-level error -root /Users/co0ki3/workspace/node-webrtc/build/external/libwebrtc/download -ensure-file /var/folders/yc/g96cv_t924sfzck4bpsrxjw80000gn/T/tmpalZS9n.ensure' returned non-zero exit status 1

________ running 'cipd ensure -log-level error -root /Users/co0ki3/workspace/node-webrtc/build/external/libwebrtc/download -ensure-file /var/folders/yc/g96cv_t924sfzck4bpsrxjw80000gn/T/tmpalZS9n.ensure' in '.'
__Platform mac-arm64 is not supported by the CIPD client bootstrap: there's no pinned SHA256 hash for it in the *.digests file.__
ninja: build stopped: subcommand failed.
Build failed
***

Previously, when testing doing **fetch webrtc**, this was not an issue.

Does anyone have the same problem or know a solution?

**Comment by hassanctech** [comment]
@CO0Ki3 were you ever able to get by this issue?  I get the same thing.

**Comment by Sergei8888** [comment]
+1 The same problem

**Comment by tigercoxgithub** [comment]
me too

**Comment by duvallj** [comment]
See https://github.com/node-webrtc/node-webrtc/pull/766
