### ISSUE TITLE
Build failures

### ISSUE THREAD

**Issue by modeswitch** [node-webrtc/node-webrtc#72]
@modeswitch from a git update copy and after removing the third_party folder this is what I get on the console on several consecutives executions of `npm install`:

```
[piranna@Latitude:~/Dropbox/Proyectos/node-webrtc]
 > npm install

> wrtc@0.0.9 install /home/piranna/Dropbox/Proyectos/node-webrtc
> node bin/build.js

depot_tools
.depot_tools not required
gclient_config
.
gclient_config complete
gclient_sync
...............................................................................................................................................................................................................
gclient_sync failed: 1 null

[piranna@Latitude:~/Dropbox/Proyectos/node-webrtc]
 > npm install

> wrtc@0.0.9 install /home/piranna/Dropbox/Proyectos/node-webrtc
> node bin/build.js

depot_tools
.depot_tools not required
gclient_config
.
gclient_config complete
gclient_sync
.................................................................................
gclient_sync failed: 1 null

[piranna@Latitude:~/Dropbox/Proyectos/node-webrtc]
 > npm install

> wrtc@0.0.9 install /home/piranna/Dropbox/Proyectos/node-webrtc
> node bin/build.js

depot_tools
.depot_tools not required
gclient_config
.
gclient_config complete
gclient_sync
....
gclient_sync complete
gclient_runhooks
....
gclient_runhooks failed: 1 null
```

**Comment by modeswitch** [comment]
Seems like there are some problems with `gclient sync` and `gclient runhooks` in some cases.

**Comment by modeswitch** [comment]
@piranna Can you run `gclient sync` and `gclient runhooks` in the `libwebrtc` directory manually?

**Comment by piranna** [comment]
When running `gclient sync` only one time on a clean install, the most insteresting parts are

```
Syncing projects:   2% ( 1/40) trunk
________ running 'svn checkout http://src.chromium.org/svn/trunk/src/testing@249215 /home/piranna/Dropbox/Proyectos/node-webrtc/third_party/trunk/testing --revision 249215 --non-interactive --ignore-externals' in '/home/piranna/Dropbox/Proyectos/node-webrtc/third_party'
svn: E175002: Unable to connect to a repository at URL 'http://src.chromium.org/svn/trunk/src/testing'
svn: E175002: OPTIONS de «http://src.chromium.org/svn/trunk/src/testing»: No se pudo leer la línea de estado: Conexión reinicializada por la máquina remota (http://src.chromium.org)
```

```
________ running 'svn checkout --depth empty http://src.chromium.org/svn/trunk/src /home/piranna/Dropbox/Proyectos/node-webrtc/third_party/chromium_gn' in '/home/piranna/Dropbox/Proyectos/node-webrtc/third_party'
svn: E175002: Unable to connect to a repository at URL 'http://src.chromium.org/svn/trunk/src'
svn: E175002: OPTIONS de «http://src.chromium.org/svn/trunk/src»: No se pudo leer la línea de estado: Conexión reinicializada por la máquina remota (http://src.chromium.org)
```

```
Error: Command svn checkout http://src.chromium.org/svn/trunk/src/testing@249215 /home/piranna/Dropbox/Proyectos/node-webrtc/third_party/trunk/testing --revision 249215 --non-interactive --ignore-externals returned non-zero exit status 1 in /home/piranna/Dropbox/Proyectos/node-webrtc/third_party
```

**Comment by modeswitch** [comment]
This looks like a network error. Can you try fixing that first and run the commands again?

**Comment by piranna** [comment]
Honestly, I don't know what can be the source of this network error, it happens both from university and my house connection. Seems the connection with the SVN server get's resetted, but don't know what could be the source of the problem :-/ Is there any other way to get a copy of the libWebrtc code? Maybe a tarball? This could easier the download...

**Comment by piranna** [comment]
I've managed to download the code at home, and I'm getting now the next error:

```
Syncing projects:  97% (39/40), done.third_party/icu   

________ running '/usr/bin/python trunk/build/cp.py trunk/../chromium_gn/.gn trunk' in '/home/piranna/Dropbox/Proyectos/node-webrtc/third_party/libwebrtc'

________ running 'download_from_google_storage --no_resume --platform=win32 --no_auth --bucket chromium-gn -s trunk/tools/gn/bin/win/gn.exe.sha1' in '/home/piranna/Dropbox/Proyectos/node-webrtc/third_party/libwebrtc'
Traceback (most recent call last):
  File "../../tools/depot_tools/gclient.py", line 1926, in <module>
    sys.exit(Main(sys.argv[1:]))
  File "../../tools/depot_tools/gclient.py", line 1916, in Main
    return dispatcher.execute(OptionParser(), argv)
  File "/home/piranna/Dropbox/Proyectos/node-webrtc/tools/depot_tools/subcommand.py", line 245, in execute
    return command(parser, args[1:])
  File "../../tools/depot_tools/gclient.py", line 1697, in CMDsync
    ret = client.RunOnDeps('update', args)
  File "../../tools/depot_tools/gclient.py", line 1244, in RunOnDeps
    self.RunHooksRecursively(self._options)
  File "../../tools/depot_tools/gclient.py", line 822, in RunHooksRecursively
    hook, cwd=self.root.root_dir, always=True)
  File "/home/piranna/Dropbox/Proyectos/node-webrtc/tools/depot_tools/gclient_utils.py", line 244, in CheckCallAndFilterAndHeader
    return CheckCallAndFilter(args, **kwargs)
  File "/home/piranna/Dropbox/Proyectos/node-webrtc/tools/depot_tools/gclient_utils.py", line 438, in CheckCallAndFilter
    **kwargs)
  File "/home/piranna/Dropbox/Proyectos/node-webrtc/tools/depot_tools/subprocess2.py", line 237, in __init__
    super(Popen, self).__init__(args, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 709, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1326, in _execute_child
    raise child_exception
OSError: [Errno 2] No existe el archivo o el directorio
```

This wasn't solved some days ago?

By the way, I'm using Linux Mint 16 on Intel 64 bits.

**Comment by modeswitch** [comment]
You're using python2?

**Comment by piranna** [comment]
By default, my machine is using Python 2.7.5, but it can also be able to use 3.3.2. Is that a problem? What version should I be using?

In any case, I suspect the problem would be with this line on the traceback I send before:

```
________ running 'download_from_google_storage --no_resume --platform=win32 --no_auth --bucket chromium-gn -s trunk/tools/gn/bin/win/gn.exe.sha1' in '/home/piranna/Dropbox/Proyectos/node-webrtc/third_party/libwebrtc'
```

If I understand correctly, it's trying to compile for Windows instead of Linux O_o I don't know why, but also the exception is not giving any info about "what's the missing file", but maybe it would be related to `trunk/tools/gn/bin/win/gn.exe.sha1`, that in fact doesn't exists on my harddisk.

**Comment by wouldgo** [comment]
It doesn't compile anything at that phase. It downloads some codecs and stuff that are mandatory in next phases.

Have you tried to run [this](https://raw.github.com/wouldgo/node-webrtc/develop/bin/build.js) with -v or --verbose ? :)

**Comment by piranna** [comment]
Same issue:

```
[piranna@Latitude:~/Dropbox/Proyectos/node-webrtc]
 > bin/build_wouldgo.js 
Going to eventually download depot tools from https://chromium.googlesource.com/chromium/tools/depot_tools.git in /home/piranna/Dropbox/Proyectos/node-webrtc/tools/depot_tools
.Going to run the depot tools command: /home/piranna/Dropbox/Proyectos/node-webrtc/tools/depot_tools/gclient config http://webrtc.googlecode.com/svn/trunk in folder /home/piranna/Dropbox/Proyectos/node-webrtc/third_party/libwebrtc 
.
Going to run the depot tools command: /home/piranna/Dropbox/Proyectos/node-webrtc/tools/depot_tools/gclient sync -D in folder /home/piranna/Dropbox/Proyectos/node-webrtc/third_party/libwebrtc
...
Going to run the depot tools command: /home/piranna/Dropbox/Proyectos/node-webrtc/tools/depot_tools/gclient runhooks in folder /home/piranna/Dropbox/Proyectos/node-webrtc/third_party/libwebrtc
................
For /home/piranna/Dropbox/Proyectos/node-webrtc/tools/depot_tools/gclient runhooks something went wrong: error code 1, signal null.
    Try to run build script with --verbose option to find the possible problem.

[piranna@Latitude:~/Dropbox/Proyectos/node-webrtc]
 > bin/build_wouldgo.js --verbose
Going to eventually download depot tools from https://chromium.googlesource.com/chromium/tools/depot_tools.git in /home/piranna/Dropbox/Proyectos/node-webrtc/tools/depot_tools
You already have depot tools, going on...
Going to run the depot tools command: /home/piranna/Dropbox/Proyectos/node-webrtc/tools/depot_tools/gclient config http://webrtc.googlecode.com/svn/trunk in folder /home/piranna/Dropbox/Proyectos/node-webrtc/third_party/libwebrtc 

/home/piranna/Dropbox/Proyectos/node-webrtc/tools/depot_tools/gclient config http://webrtc.googlecode.com/svn/trunk finished
Going to run the depot tools command: /home/piranna/Dropbox/Proyectos/node-webrtc/tools/depot_tools/gclient sync -D in folder /home/piranna/Dropbox/Proyectos/node-webrtc/third_party/libwebrtc

________ running 'svn update /home/piranna/Dropbox/Proyectos/node-webrtc/third_party/libwebrtc/trunk --non-interactive --accept postpone --ignore-externals' in '/home/piranna/Dropbox/Proyectos/node-webrtc/third_party/libwebrtc'
Updating 'trunk':
En la revisión 5524.

_____ trunk/tools/swarming_client at f9538eebbc82bdfed4768cde388c8ae8a1ac3209

/home/piranna/Dropbox/Proyectos/node-webrtc/tools/depot_tools/gclient sync -D finished
Going to run the depot tools command: /home/piranna/Dropbox/Proyectos/node-webrtc/tools/depot_tools/gclient runhooks in folder /home/piranna/Dropbox/Proyectos/node-webrtc/third_party/libwebrtc

________ running '/usr/bin/python trunk/build/cp.py trunk/../chromium_gn/.gn trunk' in '/home/piranna/Dropbox/Proyectos/node-webrtc/third_party/libwebrtc'

________ running 'download_from_google_storage --no_resume --platform=win32 --no_auth --bucket chromium-gn -s trunk/tools/gn/bin/win/gn.exe.sha1' in '/home/piranna/Dropbox/Proyectos/node-webrtc/third_party/libwebrtc'
Traceback (most recent call last):
  File "/home/piranna/Dropbox/Proyectos/node-webrtc/tools/depot_tools/gclient.py", line 1926, in <module>
    sys.exit(Main(sys.argv[1:]))
  File "/home/piranna/Dropbox/Proyectos/node-webrtc/tools/depot_tools/gclient.py", line 1916, in Main
    return dispatcher.execute(OptionParser(), argv)
  File "/home/piranna/Dropbox/Proyectos/node-webrtc/tools/depot_tools/subcommand.py", line 245, in execute
    return command(parser, args[1:])
  File "/home/piranna/Dropbox/Proyectos/node-webrtc/tools/depot_tools/gclient.py", line 1775, in CMDrunhooks
    return client.RunOnDeps('runhooks', args)
  File "/home/piranna/Dropbox/Proyectos/node-webrtc/tools/depot_tools/gclient.py", line 1244, in RunOnDeps
    self.RunHooksRecursively(self._options)
  File "/home/piranna/Dropbox/Proyectos/node-webrtc/tools/depot_tools/gclient.py", line 822, in RunHooksRecursively
    hook, cwd=self.root.root_dir, always=True)
  File "/home/piranna/Dropbox/Proyectos/node-webrtc/tools/depot_tools/gclient_utils.py", line 244, in CheckCallAndFilterAndHeader
    return CheckCallAndFilter(args, **kwargs)
  File "/home/piranna/Dropbox/Proyectos/node-webrtc/tools/depot_tools/gclient_utils.py", line 438, in CheckCallAndFilter
    **kwargs)
  File "/home/piranna/Dropbox/Proyectos/node-webrtc/tools/depot_tools/subprocess2.py", line 237, in __init__
    super(Popen, self).__init__(args, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 709, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1326, in _execute_child
    raise child_exception
OSError: [Errno 2] No existe el archivo o el directorio

/home/piranna/Dropbox/Proyectos/node-webrtc/tools/depot_tools/gclient runhooks finished
For /home/piranna/Dropbox/Proyectos/node-webrtc/tools/depot_tools/gclient runhooks something went wrong: error code 1, signal null.
    Try to run build script with --verbose option to find the possible problem.
```

I'm going to try to exec it from scratch using your build script with verbose enabled.

**Comment by wouldgo** [comment]
I also ran again the script from scrath and also my build blocks during runhooks...
The differences between my latest successful build (last nigth) is in the OS version: here at work I've an ubuntu13.10 (at home a 12.04 LTS).

As soon as I can I'll do more checks.

**Comment by piranna** [comment]
I have been trying with your script and I'm getting problems, but related
to my line. Seems one of the problems is that it's too much data to be
downloaded (sort of 1GB!), with examples and test files. Don't know if it
would be possible to do a selective sync, I didn't find a tarball yet too,
but another option would be to host ourselves a tarball with a copy of the
stable, canonical revision to be used, and maybe also after removing the
useless files.

Send from my Samsung Galaxy Note II

**Comment by piranna** [comment]
Another alternative would be to host on GitHub a git clone of the repo, so
it would lead to less errors (and we would get the code tarballs by free
;-) ). By the way, I see that's downloading a lot of third party code, like
SQLite, that's probably what make it a so big download and module. Is not
possible to use instead this pieces as dependencies of other modules? I
know the usual for binary modules is to be static libraries, but maybe it
would make sense here instead of being standalone modules... What do you
think?

2014-02-11 10:36 GMT+01:00 piranna@gmail.com piranna@gmail.com:

> I have been trying with your script and I'm getting problems, but related
> to my line. Seems one of the problems is that it's too much data to be
> downloaded (sort of 1GB!), with examples and test files. Don't know if it
> would be possible to do a selective sync, I didn't find a tarball yet too,
> but another option would be to host ourselves a tarball with a copy of the
> stable, canonical revision to be used, and maybe also after removing the
> useless files.
> 
> Send from my Samsung Galaxy Note II
> El 11/02/2014 10:13, "Dario Andrei" notifications@github.com escribió:
> 
> I also ran again the script from scrath and also my build blocks during
> 
> > runhooks...
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHubhttps://github.com/js-platform/node-webrtc/issues/72#issuecomment-34737138
> > .

## 

"Si quieres viajar alrededor del mundo y ser invitado a hablar en un monton
de sitios diferentes, simplemente escribe un sistema operativo Unix."
- Linus Tordvals, creador del sistema operativo Linux

**Comment by modeswitch** [comment]
I don't like the idea of hosting a mirror, since runhooks pulls in a bunch of deps for each platform. Reducing the number of files we pull in would be a good start.

@piranna Python2 is required, so you should be OK.

**Comment by piranna** [comment]
> Reducing the number of files we pull in would be a good start.
> 
> How would this be feasable?
> 
> @piranna https://github.com/piranna Python2 is required, so you should
> be OK.
> 
> I think it's mostly a network issue, since some weeks ago when I push my
> changes it worked flawlessly.

## 

"Si quieres viajar alrededor del mundo y ser invitado a hablar en un monton
de sitios diferentes, simplemente escribe un sistema operativo Unix."
- Linus Tordvals, creador del sistema operativo Linux

**Comment by modeswitch** [comment]
OK. I'm going to close this issue. Please open a new issue if you encounter problems with wrtc.

**Comment by wouldgo** [comment]
I resolved the _python issue_ (subprocess.py stuff); the building script built the library.
The fix is in my forked local repository.

If my #68 is ok I can also provide the new script.

Waiting for replies.
Good Night.

Dario.

**Comment by piranna** [comment]
Can you explain what was the problem? I'm trully interested, it was really
annoying... :-/

Send from my Samsung Galaxy Note II

**Comment by wouldgo** [comment]
I modified the script env path variable adding the downloaded depot tools.
Then I added some flags to sync coercing the behavior like a fresh run.
This evening I'm going to push on my fork, then we can test again if it
works or it was just "evening luck".
Il 11/feb/2014 23:24 "Jesús Leganés Combarro" notifications@github.com ha
scritto:

> Can you explain what was the problem? I'm trully interested, it was really
> annoying... :-/
> 
> Send from my Samsung Galaxy Note II

**Comment by maritz** [comment]
Subversion is btw still not mentioned in the dependencies afaict. Was not obvious to me that that was causing my builds to fail until I cloned and did `node bin/build.js --verbose`.
