### ISSUE TITLE
npm install wrtc not working. error code 1

### ISSUE THREAD

**Issue by anonymous887** [node-webrtc/node-webrtc#721]
**Please help me with this**

npm install wrtc
npm ERR! code 1
npm ERR! path /home/ashutosh887/Today/React Practice/w3/node_modules/wrtc
npm ERR! command failed
npm ERR! command sh -c node scripts/download-prebuilt.js
npm ERR! /bin/sh: 1: node-pre-gyp: not found

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ashutosh887/.npm/_logs/2022-03-15T14_02_29_140Z-debug-0.log

node version : 14.19.0

**Comment by miketimmerman** [comment]
Same issue for me. In addition to the above error, my terminal also shows the following:
```
node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: 404 status code downloading tarball https://node-webrtc.s3.amazonaws.com/wrtc/v0.4.7/Release/darwin-arm64.tar.gz
node-pre-gyp ERR! stack     at PassThrough.<anonymous> (/Users/miketimmerman/Projects/AudioServicePoc/node_modules/node-pre-gyp/lib/install.js:149:27)
node-pre-gyp ERR! stack     at PassThrough.emit (events.js:412:35)
node-pre-gyp ERR! stack     at ClientRequest.<anonymous> (/Users/miketimmerman/Projects/AudioServicePoc/node_modules/needle/lib/needle.js:538:9)
node-pre-gyp ERR! stack     at Object.onceWrapper (events.js:520:26)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:400:28)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:647:27)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:127:17)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:515:22)
node-pre-gyp ERR! stack     at TLSSocket.emit (events.js:400:28)
node-pre-gyp ERR! stack     at addChunk (internal/streams/readable.js:293:12)
node-pre-gyp ERR! System Darwin 21.3.0
node-pre-gyp ERR! command "/Users/miketimmerman/.nvm/versions/node/v14.18.2/bin/node" "/Users/miketimmerman/Projects/AudioServicePoc/node_modules/.bin/node-pre-gyp" "install"
node-pre-gyp ERR! cwd /Users/miketimmerman/Projects/AudioServicePoc/node_modules/wrtc
node-pre-gyp ERR! node -v v14.18.2
node-pre-gyp ERR! node-pre-gyp -v v0.13.0
node-pre-gyp ERR! not ok 
404 status code downloading tarball https://node-webrtc.s3.amazonaws.com/wrtc/v0.4.7/Release/darwin-arm64.tar.gz
```

**Comment by anonymous887** [comment]
Is it resolved @miketimmerman ???

Please help @makoto @substack @cjb

**Comment by miketimmerman** [comment]
@being-anonymous No, still an issue for me

**Comment by corwin-of-amber** [comment]
@being-anonymous just install node-pre-gyp (`npm i -g node-pre-gyp`).
@miketimmerman there is no support for macOS+arm64 in the official build; you can try `@koush/wrtc` as a replacement (see #714).

**Comment by notudope** [comment]
> @being-anonymous just install node-pre-gyp (`npm i -g node-pre-gyp`). @miketimmerman there is no support for macOS+arm64 in the official build; you can try `@koush/wrtc` as a replacement (see #714).

Can you add support for linux-s390x?

**Comment by chfritz** [comment]
After the better part of a day of debugging this, I finally found that the issue is this:
https://github.com/node-webrtc/node-webrtc/blob/d4ff78e49aa7e1cb2ffa54e6f6a3bda9a11d1b18/package.json#L40-L42

This *would* be fine if, before publishing, `npm install` had been run, but apparently it wasn't, because the tar ball doesn't contain the promised node-pre-gyp dependency:
```
[cfritz@homedesk:/tmp 11/04 21:10:00]
> wget https://registry.npmjs.org/wrtc/-/wrtc-0.4.7.tgz
[cfritz@homedesk:/tmp 11/04 21:10:20]
> tar tf wrtc-0.4.7.tgz 
package/lib/binding.js
package/lib/browser.js
package/lib/datachannelevent.js
package/lib/datachannelmessageevent.js
package/scripts/download-prebuilt.js
package/lib/error.js
package/lib/eventtarget.js
package/lib/icecandidate.js
package/lib/index.js
package/lib/mediadevices.js
package/lib/peerconnection.js
package/lib/rtcpeerconnectioniceerrorevent.js
package/lib/rtcpeerconnectioniceevent.js
package/lib/sessiondescription.js
package/package.json
package/LICENSE.md
package/README.md
package/THIRD_PARTY_LICENSES.md
```
and npm doesn't automatically fetch all `bundleDependencies` before publishing. Apparently it will only bundle those that are already present in `node_modules` at the time of publishing.

I'll create a PR to address this. Would be great to get it fixed and republished because it really breaks automatic installs when using `wrtc` as a dependency.

**Comment by taban-17** [comment]
> @being-anonymous just install node-pre-gyp (`npm i -g node-pre-gyp`). @miketimmerman there is no support for macOS+arm64 in the official build; you can try `@koush/wrtc` as a replacement (see #714).

Worked for me on Windows 10 x64👍

**Comment by skushagra9** [comment]
![image](https://github.com/node-webrtc/node-webrtc/assets/120712705/adf3c11e-ae3f-44fb-9f4a-252cdb252626)
src - https://www.npmjs.com/package/wrtc#supported-platforms
