### ISSUE TITLE
Unable to install WRTC node in mac

### ISSUE THREAD

**Issue by PravinBarate** [node-webrtc/node-webrtc#725]
npm ERR! code 1
npm ERR! path /Users/mahadevkale/Desktop/Insight/Sources/Nodejs/teacher-console/node_modules/wrtc
npm ERR! command failed
npm ERR! command sh -c node scripts/download-prebuilt.js
npm ERR! Remote end closed socket abruptly.
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@0.11.0
npm ERR! node-pre-gyp info using node@16.14.2 | darwin | x64
npm ERR! node-pre-gyp WARN Using needle for node-pre-gyp https download 
npm ERR! node-pre-gyp info check checked for "/Users/mahadevkale/Desktop/Insight/Sources/Nodejs/teacher-console/node_modules/wrtc/build/Release/wrtc.node" (not found)
npm ERR! node-pre-gyp http GET https://node-webrtc.s3.amazonaws.com/wrtc/v0.4.7/Release/darwin-x64.tar.gz
npm ERR! node-pre-gyp http 200 https://node-webrtc.s3.amazonaws.com/wrtc/v0.4.7/Release/darwin-x64.tar.gz
npm ERR! node-pre-gyp info install unpacking Release/wrtc.node
npm ERR! node-pre-gyp ERR! install error 
npm ERR! node-pre-gyp ERR! stack Error: Remote end closed socket abruptly.
npm ERR! node-pre-gyp ERR! stack     at TLSSocket.on_socket_end (/Users/mahadevkale/Desktop/Insight/Sources/Nodejs/teacher-console/node_modules/needle/lib/needle.js:529:17)
npm ERR! node-pre-gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:78:11)
npm ERR! node-pre-gyp ERR! System Darwin 21.4.0
npm ERR! node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/mahadevkale/Desktop/Insight/Sources/Nodejs/teacher-console/node_modules/.bin/node-pre-gyp" "install"
npm ERR! node-pre-gyp ERR! cwd /Users/mahadevkale/Desktop/Insight/Sources/Nodejs/teacher-console/node_modules/wrtc
npm ERR! node-pre-gyp ERR! node -v v16.14.2
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v0.11.0
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mahadevkale/.npm/_logs/2022-04-04T13_32_41_822Z-debug-0.log

**Comment by crisdosaygo** [comment]
You need to use x86/x64. Clone your terminal and create an x64 version. Then use nvm to install a new version of node you don't currently have (and it will automatically use the x64 version). Then run npm install and you will pull the x64 version of wrtc.

Also set `TARGET_ARCH=x64` as in 

`TARGET_ARCH=x64 npm start`

**Comment by bensewell** [comment]
The issue (I think) is the old version of node-pre-gyp. To use a newer version, I've forked the current repo (which uses the right version on the `develop` branch) , and fixed the version in the package.json.

If you want to use mine, you can try with `yarn add https://github.com/amutri/node-webrtc#amutri` - or do the same thing yourself on your own fork.

Also, vote for this: #706

**Comment by skushagra9** [comment]
![image](https://github.com/node-webrtc/node-webrtc/assets/120712705/adf3c11e-ae3f-44fb-9f4a-252cdb252626)
src - https://www.npmjs.com/package/wrtc#supported-platforms

**Comment by duvallj** [comment]
See https://github.com/node-webrtc/node-webrtc/pull/766
