### ISSUE TITLE
Still mantained?

### ISSUE THREAD

**Issue by ghost** [node-webrtc/node-webrtc#732]
Hi, is this library still maintained? Since there is no release until 1 year ago and the WebRTC version is outdated.

**Comment by charlyBerthet** [comment]
Sounds like it's not, there are critical pull requests that are pending and not reviewed... :(

**Comment by tchakabam** [comment]
Hey I was also thinking if it would not be better to compile libWebRTC to WASM straight away and have more lightweight bindings for the NodeJS platform from there. Anybody thinking the same?

**Comment by jeremyckahn** [comment]
> Hey I was also thinking if it would not be better to compile libWebRTC to WASM straight away and have more lightweight bindings for the NodeJS platform from there. Anybody thinking the same?

I wonder if https://github.com/pion/webrtc could be used in this way?

**Comment by charlyBerthet** [comment]
I moved towards https://github.com/versatica/mediasoup

**Comment by pavigor** [comment]
Hi all. 
Can someone advise alternative for wrtc? I need RTCPeerConnection implementation for tests.

**Comment by ghost** [comment]
@pavigor What kind of tests? Be more specific please... If you need an SFU there are many alternatives such as mediasoup, janus-gateway or other similar servers, but you'll need to implement their own signaling protocols. If you need only to have WebRTC somewhere you better use browser WebRTC implementation on client side.

**Comment by pavigor** [comment]
@giovanni-bertoncelli assume that I'm developing SDK which works with peerconnection. I want to test only SDK and don't want to write a bunch of code for client side just for tests. For now I'm using wrtc for unit tests but I encountered with problem like https://github.com/node-webrtc/node-webrtc/issues/735 . I have tried to inspect wrtc native code but I'm not C-developer.

**Comment by FaustXVI** [comment]
The main dev : @markandrus is still pretty active on other projects so I think this project is abandoned.
Like @pavigor , I am looking for an option to test in node directly without starting a browser. If I find an alternative I'll let you know. Otherwise, it means I ended up starting a browser :(
