### ISSUE TITLE
How to save a webRTC stream into a file on server with nodejs?

### ISSUE THREAD

**Issue by hypo-thesis** [node-webrtc/node-webrtc#734]
I get my stream from my client like this :

```
  webrtc_connection.ontrack = async (e) => {
    
 //TODO : RECORD

  }
```
How can I record / save it into a file on server? Apparently nodejs does not have MediaRecorder, so I am at loss for going further.

**Comment by s074** [comment]
There's an example where they use ffmpeg to save the stream as a file: https://github.com/node-webrtc/node-webrtc-examples/tree/master/examples/record-audio-video-stream
