### ISSUE TITLE
got an error when call  await setLocalDescription();

### ISSUE THREAD

**Issue by RajanZhan** [node-webrtc/node-webrtc#735]
as the title ,it was got an error when i call pc.setLocalDescription();  
the error as follow:
 var promise = this._pc.setLocalDescription(description);
                         ^
TypeError: Expected an object
    at RTCPeerConnection.setLocalDescription

please help me ,thinks to everyone!

**Comment by duvallj** [comment]
Duplicate of https://github.com/node-webrtc/node-webrtc/issues/677
