### ISSUE TITLE
change video quality

### ISSUE THREAD

**Issue by veeyka** [node-webrtc/node-webrtc#747]
hi . i want to change video quality and reduce it to make it easy to have a video call even with weaker internet connection . is there any ting to do this . 

my code : 

navigator.mediaDevices
    .getUserMedia({
      video: true,
      audio: true,
    }).then((stream) => {

   });

thanks

**Comment by hthetiot** [comment]
@veeyka 
You need to learn webrtc to do that, that not this repository job to teach you how.

Here is 2 samples below that will help you to achieve what you looking for, you need to click "view source on github" and find the javascript to see how it is made on each samples. 

Generally WebRTC sample is a good place to start leaning based on samples: https://webrtc.github.io/samples/

1. Change resolution of the camera

Use getUserMedia video contraints for that.

Example: 
> navigator.mediaDevices.getUserMedia({audio: true, video: {width: 320})

Doc: https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia
Sample: https://webrtc.github.io/samples/src/content/getusermedia/resolution/

2. Change the bitrate:

More complicated, see source. 
Sample: https://webrtc.github.io/samples/src/content/peerconnection/bandwidth/ 

P.s I don't recommend asking questions that can be answered via a simple Google search "getUserMedia resolution" on open source repository that have nothing to do with the scope of the project responsibilities. I replied to save time to maintainer that would most likely have closed the issue without replying as he should.

**Comment by veeyka** [comment]
> @veeyka You need to learn webrtc to do that, that not this repository job to teach you how.
> 
> Here is 2 samples below that will help you to achieve what you looking for, you need to click "view source on github" and find the javascript to see how it is made on each samples.
> 
> Generally WebRTC sample is a good place to start leaning based on samples: https://webrtc.github.io/samples/
> 
> 1. Change resolution of the camera
> 
> Use getUserMedia video contraints for that.
> 
> Example:
> 
> > navigator.mediaDevices.getUserMedia({audio: true, video: {with: 320})
> 
> Doc: https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia Sample: https://webrtc.github.io/samples/src/content/getusermedia/resolution/
> 
> 2. Change the bitrate:
> 
> More complicated, see source. Sample: https://webrtc.github.io/samples/src/content/peerconnection/bandwidth/
> 
> P.s I don't recommend asking questions that can be answered via a simple Google search "getUserMedia resolution" on open source repository that have nothing to do with the scope of the project responsibilities. I replied to save time to maintainer that would most likely have closed the issue without replying as he should.

thanks dude. good

**Comment by hthetiot** [comment]
@veeyka please close the issue now, so thr maintainer can save time and work on thr projet instead.

**Comment by BrycensRanch** [comment]
you guys are funny this repo hasnt been committed to in years the maintainer has moved on with their life fr

**Comment by hthetiot** [comment]
> you guys are funny this repo hasnt been committed to in years the maintainer has moved on with their life fr

Year I have seen worse abandoned repo, just wanted to help noob not really care about the state of the repo.

Still @BrycensRanch close this issue please.

**Comment by BrycensRanch** [comment]
i cant, I'm not a maintainer 🤷‍♂️

**Comment by hthetiot** [comment]
> i cant, I'm not a maintainer 🤷‍♂️

Sorry wrong @, I was targeting @veeyka that created the issue and should be able to close as a good practice.

**Comment by veeyka** [comment]
> > you guys are funny this repo hasnt been committed to in years the maintainer has moved on with their life fr
> 
> Year I have seen worse abandoned repo, just wanted to help noob not really care about the state of the repo.
> 
> Still @BrycensRanch close this issue please.

thanks dude you helped me alot . yes . this lib is abandoned . but not webrtc . i went to a good place to learn about webrtc and now i know that how to works. thanks alot

**Comment by hthetiot** [comment]
Glad I helped @veeyka, good luck for the future.
