### ISSUE TITLE
Does it support v4l2 source?

### ISSUE THREAD

**Issue by jim-king-2000** [node-webrtc/node-webrtc#750]
We are writing a native webrtc client which would accept a webrtc connection with its local video stream (captured from local camera) attached when receiving a MQTT signaling. Is it possible to implement it by `node-webrtc`? Here are some points:
1. Since it is a native app and there is no browser, we can't use `window.navigator.mediaDevices.getUserMedia`.
1. We'd prefer to using Node.js or Python.
1. We'd run it on SBC such as Raspberry Pi.
1. We choose MQTT instead websocket for signaling.
1. It is based on Linux so V4L2 camera is employed.

Looking forward to the reply.

**Comment by LiangHuangBC** [comment]
same question.
