### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by alfredomariamilano** [node-webrtc/node-webrtc#751]
Is the project still maintained? I guess not, but it's worth asking.
How would one go about updating the libWebRTC version?

**Comment by mghadam** [comment]
It is discontinued apparently. See the post `WebRTC Stacks (v1 - September, 2022)` on [webrtc-developers.com](https://www.webrtc-developers.com/documentation/) website. From the diagram on the post, [node-datachannel](https://www.npmjs.com/package/node-datachannel) appears to be an actively developed alternative.
