### ISSUE TITLE
Is this repo stale / abandoned?

### ISSUE THREAD

**Issue by draeder** [node-webrtc/node-webrtc#759]
There has not been an update to the code in 2+ years and over 100 issues unanswered/addressed.

**Comment by mariusrak** [comment]
There are also three new nodejs LTS versions, would be possible for the project to keep up?

**Comment by joecarl** [comment]
This project is discontinued, you can use [node-datachannel](https://github.com/murat-dogan/node-datachannel) or [werift](https://github.com/shinyoshiaki/werift-webrtc) as alternatives

**Comment by duvallj** [comment]
See https://github.com/node-webrtc/node-webrtc/pull/767
