### ISSUE TITLE
globals?

### ISSUE THREAD

**Issue by piranna** [node-webrtc/node-webrtc#76]
Should RTCPeerConnection class & friends be registered as globals, or should developers use the `wrtc` namespace? First one would allow to port browser libraries without modifying a comma, but force to use the `wrtc` namespace will not polute the global namespace and would lead to cleaner code...

**Comment by modeswitch** [comment]
There's no way around `require('wrtc')`, so it makes sense to me that if you want globals you can import `RTCPeerConnection` et. al. as `RTCPeerConnection = require('wrtc').RTCPeerConnection`.

**Comment by piranna** [comment]
I was doing what you suggested already, only that it was a bug on node-webrtc and that's why I was surprised about it and though it would be useful to define globals for that objects. I've open issue #77 for it, but anyway the debate is still open :-)
