### ISSUE TITLE
Cannot download binaries  -  Darwin m2 Pro 14.0

### ISSUE THREAD

**Issue by MatthD** [node-webrtc/node-webrtc#760]
Got error 404 on node 14/16 that should point to s3
![Capture d’écran 2023-11-03 à 16 13 42](https://github.com/node-webrtc/node-webrtc/assets/7901366/1bfc6742-7073-4591-9edf-d8ec0f7febc1)

**Comment by razvanphp** [comment]
Welcome to the club 🙂

**Comment by saygoodluck** [comment]
+1

**Comment by vlxdisluv** [comment]
same

**Comment by duvallj** [comment]
See https://github.com/node-webrtc/node-webrtc/pull/766
