### ISSUE TITLE
i am unable to install on nodejs windows 10

### ISSUE THREAD

**Issue by eassa** [node-webrtc/node-webrtc#761]
C:\Repose\webrtc\test>node -v
v18.12.0

C:\Repose\webrtc\test>npm install wrtc
npm WARN deprecated domexception@1.0.1: Use your platform's native DOMException instead
npm ERR! code 1
npm ERR! path C:\Repose\webrtc\test\node_modules\wrtc
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/download-prebuilt.js
npm ERR! 'node-pre-gyp' is not recognized as an internal or external command,
npm ERR! operable program or batch file.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Enassar\AppData\Local\npm-cache\_logs\2023-12-03T09_34_12_623Z-debug.log

**Comment by rjjrbatarao** [comment]
try this npm i -g node-pre-gyp then do npm i wrtc again

**Comment by wtmlns** [comment]
@rjjrbatarao  I have the same issue, even after npm i -g node-pre-gyp. I am ubuntu 22
