### ISSUE TITLE
Is there an easy way to use it for node 18|20

### ISSUE THREAD

**Issue by MatthD** [node-webrtc/node-webrtc#762]
Simple question for people who still use it.

Are you able to use it with node v18 or v20 ? Some NAN - NAPI functions are missing (which is strange because AFAIK it should always be retro compatible)

So someone give a try of use it?

**Comment by madhur-push** [comment]
Try using this instead: https://github.com/murat-dogan/node-datachannel/

For simple-peer polyfills: https://github.com/murat-dogan/node-datachannel/tree/master/polyfill
