### ISSUE TITLE
JS API should generate standards-compliant event objects

### ISSUE THREAD

**Issue by modeswitch** [node-webrtc/node-webrtc#8]
Right now the JS API passes webrtc objects (data channels, status codes) without wrapping them in an event object. This is not strictly comliant with the standard and will prevent webrtc libraries written for the browser from running on node-webrtc.

**Comment by kofd** [comment]
ah, should I address that in the implementation of the streams as well, or let this be fixed when it is addressed?

**Comment by modeswitch** [comment]
make the errors like the ones currently being returned and we'll fix them all later

**Comment by modeswitch** [comment]
Fixed.
