### ISSUE TITLE
Can't run after successfull build

### ISSUE THREAD

**Issue by jeena** [node-webrtc/node-webrtc#85]
I tried to install it on my Mac OS X 10.9.1, so I cloned the project and then did npm install and it compiled for a while without errors. Sadly when I tried to start the bridge.js example I got an error. You can see the whole dump here: https://gist.github.com/jeena/4ca18ed57b6c8d0d4674

**Comment by piranna** [comment]
As it sais at the top or your trace, it was not able to download and install the "bindings" module. It can be due to some temporal network issues, try to exec npm install again.

**Comment by wouldgo** [comment]
As far I know Darwin atm isn't support (that is a milestone 2 goal).
The `Symbol not found` issue you raised anyway is very helpful (actually last saturday I reviewed the build script permitting a successful built in darwin and I need to continue the integration).

**Comment by jeena** [comment]
The one at the top just tells me that I didn't compile it yet. After compilation I get the Symbol not found.

I will try it on my Linux machine now.

**Comment by jeena** [comment]
On Linux I get a different error: https://gist.github.com/jeena/14b104645eff8625351b

**Comment by piranna** [comment]
Use the --verbose flag as suggested, probably it's an issue related with missing packages that you need to install.

**Comment by wouldgo** [comment]
As the log states: have tried to run `node bin/build.js -v` (or is the message too cryptic it's changeable :-) )?

**Comment by jeena** [comment]
I didn't get what I was supposed to run with --verbose. I got this (on Linux) while running `node bin/build.js -v` https://gist.github.com/jeena/49282b4cff7cb2b07b5a

**Comment by wouldgo** [comment]
You missed the `libgtk2.0-dev` package (if I remember well) .

It complains about the missing of some dev libraries (as @piranna said to you in the gist comment).

**Comment by modeswitch** [comment]
@piranna Can you add that list of packages to the README?

**Comment by jeena** [comment]
It is not that easy to understand what the errors say honestly, but I am trying. After installing libgtk2.0-dev it now says

```
AssertionError: Point $JAVA_HOME or the java_home gyp variable to a directory containing include/jni.h
```

so I assume it is Java which I need to install?

**Comment by modeswitch** [comment]
Yeah, you'll have to install Java.

**Comment by piranna** [comment]
@modeswitch, created pull-request with the list of packages.

**Comment by jeena** [comment]
Ok after a little odyssey of finding the right path to the JDK https://github.com/js-platform/node-webrtc/pull/86#issuecomment-35370543 it finally compiled, so now when I start it with:

```
node examples/bridge.js
```

it at least doesn't complain about anything anymore, just sits there and waits for something, I assume a connection from the peer.html

Ok I now run the peer.html in the browser and got this out this JSON you describe in the README and after that a bunch of trace stuff.

Very nice, so I suppose it seems to work! Now we will only need to understand how it works and try to include it to and use it in our game, this is so exciting, thanks for doing this kind of development on the very frontier! The edge is bleeding, but that is what is most fun about it, isn't it? :D
