### ISSUE TITLE
Adaptor.js?

### ISSUE THREAD

**Issue by piranna** [node-webrtc/node-webrtc#89]
What about to include adaptor.js and serve it on browsers when using the browserified version?

**Comment by modeswitch** [comment]
What is adaptor.js?

**Comment by piranna** [comment]
It's a Javascript file done and keep updated by Google that fixes some inconsistences between Chrome and Firefox WebRTC implementations.

**Comment by piranna** [comment]
Here you have the link to the file:

https://code.google.com/p/webrtc/source/browse/trunk/samples/js/base/adapter.js

**Comment by modeswitch** [comment]
I had not intended for any part of this library to be used in the browser.

**Comment by piranna** [comment]
Obviously, it's not the purpose of the library to work on browsers :-) But since we are allowing to browserify to work on this using the native classes, I think it would be good to also unify their behaviour without requiring the user to include explicitly the adapter.js file.
