### ISSUE TITLE
Interoperability with browser based WebRTC libraries

### ISSUE THREAD

**Issue by piranna** [node-webrtc/node-webrtc#9]
Allow to use the same code for Node.js and browsers the same way that ws module allow for WebSockets.

**Comment by feross** [comment]
The way to do this would be for the WebRTC libraries that want to support node to add a "browser" field to their package.json a la https://gist.github.com/defunctzombie/4339901

**Comment by piranna** [comment]
To increase interoperability, only class that should be exported is RTCPeerConnection leaving others as internal ones, since it's what browsers do.

**Comment by modeswitch** [comment]
Is that true? In Chrome, I see RTCIceCandidate and RTCSessionDescription are visible.

**Comment by piranna** [comment]
> Is that true? In Chrome, I see RTCIceCandidate and RTCSessionDescription
> are visible.
> 
> Yes, they are visible, but per the specification you can't be able to
> create objects manually. I think they would be there just to check objects
> with the instanceof statement, no more.

## 

"Si quieres viajar alrededor del mundo y ser invitado a hablar en un monton
de sitios diferentes, simplemente escribe un sistema operativo Unix."
– Linus Tordvals, creador del sistema operativo Linux

**Comment by modeswitch** [comment]
Fixed in #48
