### ISSUE TITLE
pure virtual method called

### ISSUE THREAD

**Issue by piranna** [node-webrtc/node-webrtc#94]
When passing the tests of WebP2P.io with node-webrtc, I get the next trace output regarding to DataChannel creation and interconnection:

```
<...a lot more lines...>

-> TRACE: Call::virtual DataChannel::~DataChannel()
<- Call::virtual DataChannel::~DataChannel()
-> TRACE: Call::virtual PeerConnection::~PeerConnection()
<- Call::virtual PeerConnection::~PeerConnection()
-> TRACE: Call::virtual void DataChannel::OnStateChange()
-> TRACE: Call::void DataChannel::QueueEvent(DataChannel::AsyncEventType, void*)
<- Call::void DataChannel::QueueEvent(DataChannel::AsyncEventType, void*)
<- Call::virtual void DataChannel::OnStateChange()
-> TRACE: Call::virtual void DataChannel::OnStateChange()
-> TRACE: Call::void DataChannel::QueueEvent(DataChannel::AsyncEventType, void*)
<- Call::void DataChannel::QueueEvent(DataChannel::AsyncEventType, void*)
<- Call::virtual void DataChannel::OnStateChange()
-> TRACE: Call::virtual PeerConnection::~PeerConnection()
<- Call::virtual PeerConnection::~PeerConnection()
pure virtual method called
terminate called without an active exception
Aborted
npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0
```

Seems that the C++ PeerConnection destructor is a pure virtual method and the tests doesn't like it too much... :-)

**Comment by modeswitch** [comment]
PeerConnection::~PeerConnection is not pure virtual. The implementation is here https://github.com/js-platform/node-webrtc/blob/develop/src/peerconnection.cc#L125.

**Comment by piranna** [comment]
It's strange, then... What could then be the reason of the 'pure virtual method called' string? :-/

**Comment by modeswitch** [comment]
See if you can add a test case to node-webrtc that reproduces the failure and I'll debug from there.

**Comment by modeswitch** [comment]
Please retest this with the latest build, and reopen if you can reproduce it there.

**Comment by piranna** [comment]
I've tested with 0.0.19 and seems to not happen again.

**Comment by piranna** [comment]
```
pure virtual method called
terminate called without an active exception
Aborted
```

Ok, on v0.0.20 it's still happening... :-/

**Comment by modeswitch** [comment]
Can you send me a test case so that I can debug it?
