### ISSUE TITLE
GYP file contains hard-corded JAVA_HOME variable

### ISSUE THREAD

**Issue by apiece** [node-webrtc/node-webrtc#95]
I was trying to install the project on Ubuntu 12.04.  When I was doing "gclient sync", it threw an exemption near the end showing somehow the "hard-coded" JAVA_HOME directory, i.e. specifically "java-6-sun" cannot be found.  I wasn't able to find which GYP file it is.  Once I renamed my openjdk folder to "java-6-sun". The project got built without any hiccup just using "npm install" within "node-webrtc" folder.

**Comment by modeswitch** [comment]
JAVA_HOME isn't hard-coded. Are you sure it's not being set in your shell?

**Comment by apiece** [comment]
I am testing with Amazon instance.  I have openjdk 1.7 installed; it would
be strange that the installation would have set "java-6-sun" in the shell.

**Comment by modeswitch** [comment]
Check if the environment variable is set: `echo $JAVA_HOME` in your shell.

**Comment by apiece** [comment]
I originally set JAVA_HOME to that of openjdk, i.e. echo $JAVA_HOME =
/path/to/openjdk_folder_name, but during building, the console complaint
that one of the GYP files has set JAVA_HOME to be java-6-sun, and that's
why it could not find the actual home.  Sorry I don't have the console
capture with me, but it's somethign like (JAVA_HOME, java-6-sun)...
What I did finally was to change the openjdk folder name to "java-6-sun' to
build correctly, as I couldn't find the hard-coded parameter in any of the
GYP files.

**Comment by modeswitch** [comment]
JAVA_HOME isn't hard-coded anywhere in node-webrtc. Libjingle requires that JAVA_HOME is set before it will build correctly. Please double-check that your environment is configured as you expect.
